### ISSUE TITLE
Orm: Composite Primary Key

### ISSUE THREAD

**Issue by Luceat** [beego/beego#1074]
It seems that the Orm doesn't support Composite Primary Keys out of the box.

I have a model User as such:

type User struct{
&nbsp;&nbsp;&nbsp;id int
&nbsp;&nbsp;&nbsp;...
}
with Primary Key "Id".

I also want to create the concept of Friends with the following model:
type Friends struct{
&nbsp;&nbsp;&nbsp;Friend1 *User "orm:"rel(fk);pk""
&nbsp;&nbsp;&nbsp;Friend2 *User "orm:"rel(fk);pk""
}
In effect creating the following table:

CREATE TABLE friends (
&nbsp;&nbsp;&nbsp;friend1 REFERENCES(user)
&nbsp;&nbsp;&nbsp;friend2 REFERENCES(user)
&nbsp;&nbsp;&nbsp;PRIMARY KEY(friend1, friend2)
}

Is this a viable feature to implement or should I just go with another Id-index?

**Comment by jerson** [comment]
+1

**Comment by ljesus** [comment]
I would also like this feature.

**Comment by corescan** [comment]
+1

In the meantime, has anyone found a way to represent the composite pkey?

**Comment by JoeFerrucci** [comment]
Does beego offer Composite Primary Key yet?

**Comment by awengo** [comment]
https://github.com/awengo/beego/pull/1
准备开始完善这个功能，有什么好建议吗？目前只能暂时简单的添加复合主键
Ready to improve this feature, any good suggestions?
Currently just can simply add a composite primary key.

**Comment by xunleer** [comment]
+1
#3130

**Comment by xunleer** [comment]
#3221

**Comment by Bowenwu1** [comment]
+1

**Comment by liipx** [comment]
+1

**Comment by ZLeQ** [comment]
+1

**Comment by heramerom** [comment]
3 years has passed. Still not support?

**Comment by luolizhi** [comment]
+1
