### ISSUE TITLE
[Proposal] Implement golang.org/x/net/context in beego.Context

### ISSUE THREAD

**Issue by someone1** [beego/beego#1077]
This article details why: https://blog.golang.org/context

We can interop with other libraries more seamlessly if the beego.Context implemented this interface. This seems to be the planned way to scope requests and work between frameworks and APIs.

**Comment by webgini** [comment]
yup that would be great idea. we can have common context to deal with.

**Comment by astaxie** [comment]
Good Proposal, let me think more on this.

**Comment by someone1** [comment]
I think to do this "right" would require a lot of breaking changes. All code that might want to be scoped to the request should take the context as its first argument. This should include:
logging
sessions
orm
etc.

**Comment by astaxie** [comment]
I think we need to discuss more on it

**Comment by someone1** [comment]
@astaxie, what are your thoughts on this? Is this something we can start thinking about implementing?

If this was implemented across middlewares and hooks in beego, integration with AppEngine/Managed VMs on Google's Cloud Platform would be built-in to beego!

**Comment by astaxie** [comment]
We can implement the context in beego1.6

**Comment by frankcarey** [comment]
Any progress on this?

**Comment by astaxie** [comment]
Wait for the new go version. 
https://github.com/golang/go/commit/c1c7547f6ad7264c1d6eea3fc1645b2eab104694

**Comment by thanzen** [comment]
Will this get implemented in 1.7?

**Comment by astaxie** [comment]
just released beego1.7.0. I think 1.8 I will start to think about it. As it need Go1.7, while many people still use Go1.4
