### ISSUE TITLE
GOPATH 设置了，安装bee还是提示$GOPATH not set.

### ISSUE THREAD

**Issue by frankdou** [beego/beego#110]
➜  ~GOPATH  sudo go get github.com/astaxie/bee
package github.com/astaxie/bee: cannot download, $GOPATH not set. For more details see: go help gopath

➜  ~GOPATH  go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dyq/Workspace/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.1.1"
GOTOOLDIR="/usr/local/Cellar/go/1.1.1/pkg/tool/darwin_amd64"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-common"
CGO_ENABLED="1"

求帮助，谢谢

**Comment by lgang315** [comment]
我的也是，go env 都设置对了，还是会提示 not set gopath
求解呀

**Comment by linux-mac** [comment]
试试下面的：
> export GOPATH=/var/www/html
> export PATH=$PATH:$GOPATH/bin

**Comment by gezhixin** [comment]
把你的path打印出来，在cd一下，有可能是你设置确实错了，个把空格字母都有可能

**Comment by slclub** [comment]
I have the seam error reported

**Comment by MartineStar** [comment]
me too,how can i resolve this problem

**Comment by DennisMao** [comment]
@MartineStar  please check again your GOPATH.you can try to run `go get` on the path of your project.
