### ISSUE TITLE
RelatedSel() unable to load many-to-many records.

### ISSUE THREAD

**Issue by mewben** [beego/beego#1252]
I don't know if this is a bug or not implemented yet. Please fill me in.

I have this:

```
type Post struct {
    Id    int
    Title string
    Tags  []*Tag `orm:"rel(m2m)`
}

type Tag struct {
    Id    int
    Name  string
    Posts []*Post `orm:"reverse(many)"`
}
```

As I run this:

```
var posts []*Post
orm.NewOrm().QueryTable(new(Post)).RelatedSel().All(&posts)
```

It returns an array of posts but tags inside each record is null.

```
[
    {
        "Id": 1,
        "Title": "Post 1",
        "Tags": null
    },
    {
        "Id": 4,
        "Title": "Post 4",
        "Tags": null
    }
]
```

How to load all the related Tags? Please help.

**Comment by Hepri** [comment]
Use LoadRelated for what
RelatedSel is for Many to 1 relation

**Comment by ilgooz** [comment]
+1
I am also having "PANIC: unknown model/table name xxx" because of this [line](https://github.com/astaxie/beego/blob/af71289c25f64e35b688376d5115dbf8b93d87ab/orm/db_tables.go#L134)
@Hepri Can you please provide an example? I think LoadRelated() doesn't do the job.

**Comment by Hepri** [comment]
Oh, forget to tell, I'm using m2m through some table

    type Order struct {
        Id                  int                 `orm:"auto"`
        Requirements        []*Requirement      `orm:"rel(m2m);rel_through(github.com/Hepri/test/models.OrderRequirement)"`
    }

    type OrderRequirement struct {
        Id          int          `orm:"auto"`
        Order       *Order       `orm:"rel(fk);on_delete(do_nothing)"`
        Requirement *Requirement `orm:"rel(fk);on_delete(do_nothing)"`
    }

    type Requirement struct {
        Id          int    `orm:"auto"`
        Name        string `orm:"size(100);"`
    }

And then somewhere

    ord := &models.Order{Id: 1}
    o := orm.NewOrm()
    o.LoadRelated(ord, "Requirements")

**Comment by mewben** [comment]
I'm sorry, I think I'm misunderstood. What I wanted is to select all users along with their roles. Is this possible or not yet implemented?

**Comment by Hepri** [comment]
You should query users, iterate over them, and query roles for each one

**Comment by mbitson** [comment]
Wow- iterating over users to query for their roles repeatedly is a terrible practice! 1000 users means a minimum of 1000 queries to display a single page? Terrible, terrible plan. LoadRelated should accept a slice of structs.

**Comment by ptman** [comment]
RelatedSel for m2m would be really important to keep the number of queries down

**Comment by Hepri** [comment]
@ptman, How you imagine reducing number of queries in sql m2m?

It always depends on context of usage. If you want to show posts and tags for every post you could do this:

```
select p.id,
       p.title,
       array_to_string(ARRAY(select t.name from tags t, post_tags pt where pt.tag_id = t.id and pt.post_id = p.id), ', ') tags
  from posts p
 order by id desc
 limit 100
```

**Comment by ptman** [comment]
@Hepri By joins, instead of looping in the controller code and doing several queries.

**Comment by Hepri** [comment]
@ptman It's still just overload of the database. For every tag you will retrieve all fields of post. If you need 1000 posts, and every post will have 5 tags, db will retrieve 5000 rows instead of 1000.

**Comment by ptman** [comment]
JOINs are what relational databases are made for. If the correct columns are indexed, the query is blazing fast, and it can be limited to just return the amount of rows you want. Query latency between the app and the database makes the loop much worse than having the DB do everything in one go. The relational database can be clustered to improve read performance, just like the frontend can be run on many instances. But the query latency cannot really be improved on.

**Comment by ljesus** [comment]
@ptman did you manage to find a solution for this? I also need to perform LoadRelated on a slice. Thanks.

**Comment by ptman** [comment]
Not yet

**Comment by novikk** [comment]
+1

**Comment by enjoydiy** [comment]
I happen to meet the issue. Can beego have the way to solve the problem?

**Comment by ptman** [comment]
I switched to gorm

**Comment by lomoalbert** [comment]
+1

**Comment by enjoydiy** [comment]
I think mongodb is suiteable for this case.
