### ISSUE TITLE
Open second port for admin APIs

### ISSUE THREAD

**Issue by jacek99** [beego/beego#128]
In our Java app, we use Dropwizard.
It has a great feature where it opens up 2 separate HTTP ports:
- one for public APIs
- one for admin APIs (closed off the firewall, so no one from outside can reach it).

On the admin port it has things such as:

a) health check API for integration with an operations monitoring system like Nagios:

http://dropwizard.codahale.com/manual/core/#health-checks

b) admin tasks (e.g. run garbage collection, refresh in-memory caches, run DB migration, etc):

http://dropwizard.codahale.com/manual/core/#tasks

It would be great if beego also supported opening up 2 separate ports by default in a similar fashion and offered out of the box support for admin APIs.

Also, check out Dropwizard's use of YAML for configuration, I think it is much nicer than the .ini format. You can see in there the options for public and admin ports:

http://dropwizard.codahale.com/manual/core/#configuration-defaults

**Comment by guodayang999** [comment]
很好！

**Comment by xietianyu** [comment]
excellent

**Comment by jiftle** [comment]
excellent
