### ISSUE TITLE
post 里收到的 RequestBody 为空？

### ISSUE THREAD

**Issue by ifq** [beego/beego#131]
我想多半是我使用的问题，但是我的问题如下：

测试 `example/beeapi`，为了测试post request，我用 firefox 的插件 poster 生成 post req。 poster 的配置如下图所示，我在server端添加了打印 `fmt.Println(this.Ctx.RequestBody)` 打出来是空的，而且创建出来的object 也是默认生成的。 请问是我哪里错了么？

![tmp2](https://f.cloud.github.com/assets/1496009/925437/d7b02af0-ff78-11e2-87fe-6cf8a9263302.PNG)

**Comment by zyx89513** [comment]
我用的最新版 还是有这个问题, 都是按文档来的, copyrequestbody = true也加了 , 打印出来还是空, 但是getstring可以获取到

**Comment by lornewang** [comment]
这个问题我也出现了，都是按照文档来的，copyrequestbody = true也加了，BConfig 也打印出 true，可就是读不到，好坑

**Comment by hoobean1996** [comment]
@lornewang  最后怎么解决的呢

**Comment by hoobean1996** [comment]
还是代码配置方便

**Comment by mcgrady-forever** [comment]
好像必须用bee run起服务 而且copyrequestbody=true 这样CopyRequestBody能读到数据
