### ISSUE TITLE
Cache | panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nirajNijju** [beego/beego#1316]
Hi,
I am using go1.4 and implemented cache in our application, I am getting(sometimes) this panic message.

goroutine 11 [running]:
github.com/astaxie/beego/cache.(_MemoryCache).item_expired(0xc20808c7b0, 0x0, 0x2f, 0x0)
        /usr/local/gopath/src/github.com/astaxie/beego/cache/memory.go:225 +0xbc
github.com/astaxie/beego/cache.(_MemoryCache).vaccuum(0xc20808c7b0)
        /usr/local/gopath/src/github.com/astaxie/beego/cache/memory.go:216 +0xfc
created by github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
        /usr/local/gopath/src/github.com/astaxie/beego/cache/memory.go:201 +0x399

goroutine 1 [chan receive, 205 minutes]:
github.com/astaxie/beego.(*App).Run(0xc20800a780)
        /usr/local/gopath/src/github.com/astaxie/beego/app.go:171 +0x363
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
        /usr/local/gopath/src/github.com/astaxie/beego/beego.go:277 +0x17c
main.main()
        /usr/local/gopath/src/Mediation/main.go:54 +0x5a9

**Comment by astaxie** [comment]
@nirajNijju could you provide your code snippet

**Comment by nirajNijju** [comment]
@astaxie, I am giving snippet ( only a use-case of cache )
	// class variable
	cacheObj, err = cache.NewCache("memory", `{"interval":300}`) 
	cacheRate, err = cache.NewCache("memory", `{"interval":300}`) 

	func myMethod(input chan MyObject) {

		isUseCache := false
		rateKeyNow :=  strconv.Itoa( (minNow+1)%60 )
		rateKeyPrev :=  strconv.Itoa( (minNow)%60 )
		if cacheRate.IsExist(rateKeyNow) {
			e := cacheRate.Incr(rateKeyNow)
			if nil != e{
				logger.SetLog("[cache] |error_message|  ", logs.LevelInformational, e)
			}
		}else {
			e := cacheRate.Put(rateKeyNow, 1, 300)
			if nil != e{
				logger.SetLog("[cache] |error_message|  ", logs.LevelInformational, e)
			} 
		}

		if cacheRate.IsExist(rateKeyNow) {
			e := cacheRate.Incr(rateKeyNow)
			if nil != e{
				logger.SetLog(" error_message ", logs.LevelInformational, e)
			}
		}else {
			e := cacheRate.Put(rateKeyNow, 1, 300)
			if nil != e{
				logger.SetLog(" error_message ", logs.LevelInformational, e)
			} 
		}

		var prevRate int 
		if cacheRate.IsExist(rateKeyPrev){
			prevRate = cacheRate.Get(rateKeyPrev).(int)
		}
		if prevRate > cacheThreshold {
			isUseCache = true
			isSaveCache=true
		}
		
		cacheUserKey := this.UserId +"_"+ this.SourcePlacement
		
		//checking in cache
		if isUseCache && cacheObj.IsExist(cacheUserKey)  { 
			obj := cacheObj.Get(cacheUserKey)
			if nil !=obj{ 							// if a key in cache is expired then it return nil till next cacheGC
				cacheObj := obj.(*MyObject)
				cacheObj.IsFromCache = true
				input <- *cacheObj
				logger.SetLog("[cache] |Returning  Obj from Cache | cacheUserKey: "+cacheUserKey, logs.LevelInformational, nil)
				return
			}
		}
		
		
		// process and get result
		obj := myProcess()
		
		input <- *obj
			
		// saving into cache
		if isSaveCache  {
			cacheObj.Put(cacheUserKey, obj, 300)
			logger.SetLog("[cache] |Saved into cache key: "+cacheUserKey, logs.LevelInformational, nil)
		}	
	}
