### ISSUE TITLE
Not obligatory relation in ORM

### ISSUE THREAD

**Issue by deadkrolik** [beego/beego#1323]
I have User model and field invited_by which is not required, because user can register himself, without invitation. It's the model:

``` go
type Users struct {
    Id int `form:"-"`
    Email string `form:"-"`
    InvitedBy int `form:"-"`
}
```

And I want to have the possibility to load inviter information using RelatedSel() method. I've rewrited model to this:

``` go
type Users struct {
    Id int `form:"-"`
    Email string `form:"-"`
    InvitedBy *Users `orm:"rel(one)"`
}
```

``` go
this.connection.QueryTable(model.TableName()).OrderBy("id").RelatedSel().All(&list)
```

But it always uses INNER JOIN query. How can I load another table using LEFT JOIN query?

**Comment by Hepri** [comment]
Here is the solution. Answer was just in documentation http://beego.me/docs/mvc/model/query.md#relatedsel

    InvitedBy *Users `orm:"rel(one);null"`

**Comment by deadkrolik** [comment]
Thank you, that works. But not so obvious.

And about params for RelateSel. I run this (according to [example](http://beego.me/docs/mvc/model/query.md#relatedsel)):

```go
type Users struct {
    Id int `form:"-"`
    Email string `form:"-"`
    InvitedBy *Users `orm:"rel(one);null;column(invited_by)"`
}

this.connection.QueryTable(model.TableName()).OrderBy("id").RelatedSel("users").All(&list)
```

And get error

```php
beego:unknown model/table name `users`
```

Which parameter would be correct?

**Comment by Hepri** [comment]
RelatedSel("InvitedBy")

**Comment by deadkrolik** [comment]
I still get

```php
beego:unknown model/table name `InvitedBy`
```

**Comment by ptman** [comment]
I'm also having trouble figuring out what to use as the string parameter for RelatedSel(). And I'm not the only one: https://stackoverflow.com/questions/27397306/how-to-use-relatedsel-method-on-beego-framework-properly

**Comment by bakanis** [comment]
I always thought it describes the depth level. The default level is 2. If in your template one has to get the value deeper than 2, eg. Parent.Childen.Grandchild then in the query the relation has to be set as RelatedSel(3). Otherwise you get nil.

**Comment by ptman** [comment]
More documentation would clearly be welcome. https://github.com/astaxie/beego/blob/a89f14d80dab442927bdc11d641aa1250ab8ad71/orm/orm_queryset.go#L117 shows that it can be given both string or integer parameters. The last integer parameter seems to replace relsDepth. But there is no test case for integer params, is there? Only for no params or a single string param: https://github.com/astaxie/beego/blob/a89f14d80dab442927bdc11d641aa1250ab8ad71/orm/orm_test.go#L988

**Comment by bakanis** [comment]
What about https://github.com/astaxie/beego/blob/a89f14d80dab442927bdc11d641aa1250ab8ad71/orm/orm_test.go#L1003 ?

**Comment by ptman** [comment]
I've tried four variations of the model name in my code: Record, record, Records, records. None of them worked.
