### ISSUE TITLE
ORM自动创建数据表的问题

### ISSUE THREAD

**Issue by willsky** [beego/beego#159]
首先很感谢你们提供这么优秀的框架(beego), 最新发布了orm, 文档上有提到可以自动在数据库中创建表,但是文档里也看不到怎样去创表,看了源码后,但是没有发现可以创建自动创表数据数据库的接口,请问是暂时还没有提供这些接口么?

**Comment by LiJoah** [comment]
@slene  
请问一个关于 auto_add_now ， auto_now  和 字段注释的问题：
     ```
     type TeamInfo struct {
	SchoolLevel string    `orm: "size(32);column(school_level);description(学历)" json:"school_level"`
	Email       string    `orm: "size(64);column(email);description(邮箱)" json:"email"`
	Created     time.Time `orm: "auto_now_add;type(datetime);column(created)" json:"created"`
	Updated     time.Time `orm: "auto_now;type(datatime);column(updated)" json:"updated"`
    ```
   我这样写，description 没有生效，然后我在添加一行的时候，created 和 updated 这两个字段应该是自动更新的是嘛？不需要我手动来维护这两个字段是嘛？
   如果是这样：我得到了一个 错误： Error 1048: Column 'created' cannot be null ；
  这个错误是否是表示 auto_add_now 和 auto_add 没有生效呢？
