### ISSUE TITLE
bee migrate - Could not run migration binary: exit status 2

### ISSUE THREAD

**Issue by theRemix** [beego/beego#1600]
running `bee migrate` fails, how do i get more information on why it's failing?

```
bee migrate -driver="postgres" -conn="postgres://postgres@localhost:5432/beego-demo?sslmode=disable"
2016/01/21 10:04:24 [INFO] Using 'postgres' as 'driver'
2016/01/21 10:04:24 [INFO] Using 'postgres://postgres@localhost:5432/beego-demo?sslmode=disable' as 'conn'
2016/01/21 10:04:24 [INFO] Running all outstanding migrations
2016/01/21 10:04:28 [ERRO] Could not run migration binary: exit status 2
```

the postgres user credentials should be right, because it was errorring on unauthorized access with wrong credentials, now it is not reporting that error anymore

**Comment by ivijayprasad** [comment]
Your migration query could be wrong. I'd the same issue and it was because mysql create table query was wrong.

The error description could have been better.

**Comment by u007** [comment]
there should be a better error debugging on this
i was trying to fix this, but it is taking too long time for me.
it need to show which migration file and which line number contains the error
and what is the exact sql error message.
it is so difficult to debug this way.

**Comment by u007** [comment]
@astaxie will this be worked on anytime soon? i find this very critical...

**Comment by gnanakeethan** [comment]
@astaxie I am also experiencing this issue. I am just a newbie here, 

``` 
$ bee api product_db
$ bee generate scaffold product -fields="id:int,name:string"
```

and proceeding "yes" causes the issue on my machine, Go version 1.6, OSX 10.11.4

**Comment by astaxie** [comment]
it's a low priority issue for me now.

**Comment by Marcelo-Rodriguez-Globant** [comment]
@astaxie  How can we fix it ? Im using mysql driver ; I have exactly the same situation @theRemix
