### ISSUE TITLE
Session providers should be able to use existing connections

### ISSUE THREAD

**Issue by mmindenhall** [beego/beego#1671]
When using a session provider that uses an external data store of some kind, there should be a way to supply an existing connection/resource for beego to use.  

It's likely that the application is using the data store for more than just managing beego sessions, so it makes sense to initialize the shared connection pool (or connection), and pass it in.  This avoids having multiple connection pools to the same data store within the application.

To fix this, I believe it will require either exposing the various Provider type fields and Provider vars, or adding a NewProvider function that allows the connection (`*sql.DB`, `*redis.Pool`, `*memcache.Client,` `*couchbase.Bucket`, `*ledis.DB`) to be passed in.

The biggest problem here is with ledis.  The ledis Provider is using a `*ledis.DB` directly, which it obtains as follows:

``` go
    cfg := new(config.Config)
    cfg.DataDir = lp.savePath
    nowLedis, err := ledis.Open(cfg)
    c, err = nowLedis.Select(lp.db)
```

If my application is already using ledis (it is), the call to ledis.Open will fail due to the default ledis listening ports already being in use.  Hence, I want to be able to explicitly set the `*ledis.DB` instance for the session provider to use.

**Comment by youngsterxyf** [comment]
@astaxie Maybe we should talk about this issue

**Comment by astaxie** [comment]
what's benefit use one pool? I think use separate connection will make application easily to maintain. mix the connection is not a good idea

**Comment by mmindenhall** [comment]
@astaxie, a few points:

1.  Especially for relational databases, connections are an expensive resource.  So having multiple connection pools in a single application (each of which may have open, but unused connections lying around) is inefficient
1.  I'm just asking for the _option_ to use an existing pool (or bucket, or db handle), so the beego user can decide how they want to manage their database connections.  Anyone who wants to let beego create a new pool/bucket/handle can continue to do so.
1.  The current behavior is a big problem for ledis, as ledis automatically listens on port 6380 for incoming connections.  If my application has already opened ledis, when beego starts the session provider, it will try to create a separate ledis instance also listening on port 6380...which will fail.  Hence, I want to be able to specify the `*ledis.DB` for the session provider.
