### ISSUE TITLE
Cross-database references

### ISSUE THREAD

**Issue by mjanda** [beego/beego#1722]
I want to have some models pointing to different databases on the same machine and do cross-database joins. Beego ORM will turn db_name.table_name into

```
`db_name.table_name`
```

instead of

```
`db_name`.`table_name`
```

I can do it in this hacky way (ideally keep proper quoting character globally instead of hardcoding it), but it still feels hacky.

```
func (u *XXX) TableName() string {
    return "database_name`.`table_name"
}
```

Proper fix would be probably to modify getTableName in models_utils.go to quote it automatically, but I'm not sure how to get proper quote character in there.

**Comment by astaxie** [comment]
@mjanda How about if the table name has `.`, like `test.a`
