### ISSUE TITLE
Why Models are not like controllers

### ISSUE THREAD

**Issue by sivakumar07** [beego/beego#1915]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   1.6.1
2. What operating system and processor architecture are you using (`go env`)?
   amd64 darwin

Why models don't extend from model or orm struct like controllers?
Why Every model have to implement save, insert, update, delete? Can we handle these in a common interface? @astaxie

**Comment by astaxie** [comment]
@sivakumar07 that's our next planning.

**Comment by u007** [comment]
👍  im trying to make this work too, maybe with observer of beforesave, aftersave,
and validators. im still new to golang, i find golang nature isn't easy ...

**Comment by ysqi** [comment]
@sivakumar07 @u007 I  implement save, insert, update, delete From Beego Model, see [here](https://gist.github.com/ysqi/fe7cbb979cee180e3826b4aa4acb2c04)

**Comment by hsw409328** [comment]
现在还不支持not like吗？@astaxie
