### ISSUE TITLE
对于beego开发的一个建议

### ISSUE THREAD

**Issue by zhenweiwang1990** [beego/beego#193]
由于go get 本身不支持版本控制，搞的我有的时候不敢 go get -u github.com/astaxie/beego ，你们开发团队也不敢轻易push到master上，比如这次，我就遇到了API更改导致的问题：
undefined: beego.Context

建议beego平时开发push到开发分支上，功能稳定再合并到master上，功能稳定，到达历程碑，可以打tag，并给出changelog，另外合并到master上的时候如果有API的更改，也希望能给出changelog。

**Comment by dryyun** [comment]
@Shoot-tigers-tonight  import "github.com/astaxie/beego/context" 试试吧
