### ISSUE TITLE
用户无法选择性的读取body

### ISSUE THREAD

**Issue by MonMon2016** [beego/beego#2008]
看下这段代码，router.go的644行：

```
if r.Method != "GET" && r.Method != "HEAD" {
    if BConfig.CopyRequestBody && !context.Input.IsUpload() {
        context.Input.CopyBody(BConfig.MaxMemory)
    }
    context.Input.ParseFormOrMulitForm(BConfig.MaxMemory)
}
```

如果我设置CopyRequestBody为false，就会解析成表单，感觉这里的逻辑是否有点问题？我现在要实现PUT方式文件上传的API，文件内容是写在body里发送的，我希望先解析header来确定这次请求是否合法，再决定是继续读取完整的body还是直接回复客户端，而beego进行了如上处理后，貌似就没法做到这一点了？如果我要PUT的文件非常大时，就只能改大MaxMemory，等服务端把tcp包收全，组装成body再保存成临时文件后才交由我处理，显然不能满足要求，我想是否可以改为：

```
if r.Method != "GET" && r.Method != "HEAD" {
    if !context.Input.IsUpload() {
        if BConfig.CopyRequestBody {
            context.Input.CopyBody(BConfig.MaxMemory)
        }
    } else {
        context.Input.ParseFormOrMulitForm(BConfig.MaxMemory)
    }
}
```

这样就可以由用户选择是否由beego负责读取body，就能实现解析header后直接放弃收取body，我查了下go标准库的http服务器是在https://github.com/golang/go/issues/3595 的修改里支持了处理我提到的这种应用场景，但现在beego封装了一层后，反而不能这么用了，不知道我理解上有没有问题？或者beego有其他预留的接口可以实现我说的情况？

**Comment by imiskolee** [comment]
赞同，我们需要做ReverseProxy 如果是强制性的解析，那么就无法优雅的使用ReverseProxy。

**Comment by imiskolee** [comment]
@MonMon2016  我认为更通用的做法就像是 https://github.com/astaxie/beego/pull/2009 这里一样，提供一个配置项去控制是否进行自动的request body read动作。这样对于应用端就有更强的控制能力

**Comment by MonMon2016** [comment]
@imiskolee 目前是有BConfig.CopyRequestBody这个配置项，但是不好用

**Comment by imiskolee** [comment]
@MonMon2016 `CopyRequestBody` 的语义是不是在非上传的情况下进行一次完整的RequestBody拷贝。
`AutoReadRequestBody` 的语义是否自动对request.Body进行Read动作。如果我们希望介入Read相关的，比如Content-Length 过长则自动错误，或者进行Proxy，那么开启`AutoReadRequestBody = false` 则可以实现零拷贝

**Comment by imiskolee** [comment]
但是由于有以下这种代码的存在

```go
//input.go line 301

// Query returns input data item string by a given string.
func (input *BeegoInput) Query(key string) string {
	if val := input.Param(key); val != "" {
		return val
	}
	if input.Context.Request.Form == nil {
		input.Context.Request.ParseForm()
	}
        //这里会导致进行Body Read 并且被关闭。将无法实现AutoReadRequestBody的语义。
       //另外不理解的是方法名是Query 为啥行为会有歧义
	return input.Context.Request.Form.Get(key)
}

```

**Comment by MonMon2016** [comment]
我文档没有细读，原来还有这个配置项...受教了
