### ISSUE TITLE
Serving svgz files

### ISSUE THREAD

**Issue by ahmadissa** [beego/beego#2011]
1. What version of Go and beego are you using (`bee version`)?
   bee   :1.4.1
   beego :1.6.1
   Go    :go version go1.6.2 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?

Linux / amd64
1. What did you do?

I want to serve .svgz files from under static folder.

im testing on new application created by bee new
1. What did you expect to see?

i tried to display the img by putting the url on chrome, it displayed properly through apache server but gave the below error on beego server:

This page contains the following errors:

error on line 1 at column 1: Encoding error
Below is a rendering of the page up to the first error.

.svg files are displaying fine

below are the response header from beego server:

Accept-Ranges:bytes
Content-Length:1091
Content-Type:image/svg+xml
Date:Sat, 25 Jun 2016 09:17:19 GMT
Last-Modified:Sat, 25 Jun 2016 09:11:43 GMT
Server:beegoServer:1.6.1

and below are from apache:

Accept-Ranges:bytes
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:1091
Content-Type:image/svg+xml
Date:Sat, 25 Jun 2016 09:19:05 GMT
ETag:"443-53606d4c3ae10"
Keep-Alive:timeout=15, max=98
Last-Modified:Fri, 24 Jun 2016 14:17:30 GMT
Server:Apache/2.4.6 (Linux/SUSE)

when i added the below lines:

beego.BConfig.EnableGzip = true
beego.BConfig.WebConfig.StaticExtensionsToGzip = []string{".css", ".js", ".svgz"}

the img still NOT displaying but with below header response 

Accept-Ranges:bytes
Content-Encoding:gzip
Content-Length:1119
Content-Type:image/svg+xml
Date:Sat, 25 Jun 2016 09:28:46 GMT
Last-Modified:Sat, 25 Jun 2016 09:11:43 GMT
Server:beegoServer:1.6.1

**Comment by ahmadissa** [comment]
I think when i added the below two lines the server is compressing the svgz again

beego.BConfig.EnableGzip = true
beego.BConfig.WebConfig.StaticExtensionsToGzip = []string{".css", ".js", ".svgz"}

how can we have : Content-Encoding:gzip for .svgz files

**Comment by astaxie** [comment]
@ahmadissa could you provide the url and test files
