### ISSUE TITLE
RawSetter.QueryRows do not support Cusom Fields when  mapping to Struct

### ISSUE THREAD

**Issue by tasdingoo** [beego/beego#2034]
1. What version of Go and beego are you using (`bee version`)?
   bee   :1.4.1
   beego :1.6.0
   Go    :go version go1.5.3 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
3. What did you do?
   type MyTime time.Time
   type MyStruct struct {
       Id int
       Name string
       CreateTime MyTime
   }
   func GetMyStruct (id int){
       o := orm.NewOrm()
       sql := "select \* from my_struct"
       var myStructs []*MyStruct
       o.Raw(sql).QueryRows(&myStructs)
   }
4. What did you expect to see? What did you see instead?
   
   What I wanna see is the correct value of  field "CreateTime".
   
   e.g.  "2016-05-10 12:09:34" is the value of CreateTime in database. But when I Use the func  "QueryRows" to  query that, it returns zero.

**Comment by astaxie** [comment]
yes

**Comment by tasdingoo** [comment]
then what?

**Comment by astaxie** [comment]
there's no plan to support now

**Comment by pawatzaza** [comment]
ok

**Comment by astaxie** [comment]
@pawatzaza what are you doing?
