### ISSUE TITLE
BeeLogger实现存在性能问题

### ISSUE THREAD

**Issue by gaokewoo** [beego/beego#2040]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   bee   :1.4.1
   beego :1.6.1
   Go    :go version go1.5 windows/amd64
2. 现象：
   在性能测试时，将配置文件中的loglevel改为3，虽然日志不输出了，但是查看调用的heap，发现很多都锁在sync.(*Pool).getSlow上。

原因查找：
看了下代码，发现即使我将配置中的loglevel改为3，但并不影响BeeLogger中的bl.level成员变量，这个变量在初始化时值为LevelDebug，可以通过SetLevel设置，但并没有看到调用该方法的代码。
这样会导致，在通过beego.BeeLogger写日志的时候，只要level是大于等于LevelDebug的，都会调用方法fmt.Sprintf将日志数据存到msg变量中，而fmt.Sprintf的实现用到了sync.(*Pool)锁。

尝试：
通过手工调用beego.BeeLogger.SetLevel(3)，看了下heap，锁的情况减少了很多。

**Comment by astaxie** [comment]
If `fmt.Sprintf` is the root cause, we can't do anything
