### ISSUE TITLE
orm 使用问题

### ISSUE THREAD

**Issue by cddaiwei** [beego/beego#2063]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   go version go1.6.2

bee version 1.4.1
1. What operating system and processor architecture are you using (`go env`)?
   windows7 x64
2. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

beego orm 使用过程碰到问题
有如下表
//group表定义

```
type Group struct {
    Id             int
    Name           string //组名 
    Creater        *User   `orm:"rel(fk);column(creater)"` //创建人
    MemberUserList []*User `orm:"rel(m2m);rel_table(group_member)"` //成员列表
    AdminList      []*User `orm:"rel(m2m);rel_table(group_admin)"`  //管理员列表
}
```

//user表定义

```
type User struct {
    Id              int
    Name            string //用户名
    GroupCreateList []*Group `orm:"reverse(many)"` //创建组列表
    GroupMemberList []*Group `orm:"reverse(many);rel_table(group_member)"` //所在组列表
    GroupAdminList  []*Group `orm:"reverse(many);rel_table(group_admin)"`  //为管理员的组列表
}
```

通过 如下语句（1）

```
        o := orm.NewOrm()
    user := User{}
    o.QueryTable("user").Filter("id", 1).One(&user)

    o.LoadRelated(&user, "GroupMemberList") 
        o.LoadRelated(&user, "GroupAdminList")
```

可以顺利执行并得到关联关系

但是如果执行以下语句 （2）

```
        o := orm.NewOrm()
    group := Group{}
    o.QueryTable("group").Filter("id", 1).One(&group)

    o.LoadRelated(&group, "MemberUserList")  //执行到此处代码就报错 提示 panic: runtime error: invalid memory address or nil pointer dereference
        o.LoadRelated(&user, "AdminList")
```

通过测试 若去掉Group表里面的fk和User表里面的反向关联。以上两种方式都可以顺利执行并得到m2m的关联关系

疑问：表如上定义是否符合beego orm 规范
1. What did you expect to see?
   期望解决上述问题
2. What did you see instead?
   暂时无

**Comment by astaxie** [comment]
@cddaiwei could you update the issues for the code use the (code block)[https://guides.github.com/features/mastering-markdown/#examples]?

**Comment by cddaiwei** [comment]
@astaxie The complete code examples are as follows


    package main

    import (
	    "fmt"
	    "github.com/astaxie/beego/orm"
	    _ "github.com/go-sql-driver/mysql"
    )

    //user表定义 define table user
    type User struct {
	    Id              int
	    Name            string   //用户名 name
	    GroupCreateList []*Group `orm:"reverse(many)"`                         //创建组列表 create groups
	    GroupMemberList []*Group `orm:"reverse(many);rel_table(group_member)"` //所在组列表 memebers
	    GroupAdminList  []*Group `orm:"reverse(many);rel_table(group_admin)"`  //为管理员的组列表 admins
    }

    //group表定义 define table group
    type Group struct {
	    Id             int
	    Name           string  //组名
	    Creater        *User   `orm:"rel(fk);column(creater)"`          //创建人 create
	    MemberUserList []*User `orm:"rel(m2m);rel_table(group_member)"` //成员列表 members
	    AdminList      []*User `orm:"rel(m2m);rel_table(group_admin)"`  //管理员列表 admins
    }

    //初始化相关数据 init datas
    func init() {
	     err := orm.RegisterDriver("mysql", orm.DRMySQL)
	     if err == nil {
		    err = orm.RegisterDataBase("default", "mysql", "root:123456@/test?charset=utf8")
		    if err == nil {
			    orm.RegisterModel(new(User), new(Group))
		    	err = orm.RunSyncdb("default", false, true)
			    if err != nil {
				    fmt.Println("RunSyncdb Err:", err)
			    } else {
				    //添加测试数据  add test data
				    addTestData()
			    }
		    } else {
			    fmt.Println("RegisterDataBase Err:", err)
		    }
	    } else {
		    fmt.Println("RegisterDriver Err:", err)
	    }
    }

    //添加测试数据 add test data
    func addTestData() {
	    o := orm.NewOrm()

	    user := User{}
	    user.Name = "test1"
	    uId, err := o.Insert(&user)
	    if err == nil {
		    user.Id = int(uId)
		    group := Group{}
		    group.Name = "group1"
		    group.Creater = &user
	    	gId, err := o.Insert(&group)
	    	if err == nil {
			    group.Id = int(gId)
			    m2m := o.QueryM2M(&group, "MemberUserList")
			    group.MemberUserList = append(group.MemberUserList, &user)
			    _, err := m2m.Add(&user)
			    if err == nil {
				    m2m = o.QueryM2M(&group, "AdminList")

				    _, err := m2m.Add(&user)
				    if err != nil {
				    	fmt.Println("m2m.Add AdminList Failed:", err)
				    }
			    } else {
				    fmt.Println("m2m.Add MemberUserList Failed:", err)
			    }
		    } else {
			    fmt.Println("Insert Group Failed:", err)
		    }
	    } else {
		    fmt.Println("Insert User Failed:", err)
	    }
    }

    //获取user的相关关联  get user relate information
    func GetUserRelate() {
	    o := orm.NewOrm()
	    user := User{}
	    err := o.QueryTable("user").Filter("id", 1).One(&user)
	    if err == nil {
		    _, err1 := o.LoadRelated(&user, "GroupCreateList")
		    _, err2 := o.LoadRelated(&user, "GroupMemberList")
		    _, err3 := o.LoadRelated(&user, "GroupAdminList")
		    if err1 == nil && err2 == nil && err3 == nil {
			    fmt.Println("Relate User: ", user)
		    }

	    } else {
		    fmt.Println("QueryTable Failed:", err)
	    }
    }

    //获取group的相关关联 get group relate information
    func GetGroupRelate() {
	    o := orm.NewOrm()
	    group := Group{}
	    err := o.QueryTable("group").Filter("id", 1).One(&group)
	    if err == nil {
		    _, err1 := o.LoadRelated(&group, "MemberUserList") //执行到此处代码就报错 提示 panic: runtime error: invalid memory address or nil pointer dereference
		    _, err2 := o.LoadRelated(&group, "AdminList")
		    if err1 == nil && err2 == nil {
			    fmt.Println("Relate Group: ", group)
		    }
	    } else {
		    fmt.Println("QueryTable Failed:", err)
	    }
    }

    func main() {
	    GetUserRelate()
	    GetGroupRelate()
    }

**Comment by cddaiwei** [comment]
@astaxie I want to solve the problem and i need you help thank you

**Comment by astaxie** [comment]
@cddaiwei could you provide your database SQL. So we I can reproduce in my local. Thanks

**Comment by baixiaoshi** [comment]
one这个方法有时候取不到数据，db中明显只有一条，但是有时候就是取不到
