### ISSUE TITLE
开启热更新后,在Bee工具下运行偶尔panic

### ISSUE THREAD

**Issue by zzzzzlucky** [beego/beego#2099]
Bee v1.5.0
Beego 1.7
都是今天刚更新的
System Linux mint17.3,Ubuntu14.04的核

背景:
1\开启了beego的热更新
2\项目代码都能成功编译
3\bee工具用bee run命令运行后什么都没做,过会儿就会出现
4\偶然性,不是每次
5\ GOROOT=/usr/local/go,GOPATH=/data/mygo
具体错误信息
![](http://ww2.sinaimg.cn/large/c704dca4gw1f6y2jeri2bj20mz0d9adk.jpg)

更新问题:
今天又遇到了一次,更新点线索
今天触发的操作是,在bee run运行中,使用ctrl+c停止进程时,出现了
![](http://ww4.sinaimg.cn/large/c704dca4gw1f6z496vgs9j20jk0nhdkl.jpg)

**Comment by skyleelove** [comment]
同问，我也遇到了类似的问题
