### ISSUE TITLE
Can't define HTTP code in Error Handling

### ISSUE THREAD

**Issue by dimaxgl** [beego/beego#2118]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?

> ├── Beego     : 1.7.0
> ├── GoVersion : go1.6.2
> ├── GOOS      : linux
> ├── GOARCH    : amd64
> ├── NumCPU    : 4
> ├── GOPATH    : /home/dm/gocode
> ├── GOROOT    : /usr/lib/go-1.6
> ├── Compiler  : gc
> └── Date      : Thursday, 25 Aug 2016
1. What operating system and processor architecture are you using (`go env`)?

> GOARCH="amd64"
> GOBIN=""
> GOEXE=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/dm/gocode"
> GORACE=""
> GOROOT="/usr/lib/go-1.6"
> GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
> GO15VENDOREXPERIMENT="1"
> CC="gcc"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
> CXX="g++"
> CGO_ENABLED="1"
1. I need to get always HTTP code 200.
   I try to define own ErrorController as it described in: [http://beego.me/docs/mvc/controller/errors.md](http://beego.me/docs/mvc/controller/errors.md)

I tried to use Finish() function, for example:

`func (c *ErrorController) Finish() {
    c.Ctx.Output.SetStatus(200)
}`

I tried to use c.Ctx.ResponseWriter.WriteHeader(200), but in both cases output HTTP code is error code, such as 404,500, etc.

**Comment by dchukmasov** [comment]
Were you able to resolve this?
