### ISSUE TITLE
grace模块热重启不完善（旧连接在还未处理完的情况下就被强制关闭了）

### ISSUE THREAD

**Issue by AdamGuan** [beego/beego#2123]
环境
go version: 1.7
beego version: 1.6.1
centos7.0, amd64
1. 开启Graceful后， 运行kill -HUP pid重启进程的时候， 旧连接其实并没有继续处理， 而是直接关闭了随着旧进程, 看了代码是在grace/server.go中process.Kill()的时候把新进程的父进程直接杀死, 发送的是SIGKILL信号，进程不会处理，直接被杀死，其实在handleSignals函数里面也确实没有处理这种信号。所以，代码改为如下：
   文件：grace/server.go，  函数ListenAndServe()以及 ListenAndServeTLS()
   
   ```
   //      err = process.Kill()
   err = process.Signal(os.Interrupt)
   ```
   
   经过测试可以正常处理完未完成的连接。
2. 上次有提到grace模块出现panic: sync: negative WaitGroup counter的错误，日志是定位到.Add(1)那里出的错，说是在beego 1.7里面修复，但是看了代码似乎也没有看到grace这块的处理。  看能否如下修改 
   文件： grace/listener.go， 函数Accept(), 加上recover
   
   defer func() {
       if r := recover(); r != nil {
           log.Println("WaitGroup <= -2  ", r)
       }
   }()
   gl.server.wg.Add(1)

**Comment by zjjott** [comment]
+1

**Comment by linclin** [comment]
good

**Comment by astaxie** [comment]
please try the develop branch. There's a PR fix this.
