### ISSUE TITLE
ORM cannot read table with uppercase letter on it's name

### ISSUE THREAD

**Issue by ronaldwh** [beego/beego#2143]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   Beego: 1.7.90
   Go: go1.6.3
2. What operating system and processor architecture are you using (`go env`)?
   windows
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

var user User
o := orm.NewOrm()
err := o.QueryTable("User").Filter("Id", "10").One(&user)
1. What did you expect to see?

SQL Query should be '[SELECT T0.`Id`, T0.`Email` FROM `User` T0 WHERE T0.`Id` = ? LIMIT 1] - `10`'
The table's and field's names should start with capital letter.
1. What did you see instead?

SQL Query is [SELECT T0.`id`, T0.`email` FROM `user` T0 WHERE T0.`id` = ? LIMIT 1] - `10`
the err is 'Error 1146: Table 'dbname.user' doesn't exist

This error is because of the table's name does not start with capital letter, it should use 'dbname.User' instead.

**Comment by astaxie** [comment]
beego ORM use the snakeString to format the fields and tablename. It will turn to lowercase

**Comment by ronaldwh** [comment]
Does that mean we have to change all our tablenames to lowecase? and if that is not the option, we can't use beego ORM? Is there any other alternative that we can use?

**Comment by astaxie** [comment]
you can define like this:

```
type User struct {
    Id int         `orm:"column(Id)"`
    Name string    `orm:"column(Name)"`
}

func (u *User) TableName() string {
    return "User"
}
```

**Comment by ronaldwh** [comment]
I have tried that and now it throws an error

![image](https://cloud.githubusercontent.com/assets/1446641/18306363/0e9a3f6a-751e-11e6-850e-4f64eded23ad.png)

**Comment by astaxie** [comment]
@ronaldwh could you provide more example code for me.

**Comment by ronaldwh** [comment]
Hi, I created the project with `bee api `command 
this is my 'main.go'

```
package main

import (
	_ "api-1.0/routers"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

func init() {
	orm.RegisterDriver("mysql", orm.DRMySQL)
	
        orm.RegisterDataBase("default", "mysql", "removed_on_purpose")
}

func main() {
	orm.Debug = true
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}
	beego.Run()
}
```

and this is my 'user.go' in the models folder.

```
package models

import (
	"errors"

	"github.com/astaxie/beego/orm"
)

var (
	UserList map[string]*User
)

func init() {

	orm.RegisterModel(new(User))

}

type User struct {
	Id    int    `orm:"column(Id)"`
	Email string `orm:"column(Email)"`
}

func (u *User) TableName() string {
	return "User"
}

func AddUser(u User) int {
	return 0
}

func GetUser(uid int) (u *User, err error) {
	return nil, errors.New("Not implemented")
}

func GetAllUsers() map[string]*User {
	return UserList
}

func UpdateUser(uid string, uu *User) (a *User, err error) {
	return nil, errors.New("User Not Exist")
}

func Login(username, password string) bool {
	var user User
	o := orm.NewOrm()
	err := o.QueryTable("User").Filter("Id", "10").One(&user)

	checkErr(err)

	return false
}

func DeleteUser(uid string) {
	//	delete(UserList, uid)
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

```

**Comment by monday-ch** [comment]
@astaxie  Hi, is that possible to make the "snakeString" as a public function that we can set the name-to-field as needed,  just like  the [sqlx](https://github.com/jmoiron/sqlx/blob/f980a91bdc37abef88269b8f122d7de6352102f5/sqlx.go#L18-L28)  : `var NameMapper = strings.ToLower`


 And another thing, there looks a little problem with the snakeString function you used in the code:
The comment say XxYY to xx_yy, and actually it is xx_y_y (and what I want is xx_yy in my code)
```
// snake string, XxYy to xx_yy , XxYY to xx_yy
func snakeString(s string) string {
	data := make([]byte, 0, len(s)*2)
	j := false
	num := len(s)
	for i := 0; i < num; i++ {
		d := s[i]
		if i > 0 && d >= 'A' && d <= 'Z' && j {
			data = append(data, '_')
		}
		if d != '_' {
			j = true
		}
		data = append(data, d)
	}
	return strings.ToLower(string(data[:]))
}
```
  
Thanks.

**Comment by amrfaissal** [comment]
@monday-ch Can you report the `snakeString` bug [here](https://github.com/astaxie/beego/issues/new) so we can fix it? Thanks.
