### ISSUE TITLE
The insertFilter didn't respect the given pattern, and caused redirect exception

### ISSUE THREAD

**Issue by thanzen** [beego/beego#2154]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   Go 1.7
   Beego 1.7.0
2. What operating system and processor architecture are you using (`go env`)?
   Ubuntu 15
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
   code is cloned from **https://github.com/beego/wetalk** without modifcation.

The line below caused the problem.

beego.InsertFilter("/login/*", beego.BeforeRouter, auth.OAuthRedirect)

This will lead to circular redirect exception when user tried to access http://localhost:8080/login
    error 2016/09/11 02:58:16 [log.go:70] [E] OAuthRedirect unknown provider 
1. What did you expect to see?
   The filter should be applied  to /login since the patter is /login/\* 
2. What did you see instead?
   redirect exception 
   error 2016/09/11 02:58:16 [log.go:70] [E] OAuthRedirect unknown provider

**Comment by alexandru-porcescu** [comment]
+1

**Comment by criminalist** [comment]
+1
