### ISSUE TITLE
ORM使用PostgreSQL修改表结构问题

### ISSUE THREAD

**Issue by zdreamx** [beego/beego#2169]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   GO1.7.1
   beego 1.7.0
2. What operating system and processor architecture are you using (`go env`)?
   linux_AMD64
3. What did you do?
   使用PostgreSQL.
   当表结构修改过后，比如添加一个 BYTE 类型的字段。重新bee run后数据表格不能自动修改。
   其他数据库没有该问题
4. What did you expect to see?
5. What did you see instead?

**Comment by astaxie** [comment]
你想表达什么意思啊？我没听明白

**Comment by zdreamx** [comment]
在使用PostgreSQL数据库的情况下。
假设我原来已经有一张表。然后我修改了这个表结构，就是添加一些新的字段，比如下图


然后用orm.RegisterModel注册模型，在mysql数据库下一切都正常。在PostgreSQL下执行添加字段到有byte的类型的字段就出问题了。


2016-09-20






张建义
浙江理工大学 现代纺织装备研发中心
手机：13750832432
邮箱: zdreamx@126.com
网站: www.zdreamx.com



发件人：astaxie <notifications@github.com>
发送时间：2016-09-19 20:57
主题：Re: [astaxie/beego] ORM使用PostgreSQL修改表结构问题 (#2169)
收件人："astaxie/beego"<beego@noreply.github.com>
抄送："zdreamx"<zdreamx@126.com>,"Author"<author@noreply.github.com>

你想表达什么意思啊？我没听明白

**Comment by zdreamx** [comment]
我以前在qq群里发过
[杭州]zdreamx<zdreamx@126.com> 2016-06-14 18:20:51
@[上海]Asta谢 orm 使用postgre数据库  当向某一个表添加字段，字段类型是uint8或其他时。会发生错误。错误原因是sql语句有问题，生成的sql格式如下：ALTER TABLE "tablexxx" ADD COLUMN "fieldxxx" smallint CHECK("%COL%" >= 0 AND "%COL%" <= 255) NOT NULL  DEFAULT 0 。其中%COL% 未作替换。我查看新建表格时的sql那句那里是做了替换的。
[杭州]zdreamx<zdreamx@126.com> 2016-06-14 18:24:19查看前后消息
@[上海]Asta谢 有时间看一下。定位于orm/cmd_utils.go ->getColumnAddQuery函数


2016-09-20






张建义
浙江理工大学 现代纺织装备研发中心
手机：13750832432
邮箱: zdreamx@126.com
网站: www.zdreamx.com



发件人：astaxie <notifications@github.com>
发送时间：2016-09-19 20:57
主题：Re: [astaxie/beego] ORM使用PostgreSQL修改表结构问题 (#2169)
收件人："astaxie/beego"<beego@noreply.github.com>
抄送："zdreamx"<zdreamx@126.com>,"Author"<author@noreply.github.com>

你想表达什么意思啊？我没听明白

**Comment by zdreamx** [comment]
晕。。。邮件回复 直接贴出来了。。。。
