### ISSUE TITLE
orm中，如何指定自定义多对多查询中LoadRelated时的中间表名和字段

### ISSUE THREAD

**Issue by wjlight** [beego/beego#2203]
结构体：
`type Post struct {
    Id    int64
    Title string
    Tags  []*Tag orm:"rel(m2m)"
}

type Tag struct {
    Id    int64
    Name  string
    Posts []*Post orm:"reverse(many)"
}`

在使用orm.LoadRelated的时候，查询时默认以 “post_tags” 名的中间表，和“post_id” 和 “tag_id” 两个字段，请问可以指定这个中间表的名字么和字段么？

**Comment by tonyzzp** [comment]
orm:"rel(m2m);rel_table(the_table_name)"
