### ISSUE TITLE
Can't set headers in custom error handler

### ISSUE THREAD

**Issue by smacker** [beego/beego#2207]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?

```
root@10586e8c52d2:/go/src/tms# bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.2

├── Beego     : 1.7.1
├── GoVersion : go1.7
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 1
├── GOPATH    : /go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Monday, 3 Oct 2016
```
1. What operating system and processor architecture are you using (`go env`)?

```
root@10586e8c52d2:/go/src/tms# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build080315219=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
1. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.

```
// minimal example for router.go:
return func jsonError(rw http.ResponseWriter, r *http.Request) {
    rw.Header().Set("Content-Type", "application/json; charset=utf-8")
    rw.Write("{\"message\":\"correct json\"}")
}

func init() {
    beego.ErrorHandler("404", jsonError)
}
```
1. What did you expect to see?
   "Content-Type: application/json; charset=utf-8" header in response.
2. What did you see instead?
   Header: "Content-Type: text/plain; charset=utf-8"

Also I can't set any other header.

Looks like it happens because beego call `ctx.ResponseWriter.WriteHeader(code)` before `err.handler(ctx.ResponseWriter, ctx.Request)` in `executeError` ( https://github.com/astaxie/beego/blob/master/error.go#L418 ).

If I change order of this calls - everything works as expected.

**Comment by apremalal** [comment]
Helo Devs,

I can confirm this issue with bee version 1.9.2 and beego version 1.9.2.
