### ISSUE TITLE
AppConfigPath undefined

### ISSUE THREAD

**Issue by PumpkinSeed** [beego/beego#2230]
1. What version of Go and beego are you using (`bee version`)?
   Go1.7.1
   BeeGo1.5.2
2. What operating system and processor architecture are you using (`go env`)?
   Fedora - Linux - amd64
3. What did you do?
   I wanted to use the `beego.AppConfigPath` to change the place of the config file.
4. What did you expect to see?
   Change the configuration file place.
5. What did you see instead?
   error: undefined: beego.AppConfigPath

[Documentation](https://beego.me/docs/mvc/controller/config.md#basic-config)

**Comment by airylinus** [comment]
there is no such variable named  beego.AppConfigPath so far as I know.
do you mean beego.appConfigPath ?  beego/config.go line 120.

btw: You may use beego.LoadAppConfig() load your own config file instead of change the private property.
That's what I have done --> https://github.com/airylinus/inspector

**Comment by PumpkinSeed** [comment]
Hi @airylinus 

I didn't want to change the private property, I just wanted to use the property which is in the documentation. If we are talking about the same propertz I don't understand why this important thing is a private property, because in this case it is block the managament of the configuration.

What this property provide make better management if my binary in the `/usr/bin/` and the configuration file in the `/etc/` it is require to set the config file location. 

---

I checked the source and I think the LoadAppConfig property name is confusing because it is not loading an appconfig, it is setting it. It is good for me, but I think you yhould update the documentation on the website. Can I somehow contribute or help to you? 

Thank you,
Ferenc

**Comment by malaschitz** [comment]
```
func init() { //func init in main.go
fmt.Println("INIT")
configFile := flag.String("config", "conf/app.conf", "Path to config file")
flag.Parse()
fmt.Println("Config file", *configFile)
err := beego.LoadAppConfig("ini", *configFile)
```

**Comment by PumpkinSeed** [comment]
Close it because it's irrelevant, I guess.
