### ISSUE TITLE
beego 原生sql，参数类型为time.Time，会报错

### ISSUE THREAD

**Issue by uniqueque** [beego/beego#2233]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
   | ___ \
   | |_/ /  ___   ___
   | ___ \ / _ \ / _ \
   | |_/ /|  __/|  **/
   __**/  _**| _**| v1.5.2

├── Beego     : 1.7.1
├── GoVersion : go1.7
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : D:\Code\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Wednesday, 19 Oct 2016
1. What operating system and processor architecture are you using (`go env`)?
   set GOARCH=amd64
   set GOBIN=
   set GOEXE=.exe
   set GOHOSTARCH=amd64
   set GOHOSTOS=windows
   set GOOS=windows
   set GOPATH=D:\Code\Go
   set GORACE=
   set GOROOT=C:\Go
   set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
   set CC=gcc
   set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
   set CXX=g++
   set CGO_ENABLED=1
2. What did you do?
   beego1.7.1中执行原生sql，参数为time.Time时，会导致报错，
   现在orm中getFlatParams的代码是
   if fi != nil && fi.fieldType == TypeDateField {
   arg = v.In(tz).Format(formatDate)
   } else if fi != nil && fi.fieldType == TypeDateTimeField {
   arg = v.In(tz).Format(formatDateTime)
   } else {
   arg = v.In(tz).Format(formatTime)
   }
   原生sql执行，fi传的是nil，执行的是else，变成time格式了而不是datetime

个人修改
if fi.fieldType == TypeDateField {
    v = t.In(tz).Format(formatDate)
} else if fi.fieldType == TypeDateTimeField {
    v = t.In(tz).Format(formatDateTime)
} else if fi.fieldType == TypeTimeField {
    v = t.In(tz).Format(formatTime)
} else {
    v = t.In(tz).Format(formatDateTime)
}

**Comment by xlon3** [comment]
我也遇到了这个问题，由 1.6.1 升级至 1.7.1 后，orm.Raw() 里的 time.Time 默认类型由 formatDateTime 改成了 formatTime ，现只能手动修改默认值以兼容业务代码。
