### ISSUE TITLE
请在 bee 生成时生成 .editorconfig

### ISSUE THREAD

**Issue by wenerme** [beego/beego#2243]
因为每个人的编辑器都有所不同,如果按照 go 的方法来,那么所有的都是使用 tab 而不是 space, 所以建议生成  .editorconfig 以便于更好的统一代码风格

**Comment by wei18810109052** [comment]
go语言是统一的风格吧。。

**Comment by wenerme** [comment]
语言风格是统一的但并不代表编辑器会统一,比如我如果用 idea, 之前设置为 tab 为4个空格,那么格式就乱了

**Comment by astaxie** [comment]
这个gofmt做的事情吧

**Comment by wenerme** [comment]
但是写代码的时候会习惯性的使用编辑器的代码格式化,虽然提交时有 gofmt 选项,但默认是未选中的,并且有些编辑器是不支持调用 gofmt 的,感觉有 .editorconfig 会相对好些 规范一点
