### ISSUE TITLE
swagger正则表达式问题

### ISSUE THREAD

**Issue by victor-u** [beego/beego#2282]
bee v1.5.2
go v 1.7.1

go环境（ubuntu 16.10）：
# native compiler linux amd64
GOROOT=/usr/local/go
GOBIN=$GOROOT/bin
GOARCH=amd64
GOOS=linux
CGO_ENABLED=1

GO15VENDOREXPERIMENT=1

PATH=$GOROOT/bin:$PATH

LITEIDE_GDB=gdb
LITEIDE_MAKE=make
LITEIDE_TERM=/usr/bin/gnome-terminal
LITEIDE_TERMARGS=
LITEIDE_EXEC=/usr/bin/xterm
LITEIDE_EXECOPT=-e

LITEIDE_SHELL=gnome-terminal;lxterminal;konsole;xfce4-terminal;xterm

在controllers定义了一个方法：

// @Title get user's privilege
// @Description get user's privilege
// @Param	corpid		path 	string		true		"CorpId for privilegeUser"
// @Param	uid			path 	int64		true		"userid"
// @Success 200 body []*models.Privilege_user
// @Failure 403 body is empty
// @router /:corpid([0-9]+)/:uid([0-9]+) [get]
func (self *PrivilegeUserController) GetAllPrivilege() {
     具体代码略过
}

通过http形式访问，没有问题：
![image](https://cloud.githubusercontent.com/assets/13587450/20306903/d52880bc-ab77-11e6-8172-2bb609ed3cf7.png)

但是 使用swagger，始终报404，下面是截图
![image](https://cloud.githubusercontent.com/assets/13587450/20306882/bd2bb27c-ab77-11e6-8150-e1ed3a8ef40d.png)

没有找到什么原因

**Comment by victor-u** [comment]
是swagger2不支持正则表达式了吗？

**Comment by astaxie** [comment]
这个是我们bee解析的时候没有解析引起的

**Comment by victor-u** [comment]
bee支持正则表达式，有版本规划吗
