### ISSUE TITLE
API doc auto-generate with multi-namespaces

### ISSUE THREAD

**Issue by Bittenbydog** [beego/beego#2284]
GoVersion : go1.7.3
Beego     : 1.7.1

---

GOARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

OS: macOS Sierra
Processor: 2.5 GHz Intel Core i7

---

The API auto-generating is a very helpful feature. But, as I thought, there may be some thing not friendly enough. Here is my situation:

Using two name space to separate `admin` and `API` paths, so the paths look like:

 ```
        "/"
          |-- "api"
          |     |-- "/object"
          |     |-- "/user"
          |     |-- "......."
          |
          |
          |-- "admin"
                |-- "/login"
                |-- "/logout"
                |-- "......."
```

In order to accomplish this design, I have codes like:

```go
        // API namespaces
        api_ns := beego.NewNamespace("/api",
            beego.NSNamespace("/object",
			beego.NSInclude(
				&controllers.ObjectController{},
			),
		),
		beego.NSNamespace("/user",
			beego.NSInclude(
				&controllers.UserController{},
			),
		),
        )
        // Admin namespaces
        admin_ns := beego.NewNamespace("/admin",
	    beego.NSNamespace("/login",
			beego.NSInclude(
				&controllers.LoginController{},
			),
		),
	    beego.NSNamespace("/logout",
			beego.NSInclude(
				&controllers.LogoutController{},
			),
		),
        )
        beego.AddNamespace(api_ns, admin_ns)
```

After the works of swagger, I got the API docs.
    
However all the third-class paths (i.e. "/object") are under one same second-class path.
    
Obviously, according to the design graph, the path like "/api/login" is a wrong path.

So, is there a way to accomplish the goal of generating right API docs with multi-namespaces?

And thank you for your works, this is a excellent web framework.

**Comment by astaxie** [comment]
@Bittenbydog it's not support now.

**Comment by heidsoft** [comment]
我也遇到了，如果在设置三个层次的namespace时，也无法生成doc

**Comment by Bittenbydog** [comment]
@heidsoft  额...三个层次那个就不要提了吧？文档有明确地说明当前只支持两层啊...

**Comment by apremalal** [comment]
Is there any plan to add support to this very helpful feature?

**Comment by muhammad-asif** [comment]
@astaxie is there a plan to support this in near future?
