### ISSUE TITLE
beego的Session功能

### ISSUE THREAD

**Issue by RobinWuDev** [beego/beego#23]
我使用了beego的ViewCotnroler的StartSession方法，但是报错了。
调用代码

``` Go
func (this *ApiController) Get() {
    session := this.StartSession()
    err := session.Set("dddd", "ffff")
    beego.Error(err.Error())
    defer models.ErrorRecover(&this.Controller)()

    this.Ctx.Request.ParseForm()
    this.Ctx.ContentType("application/json")
    action := this.Ctx.Request.Form.Get("action")
    switch action {
    case "index":
        index(this)
    default:
        models.CheckErr(errors.New("没有找到服务"), "调用接口失败")

    }
}
```

下面报错信息
2013/03/28 20:30:32 [C] [Handler crashed with error runtime error: invalid memory address or nil pointer dereference]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/runtime/proc.c 1443]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/runtime/runtime.c 128]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/runtime/thread_darwin.c 418]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/sync/atomic/asm_amd64.s 12]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/sync/mutex.go 40]
2013/03/28 20:30:32 [C] [/Users/lsdev/Documents/Code/go/src/github.com/astaxie/session/session.go 60]
2013/03/28 20:30:32 [C] [/Users/lsdev/Documents/Code/go/src/github.com/astaxie/beego/controller.go 157]
2013/03/28 20:30:32 [C] [/Users/lsdev/Documents/Code/go/src/lsdevBlog/controllers/api/api.go 38]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/reflect/value.go 521]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/reflect/value.go 334]
2013/03/28 20:30:32 [C] [/Users/lsdev/Documents/Code/go/src/github.com/astaxie/beego/router.go 230]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/net/http/server.go 669]
2013/03/28 20:30:32 [C] [/Users/lsdev/dev/go/src/pkg/runtime/proc.c 271]

**Comment by JackHighBlack** [comment]
beego.BConfig.WebConfig.Session.SessionOn = true,
 和StartSession
