### ISSUE TITLE
[Proposal] 增加一个新的Logger以支持阿里云日志服务

### ISSUE THREAD

**Issue by hongliang81** [beego/beego#2302]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.1

├── Beego     : 1.7.0
├── GoVersion : go1.7
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : 
├── GOROOT    : /usr/local/Cellar/go/1.7/libexec
├── Compiler  : gc
└── Date      : Thursday, 1 Dec 2016

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/96/_xs_c7sd5_v038fvp9_kmh940000gn/T/go-build143983741=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
使用Beego开发分布式应用，需要实现集中日志。

4. What did you expect to see?
想使用阿里云的日志服务，做到不落盘直接推送。

5. What did you see instead?
目前阿里云只有一个第三方的Go SDK，而且只支持写入，不如直接集成到Beego中。

**Comment by hongliang81** [comment]
已经实现了，通信部分用的是阿里云客服提供的第三方SDK。
目前支持：
- 缓存，支持设置大小，最大64，达到最大缓存后一起推送的日志服务
- 主题，支持设置多个主题，在日志中用“##”分隔主题和日志内容，Logger将自动解析和匹配，匹配不上的将写入空主题。

**Comment by astaxie** [comment]
@hongliang81 please send the PR to develop branch

**Comment by hongliang81** [comment]
@astaxie will do after a short trial with my own project. should be no long than 2-3 days.

**Comment by astaxie** [comment]
@hongliang81 you need to pull request....

**Comment by hongliang81** [comment]
@astaxie I sware I did...... but still got a 403
![image](https://cloud.githubusercontent.com/assets/17023125/21474363/f20f5a7e-cb58-11e6-99b4-658cf1cc8d4f.png)
any ideas?.....

**Comment by astaxie** [comment]
you need to fork and push to your own repo. and then send pull request to astaxie/beego

**Comment by hongliang81** [comment]
sorry, never done this before. pull request created~

**Comment by lubaoyilang** [comment]
@hongliang81 你好，目前beego已经升级到 1.8 版本了，看到您新增加的阿里log，但是在使用过程中有些问题，想请教一下。
1. 初始化的时候，直接用下边这句就可以 增加 阿里云日志写入了，对吗？
	XLog.SetLogger(logs.AdapterAliLS, `{"Project":"server","Endpoint":"cn-beijing.log.aliyuncs.com","KeySecret":"XXXXX","KeyID":"XXXXXX","LogStore":"web-log","Topics":"","Source":"TEST-Web","FlushWhen":2,,"Level":7}`)

2.当我有日志需要写入的时候，可以直接调用 下边这句 就可以了吗？
	beego.Info("Start:"+mothed+" IP:"+ip," clientFrom:"+clientFrom, " clientSystemVerson:"+clientSystemVerson," clientAPPVersion:"+clientAPPVersion," Token:", Token, " URL:", URL," Body:"+Body)


3.但是我调用完成后，阿里云日志后台没有日志写入，但是 调试输出窗口 也没有发现 有错误信息。是我配置的有问题吗？还是 使用的有问题呢？

**Comment by alicksnake22** [comment]
阿里日志刚好用到，@hongliang81能写一下输出格式吗

**Comment by alicksnake22** [comment]
@lubaoyilang 还是不太懂使用方法，能告诉一下吗
