### ISSUE TITLE
Unexpect “multiple response.WriteHeader calls” while using OutPut.SetStatus(...)

### ISSUE THREAD

**Issue by szyhf** [beego/beego#2312]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.7.2

2. What operating system and processor architecture are you using (`go env`)?

macOS

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

While creating an api application and want to controller the http status code.
In controller func:

```golang
func(this*AController)Hello(){
       // Any way I can found to write something to response
	this.Ctx.WriteString("Somethine")

	this.Ctx.Output.JSON(this, false, false)
	this.Ctx.Output.Body([]byte("HELLO"))

	this.Ctx.ResponseWriter.WriteHeader(this.status)
	this.Ctx.ResponseWriter.Write([]byte("World"))
	this.Ctx.ResponseWriter.ResponseWriter.Write([]byte("LoL"))

     // Set status code
     this.Ctx.Output.SetStatus(400)
    // No matter where I put the SetStatus, before "write to response" or after "write to response"
}
```

4. What did you expect to see?

The “multiple response.WriteHeader calls” won't appear.

5. What did you see instead?

The “multiple response.WriteHeader calls” appear.

What did I found :

```golang
// In [output.go:76]
func (output *BeegoOutput) Body(content []byte) error {
      //......
	// Write status code if it has been set manually
	// Set it to 0 afterwards to prevent "multiple response.WriteHeader calls"
	if output.Status != 0 {
		output.Context.ResponseWriter.WriteHeader(output.Status)
		output.Status = 0
	}
      //......
      io.Copy(output.Context.ResponseWriter, buf)
}
// What I found in [router.go:878]
func (p *ControllerRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request){
    //......
    // Call WriteHeader if status code has been set changed
    if context.Output.Status != 0 {
	    context.ResponseWriter.WriteHeader(context.Output.Status)
   }
}
```

I found the try to prevent from the "multiple response.WriteHeader calls" but I found it doesn't work well.

My opinion:

The interface of http.ResponseWrite says that, if the Write() is called while the WriteHeader() didn't called, the WriteHeader() will assume StatusOK (200) as the http status code to response, in that case, once called Write(), the status code should not be set again, else will case the message.

All of the function I found list above will case ther Write(), even the "io.Copy(output.Context.ResponseWriter, buf)//[output.go:76]" will case the "Multiple calls".

If I SetStatus() before using WriteSTH(...), the code below doesn't work well and I think its a bug:

```golang
// In [context.go:198]
// Its the func called in [router.go:878]
func (r *Response) WriteHeader(code int) {
	if r.Status > 0 {
		//prevent multiple response.WriteHeader calls
		return
	}
	r.Status = code
	r.Started = true
	r.ResponseWriter.WriteHeader(code)
}
```

The r.Status is still 0 after any WriteSTH(..) func called, testing code like :

```golang
func(this*AController)Hello(){
 	// Set status code
    this.Ctx.Output.SetStatus(400)
    // Try any write func below is fine.
	this.Ctx.WriteString("Somethine")

	//this.Ctx.Output.JSON(this, false, false)
	//this.Ctx.Output.Body([]byte("HELLO"))

	//this.Ctx.ResponseWriter.WriteHeader(this.status)
	//this.Ctx.ResponseWriter.Write([]byte("World"))
	//this.Ctx.ResponseWriter.ResponseWriter.Write([]byte("LoL"))

	// Print the response.Status, the same method in In [context.go:198]
	beego.Debug("this.Ctx.ResponseWriter.Status: ", this.Ctx.ResponseWriter.Status)
	// The console:
	// 2016/12/06 20:49:44 [D] [a_controller.go:38] this.Ctx.ResponseWriter.Status:  0
	// 2016/12/06 20:49:44 [server.go:2315] [HTTP] http: multiple response.WriteHeader calls
}
```

In this case, even the WriteHeader(...) is called by Write(...), the ResponseWriter.Status is still 0, and in the [context.go:198], the "prevent multiple response.WriteHeader calls" didn't work well.

Firstly I don't think to set the Output.Status = 0 in Output.Body(...) is fine, sometimes, the response status is needed in filter "AfterExec", where I found this problem. I want to do something in filter if the status is OK or NotOK, and the status code case error.

In go's design, the status code should set only once in an conversition, and ResponseWriter.Write(...) will auto call WriteHeader(...), so write response should called after all the work has done.

The output keep the status set by controller untill the end of ServeHTTP(...), so the output can also keep the response(body) after the output.status has write to header.

But this will case more memory and its not needed.

What I slove the problem now is :

```golang
func(this*AController)Hello(){
	// Set status before write body and use WriteHeader instead of Output.SetStatus(...)
	this.Ctx.ResponseWriter.WriteHeader(400)

	this.Ctx.WriteString("Somethine")
}
/// In filter
func RepeatablePointFilter(ctx *context.Context) {
	// use ResponseWriter.Status instead of Output.Status
	beego.Debug(ctx.ResponseWriter.Status)
}
```

Above all, it's the Output.Status has some conflict with the Write func of Context, and the old solution doesn't works well.

**Comment by arma7x** [comment]
Happen to me too, solve by;
this.Ctx.Output.SetStatus(400) //set status first
this.ServeJSON() // then server content
this.StopRun() // finally stop controller(if in 'if else' condition)
