### ISSUE TITLE
API RequestBody fields are empty after getting error at some [A need rather than a issue]

### ISSUE THREAD

**Issue by berk-can** [beego/beego#2313]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.6
beego 1.7.1

2. What operating system and processor architecture are you using (`go env`)?
amd64

3. What did you do?
I create a controller and try to get parameters from request like as mentioned below:
requestBody := models.TaskListExt{}
json.Unmarshal(t.Ctx.Input.RequestBody, &requestBody)

and I get a parse error in a field (it was time.Time)
and after getting error, remaining fields are not parsed

4. What did you expect to see?
I expect other fields to be parsed despite having error at another field

5. What did you see instead?
When I get the error, it stopped the parsing process of struct

Is there a way to enable parsing other fields as they should be despite having error in some fields ?

**Comment by amrfaissal** [comment]
@berk-can `json.Unmarshal()` does not report an error if values in the `ctx.Input.RequestBoby` do not correspond to values in `requestBody`, but it does return errors in case of a syntax error or a type mismatch.
Did you check the format of the value of type `time.Time`?

**Comment by berk-can** [comment]
@amrfaissal Yeah I solved my problem with time.Time now it works flawlessly;
I only want to open this issue because I thought if there can be a feature like that it would be awesome
If it is not right place to open a issue to want a feature or talk about it, I can delete issue ?

**Comment by amrfaissal** [comment]
You are in the right place. Regarding your feature request, I think that's the default behavior of `json.Unmarshal()` but a helper function can be added to do explicit checking. @astaxie What do you think?
