### ISSUE TITLE
beego在prod模式下能否通过参数控制模板缓存

### ISSUE THREAD

**Issue by gloomyzerg** [beego/beego#2318]
Beego     : 1.7.1

目前prod模式下模板总是在启动时加入map缓存的

但有时仅仅修改了模版中的一个样式就需要重启整个应用对于一部应用来说代价过大了.
应用重启可能需要做HA的切换,服务的注册,本地缓存的重建,检查各种环境,服务,数据的依赖等等.

希望beego能支持通过配置项 来让用户决定是否使用模版缓存.
模板缓存带来的性能提升也并非是所有类型的应用都必须的,我建议能让用户自行去选择.
例如: EnableTemplateCache = false

**Comment by astaxie** [comment]
这个可以考虑改进的
