### ISSUE TITLE
how to use dockerfile to create beego image?

### ISSUE THREAD

**Issue by developerzyy** [beego/beego#2327]
1. FROM registry.cn-hangzhou.aliyuncs.com/mocostudio/golang:latest
2. ENV APP_DIR=$GOPATH/src/web-test
3. COPY . $APP_DIR
4. WORKDIR $APP_DIR
5. RUN go get && go install && find . -name "*.go" | xargs rm -f
6. ENTRYPOINT $GOPATH/bin/web-test
7. EXPOSE 80

But I can't find the `hello.tpl` page after I enter `localhost/hello`
Here is not to start with `bee run`
So I change dockerfile with
1. FROM registry.cn-hangzhou.aliyuncs.com/mocostudio/golang:latest
2. RUN go get github.com/astaxie/beego && go get github.com/beego/bee
3. CMD ["bee","run"]
4. EXPOSE 80

Then I collapsed,I log docker
1. 2016/12/15 17:05:54 FATAL    ▶ 0001 No application '/go' found in your GOPATH`
What should I  @astaxie 
附上中文：
我用dockerfile生成image，但是beego不用bee run跑起来，访问页面的时候会找不到页面，但是用dockerfile中写运行bee run又报错，真心求@astaxie 帮帮忙，急

**Comment by developerzyy** [comment]
@astaxie 先谢过大神

**Comment by amrfaissal** [comment]
@developerzyy This pull request https://github.com/beego/bee/pull/342 will do it for you (once merged).
