### ISSUE TITLE
proposal:  orm add SUM() function to  the builder

### ISSUE THREAD

**Issue by goldalworming** [beego/beego#2329]
Hi, how to sum column in beego. I learn in advanced query and didn't find it? 
can anybody give information to select sum(columnname) from table ?

**Comment by hairichuhe** [comment]
I want to know , too!

**Comment by hsw409328** [comment]
I want to know , too!

**Comment by dengyuankai272** [comment]
I want to know , too!

**Comment by DennisMao** [comment]
@goldalworming  It seems no suitable functions to that you need.

**Comment by iscitychan** [comment]
I want to know , too!
