### ISSUE TITLE
get nil value when pass values from filter to controller

### ISSUE THREAD

**Issue by ckahi** [beego/beego#2332]
when i use `ctx.Input.SetData("startTime", -time.Now().UnixNano())` to setdata and use 

`ctx.Input.GetData("startTime")` in my controller to getData with ab testing `ab -n 5000 -c 500`, i got `nil` value?

my enviroment:

Beego     : 1.7.1
GoVersion : go1.7.1

**Comment by astaxie** [comment]
I have no idea based on your information

**Comment by Raggaer** [comment]
Usually on a controller you access the data with `c.Data` how are you calling `ctx.Input.GetData` on a controller?

**Comment by cjsky** [comment]
@astaxie 
@Raggaer 

`
func init() {
	beego.InsertFilter("/*", beego.BeforeRouter, func(ctx *context.Context) {
		ctx.Input.SetData("startTime", -time.Now().UnixNano())
	})
}
`
