### ISSUE TITLE
model 增加字段后，不能正确Mirgrate 

### ISSUE THREAD

**Issue by toplinuxsir** [beego/beego#2335]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.1

├── Beego     : 1.7.2
├── GoVersion : go1.7.3

2. What operating system and processor architecture are you using (`go env`)?
  
GOARCH="amd64"
GOBIN="/home/lhs/soft/go1.7.3/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=/****/go1.7.3/gopath"
GORACE=""
GOROOT="/*o****ft/go1.7.3/go"
GOTOOLDIR="/***g/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build691757342=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
 在已经存在的Model里面增加 外键字段：
   type BillPrint struct {
	Id           uint64     `orm:"pk;auto" form:"id"`
	BillNo       string     `orm:"index" form:"bill_no"`
	Barcode      string     `orm:"index"`
	MTypeCode    string     `orm:"index"`
	Seq          uint32     `orm:"index;null"

	ServerCfg *ServerConfig `orm:"rel(fk)"`  // 新增字段
}

4. What did you expect to see?

    
5. What did you see instead?

   models.BillPrint.ServerCfg` for table `t_bill_print_log`
    ALTER TABLE "t_bill_print_log" ADD COLUMN "server_cfg_id" bigint CHECK("%COL%" >= 0) NOT NULL 
   Error in Run SyncDB
 pq: 字段 "%COL%" 不存在

**Comment by toplinuxsir** [comment]
?? any idea?

**Comment by astaxie** [comment]
yea, it's still not support now

**Comment by toplinuxsir** [comment]
It is still not support now ?
