### ISSUE TITLE
XSRF和SaveFile的问题和修改

### ISSUE THREAD

**Issue by hwfy** [beego/beego#2364]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.7.1

2. What operating system and processor architecture are you using (`go env`)?
ubuntu64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

# 一、XSRF
### // 获取token
```go
func (this *MainController) Login( ) {
	this.Data["json"]=this.XSRFToken()
}
```
### // 验证token
```go
beego.AddNamespace(ns.Filter("before"), func(ctx *context.Context) {
   ctx.CheckXSRFCookie()
})
```

### // 出现错误

XSRF cookie does not match POST argument

### // 错误原因

CheckXSRFCookie方法内 if ctx._xsrfToken != token 永远成立，因为ctx._xsrfToken不是this.ctx_xsrfToken的值，对象不一致

### // 修改方法1
context.go
```go
func (ctx *Context) CheckXSRFCookie(key string) bool {
	token := ctx.Input.Query("_xsrf")
	if token == "" {
		token = ctx.Request.Header.Get("X-Xsrftoken")
	}
	if token == "" {
		token = ctx.Request.Header.Get("X-Csrftoken")
	}
	if token == "" {
		//'_xsrf' argument missing from POST
		ctx.Abort(403, "请勿非法访问")
		return false
	}
	xsrfToken, _ := ctx.GetSecureCookie(key, "_xsrf")

	if xsrfToken != token {
		//XSRF cookie does not match POST argument
		ctx.Abort(403, "请勿非法访问")
		return false
	}
	return true
}
```
### // 修改方法2
context.go
```go
func (ctx *Context) Abort(status int, body string) {
	ctx.Output.SetStatus(status)
        //打印错误信息
	ctx.WriteString(body)
	//panic(body)
}
```

-------------------------------------------------------------------------------
# 二、SaveFile
### // 上传文件
```go
_, fh, _ := this.GetFile("atta")
this.SaveToFile("atta", "./upload/"+fh.Filename )
```
### // 出现问题

这两个方法内都用到了Ctx.Request.FormFile("atta")，请求两次效率下降；
当upload目录不存在时就会上传为空

### // 修改方法
controller.go
```go
func (c *Controller) SaveToFile(fromfile, tofile string) (string, error) {
       //不需要省略h
	file, h, err := c.Ctx.Request.FormFile(fromfile)
	if err != nil {
		return "", err
	}
	defer file.Close()
       //创建目录，存在则忽略
	err = os.MkdirAll(tofile, 0777)
	if err != nil {
		return "", err
	}
	f, err := os.OpenFile(tofile+h.Filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
	if err != nil {
		return "", err
	}
	defer f.Close()
	io.Copy(f, file)
       //返回路径，可能需要保存数据库
	return tofile + h.Filename, nil
}
```

**Comment by SergeyJay** [comment]
I met the same problem
