### ISSUE TITLE
beego orm mysql connection reset by peer

### ISSUE THREAD

**Issue by haroldTlan** [beego/beego#2388]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
the lastest

2. What operating system and processor architecture are you using (`go env`)?
go version go1.7 linux/amd64

3. What did you do?
I am using beego orm to connet remote machine. Everytime I reboot someone, then two sentences appeared.

[mysql] 2017/01/13 09:56:24 packets.go:33: read tcp 192.168.2.83:44070->192.168.2.144:3306: read: connection reset by peer
[mysql] 2017/01/13 09:56:24 packets.go:124: write tcp 192.168.2.83:44070->192.168.2.144:3306: write: broken pipe

Is that ok?

**Comment by Raggaer** [comment]
This is an error of the `go-sql-driver`

Maybe this can help [go-sql-driver issue 353](https://github.com/go-sql-driver/mysql/issues/353)

**Comment by haroldTlan** [comment]
@Raggaer I had set `orm.SetMaxIdleConns("default", 30)` which is mean  SetMaxOpenConns but it was useless.

**Comment by haroldTlan** [comment]
[2017-01-16 14:01:26] [ERR] [EVENT] dial tcp 192.168.2.201:3306: getsockopt: connection refused
[2017-01-16 14:01:26] [ERR] [EVENT] dial tcp 192.168.2.201:3306: getsockopt: connection refused
the broken pipe appears more , the program will be crashes, you can not use beego orm to do anything, select\insert\update

**Comment by Raggaer** [comment]
I think your best bet is to open the issue on the go-sql driver
