### ISSUE TITLE
{{ template "path/to/file" }} feature

### ISSUE THREAD

**Issue by sharego** [beego/beego#2396]
GO 1.7 windows/amd64 + beego v1.7.2

Template in template is a good feature, Thanks. syntax like this `{{ template "path/to/file" }}`
now the filepath use literal string, hard code. Can we use variable like `{{template .SubTemplateFilepath}}` or `{{template $subTemplateFilePath}}` 

If support , how can i do, thank you very much

**Comment by Raggaer** [comment]
What do you want to achieve?

Go `html/template` does not support using variables to call a template. You can only do it with a string yourself `{{ template "name" pipeline }}`

You can however create a template function to achieve this:

http://stackoverflow.com/questions/20716726/golang-text-html-template-call-other-templates-with-dynamic-name

You might need to use `beego.ExecuteTemplate`

**Comment by Raggaer** [comment]
I am not sure if you can do `this.Data["templateName"] = "test.tpl"` and then on your layout do

`{{ template .templateName }}`
