### ISSUE TITLE
Is is possible to debug in IntelliJ IDEA

### ISSUE THREAD

**Issue by logzc** [beego/beego#2405]
My Env:
```
Windows 10 x64
beego 1.7.2 (beego framework)
golang version: go1.7.4
IntelliJ IDEA 2016.3.3
```

I created a simplest project by
```
bee new hello
```

Everything is ok if I use `bee run hello` to start the application.

However when I use this way to run the application
![debug](https://cloud.githubusercontent.com/assets/20283661/22116398/53727476-deab-11e6-9d09-350a2ee944bb.png)

When I open url `http://127.0.0.1:8080/` in Chrome, I got this message:
![error](https://cloud.githubusercontent.com/assets/20283661/22116672/30edc0ee-deac-11e6-866f-b70f01eb9ddf.png)

It seems that there are many differents between the two ways. However,  `bee run hello`  can only run without debug feature. If I use the second way to way the application, debug will be very easy.
![debug-view](https://cloud.githubusercontent.com/assets/20283661/22116627/0a0d27da-deac-11e6-96af-4c01d941987b.png)

As you know debug is very neccessay in coding.

So I'm wondering whether it is possible to run beego in such debug mode in IntelliJ.

**Comment by zjjott** [comment]
`bee run `  can run with debug frame
![image](https://cloud.githubusercontent.com/assets/3733548/23060718/e91f78d0-f539-11e6-84c5-03850e487b5d.png)

as you can see,I run `bee generate doc` ,you can change it to `bee run`

**Comment by rafa-lft** [comment]
@zjjott I tried what you mention: change 'generate doc' --> 'run' . I'm now able to run it from the IDE and it works. However when I try to debug it from Gogland, it doesn't stop in any breakpoint.
Any idea?
Im using Gogland (https://www.jetbrains.com/go/download/) Version 1.0 Preview/EAP Feb, 10 2017. Not IntelliJ + Plugin.

**Comment by jinleileiking** [comment]
use vim  + delve

**Comment by zjjott** [comment]
@rafa-lft I'm using Gogland too, your working directory settings is all right? also you need 'debug run ... ' the 'bee run'
what is the gogland console output?

**Comment by zjjott** [comment]
I'm sorry,using `bee run ` will run the beego project in sub process.
Beego load config when the sub process start,and sub process is not in debugger

I using main.go to debug and all things work good.

**Comment by timchenxiaoyu** [comment]
If I run main.go  , conf.app does not load

**Comment by toddams** [comment]
Bump
