### ISSUE TITLE
Make the name-to-field in the ORM customizable.

### ISSUE THREAD

**Issue by monday-ch** [beego/beego#2407]
This is a suggestion paste from #2143 

 Hi, is that possible to make the "snakeString" as a public function that we can set the name-to-field as needed,  just like  the [sqlx](https://github.com/jmoiron/sqlx/blob/f980a91bdc37abef88269b8f122d7de6352102f5/sqlx.go#L18-L28)  : `var NameMapper = strings.ToLower`

 And another thing, there looks a little problem with the snakeString function you used in the code:
The comment say XxYY to xx_yy, and actually it is xx_y_y (and what I want is xx_yy in my code)
```
// snake string, XxYy to xx_yy , XxYY to xx_yy
func snakeString(s string) string {
	data := make([]byte, 0, len(s)*2)
	j := false
	num := len(s)
	for i := 0; i < num; i++ {
		d := s[i]
		if i > 0 && d >= 'A' && d <= 'Z' && j {
			data = append(data, '_')
		}
		if d != '_' {
			j = true
		}
		data = append(data, d)
	}
	return strings.ToLower(string(data[:]))
}
```
  
Thanks.

**Comment by oitimon** [comment]
Any progress? Thanks.
