### ISSUE TITLE
Add protocol buffer feature

### ISSUE THREAD

**Issue by captain-me0w** [beego/beego#2410]
how beego have seperate function for json likewise pls do for protocol buffer also because rite now i wrote my custom implementation if you provide separate function in framework itself it will be great

**Comment by welemon** [comment]
we use both beego and protobuf3, but our final output (IO) are JSON format. So they play together nicely, protobuf3 will translate the proto file into golang structs and take the responsibility to parse / serialize with JSON string, while beego just serve the result at higher levels. 
If you wish not using JSON but protobuf binary stream, I suspect gRPC is a better fit than beego :)

**Comment by CBDlkl** [comment]
希望添加protobuffer的支持，因为现在给移动APP提供API支持，开始要求这个了。
