### ISSUE TITLE
ORM does not support BLOB types

### ISSUE THREAD

**Issue by littledot** [beego/beego#2411]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go: go version go1.7.4 darwin/amd64
beego: 1.7.2

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Are there any plans for the ORM to support BLOB data types?
If there are none, what's the reason?
```
type Screenshot struct {
	ImageSource []byte
}
```

4. What did you expect to see?
Successful creation of MySQL table

5. What did you see instead?
```
field: app.Screenshot.ImageSource, unsupport field type , may be miss setting tag
```

**Comment by Raggaer** [comment]
Maybe you need to add a tag to that struct field?

`orm:"type(blob)"`
