### ISSUE TITLE
graceful update with supervisord

### ISSUE THREAD

**Issue by Bittenbydog** [beego/beego#2418]
GoVersion : go1.7.3
Beego     : 1.7.1

---

GOARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

OS: macOS Sierra
Processor: 2.5 GHz Intel Core i7

---

热更新是一项非常有用也很出彩的特性。但是当应用到线上环境时，就不适合用 `supervisor` 来部署应用了。举例来说：

1. 用 `supervisor` 运行了 `gopkg`(编译好的项目二进制文件)，PID 为 2000
2. 向 PID 为 2000 的进程发送` HUP` signal，热更新机制启动，得到新运行的 gopkg 的 PID 为 2001
3. PID 2000 进程处理完了所有请求，成功退出
4. PID 2001 继续正常运行

理想状况是，`supervisor` 放弃 2000 进程，转而继续监控 PID 为 2001 的进程。

但现实情况是 2000 进程退出，`supervisor` 尝试重启，但由于端口被 2001 进程占用，重启失败。

现在在用 `nohup` 来部署应用，没有使用 `supervisor` 那么令人放心。

所以，请问有没有方案来解决这一问题呢？或者谁有相关的思路，可以讨论下。

谢谢。

--- 

The graceful update is an very excellent and helpful feature. However, when I enable it in production environment, I could not properly run the APP with `supervisor`.

For example:

1. I have run the `gopkg`(the compiled binary file of my APP) with PID 2000
2. Send a `HUP` signal to trigger graceful update, then I get a new running gopkg with PID 2001
3. PID 2000 handle all the old requests and then exit successfully
4. PID 2001 keep running

The ideally situation is that the `supervisor` abort 2000 process and turn to monitor 2001 process.

But the fact is the 2000 has exited and `supervisor` keep trying to restart it. Since the net port is occupied by the 2001 process, the restart is failed.

Currently, I use `nohup` to run my APP, obviously, I have lost the benefits of `supervisor`.

So, is there any body could give me some suggestion to solve this issue?

Thank you very much.

**Comment by pathbox** [comment]
"但是当应用到线上环境时，就不能够用 supervisor 来部署应用了" 这句话是错的吧。。。应该是说 supervisor不适合上面所说的热更新的部署，因为supervisor  尝试重启 PID2000 而没有切换到 PID2001 而端口又被PID2001 占用了 从而重启失败。

**Comment by Bittenbydog** [comment]
@pathbox  已修改，谢谢

**Comment by astaxie** [comment]
真正做到热更新只能等到1.8版本的发布了

**Comment by jinleileiking** [comment]
这个问题解决了么？正准备要用。

**Comment by jinleileiking** [comment]
我用最新版本 配合supervisor， 试了一下，不行。

**Comment by Bittenbydog** [comment]
@jinleileiking  没再折腾，直接用了 `nohup` 来部署

**Comment by jinleileiking** [comment]
@Bittenbydog 我们也不折腾了，用ab方案，就是麻烦点。。。

**Comment by magicleo** [comment]
这个问题现在修复了吗？
