### ISSUE TITLE
there exists a default 302 redirect in beego?

### ISSUE THREAD

**Issue by ryanzpn** [beego/beego#2424]
beego 1.7.2 on mac

every time i click on a button, it will 302 redirect to the main page of my application, 127.0.0.1:8080, , i don't want it and i don't know why there is a redirect?

the logs is below:

2017/02/09 16:52:37 [D] [server.go:2202] |      127.0.0.1| 302 |      35.96µs|   match| GET      /ws   r:/ws
2017/02/09 16:52:37 [D] [server.go:2202] |      127.0.0.1| 200 |   1.358137ms|   match| GET      /     r:/
2017/02/09 16:52:37 [D] [server.go:2202] |      127.0.0.1| 200 |    254.366µs|   match| GET      /static/css/bootstrap.min.css
2017/02/09 16:52:37 [D] [server.go:2202] |      127.0.0.1| 200 |    255.397µs|   match| GET      /static/js/jquery-1.10.1.min.js

For ease of debugging, i remove the corresponding action on clicking the addfriendbtn in the js file.

    $('#addfriendbtn').click(function() {
        //addfriend();
    });

and the html file:

{{template "base/base.html" .}}
{{define "head"}}
<title>{{i18n .Lang "websocket_chatroom"}} - {{i18n .Lang "app_intro"}}</title>
{{end}}
{{define "body"}}
<div class="container">
    <h3>{{i18n .Lang "username"}}: <span id="uname">{{.UserName}}</span></h3>
    <h3>{{i18n .Lang "contacts"}}:</h3>
    <form class="form-inline">
        <button id="updatebtn" type="button" class="btn btn-default">{{i18n .Lang "update"}}</button>
    </form>

    <ul id="contacts">
        <li></li>
    </ul>

    <form class="form-horizontal">
        <div class="form-group">
            <label class="col-md-3 control-label">{{i18n .Lang "friend_name"}}: </label>
            <div class="col-md-5">
                  <input type="text" class="form-control" id="friend_name" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button id="addfriendbtn" type="submit" class="btn btn-info">{{i18n .Lang "add_friend"}}</button>
            </div>
        </div>
    </form>

    <form class="form-horizontal">
        <div class="form-group">
            <label class="col-md-3 control-label">{{i18n .Lang "friend_name"}}: </label>
            <div class="col-md-5">
                  <input type="text" class="form-control" id="friend_name" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button id="removefriendbtn" type="submit" class="btn btn-info">{{i18n .Lang "remove_friend"}}</button>
            </div>
        </div>
    </form>

</div>

{{end}}

thx

**Comment by bakanis** [comment]
The redirect is caused by your button "submit" type. Change button type to prevent submitting the form, eg. <button type="button"></button>
