### ISSUE TITLE
最近开发了一个根据yaml配置文件控制哪些url是否启用的功能，看是否有必要提个mr

### ISSUE THREAD

**Issue by jinleileiking** [beego/beego#2433]
感觉最好是做成插件。目前没有插件机制。

可以做成配置项。

**Comment by astaxie** [comment]
嗯，你可以写一个plugin，放你自己的repos下面也可以，然后beego/beedoc提一个pr，把你的使用和介绍放进去

**Comment by jinleileiking** [comment]
@astaxie 现在beego有插件机制了么？我搜了搜，没搜到，能否提供一个链接，多谢。
