### ISSUE TITLE
有无考虑增加Beego对GraphQL的支持？谢谢。

### ISSUE THREAD

**Issue by CHCP** [beego/beego#2441]
Beego 2.0：有无考虑增加Beego对GraphQL的支持？谢谢。

**Comment by astaxie** [comment]
我不熟悉GraphQL啊，如果社区可以贡献那是最好了, 😃

**Comment by CHCP** [comment]
前社区有几个使用Golang实现GraphQL的开源项目，例如https://github.com/graphql-go/graphql ，
如果能集成到Beego会更好。
