### ISSUE TITLE
lack support for mysql's fulltext (index) search, MATCH AGAINST

### ISSUE THREAD

**Issue by kerneltravel** [beego/beego#2448]
the Beego 1.7.2 version does support the mysql 5.7 's MATCH AGAINST fulltext-search.
source code orm/db_mysql.go is just take 'LIKE' for fulltext-search.  
`// mysql operators.
var mysqlOperators = map[string]string{
	"exact":     "= ?",
	"iexact":    "LIKE ?",
	"contains":  "LIKE BINARY ?",
	"icontains": "LIKE ?",
	// "regex":       "REGEXP BINARY ?",
	// "iregex":      "REGEXP ?",
	"gt":          "> ?",
	"gte":         ">= ?",
	"lt":          "< ?",
	"lte":         "<= ?",
	"eq":          "= ?",
	"ne":          "!= ?",
	"startswith":  "LIKE BINARY ?",
	"endswith":    "LIKE BINARY ?",
	"istartswith": "LIKE ?",
	"iendswith":   "LIKE ?",
}`

as mysql 5.7 and later version will be common, this feature maybe more useful

**Comment by zjjott** [comment]
maybe you can use `Raw SQL`:https://beego.me/docs/mvc/model/rawsql.md
I also want beego orm to have some extensions  😆

**Comment by kerneltravel** [comment]
tks.  [shorm](https://github.com/shengzhi/shorm) is a fearture-rich ORM writen by golang.

**Comment by tedli** [comment]
I want `REGEXP` too. May be beego orm should consider provide a plugin interface, that's something like a `CondGenerator`, users can define their own `__` sperated syntax like `.Filter("name__regexp", "abc\d+")`.

The CondGenerator can be something like this:

```go
type CondGenerator interface {
	Generate(fieldName string, args []interface{}) (cond string, err error)
}

orm.RegisterCondGenerator(db string, generator CondGenerator)
```
