### ISSUE TITLE
can upload to cdn and replace static resource url when deploy?

### ISSUE THREAD

**Issue by xurwxj** [beego/beego#2459]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
latest

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

want to upload all static reource to cdn when deploy to server or build
5. What did you see instead?

serve directly by beego or nginx map.

**Comment by ysqi** [comment]
hi @xurwxj  can define a template function to create static resource html tag.

```go
var assetsDNSURL = "https://static.yushuangqi.com"
// AssetsHTML create resource path
func AssetsHTML(absURL string) template.HTML {
	if absURL == "" {
		return ""
	}
	if !strings.HasPrefix(absURL, "/") {
		absURL = "/" + absURL
	}

	// if beego.BConfig.RunMode == "prod" {
	for k := range beego.BConfig.WebConfig.StaticDir {
		if strings.HasPrefix(absURL, k) {
			absURL = strings.Replace(absURL, k, assetsDNSURL, 1)
			break
		}
	}
	// }
	ext := strings.Split(path.Ext(absURL), "?")[0]
	switch ext {
	case ".css":
		return beego.AssetsCSS(absURL)
	case ".js":
		return beego.AssetsJs(absURL)
	default:
		beego.Error("can not handler asset:", absURL)
		return template.HTML(absURL)
	}
}

func init() {
	beego.AddFuncMap("assets", AssetsHTML)
}

```
and use `assets` to get static resouce html tag in template html ,e.g.
```html
{{assets "static/css/main.css?a=3&s=3"}}
{{assets "s2/css/main.css"}}
{{assets "static/js/main.js"}}
{{assets "/static/js/main2.js"}}
```
output:
```html
<link href="https://static.yushuangqi.com/css/main.css?a=3&s=3" rel="stylesheet" />
<link href="/s2/css/main.css" rel="stylesheet" />
<script src="https://static.yushuangqi.com/js/main.js"></script>
<script src="https://static.yushuangqi.com/js/main2.js"></script>
```

**Comment by xurwxj** [comment]
as following is my real need:
1. extend "bee pack" command to support upload static directory to specific remote url(or upload to aliyun oss or qiniu), then change conf var such as "staticprefix".
2. a template tag defined to change static resource url according runmode and conf var "staticprefix", this is exactly the same as what you wrote above. though the "assetDNS" will be got from conf and updated by step 1.

**Comment by xurwxj** [comment]
any plan to extend bee to be analogous to the webpack/gulp/grunt in nodejs?
