### ISSUE TITLE
m2m query problem

### ISSUE THREAD

**Issue by StayYouth1993** [beego/beego#2498]
can I use m2m query with multiple query condition？
for example:
```go
type Post struct {
    Id    int
    Title string
    User  *User  `orm:"rel(fk)"`
    Tags  []*Tag `orm:"rel(m2m)"`
}
type Tag struct {
    Id    int
    Name  string
    Posts []*Post `orm:"reverse(many)"`
}
```
I want to find the Post list which has Tag named "a" & "b" both, how to query this with Relational Query?
For now, I can only use  Hierarchical Queries to solve such problem which seems very troublesome to me.

**Comment by luongs3** [comment]
no solution ?????
