### ISSUE TITLE
Registermodel以及RunSyncdb前一定要把数据库写死？

### ISSUE THREAD

**Issue by dongfengkuayue** [beego/beego#2499]
先register一个model
然后runsyncdb
如果初始化时候连接中不写db名称，那么这时会报`no database selected`错误
可以不写死然后在代码中配置吗

**Comment by zjjott** [comment]
runsyncdb的含义就是sync db啊？你期望什么样的方式来进行配置？

**Comment by dongfengkuayue** [comment]
期望我自己定义在哪个数据库CRUD
现在是要写死在dburl中
我是想在sql语句中定义：
`create table datebase1.tableA ...`
`select * from database2.tableB,database1.tableA ...`
因为涉及到多个数据库，我不想建立多个database的连接
但是现在orm的代码里头给table名都加了反引号，我没办法这样create table

**Comment by zjjott** [comment]
跨库查询不是一个常规操作啊，这样的查询在JOIN、WHERE的效率都不如放在一个库里，权限管理也是个问题
或者你试试https://beego.me/docs/mvc/model/querybuilder.md

**Comment by dongfengkuayue** [comment]
sql语句比较复杂，我是直接用Raw的，所以才有这种需求

**Comment by astaxie** [comment]
为啥你都想自定义SQL了，还使用`runsyncdb`?

**Comment by dongfengkuayue** [comment]
@astaxie
还是想通过struct映射过去，方便些，只是想自定义database这个字段，其他部分还是代码生成

**Comment by astaxie** [comment]
不支持

**Comment by chaegumi** [comment]
跨数据库查询有什么例子吗，用db.table1 这样的形式报错，数据库连接是什么样子的，搜索不到
