### ISSUE TITLE
Who are using beego

### ISSUE THREAD

**Issue by astaxie** [beego/beego#2502]
If your company is using beego, please leave the comments below. AFAIK there are a lot of China companies using beego now. Here is an example:

### HuaWei Cloud 

- Which system: Private Cloud system
- Functions: All apis are based on beego.
- Codes: 10w+ lines
- QPS: 20,000 
Site: http://www.hwclouds.com/

**Comment by BorisBorshevsky** [comment]
## Gett
- Which system: All around - microservices
- Functions: All new Apis and some UI.
- Site: https://gett.com/

**Comment by nwaycn** [comment]
#  FSGUI

  

- Which system: Private Cloud system

- Functions： All Web Manage

- QPS: ~2,000

- Desc: 基于FreeSwitch的软交换管理,BeeGo1.7界面开发

- Site: http://139.196.40.50:8080/login  , admin ,123456

**Comment by jjz** [comment]
##my blog  http://jiangjiazhi.com/

**Comment by mohakkataria** [comment]
## Zomato

Which system: Multiple Internal-use microservices
Functions: All apis are based on beego.
QPS: 1000 (max in-toto of all)
Site: https://www.zomato.com/
