### ISSUE TITLE
form中怎么定义model对象

### ISSUE THREAD

**Issue by xurwxj** [beego/beego#2507]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.7.2
GoVersion : go1.8

2. What operating system and processor architecture are you using (`go env`)?
├── GOOS      : darwin
├── GOARCH    : amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```
type Article struct {
	Name     string `form:"Name,text,名 称：" required:"true" pattern:"^[A-Za-z0-9\u4e00-\u9fa5]{1,1024}$" err:"名称不能已经存在且必须是字母、数字或汉字，不区分大小写，长度在1～1024个" valid:"Required;MaxSize(1024)"`
	Category string `form:"Category,multiselect,分 类：" class:"multis" required:"true" err:"分类必须至少选择1个" valid:"Required"`
	Content  string `form:"Content,textarea,内 容：" class:"wysiwg_area" required:"true" err:"内容不能为空" valid:"Required"`
	Tags     string `form:"Tags,multiselect,标 签：" class:"multis_create"`
}
```

4. What did you expect to see?
Category是分类表，tags是标签表，我希望是多选的，怎么给这个struct传选项让renderform能正确渲染出来多选select？
5. What did you see instead?
不知道怎么传选项，这个struct中的category和tags应该怎么设置类型。

**Comment by zjjott** [comment]
现在还没有form和model的联动，但你可以自定义一个Article struct的Valid函数，来做通过默认验证后的一些自定义验证，详见：https://beego.me/docs/mvc/controller/validation.md

renderFormField还没有这样的功能，你可以扩展一个模板函数来实现这样的功能
