### ISSUE TITLE
为什么每次HTTP response里都有set-cookie?

### ISSUE THREAD

**Issue by guotie** [beego/beego#252]
为什么每次HTTP response里都有set-cookie? 怎么改变它？

**Comment by yingyan003** [comment]
@slene 这个问题最后怎么解决的，我现在也遇到这情况

**Comment by yingyan003** [comment]
@astaxie 这个问题最终的解决方法是什么呢？这里也没有说，官方文档也没有提到。另外，我不用session模块，但使用controller自带的session操作方法，可我并不想请求的时候给客户端返回set-cookie,如何关闭这个set-cookie 的操作呢？官方文档真的需要好好完善了，总不能每次遇到问题就去看源码吧，太影响开发效率了。
