### ISSUE TITLE
关于表单验证的建议

### ISSUE THREAD

**Issue by cbwfree** [beego/beego#2522]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : 1.8.0
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/cbwfree/Code/Golang
├── GOROOT    : /usr/local/Cellar/go/1.8/libexec
├── Compiler  : gc
└── Date      : Wednesday, 22 Mar 2017

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/cbwfree/Code/Golang"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5r/z_8kr3356hq35p8fbxqmwk6m0000gn/T/go-build913975362=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
希望表单验证可以增加一个自定义字段名称的 StructTag, 在错误提示时, 可以使用自定义的名称而不是字段名.
另外, 验证时如果不写 Required 条件, 其他条件应该在该字段不为零值时验证.

5. What did you see instead?

**Comment by zjjott** [comment]
> 希望表单验证可以增加一个自定义字段名称的 StructTag, 在错误提示时, 可以使用自定义的名称而不是字段名.

这个可以靠展开valid.Errors时做对应的操作。不过beego里面到处都没有label和i18n的设置，只能靠外部组件了

> 另外, 验证时如果不写 Required 条件, 其他条件应该在该字段不为零值时验证.

这样似乎不符合Required的语义

**Comment by miraclesu** [comment]
@astaxie 关于 `Required` 的建议我觉得可以考虑，比如对于 `Email`、`IP` 等这些字符串的函数，如果不写 `Required`，对于空字段不进行验证，你觉得呢？
#2713

**Comment by astaxie** [comment]
@miraclesu 恩，我觉得可以的，你来做这个修改吗？
