### ISSUE TITLE
beego panic 200 in prov

### ISSUE THREAD

**Issue by hyhlinux** [beego/beego#2529]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
➜  imgfit git:(panic) ✗ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/apple/go-dev
├── GOROOT    : /usr/local/Cellar/go/1.7.4_1/libexec
├── Compiler  : gc
└── Date      : Friday, 24 Mar 2017
➜  imgfit git:(panic) ✗

2. What operating system and processor architecture are you using (`go env`)?
➜  imgfit git:(panic) ✗ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/go-dev"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.7.4_1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.4_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fy/whcwmcyx7tnc33h9x5y1q1pw0000gn/T/go-build061875999=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
➜  imgfit git:(panic) ✗

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
view:
func (this *ImgfitV1Controller) Get() {
	//标记是否返回原图
	panic("test")
}

i get 200 in prov mod

4. What did you expect to see?
  i wanto get 500. 

5. What did you see instead?
beego/config.go
	if BConfig.RunMode == DEV && BConfig.EnableErrorsRender {
			showErr(err, ctx, stack)
		}
        ctx.ResponseWriter.WriteHeader(500)

**Comment by zjjott** [comment]
your can write `beego.ErrorHandler` for your customer behavior

**Comment by hyhlinux** [comment]
亲， 这不是自定义错误 。 
进func (this *ImgfitV1Controller) Get() {
//程序crash 掉了， 某个三方库panic了， 导致本次执行的go 程crash,
//此时beego 返回了200. 这个是不能接受的在非dev模式 
}

**Comment by hyhlinux** [comment]
我这边不能 beego.ErrorHandler("200", xxxxxx) 这样处理吧？不好意思，我可以更友好一点****

**Comment by zjjott** [comment]
OIC , recover from Panic is func `recoverPanic` in `BConfig.RecoverFunc`:
```
if BConfig.EnableErrorsShow {
    if _, ok := ErrorMaps[fmt.Sprint(err)]; ok {
        exception(fmt.Sprint(err), ctx)
				return
	}
}
```
it try to found error in `ErrorMap` that is register by `beego.ErrorHandler` ,for exceptions that are not registered, will not process
so some panic error like this:
```
// @router /test [post]
func (c *TestController) Post(){
	panic("500")
}
```
will be process
but 
```
// @router /test [post]
func (c *TestController) Post(){
	panic("other error")
}
```
will not be process

try to overwrite `BConfig.RecoverFunc`

**Comment by hyhlinux** [comment]
ok, i will try
