### ISSUE TITLE
controller.ServeJSON should work will with beego.NSAfter

### ISSUE THREAD

**Issue by printfcoder** [beego/beego#2534]
beego.NSAfter does not work after controller.ServeJSON

**Comment by zjjott** [comment]
can you provide reproducible code?

**Comment by printfcoder** [comment]
It is a bug, I check the beego source code. 
github.com/astaxie/beego/controller.go:309
`

// ServeJSON sends a json response with encoding charset.
func (c *Controller) ServeJSON(encoding ...bool) {
	var (
		hasIndent   = true
		hasEncoding = false
	)
	if BConfig.RunMode == PROD {
		hasIndent = false
	}
	if len(encoding) > 0 && encoding[0] == true {
		hasEncoding = true
	}
	c.Ctx.Output.JSON(c.Data["json"], hasIndent, hasEncoding)
}
`
Ctx.Output.JSON is called, and beego router's func NSAfter never executes when current request has been output anything [see](https://github.com/astaxie/beego/issues/679)
`c.Ctx.Output.JSON(c.Data["json"], hasIndent, hasEncoding)`

**Comment by zjjott** [comment]
case by `Namespace` insert `FinishRouter` filter to beego, but actually beego handle filter when response have not wroten anything
you can use `beego.InsertFilter` and add `returnOnOutput` params

```
beego.InsertFilter("*",beego.FinishRouter,function(ctx *Context){}, false)
```

**Comment by printfcoder** [comment]
yes, but when the style of using router like 
`beego.NSRouter("/:lang", &controllers.Controller{}, "post:SetLang")`
then the data processed by controller can not be passed to ctx. 
Controller handles ctx, in turn, ctx cannot handle controller.

**Comment by astaxie** [comment]
> then the data processed by controller can not be passed to ctx.
you can. one request one ctx for all filters and controller
