### ISSUE TITLE
what model MUST need a primary key field, default use 'id' if not set?

### ISSUE THREAD

**Issue by chiuan** [beego/beego#2546]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.7.4
beego1.8

2. What operating system and processor architecture are you using (`go env`)?
amd64

because i have multi primary key of the model,so dont need "Id" one.

**Comment by ajaychk** [comment]
same issue

**Comment by dchaofei** [comment]
same issue
