### ISSUE TITLE
ORM m2m query error

### ISSUE THREAD

**Issue by kutear** [beego/beego#2552]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : 1.7.2
├── GoVersion : go1.8
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/***/Work/golang
├── GOROOT    : /opt/go
├── Compiler  : gc
└── Date      : Thursday, 6 Apr 2017

2. What operating system and processor architecture are you using (`go env`)?
GOPATH="/home/***/Work/golang"
GORACE=""
GOROOT="/opt/go"
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build211648297=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```golang
type Dialog struct {
	PositiveAction []*Action `orm:"rel(m2m);rel_table(dialog_positive_action)"`
	NegativeAction []*Action `orm:"rel(m2m);rel_table(dialog_negative_action)"`
        ...
}

type Action struct {
        ...
}

// And I query with this
res := &database.Dialog{
		Id: 1,
}
ormer.LoadRelated(res, "PositiveAction")
ormer.LoadRelated(res, "NegativeAction")  //error line ,if i remove this line, i can get all PositiveAction  
```

4. What did you expect to see?
I wish I can get all Action both PositiveAction and NegativeAction in `res`

5. What did you see instead?
> server:runtime error: invalid memory address or nil pointer dereference
/opt/go/src/runtime/asm_amd64.s:514
/opt/go/src/runtime/panic.go:489
/opt/go/src/runtime/panic.go:63
/opt/go/src/runtime/signal_unix.go:290
/home/***/Work/golang/src/github.com/astaxie/beego/orm/orm.go:421
/home/***/Work/golang/src/github.com/astaxie/beego/orm/orm.go:373
/home/***/Work/golang/src/github.com/astaxie/beego/orm/orm.go:284
//error line

And I found this same with #1109

anyone can help me?

**Comment by phuctranhoang** [comment]
I have the same problem with Beego version 2.0.1 and MySQL. Anyone can help me?
