### ISSUE TITLE
static目录下的.apk文件下载后不能安装

### ISSUE THREAD

**Issue by GavinYang-LR** [beego/beego#2554]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
golang 1.7
beego 1.8.0

2. What operating system and processor architecture are you using (`go env`)?

编译平台： macbook air
运行平台：centos6.4    64bit

3. What did you do?
我发布apk应用是直接在放在 /static/zwtx.apk ,手机任何浏览器下载都会无法安装，文件大小一致，但不能解析安装。

没有使用gzip的配置，原来使用beego1.1 最近升级为最新版本出现的，测试beego1.1版本没有这样的问题

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
你原始文件和下载的文件进行 md5 校验一下看看

**Comment by yyl719133368** [comment]
@astaxie 
你好 ，我把手机下载的apk文件上传到服务器上对比了下
jyxz1.apk 为手机下载的
jyxz.apk 为服务器上的源文件

**对比结果**：
大小一致，md5不一致

**大小信息：**
-rw-r--r--  1 root root  5312058 Apr 10 11:35 jyxz1.apk
-rw-r--r--  1 root root  5312058 Mar  9 14:58 jyxz.apk

**md5信息：**
b936469f4210d2824e6f5366e4e21596  jyxz1.apk
3a23a33e37c9a04ec62eb6096962da67  jyxz.apk

**Comment by astaxie** [comment]
看上去是其中的一些byte数据被修改了

**Comment by yyl719133368** [comment]
是的，有什么办法暂时避免这种问题？

**Comment by zjjott** [comment]
手机下载时，中间有经过什么运营商的代理吗？
用wget下载是否可以复现？

**Comment by zjjott** [comment]
可以使用nginx直接分发静态文件，看还有没有这个问题

**Comment by yyl719133368** [comment]
@zjjott  没有任何代理的 

nginx直接分发没有问题的，这不是用beego方便嘛，

**Comment by zjjott** [comment]
试试电脑上用wget或者curl能不能复现？
我试了试大文件都是正常的

**Comment by linux-mac** [comment]
这种静态文件还是交给nginx吧

**Comment by JessonChan** [comment]
@yyl719133368 问题是否解决了？

**Comment by yyl719133368** [comment]
@JessonChan 没有解决呢...

**Comment by JessonChan** [comment]
@yyl719133368 这个问题我没有办法复现，在电脑上都是正常的。你能否提供一个最简单的可以复现的工程给我？
