### ISSUE TITLE
Can i use MaxBytesReader or limit size request body from GetFile() ?

### ISSUE THREAD

**Issue by FaionSax** [beego/beego#2566]
I want limit upload file (30Mb) from ajax upload. In beego code i`m read 
> It stores up to maxMemory bytes of the file parts in memory and the remainder on disk in temporary files.

Can i don`t save data in OS /tmp dir if data > 30Mb?
Can i use MaxBytesReader -->

>  MaxBytesReader is similar to io.LimitReader but is intended for limiting the size of incoming request bodies. In contrast to io.LimitReader, MaxBytesReader's result is a ReadCloser, returns a non-EOF error for a Read beyond the limit, and closes the underlying reader when its Close method is called.

or analog func.

Thanks for BeeGo

**Comment by zjjott** [comment]
you can use nginx behind golang to process those request, it's not a good idea to do this process in go...If you have to do this,this beego `InsertFilter`
