### ISSUE TITLE
如何在beego中使用http proxy?

### ISSUE THREAD

**Issue by aztack** [beego/beego#2571]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

> beegon 1.8.1

2. What operating system and processor architecture are you using (`go env`)?
> GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wangweihua/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ql/0pgtpt3566l1zn584q11_74r0000gn/T/go-build860118114=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

请beegon是否有内置的HTTP Proxy功能？如果没有，如何使用第三方HTTP Proxy库？
我想达到的目的类似node的expressjs框架的express-http-proxy库提供的功能：

```js
var app = express()
app.use(proxy('other server url', {
  decorateRequest: (req) => {
    // modify request object
    return req
  },
  forwardPath: (req, res) => require('url').parse(req.url).path
}))
```
这样，将某些请求转发到'other server url' 指向的服务并返回对应内容。可以在decorateRequest函数中修改request对象（比如增加token）。

谢谢

**Comment by zjjott** [comment]
使用Go标准库`net/http`:
```golang
resp, err := http.Get("http://example.com/")
```
或者`beego/httplib`:
```golang
httplib.Get("http://beego.me/").Response()
```
