### ISSUE TITLE
Swagger is not working for array variables

### ISSUE THREAD

**Issue by RajeshKumar1990** [beego/beego#2599]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.3

├── Beego     : 1.8.0
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Model Definition:
```
 type A struct {
	Name   string
	Value  float64
	CValue C
	Values []int
}
type B struct {
	Name   string
	Value  float64
	CValue C
	Array  []int
}
type C struct {
	Person string
	Number int64
}

```
Controller:
```
// @Title Post
// @Description POST Category
// @Param	body body   models.structinfo.A	true "The Supplier content"
// @Success 200 	{string} models.structinfo.Materials
// @Failure 403 body is empty
// @router /populate [post]
func (this *SampleController) Populate() {
	var src interface{}
	dst := B{}
	err := json.Unmarshal(this.Ctx.Input.RequestBody, &src)
	if err != nil {
		this.Data["json"] = "Error in the input"
	} else {
		fmt.Println("----------------")
		fmt.Println(src)
		fmt.Println("-----------------")
		err := helper.Populate(&dst, src)
		if err != nil {
			this.Data["json"] = err
		} else {
			fmt.Println(dst)
			this.Data["json"] = dst
		}
	}
	this.ServeJSON()
}

```
![swagger2](https://cloud.githubusercontent.com/assets/22511293/25420354/5eb48b96-2a8a-11e7-9323-bcef9c438d84.JPG)

My swagger.json model definition looks like this 
```
       "controllers.A": {
            "title": "A",
            "type": "object",
            "properties": {
                "CValue": {
                    "$ref": "#/definitions/models.structinfo.C"
                },
                "Name": {
                    "type": "string"
                },
                "Value": {
                    "type": "number",
                    "format": "double"
                },
                "Values": {}
            }
        },
```
4. What did you expect to see?
Values int array in the swagger definition

5. What did you see instead?
i see an empty braces.

**Comment by baobeimm** [comment]
+1

**Comment by julienkosinski** [comment]
I think I have the same bug here, strange thing is that sometimes I see empty braces and some other times it works and I can't see the difference. Don't know what's going on. I'm wandering if it's not a swagger issue because the swagger.json generation seems ok on my side...
