### ISSUE TITLE
ParseForm ignore empty fields

### ISSUE THREAD

**Issue by osavchenko** [beego/beego#2602]
1. What version of Go and beego are you using (`bee version`)?

```
├── Beego     : 1.8.1
├── GoVersion : go1.8.1
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Users\user\go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Wednesday, 26 Apr 2017
```

2. What operating system and processor architecture are you using (`go env`)?

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\user\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

3. What did you do?

I tried to handle form submission with such code:

```
type UsersController struct {
	beego.Controller
}

func (c *UsersController) Save() {
	user := models.User{}

	c.ParseForm(&user)

        ...
}
```

```
type User struct {
	Id       uint64 `form:"-"`
	Name     string `orm:"size(255)" valid:"Required; MaxSize(255)" form:"name"`
	Email    string `orm:"size(255)" valid:"Required; MaxSize(255); Email" form:"email"`
	Password string `orm:"size(120)" valid:"MaxSize(72)" form:"password"`
}
```

And submit form like:

```
name: "test user"
email: "" (empty field)
```

4. What did you expect to see?

When form has empty fields (like `email`) they should not be ignored, it's just empty field and it should be processed.

5. What did you see instead?

Empty form fields are ignored.

**Comment by zjjott** [comment]
`ParseForm ` only do **parse** .not **validate**,you may use like this:
```
        valid := validation.Validation{}
	err := c.ParseForm(form)
	if err != nil {
		return false, err.Error()
	}

	b, err := valid.RecursiveValid(form)
	if err != nil {
		return false, err.Error()
	}
        if !b {
		msg := HandleErrors(valid.Errors)
		return false, msg
	}
```

**Comment by osavchenko** [comment]
I know, but I'm not sure about [this lines](https://github.com/astaxie/beego/blob/master/templatefunc.go#L311-L313) in beego. As I understand if form has empty field parser just ignore it.

**Comment by osavchenko** [comment]
Looks like it's normal behaviour? Really?

**Comment by zjjott** [comment]
if there is a empty string on `url.Values`,it will not be parsed
looks normal,what is your doubt

**Comment by osavchenko** [comment]
It should be parsed to empty value. What if I fill form and want to set one field to empty value?

**Comment by zjjott** [comment]
string in struct is set empty string as default when use `new` keyword,do you have a try?
```
gore> type Domain struct{ID string}
gore>
gore> a:=new(Domain)
&main.Domain{ID:""}
```

**Comment by osavchenko** [comment]
Yes, on new objects it's works well. But what if I want to update existing object? Maybe I'm doing something wrong

**Comment by zjjott** [comment]
someone want to keep object attrbutes when it's empty
someone like you want to update object
who is right?
so there are common ground: create a new object and get what you want,implement yourself logic
BTW,update database should use `Update` method,and it will update column that you need

**Comment by osavchenko** [comment]
In this case we has two ways how to solve it:
1. Just don't add `form` annotation and field will not updated. If you add field to form it **should** be updated anyway. In other cases validation rule`required` has no sense.
2. Implement functionality for different forms for one model.

**Comment by DaveData** [comment]
I agree with @osavchenko .

If you don't want to change an objects property, don't inlcude that property in a form. If it's included in the form, set the property to the given value, event if it's empty.

Let's say I have a user profile and want to empty my "company" field; as a user I expect when I empty the form and save, the property is overwritten with an empty string.

This behaviour seems to be prevented by https://github.com/astaxie/beego/blob/master/templatefunc.go#L311

**Comment by astaxie** [comment]
@osavchenko @DaveData IMO the ParseForm is try to convert the form value to struct, while this struct is supposed to be a new struct. While form empty value are the default value in struct. 

Let's have a example for the bool. If the form is empty, then it will return a err when convert it to bool. I don't think that's what we wanted. The same will happen for int and other type.
