### ISSUE TITLE
redis error

### ISSUE THREAD

**Issue by weiwolves** [beego/beego#2604]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go 1.8.1
beego 1.8.1
bee 1.8.3
redigo newest update

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux" ----- centos 7
GOPATH="/data/repos/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build122521219=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

after my dashboard production upgrade from beego1.8 to beego1.8.1, when access the login page,
error message shows:

...
                </style>
        </head>
        <body>
                <div id="wrapper">
                        <div id="container">
                                <div class="navtop">
                                        <h1>Service Unavailable</h1>
                                </div>
                                <div id="content">
                                        <br>The page you have requested is unavailable.<br>Perhaps you are here because:<br><br><ul><br><br>The page is overloaded<br>Please try again later.</ul>
                                        <a href="/" title="Home" class="button">Go Home</a><br />

                                        <br>Powered by beego 1.8.1
                                </div>
                        </div>
                </div>
        </body>
</html>

and the dashboard log write:
[dashboard_controller.go:35] AuthController Signin ^[[0m
2017/04/27 17:18:16 ^[[1;44m[D] [dashboard_controller.go:72] body: map[]  ^[[0m
2017/04/27 17:18:16 ^[[1;44m[D] [server.go:2568] |183.214.201.187|^[[42m 200 ^[[0m|   2.013219ms|   match|^[[44m GET     ^[[0m /auth/signin   r:/auth/signin^[[0m
2017/04/27 17:18:16 ^[[1;44m[D] [server.go:2568] |183.214.201.187|^[[42m 200 ^[[0m|    450.896µs|   match|^[[44m GET     ^[[0m /favicon.ico^[[0m
2017/04/27 17:19:14 ^[[1;31m[E] [server.go:2568] redigo: nil returned^[[0m

error repeated every time

after i downgrade to beego 1.8.0, all other libs (redigo, etc) keep unchanged, it works fine!!

'cause it's a in-production issue,i just remembered and can't except the code for you guys

I think i met a issue, or anyone can point out i missed sth.

**Comment by OlegFX** [comment]
I have the same issue with the latest beego version.
