### ISSUE TITLE
Support for Fatal log level

### ISSUE THREAD

**Issue by apremalal** [beego/beego#2606]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.8.1 darwin/amd64
bee v1.8.1

2. What operating system and processor architecture are you using (`go env`)?
OS mac

is log.Critical supposed to exit the application? isn't it suppoed to be the equivalent of log.Fatal in the native log package? If not, is there a way to log and exit at the same time (similar functionality to log.Fatal)?

**Comment by zjjott** [comment]
Fatal is equivalent to l.Print() followed by a call to os.Exit(1).

**Comment by apremalal** [comment]
@zjjott Aware of that. Is there a reason for beego to not to have log.Fatal() kind of functionality?. It'd be convenient to have a single method to print out a log and exit the app in a fatal error.

**Comment by zjjott** [comment]
beego is a web framework, so most of error happen in request is can be recover,why must be exit the app?

**Comment by apremalal** [comment]
@zjjott we might need to exit the app in an application initialization phase for reasons like external service unavailability, service credential failures etc..

**Comment by zjjott** [comment]
so do it by `os.Exit(1)` or `log.Fatal`, beego will not do this,because it's a web framework,robust is important

**Comment by apremalal** [comment]
@zjjott I don't think robustness have anything to do here. I've already used os.Exit. This thread is about the support for log.Fatal wrapper with beeg/log. IMO log.Critical it's good to include os.Exit(1)

**Comment by zjjott** [comment]
beego.Log is just a log component with this web framework,it's not like go `log` package,why web framework **must** do this thing belong to system?
If you must do so,you can implement your own `Logger` interface,write anything logic you want, panic or exit or other
