### ISSUE TITLE
Orm -fk is not acting as foreign key 

### ISSUE THREAD

**Issue by RajeshKumar1990** [beego/beego#2607]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.3

├── Beego     : 1.8.0
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Friday, 28 Apr 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
This is my struct
```
type Category struct {
		Id      int       `orm:"pk;auto;type(int);column(id)"`
		Name    string    `orm:"column(name);type(varchar);size(100)"`
	}
type Materials struct {
		Id       int64     `orm:"pk;auto;type(serial);column(id)"`
		Category *Category `orm:"rel(fk);column(category_id)"`
		Name     string    `orm:"column(name);type(text)"`
	}
	
```
In this Materials struct , it has  the foreign key to category.By normal when i try to insert in the materials,it will check if the value of the foreign key(category_id) is present in the category primary key(id).If not it wont allow the user to insert.But here i can insert any value inside the materials foreign key (category_id) even the values which is not present in primary key of category.

4. What did you expect to see?
If the value of the foreign key is inserted it need to check if the value is present in the primary key of category.If the value is not present it needs to throw an error.
5. What did you see instead?
It just insert the value without giving out the error.

**Comment by Bowenwu1** [comment]
+1 I encouter this problem too

**Comment by asish-tom** [comment]
+1
