### ISSUE TITLE
how to generate "example" in propertie of object to swagger.yaml

### ISSUE THREAD

**Issue by zhudongmei** [beego/beego#2614]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8.3

2. What operating system and processor architecture are you using (`go env`)?
use bee generate docs to generte yaml.
but in the object properties,there is no example.
i want to know ,how to add example in object of my code

4. What did you expect to see?
the swagger.yaml has example value

**Comment by zhudongmei** [comment]
@astaxie, please take a look

**Comment by astaxie** [comment]
not support now

**Comment by gnanakeethan** [comment]
Can you clarify? I think this was a working mechanism in the previous releases. It will be easier if we could have it.

**Comment by Colstuwjx** [comment]
How's it going right now?
