### ISSUE TITLE
session redis支持sentinel吗

### ISSUE THREAD

**Issue by anjingxz** [beego/beego#2619]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8.1

2. What operating system and processor architecture are you using (`go env`)?
1.8

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
支持sqlserver

5. What did you see instead?
iris

**Comment by zjjott** [comment]
easy to implement by using https://github.com/FZambia/go-sentinel : Redis Sentinel support for redigo library
and overwrite `SessionInit` method,register yourself session engine
