### ISSUE TITLE
Beego routes中的路由和InsertFilter冲突问题（必现）

### ISSUE THREAD

**Issue by PaulChen2016** [beego/beego#2622]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : 1.7.2
├── GoVersion : go1.7.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    :******
*************
├── GOROOT    :*******
├── Compiler  : gc
└── Date      : Wednesday, 3 May 2017

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jason/code/GOLIB:/home/jason/code/ATMP"
GORACE=""
GOROOT="/home/jason/go"
GOTOOLDIR="/home/jason/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build788844631=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
3.1>routes中通过如下方式定义路由，在main.go中引用
ns := beego.NewNamespace("/v1",
		beego.NSNamespace("/user",
			beego.NSInclude(
				&user.UserController{},
			),
		),
	)
	beego.AddNamespace(ns)
3.2>main.go中，通过beego.InsertFilter("/*", beego.BeforeRouter, FilterUser)增加一个过滤函数

3.3>系统build，运行后，3.1中定义的路由不生效

3.4>规避措施，注释掉main.go的InsertFilter语句，删除routes目录下生成的临时代码文件，重新编译运行。然后再去掉main.go中的注释，是InsertFilter方法生效。重新编译运行，ok；

每次增加新的路由都要通过3.4的规避方法

4. What did you expect to see?
解决该冲突问题 ，不用规避方法

5. What did you see instead?

**Comment by zjjott** [comment]
如何运行？bee run还是咋？没有遇到这种情况。。。

**Comment by PaulChen2016** [comment]
就是go build后运行可执行程序

**Comment by zjjott** [comment]
过程是这样的：你在router(假设对应的文件夹中只有一个router.go)中修改之后，编译，此时不会生成对应的commentsRouter.go，而会在先运行一下对应的二进制时，才生成对应的commentsRouter.go，由于golang编译的机制，此时二进制的router里是没有commentsRouter.go对应的路由的，所以请求会404
只需要再运行一下go build，把这个commentsRouter编译进去就行
和Filter应该没有关系

**Comment by zjjott** [comment]
另外由注释生成路由这个逻辑，只在dev模式下会执行，这个在文档里也是有说的：https://beego.me/docs/mvc/controller/router.md
