### ISSUE TITLE
Create a gin_index for jsonb in postgresql for orm

### ISSUE THREAD

**Issue by RajeshKumar1990** [beego/beego#2623]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.3

├── Beego     : 1.8.0
├── GoVersion : go1.6.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Tuesday, 2 May 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I am trying to use jsonb in postgresql.The postgresql have a gin index for the jsonb for efficient querying.
Does beego supports this in the model definition.
If not will there be any future updates on this.
Thanks.

4. What did you expect to see?
Adding the gin index for jsonb column

**Comment by astaxie** [comment]
It's not support now

**Comment by RajeshKumar1990** [comment]
@astaxie Will there be a support in future!!!!
Thanks

**Comment by astaxie** [comment]
@RajeshKumar1990 yea, that's possible.
