### ISSUE TITLE
当根路由相同，版本号不同时，自动化文档生成模型不能正常显示

### ISSUE THREAD

**Issue by lycblank** [beego/beego#2625]
我有两个版本的用户操作，分别对应
/v1/user/xxx
/v2/user/xxx
但是/v1/user下的所有模型不能正常显示， /v2/user下的模型正常显示
当我去掉/v2/user这个路由时，/v1/user下的模型能正常显示

**Comment by zjjott** [comment]
有可复现的代码吗？不能正常显示的部分代码是？

**Comment by astaxie** [comment]
是的，目前只支持一个版本的文档，因为在swagger里面没有这样的支持，目前有的解决方案是根据不同的baseURL生成不同的swagger.json。 

http://tech.asimio.net/2016/05/07/Documenting-multiple-REST-API-versions-using-Spring-Boot-Jersey-and-Swagger.html
