### ISSUE TITLE
关于注解路由的问题【不是大问题，甚至不是问题】

### ISSUE THREAD

**Issue by Tom-Kail** [beego/beego#2626]
1. What version of Go and beego are you using (`bee version`)?
```
├── Beego     : 1.8.0
├── GoVersion : go1.8
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : D:\gopath
├── GOROOT    : C:\Go
├── Compiler  : gc
└── Date      : Friday, 5 May 2017
```

2. What did you do?

一、 /path 和 [post]之间有两个空格
`// @router /path  [post]`

二、 /path 和 [post]之间有一个空格
`// @router /path [post]`

情况一会导致生成注解路由失败，程序无法运行

手残，多加了个空格，眼拙，没看出来，最后通过看源码才知道原因。。

**Comment by astaxie** [comment]
恩，可以改进的更好，其实params支持任意多个space，这些其实也可以改进成这样
