### ISSUE TITLE
如何知道beego成功匹配的注册URL是什么？

### ISSUE THREAD

**Issue by zenghuiLee** [beego/beego#2627]
@huacnlee @tmc 

例如 用户访问的 /api/user/v1/users/123/userid  匹配的是这个注册路由 /api/user/v1/users/:userId/userid 而不是别的？

实现集中鉴权，所有的访问路由集中用一个controller函数处理，需要知道所访问的url所对应的注册url是什么

**Comment by zenghuiLee** [comment]
@astaxie

**Comment by astaxie** [comment]
这个接口没有暴露出来，应该是在routerInfo.pattern

**Comment by zjjott** [comment]
集中鉴权例如AWS 签名不是要的是前者么？
BTW集中鉴权可以用Filter的。。。
