### ISSUE TITLE
当model 不在项目目录下,导入的是其他项目的 model 时，自动化文档生成模型不能正常显示，结构是空的

### ISSUE THREAD

**Issue by uuappli** [beego/beego#2632]
1. What version of Go and beego are you using (`bee version`)?

Beego     : 1.8.2
GoVersion : go1.8.1
GOOS      : darwin
GOARCH    : amd64

2. What operating system and processor architecture are you using (`go env`)?
GOOS      : darwin
GOARCH    : amd64
NumCPU    : 4

3. What did you do?

由于多个项目都要用到 model 层，所以个 model 抽出来成公共项目，结果在当前项目下 自动化文档生成model不能正常显示，结构是空的，model 不在当前项目目录

注解
`
// @Title 用户登录

// @Description 用户登录

// @Param	username		query 	string	true		"用户名"

// @Param	password		query 	string	true		"密码"

// @Success 200 {object} models.DoctorEntity

// @Failure 403 user not exist

// @router /login [get]
`

4. What did you expect to see?
能正常显示

5. What did you see instead?
<img width="320" alt="2017-05-11 09 50 21" src="https://cloud.githubusercontent.com/assets/6519730/25928539/58b8ff96-362f-11e7-9bb6-ef7291cf0c9a.png">

<img width="1022" alt="2017-05-18 15 03 51" src="https://cloud.githubusercontent.com/assets/6519730/26190289/3e638362-3bdb-11e7-809d-8b440daab429.png">

**Comment by astaxie** [comment]
please provide more information with the issue template

**Comment by uuappli** [comment]
已更新
