### ISSUE TITLE
commentsRouter_controllers.go删除之后，重新启动无法再生成

### ISSUE THREAD

**Issue by yyf1986** [beego/beego#2647]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.8.2
├── GoVersion : go1.7.4
2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/usr/lib/golang/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/gocode"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build139263842=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"
3、问题描述
我手动删除了正在执行的commentsRouter_controllers.go，然后在重新启动就无法在自动生成了，swagger的页面可以访问，但是api访问不了

**Comment by alexsunxl** [comment]
设置成dev模式，然后跑一下bee run.
貌似现在没办法单独生成 comments router

**Comment by yyf1986** [comment]
貌似是这样，必须是dev的模式下，如果控制器里面增加方法，commentsRouter_controllers.go里面的内容才会更新

**Comment by astaxie** [comment]
是的，只有在dev模式下才会重新生成
