### ISSUE TITLE
sessionprovider=file时 经常出现session丢失

### ISSUE THREAD

**Issue by wei193** [beego/beego#2666]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.8.0

2. What operating system and processor architecture are you using (`go env`)?
├── GoVersion : go1.8
├── GOOS      : darwin

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
网页请求中包括5个左右请求，其中有一个是用Handler 写的websocket，经常在调用websocket以后，session丢失。在没有调用该接口的情况下，基本不会出现session丢失情况，websocket中的代码如下,如有不合理希望指出
func (h *WS) ServeHTTP(w http.ResponseWriter, r *http.Request) {
        c, err := ws_upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
	s, err := beego.GlobalSessions.SessionStart(w, r)
	if err != nil {
		return
	}
	defer s.SessionRelease(w)
	role := s.Get("role")
	role_session := role.(map[string]string)
	go Listen(role_session["id"], c)
}

4. What did you expect to see?

5. What did you see instead?

**Comment by sicojuy** [comment]
我也发现了这个问题，session使用外部存储（file，redis，mysql等）时，旧的session会覆盖新的session，尤其在使用websocket的时候很容易复现。
原因是，在一个请求开始的时候会从外部存储读取session信息，在请求结束时将session写回外部存储，中间临时保存session数据在内存中。当有多个请求同时进行时，对session的修改会在其他请求完成时被重写。
我已经修复了session redis存储问题：https://github.com/sicojuy/beego/commit/cc56c3271b27ee326eca1e2a1034ca3bc9ae2d18
如果被merge，我会继续修复其他存储中间件的bug。

**Comment by sicojuy** [comment]
```
type SessionController struct {
	beego.Controller
}

func (c *SessionController) Get() {
	time.Sleep(10 * time.Second)
	v := c.GetSession("xxx")
	if v != nil {
		c.Ctx.WriteString(v.(string))
	} else {
		c.Ctx.WriteString("not found")
	}
}

func (c *SessionController) Set() {
	val := c.GetString("val")
	c.SetSession("xxx", val)
	c.Ctx.WriteString("ok")
}
```

你好，@astaxie 
通过这个代码可以重现bug，Get()请求耗时10s，在这个请求过程中，所有Set()请求对session的修改都是无效的。因为Get()请求结束后，会覆盖重写session，而这并不包含Set()对session的变更。

**Comment by astaxie** [comment]
因为HTTP API是无状态请求，也就是说你的Get请求过来的时候没有带有任何的session_id，那么服务器端就会生成一个session_id，但是这个是等到返回的时候设置到客户端的，这个时候你再次请求Set()的时候，也是不带有任何的session_id，那么系统会再次生成一个新的session_id，返回给客户端，这样就会出现如下这样的过程：

```
Get请求
生成新的session_id
Set请求
生成新的session_id
Set的response设置session_id成功
Get的response设置session_id成功
```
经过上面这样的测试就会发现你最后的session_id是get的session_id

**Comment by astaxie** [comment]
这个属于session locking的问题，我需要好好思考一下这个问题

**Comment by sicojuy** [comment]
你好，@astaxie
可能我前面描述的不够清楚，我认为跟你所描述的是两种情况：
你所描述的情况是：首次请求，新建的session覆盖旧的session。
我前面描述的情况是：对于已存在的session，在并发请求下，因为回写到外部存储有个时间差，所有会造成session覆盖问题。

**Comment by arthur-xie** [comment]
这个在Provider中做一个map不能解决问题，用redis来存储session，一个是可以多个web server共享，二个是web server重启session不丢失。在本地内存中放一个副本，不能解决你所描述的问题。

**Comment by sicojuy** [comment]
👍👍嗯，确实，我考虑欠缺了

在 2017-08-01 18:36:41，"Arthur Xie" <notifications@github.com> 写道：


这个在Provider中做一个map不能解决问题，用redis来存储session，一个是可以多个web server共享，二个是web server重启session不丢失。在本地内存中放一个副本，不能解决你所描述的问题。

**Comment by davidwtf** [comment]
不只是file， redis 也有类似问题，本质是缓存同步的问题。
为什么这个issue报出来这么长时间了，还是open的状态？
有这个问题，beego根本不能上生产啊！！
@astaxie

**Comment by davidwtf** [comment]
下面的附件应该能解决redis上的问题
[myredis_session.go.txt](https://github.com/astaxie/beego/files/2404393/myredis_session.go.txt)

**Comment by leo220yuyaodog** [comment]
beego v1.12.12 仍然存在这个问题，session没能写入文件或redis
