### ISSUE TITLE
logs模块关闭日志颜色的问题

### ISSUE THREAD

**Issue by letian0805** [beego/beego#2668]
调用 logs.SetLogger("console", `{"color":false}`)后，通过logs.Info 等接口输出的日志还是带有颜色

**Comment by wagyu298** [comment]
@letian0805 Hi, I got the same problem. I succeed to disable console colors by the following codes.

```
// main.go
func init() {
    beeLogger := logs.GetBeeLogger()
    beeLogger.DelLogger("console")
    beeLogger.SetLogger("console", `{"color":false}`)
    // ...
}
```

**Comment by ninjadq** [comment]
+1 same problem
