### ISSUE TITLE
Swagger(3.0) 中Param和Success中不能指定其其它项目中的对象

### ISSUE THREAD

**Issue by moodmass** [beego/beego#2669]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

![image](https://cloud.githubusercontent.com/assets/2222124/26395969/510cb02e-40a4-11e7-9cea-24da9c0ce84e.png)

2. What operating system and processor architecture are you using (`go env`)?

![image](https://cloud.githubusercontent.com/assets/2222124/26395943/3fa9c3e4-40a4-11e7-80fa-1ead4f84041b.png)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

我的配置
// @Param  body  body api.ReqLogin  true  ""
// @Success 200 {object} api.RespCxt

这两个对象都是另外一个模块中的对象，启动的时候出现：
![image](https://cloud.githubusercontent.com/assets/2222124/26396777/c3c8f094-40a6-11e7-8016-caba298751fc.png)

4. What did you expect to see?

能够找到其它模块中的对象

5. What did you see instead?

**Comment by imiskolee** [comment]
its look at a bug

**Comment by Unicom1** [comment]
我也遇到同样的问题，无法引入其他项目的对象
