### ISSUE TITLE
Foreign keys in native database

### ISSUE THREAD

**Issue by francoishill** [beego/beego#267]
The foreign keys, rel(fk), should be stored in the native database too.

An example would be
`FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE`

**Comment by lucasSa** [comment]
is there a planed feature for foreign keys? +1

**Comment by aacanakin** [comment]
is there a planed feature for foreign keys? +1

**Comment by jerson** [comment]
+1 :100:

**Comment by fnkr** [comment]
+1

**Comment by jmblck** [comment]
+1

**Comment by archerbj** [comment]
do we already have this feature or in/out of the plan ?
