### ISSUE TITLE
关于路由的扩展

### ISSUE THREAD

**Issue by liunianmoshi** [beego/beego#2672]
不知道在路由这块能不能改进下，注册路由不在一个个的根据url去写，像nodejs的路由是可以扩展读文件调用相应的方法，.net 的mvc框架，也是可以动态的根据url获取相应的控制器在去调用相应的控制器方法，不在beego这块有没有类似的扩展或者怎么去实现这种根据url动态的去调用相应的控制器，而不是人工的一个个的去注册路由？
想实现的像这种的形势，
 routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );
不知道beego这块能实现不？

**Comment by astaxie** [comment]
Go是一个静态语言，所以他编译之前这些controller必须是知道的，不然就没办法找到这些controller

**Comment by liunianmoshi** [comment]
C#也算是一个静态语言，目前微软的mvc路由这块，是把所有的路由规则缓存下来，然后通过url映射相应的路由规则，然后去反射获取controller的实例，在去调用controller里的method，这样可以达到路由注册这块的简化，虽然反射会因为查找和加载牺牲一些性能，但是这个过程可以放在应用程序启动前去自动注册好并缓存下来还是可以的，我目前还没深入了解过go这个语言，只是个个人建议，因为按目前的路由注册形式，如果我的业务比较庞大，可能需要几十个甚至上百个controller，那一个个的在route上去写，不管从代码量还是整体的代码规范上看都有点冗余，不知道这块作者目前有没有好的解决办法

**Comment by cch123** [comment]
现在已经不流行在一个项目里堆上百个接口了。。。

**Comment by liunianmoshi** [comment]
这不是上百个接口的问题，一个后台程序需要十个控制这很正常吧，十个控制器就需要在路由上注册十个控制器以及对应的url，不感觉这种方式有点冗余吗？

**Comment by vipplayerdev** [comment]
用Golang实现过，具体思路是通过映射去完成，有点类似Tp的免路由模式。基于Golang的特性，你仍然需要做一个映射用的表。
