### ISSUE TITLE
beego orm MYSQ链接被断开如何解决？

### ISSUE THREAD

**Issue by EchoLiew** [beego/beego#2673]
错误如下：
[mysql] 2017/01/15 12:23:43 packets.go:124: write tcp 127.0.0.1:45697->127.0.0.1:3306：write: broken pipe

好像orm也没有提供设置超时时间的方法，这个问题怎么解决呢？求指导，谢谢！

**Comment by astaxie** [comment]
https://forum.golangbridge.org/t/mysql-broken-pipe/2086/7
