### ISSUE TITLE
问一下，怎么自定义日志格式，增加user-agent和refer？

### ISSUE THREAD

**Issue by lf2186** [beego/beego#2674]
1，beego 1.8.4
2，ubuntu 16.04
3，需要自定义日志格式，增加ua和refer，请问怎么配置？

**Comment by smallfish** [comment]
需要修改 https://github.com/astaxie/beego/blob/master/router.go#L875

不过不建议这么改，应该在 beego 之前有类似 nginx 这样的 webserver 负责转发，在 webserver 里记录 ua 之类
