### ISSUE TITLE
beego orm unsuported tags error does not reveal the line code where error occured

### ISSUE THREAD

**Issue by bakanis** [beego/beego#2675]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?
centos 7, x64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
models.Model line:xxx unsupport orm tag not null

5. What did you see instead?
unsupport orm tag not null

**Comment by astaxie** [comment]
？

**Comment by bakanis** [comment]
Well, it should be logged where that unsupported orm tag exist in the model. Image, there are many models and the compiler does not give idea which model is incorrect. 
E.g. beego tells the file name and the line where error is
2017/05/25 20:07:12 ERROR    ▶ 0004 Failed to build the application: models/init.go:11:2: cannot find package 
But orm error just says 'unsupportet orm tag not null'.
