### ISSUE TITLE
beego的orm中count()函数不能不支持类似count(field)的查询

### ISSUE THREAD

**Issue by qiangmzsx** [beego/beego#2679]
HI，astaxie：
    最近使用beego的orm时候发现调用QuerySeter接口中的count()只能查询：
    SELECT COUNT(*) FROM `albums_category`
   如果业务需要查询：
   SELECT count(DISTINCT `albums_id`)  FROM`albums_category`
 就不被支持了。所以后续是否可以加上这个功能？

**Comment by xuange306** [comment]
同样的, 业务需要翻页连表查询, 不能 count, 就比较尴尬
