### ISSUE TITLE
日志文件格式有JSON格式的演示吗？

### ISSUE THREAD

**Issue by zplzpl** [beego/beego#2680]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
golang: v1.8.0
beego: v1.8.3

2. What operating system and processor architecture are you using (`go env`)?
windows 7

我并不是发现了异常与BUG，我只是想咨询一下。BEEGO是否有JSON输出日志的案例？

**Comment by qiangmzsx** [comment]
建议使用https://github.com/sirupsen/logrus
