### ISSUE TITLE
使用cache（mem）的一些问题

### ISSUE THREAD

**Issue by yyf1986** [beego/beego#2686]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
只用了cache模块
go get github.com/astaxie/beego/cache

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\WorkSpace\Go
set GORACE=
set GOROOT=C:\go
set GOTOOLDIR=C:\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
func main() {
	bm, err := cache.NewCache("memory", `{"interval":10}`)
	if err != nil {
		fmt.Println("err")
	}
	bm.Put("astaxie", 1,20*time.Second)
	fmt.Println(bm.Get("astaxie"))
	time.Sleep(11*time.Second)
	fmt.Println(bm.Get("astaxie"))
	time.Sleep(11*time.Second)
	fmt.Println(bm.Get("astaxie"))
}
4.问题
按照文档上的，说interval是gc回收时间，但是Put也有个设置存活时间的。我设置了回收时间是10s，然后放到内存里面的key是20s，然后我等待11s之后值还是有的，在Put的存活时间之后，key不存在了

**Comment by astaxie** [comment]
GC回收的意思是说已经过期的会自动删除，例如你设置的回收时间是20s，然后你Put的key时间是10s，然后你就没有其他任何操作了，那么当GC触发的时候就会把过期的key删除掉，没有过期的不会删除，这也就是你的case里面key还是存活着

**Comment by lifei6671** [comment]
GC时间应该是扫描过期key的时间间隔吧。

**Comment by yyf1986** [comment]
@astaxie gc回收时间小于Put设置的过期时间，那么key过期之后还是会存在内存里面？不会被回收？

**Comment by yyf1986** [comment]
@astaxie 不管我设置的gc时间大于Put过期时间，还是Put过期时间大于gc回收时间，在最大的那个时间到之后，key的值都是nil。nil指变量为空，是不是就是说key还在，只是为空？
