### ISSUE TITLE
在controller以外的函数中有没有可以获取当前运行的controller实例的API?

### ISSUE THREAD

**Issue by gtechx** [beego/beego#2691]
RT

**Comment by astaxie** [comment]
https://godoc.org/github.com/astaxie/beego#Controller 的     AppController interface{}

**Comment by nature19862001** [comment]
可能我的意思没表达清楚：
我定义了一个model,没有继承beego.Controller。想问下，除了传递controller实例参数，在model的函数中有没有获取当前正在运行的controller实例的方法？
