### ISSUE TITLE
[自动化文档] Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by ibuler** [beego/beego#2694]
如果设置了 外键等约束，自动化文档会提示 ·Maximum call stack size exceeded ·

![image](https://cloud.githubusercontent.com/assets/17382885/26824949/c6d7c618-4ae5-11e7-921d-814bdd9374d3.png)

https://github.com/swagger-api/swagger-ui/issues/2923  应该循环引用的问题

**Comment by julienkosinski** [comment]
Beego swagger have been updated at version 3.0.13 which fix everything :)
