### ISSUE TITLE
How to disable tls1.0 suport when beego run as a server?

### ISSUE THREAD

**Issue by guagualvcha** [beego/beego#2695]
Beego run as a server, support tls1.0、tls1.1, tls1.2 protocal.  Since security issue, i want to disable tls1.0, but i don't know how.
I test if a server support specified tls protocal using commad:
openssl s_client -connect {host}:{port} -tls1{x}

**Comment by astaxie** [comment]
`beego. BeeApp.Server.TLSConfig = &tls.Config{ MinVersion:1}`

More information please refer to https://golang.org/pkg/crypto/tls/#Config 

````
 // MinVersion contains the minimum SSL/TLS version that is acceptable.
        // If zero, then TLS 1.0 is taken as the minimum.
        MinVersion uint16

        // MaxVersion contains the maximum SSL/TLS version that is acceptable.
        // If zero, then the maximum version supported by this package is used,
        // which is currently TLS 1.2.
        MaxVersion uint16
```

**Comment by kevinbin** [comment]
改了sslscan 扫描还是会显示tls 1.0
![5331596710759_ pic_hd](https://user-images.githubusercontent.com/345933/89524607-719a3380-d817-11ea-8ded-66431c354462.jpg)
![5341596710767_ pic_hd](https://user-images.githubusercontent.com/345933/89524609-7363f700-d817-11ea-96c6-7238c4fae217.jpg)

go 1.14版本

**Comment by flycash** [comment]
你可以先检查两件事：
1. `Server.Config = tlsConfig` 是否发生在`Run`调用之前；
2. 其次有没有开启`AutoTLS`功能；

在`Run`方法内部，有几个地方都会直接自己创建`TLSConfig`。你可以考虑断点进去看是否走到了那一步。
