### ISSUE TITLE
利用model创建表时，如何指定”CHARSET=utf8”？

### ISSUE THREAD

**Issue by cyongxue** [beego/beego#2698]
1. mac pro
2. bee 1.8.0
3. go 1.8.0
4. 利用model创建表时，如何指定”CHARSET=utf8”？因为我
type User struct {
    Id                  int

    Name                string                  // 用户名
    PassWord            string                  // 密码
    Avatar              string                  // 头像
    Signature           string                  // 签名
    Email               string                  // 邮箱
    WebSite             string                  // 站点

    Create      int64
    Updated     int64
    Status      int
}这样创建的表，是不支持中文的。看了下beego生成的sql语句为：
CREATE TABLE IF NOT EXISTS `social` (
        `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
        `sort_id` integer NOT NULL DEFAULT 0 ,
        `name` varchar(255) NOT NULL DEFAULT '' ,
        `extra_url` varchar(255) NOT NULL DEFAULT '' ,
        `icon` varchar(255) NOT NULL DEFAULT '' ,
        `create` bigint NOT NULL DEFAULT 0 ,
        `updated` bigint NOT NULL DEFAULT 0 ,
        `status` integer NOT NULL DEFAULT 0 
    ) ENGINE=InnoDB;

**Comment by lifei6671** [comment]
你手动创建的数据库编码为utf8就可以了。orm应该不支持指定编码。

**Comment by chenyangguang** [comment]
So 注册db时的这个设置charset 又有啥用咧？	`rdbErr := orm.RegisterDataBase("default", "mysql", "username:passport@/db_name?charset=utf8")`

**Comment by shiruitao** [comment]
同样遇到这个问题

**Comment by knight110001** [comment]
Upload a solution for this issue based on 1.11.1 for your reference.
[model_charset_support.zip](https://github.com/astaxie/beego/files/3027640/model_charset_support.zip)

**Comment by knight110001** [comment]
and then you can do as following,

replace your version:

RegisterModel(models ...interface{})

to:

RegisterModelWithCharset(charset string, models ...interface{}) 

in your use cases.

Enjoy yourselves!

**Comment by lisgroup** [comment]
`RegisterModelWithCharset()` 方法在哪里呢？@knight110001
