### ISSUE TITLE
交叉编译后，POST的requestbody通过r.Ctx.Input.RequestBody读取为空

### ISSUE THREAD

**Issue by tedgxt** [beego/beego#2699]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go verison: 1.8
beego : 1.8.2
bee: 1.8.3

2. What operating system and processor architecture are you using (`go env`)?
Window7

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

交叉编译命令：CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go

4. What did you expect to see?

5. What did you see instead?
beego框架提供的读取requestbody为空。

**Comment by bolls** [comment]
/conf/app.conf
`CopyRequestBody = true`

**Comment by TedGreen** [comment]
@bolls 
CopyRequestBody选项已经配置为true了

**Comment by astaxie** [comment]
确认你的配置文件读取到了
