### ISSUE TITLE
使用cache(mem)模块,遇到map读写的问题

### ISSUE THREAD

**Issue by slxgsy** [beego/beego#2700]
go的版本是1.8.2 ，程序运行一段时间的会报错，日志如下：

fatal error: concurrent map iteration and map write

goroutine 38 [running]:
runtime.throw(0x9ca49e, 0x26)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42003ee98 sp=0xc42003ee78
runtime.mapiternext(0xc42003ef68)
	/usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc42003ef48 sp=0xc42003ee98
github.com/astaxie/beego/cache.(*MemoryCache).vaccuum(0xc420272b70)
	/data/src/github.com/astaxie/beego/cache/memory.go:220 +0x102 fp=0xc
42003efd8 sp=0xc42003ef48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42003efe0 sp=0xc42003efd8
created by github.com/astaxie/beego/cache.(*MemoryCache).StartAndGC
	/data/src/github.com/astaxie/beego/cache/memory.go:206 +0x189

**Comment by qiangmzsx** [comment]
可以看看：https://github.com/qiangmzsx/beegofreecache
