### ISSUE TITLE
自动生成文档

### ISSUE THREAD

**Issue by rd-code** [beego/beego#2702]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by MrrDai** [comment]
1 whar version of go and beego are you using
├── Beego     : 1.8.3
├── GoVersion : go1.8
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/rd/work/git/
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 9 Jun 2017
2 What operating system and processor architecture are you using (go env)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rd/work/git/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build635157847=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
3 what did you do
bee generate docs
models.role下的Model 可以正常找到，
models.role:
`type Model struct {
	ID          string      `orm:"pk;column(id)" json:"id"`
	Name        string      `orm:"size(100);column(name)" json:"name"`
	Status      int         `orm:"size(1);column(status)" json:"status"`
	Comment     string      `orm:"size(250);column(comment)" json:"comment"`
	CreatedBy   int32       `orm:"column(create_by)" json:"createdBy"`
	CreatedTime time.Time   `orm:"column(create_time)" json:"createdTime"`
	UpdatedTime time.Time   `orm:"column(update_time)" json:"updatedTime"`
	Count       int         `orm:"-" json:"count"`
}`

models.permission下的Model找不到，浏览器输出的结果使用的是role的model
models.permission
`type Model struct {
	ID          string `orm:"pk;column(id)" json:"id"`
	Description string `orm:"size(250);column(description)" json:"desc"`
	Parent      string `orm:"size(100);column(parent_id)" json:"parent"`
	Code        string `orm:"size(20);column(code)" json:"code"`
	Status      int    `orm:"size(1);column(status)" json:"status"`
	Count       int    `orm:"-" json:"count"`
}

type Structure struct {
	Data  Model       `json:"data", orm:"-"`
	Child []Structure `json:"ch
```ildren", orm"-"`
}`

controller注解
// @Title Get
// @Description Get permission and count as id
// @Param   id  path   string   true  "the permission id"
// @Success 200 {object} models.permission.Model
// @Failure 500 get permission error message
// @router /:id/retrieve [get]

response class example value
`{
  "comment": "string",
  "count": 0,
  "createdBy": 0,
  "createdTime": "string",
  "id": "string",
  "name": "string",
  "status": 0,
  "updatedTime": "string"
}
`

**Comment by MrrDai** [comment]
已经度过issue [https://github.com/astaxie/beego/issues/2569](url)

**Comment by MrrDai** [comment]
找到原因了，是swaggergen.parsePackageFromDir扫描文件时以包名作为key，如果出现多个相同的包名的话，后面的会覆盖掉前面的信息
