### ISSUE TITLE
Generating app code from SQLite database is not supported yet

### ISSUE THREAD

**Issue by gamegrd** [beego/beego#2711]
➜  src bee api mid -driver=sqlite -conn=./db.sqlite
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.4
2017/06/12 11:36:34 WARN     ▶ 0001 You current workdir is not inside $GOPATH/src.
2017/06/12 11:36:34 INFO     ▶ 0002 Creating API...
        create   /Users/anonymous/Project/go/src/mid
        create   /Users/anonymous/Project/go/src/mid/conf
        create   /Users/anonymous/Project/go/src/mid/controllers
        create   /Users/anonymous/Project/go/src/mid/tests
        create   /Users/anonymous/Project/go/src/mid/conf/app.conf
        create   /Users/anonymous/Project/go/src/mid/main.go
2017/06/12 11:36:34 INFO     ▶ 0003 Using 'sqlite' as 'driver'
2017/06/12 11:36:34 INFO     ▶ 0004 Using './db.sqlite' as 'conn'
2017/06/12 11:36:34 INFO     ▶ 0005 Using '' as 'tables'
2017/06/12 11:36:34 FATAL    ▶ 0006 Generating app code from SQLite database is not supported yet.

**Comment by astaxie** [comment]
yes
