### ISSUE TITLE
这是不是一个bug呢？模板中键值的名字（数字）索引map数据的方式

### ISSUE THREAD

**Issue by gtechx** [beego/beego#2721]
今天使用模板的时候，发现如下情况：
this.Data["xxx"] = map[string]string{"0": "aaaa"}
上面是代码里面给的数据。
在模板里面我这么用会报错。
{{.xxx.0}}

我在其他地方有用到过这样使用键值的名字索引map数据的方式，没有报错。官网上貌似也有类似的使用说明。
不过这里特殊的是键值名字是数字，而不是字母。

**Comment by astaxie** [comment]
这个如果不能调用就是Go的bug了
