### ISSUE TITLE
go version go1.8.1 darwin/amd64 文件总是自动还原

### ISSUE THREAD

**Issue by benjamin-wen** [beego/beego#2729]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
    go version go1.8.1 darwin/amd64
    beego v1.8.4

2. What operating system and processor architecture are you using (`go env`)?
macOS Sierra, amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Almost each time i run my api application with `bee run xxx`, the file `go version go1.8.1 darwin/amd64` seems to change aumatically to the way it was initially created.

4. What did you expect to see?
source file stays the way they are edited.

5. What did you see instead?

**Comment by zssr** [comment]
turns out that when user.go & object.go files in models & controllers directories affect this behavior. maybe it's beego's feature.
