### ISSUE TITLE
`EnableXSRF = false` does work in the Controller, it still demands the XSRF in the post data

### ISSUE THREAD

**Issue by Jolly23** [beego/beego#2730]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Beego     : 1.8.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build959410788=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

----------------------------------------------------------------------

According to the [Beego XSRF](https://beego.me/docs/mvc/controller/xsrf.md), I enabled the xsrf protection in the conf file, 

    enablexsrf = true
    xsrfkey = xxxxxxx

And there is an API service which does not need the XSRF verification.

So I wrote `c.EnableXSRF = false` in the first line of that Controller, but it does not work, it still demands the xsrf in the post data.

Is somewhere I have made the mistake?

    func (c *APIController) ServiceCGI() {
	    c.EnableXSRF = false
            ............
    }

Logs:

    [C] [asm_amd64.s:514] the request url is  /cgi-bin/service/something
    [C] [asm_amd64.s:514] Handler crashed with error '_xsrf' argument missing from POST

**Comment by RajeshKumar1990** [comment]
I dont know this option is available for particular  service of a controller .As far as the beego doc says this depends on the complete controller.please try giving it in the prepare statement of the controller.Then all the request coming to that controller will never ask the xsrf token.
For additional questions you can look at this link 
[https://beego.me/docs/mvc/controller/xsrf.md](url)
Thanks.

**Comment by SergeyJay** [comment]
I met the same problem.

**Comment by SergeyJay** [comment]
I have the same problem when I used `EnableXSRF = false`  in the Controller

**Comment by pytomtoto** [comment]
@Jancd @Jolly23 
just work with Prepare method.
it's a support controller setting.
```
func (c *AuthUserController) Prepare() {
    c.EnableXSRF = false
}
```
