### ISSUE TITLE
unexpected fault address 0x0

### ISSUE THREAD

**Issue by allenhaozi** [beego/beego#2733]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

2017/06/21 16:22:27 [C] [asm_amd64.s:514] the request url is  /hotword
2017/06/21 16:22:27 [C] [asm_amd64.s:514] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/asm_amd64.s:514
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/panic.go:489
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:288
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/asm_amd64.s:514
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/panic.go:489
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/panic.go:63
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/signal_unix.go:290
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:887
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:608
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:645
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:659
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:767
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:774
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:741
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:753
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:645
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:659
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:645
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:659
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:323
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:617
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:690
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:706
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:323
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:296
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:161
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/encoding/json/encode.go:170
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/test/go/work/src/github.com/astaxie/beego/context/output.go:191
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/test/go/work/src/github.com/astaxie/beego/controller.go:322
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/test/go/work/src/vertical_go/controllers/hotword.go:38
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/test/go/work/src/github.com/astaxie/beego/router.go:799
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/net/http/server.go:2568
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/net/http/server.go:1825
2017/06/21 16:22:27 [C] [asm_amd64.s:514] /home/allen.mh/local/go/src/runtime/asm_amd64.s:2197
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4f18a6]

**Comment by astaxie** [comment]
I have no idea on this issue

**Comment by jannes-sa** [comment]
I'm also get this error

**Comment by jannes-sa** [comment]
2017/10/20 15:15:59 [C] [asm_amd64.s:514] the request url is  /sav_account/v1/accounts
2017/10/20 15:15:59 [C] [asm_amd64.s:514] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:514
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/panic.go:489
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/panic.go:63
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/signal_unix.go:290
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /go/src/account/thirdparty/grpc.go:148
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /go/src/account/thirdparty/grpc.go:61
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /go/src/account/models/account.go:256
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /go/src/account/models/account.go:226
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /go/src/account/controllers/account.go:95
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:514
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/reflect/value.go:434
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/reflect/value.go:302
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /go/src/github.com/astaxie/beego/router.go:815
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/server.go:2568
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/net/http/server.go:1825
2017/10/20 15:15:59 [C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:2197
