### ISSUE TITLE
Caching entire response

### ISSUE THREAD

**Issue by harikt** [beego/beego#2736]
Hi, 

I was trying to cache the entire response. Before I talk more on it, let me provide more details.

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

```
├── Beego     : 1.8.0
├── GoVersion : go1.8.1
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /projects/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Thursday, 22 Jun 2017
```

2. What operating system and processor architecture are you using (`go env`)?

```
GOARCH="amd64"
GOBIN="/projects/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build715877389=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```
3. What did you do?

From the docs https://beego.me/docs/mvc/ , I think there are a few ways to cache the content. Write to ResponseWriter . That's it.

Problem is how to get the contents we need to be written to cache. Below is my current implementation.

1. Reading from cache via `BeforeRouter` filter.

The hash is calculated from the uri and it tries to get the cache associated with the request and if so write to [ctx.Output.Body(p)](https://github.com/astaxie/beego/blob/cab8458c1c4a5a3b4bf5192922be620e6dede15b/context/output.go#L62) which internally writes back to [ResponseWriter](https://github.com/astaxie/beego/blob/cab8458c1c4a5a3b4bf5192922be620e6dede15b/context/context.go#L55). So far so good.

```
var IfCached = func(ctx *context.Context) {
    bm, err := cache.NewCache("file", `{"CachePath":"./cache","FileSuffix":".cache","DirectoryLevel":2,"EmbedExpiry":120}`)
    if err == nil && ctx.Request.Method == "GET" {
        uri := ctx.Request.RequestURI
        crc32q := crc32.MakeTable(0xD5828281)
        key := fmt.Sprintf("%x", crc32.Checksum([]byte(uri), crc32q))
        val := bm.Get(key)
        if val != nil {
            p := val.([]byte)
            ctx.Output.Body(p)
        }
    }
}
beego.InsertFilter("/*", beego.BeforeRouter, IfCached)
```

2. Writing to cache. 

The problem here is there is no way to get the rendered content from `ResponseWriter` . Currently what I am doing is render again via `RenderBytes()` again. Can we have a `BodyContent`  field inside [BeegoOutput](https://github.com/astaxie/beego/blob/cab8458c1c4a5a3b4bf5192922be620e6dede15b/context/output.go#L36
) ?

```
func (this *BaseController) Finish() {
	if this.Ctx.Request.Method == "GET" {
		bm, err := cache.NewCache("file", `{"CachePath":"./cache","FileSuffix":".cache","DirectoryLevel":2,"EmbedExpiry":120}`)
		uri := this.Ctx.Request.RequestURI
		if err == nil {
			crc32q := crc32.MakeTable(0xD5828281)
			key := fmt.Sprintf("%x", crc32.Checksum([]byte(uri), crc32q))
			value := bm.Get(key)
                        var content string
			if value == nil {
				rb, err1 := this.RenderBytes()
				if err1 == nil {
					content = string(rb)
				}
			}

			if content != "" {
				bm.Put(key, content, 5000)
			}
		}
	}
}
```

So that we don't need to call `RenderBytes()` again.

4. What did you expect to see?

A way to get back the rendered contents.

5. What did you see instead?

No way to get the rendered content.

Consider this as a Featured request. If you guys think, we can add a field `BodyContent` to output I am happy to send a PR. I am new to go and beego so not sure if there is a better way for the same.

**Comment by harikt** [comment]
I am not sure why do you want to reset the Statuscode once it is set to ResponseWriter ? https://github.com/astaxie/beego/blob/cab8458c1c4a5a3b4bf5192922be620e6dede15b/context/output.go#L78 .

**Comment by TrAnn3l** [comment]
I think the problem is that you create a new cache everytime. Try to create it as global object.

For me, my cache is working like this:

```
var Cache cache.Cache

func init() {
	Cache, _ = cache.NewCache("memory", `{"interval":60}`)
}

func (this *MainController) Get() {
	if Cache.IsExist("index") {
		this.Data = Cache.Get("index").(map[interface{}]interface{})
		this.TplName = "index.tpl"
		return
	}

       //Doing the normal stuff like putting thing in this.Data[]

        this.TplName = "index.tpl"
	Cache.Put("index", this.Data, 5000)
}
```

**Comment by harikt** [comment]
Thank you @TrAnn3l . Thanks for providing your code. I was thinking of using the same rendered content vs rendering again. The problem is not with cache itself.
