### ISSUE TITLE
No way to format logs/log as JSON for ELK stack?

### ISSUE THREAD

**Issue by bamling** [beego/beego#2738]
Currently, there seems to be no way of configuring the log format for a beego application. I'd like to run a dockerized beego application, that utilizes JSON logging over stdout to send messages to our ELK stack.

I looked into the logs module but there seems to be no way of achieving what I desire. 
- is there a possible workaround? 
- is this (or a similar) feature on the road map?
- what are the thoughts of the community/contributors about this?

**Comment by fasilk008** [comment]
The solution provided only supports for access logs. Cant seem to log normal error logging with beego logs package in JSON format. 
Is there any other workaround or solution?
