### ISSUE TITLE
API Documentation of array schema

### ISSUE THREAD

**Issue by RajeshKumar1990** [beego/beego#2764]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.4

├── Beego     : 1.8.3
├── GoVersion : go1.8.3
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Friday, 14 Jul 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=C:\Projects\Go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

I m looking to create array of  objects like this in swagger using annotations
![swagger3](https://user-images.githubusercontent.com/22511293/28197499-e681a8dc-6889-11e7-9008-e9be2707bc39.JPG)

This one i manually created it without using anotations .
The swagger json looks like this 
```
"parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "the LeaveType",
                        "required": true,
                        "schema":{
                            "type": "array",
                                "items":
                                    { 
                                        "$ref":"#/definitions/structinfo.LeaveType"                               
                                    }    
                            }
                                
                        }
                ],
```
can some one tell me how to create this using annotations in beego api
I used something like this but its not working.
`// @Param body   body	array    structinfo.LeaveType  	true   "the LeaveType"`

Thanks

**Comment by gnanakeethan** [comment]
```
@Param body body []structinfo.LeaveType true "the LeaveType"
```

Can you change your comment like this?

**Comment by RajeshKumar1990** [comment]
I tried @gnanakeethan  but i m getting only the object not array of objects....
![swagger4](https://user-images.githubusercontent.com/22511293/28197970-07fe65f6-688d-11e7-93b4-c282db572010.JPG)

**Comment by gnanakeethan** [comment]
I think there is something on that. I am looking into the generator code. Wait a moment.

**Comment by gnanakeethan** [comment]
@astaxie This issue can be reproduced. There is no method to catch arrays on the swagger generator for params.
