### ISSUE TITLE
JSON type support in beego ORM

### ISSUE THREAD

**Issue by apremalal** [beego/beego#2769]
MySQL 5.7.8+ has introduced native json column type support.   I was experimenting with the following code. 

```
type MyStruct struct {
	ID      int64 `json:"id" orm:"pk"`
	Name 	string `json:"name"`
	Content map[string]interface{} `json:"content"`
}

func init() {
	orm.RegisterModel(new(MyStruct))
}
```
And it throws `unsupport field type &map[], may be miss setting tag` error.

Is there a way to insert and read mysql json data types using beego orm?

**Comment by theburn** [comment]
我看了beego对PG可以设置数据库层面的json/jsonb字段，但是似乎在MySQL中无法设置，但是现在5.7.8+ 以后的版本已经支持了，可否为MySQL也加上type(json)的支持？
https://github.com/astaxie/beego/blob/f16688817aa428d10361394015b40d096b680542/orm/db_mysql.go#L44
mysql的json字段现在可以用内置函数实现一些比较有意思的特性，比如把某个字段作为虚拟列，用于索引，个人觉的还是很有必要的

**Comment by boyaziqi** [comment]
我有如下代码，使用 `Values` 返回 json 时首字母不能小写，使用 `All` 替换则没这个问题。这个问题有比较好的解决方案吗？
环境：
- go: 1.12
- beego: 1.12
- os: macOS
```go
package controllers

import (
	"fmt"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	"quickstart/models"
)

type MainController struct {
	beego.Controller
}

func (c *MainController) Get() {
	o := orm.NewOrm()
	var maps []orm.Params
	var doctor = new(models.Doctor)
	num, err := o.QueryTable(doctor).Values(&maps, "id", "name", "gender", "introduce")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(num)
	c.Data["json"] = map[string]interface{}{"data": &maps}
	c.ServeJSON()
}
```
`models.Doctor` 定义如下：
```go
type Doctor struct {
	Id        int    `json:"id" orm:"pk"`
	Name      string `json:"name" orm:"size(50)"`
	Gender    string `json:"gender" orm:"size(2)"`
	Introduce string `json:"introduce" orm:"size(255)"`
}
```
