### ISSUE TITLE
Feature Request - generate table with blob type field

### ISSUE THREAD

**Issue by qingkongabc** [beego/beego#2772]
1. What version of Go and beego are you using (`bee version`)?
go:1.8.3 beego:1.8.3

2. What operating system and processor architecture are you using (`go env`)?
ubuntu16.04 amd64

I'd like to store session in Mysql. There is a field named session_data which type is blob. However, beego can't automatically create table with blob.Is there any solution?

**Comment by trainchou** [comment]
The owner of this issue changed the title twice and it looks like he really need this feature. Meanwhile, I think generating table with blob type field is really in need. Hope someone could work on this.
