### ISSUE TITLE
bee api生成的swagger.json文件报错

### ISSUE THREAD

**Issue by caiya** [beego/beego#2774]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

1.8.3
2. What operating system and processor architecture are you using (`go env`)?
windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by caiya** [comment]
如下定义的struct对象（Id_类型为bson.ObjectId，使用的是mgo库）
`// 地图配置对象
type MapConf struct {
	Id_       bson.ObjectId `bson:"_id" json:"_id"`
	Name      string        `json:"name" bson:"name" valid:"Required;MaxSize(15)"`
	Type      string        `json:"type" bson:"type" valid:"Required"`
	Service   string        `json:"service" bson:"service" valid:"Required"`
	Scope     string        `json:"scope" bson:"scope" valid:"Required"`
	Center    string        `json:"center" bson:"center" valid:"Required"`
	ZoomLevel string        `json:"zoomlevel" bson:"zoomlevel" valid:"Required"`
	IsStatic  bool          `json:"isstatic" bson:"isstatic" valid:"Required"`
}`
controller的注释是这么写的：
`// @Title get mapConf
// @Description 获取地图配置信息
// @Param	type query string false "地图类型（2D、2.5D、3D）"
// @Success 200 {object} models.MapConf
// @Failure 500 Internal Server Error
// @router / [get]`

然后bee api生成的swagger报错如下：

**Comment by caiya** [comment]
![111](https://user-images.githubusercontent.com/12036572/28397314-68b4e938-6d33-11e7-86ff-ac397ec50a33.png)

**Comment by xinwu-yang** [comment]
你换成swagger2 试一下～
