### ISSUE TITLE
Orm binary field - models.User.Password, unsupport field type , may be miss setting tag

### ISSUE THREAD

**Issue by mytc** [beego/beego#2776]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.8.3

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu

3. What did you do?
I am trying to use bcrypt to generate password, but it cannot insert the data into the database. It give me this error:

> field: models.User.Password, unsupport field type , may be miss setting tag

Here is my codes:

```

package models

import (
	"fmt"
	"github.com/astaxie/beego/orm"
	"golang.org/x/crypto/bcrypt"
	"time"
)

type User struct {
	Id        int
	Username  string `orm:"unique;size(100)"`
	Password  []byte
	Email     string    `orm:"unique"`
	Created   time.Time `orm:"auto_now_add;type(datetime)"`
	Updated   time.Time `orm:"auto_now;type(datetime)"`
	Acitvated time.Time `orm:"null"`
}

func init() {
	orm.RegisterModel(new(User))

}

func InitData() {
	fmt.Println("init data..")
	orm.Debug = true
	ormerr := orm.RunSyncdb("default", false, true)
	if ormerr != nil {
		fmt.Println(ormerr)
	}
	o := orm.NewOrm()
	o.Using("default")

	alluser := User{Id: 1}
	err := o.Read(&alluser)

	if err == orm.ErrNoRows {
		fmt.Println("No result found.")
	} else if err == orm.ErrMissPK {
		fmt.Println("No primary key found.")
	} else {
		user := new(User)
		user.Username = "aaa"

		bs, err := bcrypt.GenerateFromPassword([]byte("123456"), 11)

		if err != nil {
			fmt.Println("bcrypt error : ", err)
			return
		}
		user.Password = bs
		user.Email = "aa@aaa.com"

		o.Insert(user)
	}

}

```
I am using postgres btw.

Seem the struct field Password field can't be slice of byte. I can't find the solution of this. Do I need to convert the slice of binary to string in order to store it in database? It seem so redundant to do so.

**Comment by Rillian-Grant** [comment]
I am having the exact same issue.

**Comment by mohamadpk** [comment]
i don't know about PostgreSQL types. use this 
Password  []byte `orm:"type(blob)"`
