### ISSUE TITLE
beego run tips

### ISSUE THREAD

**Issue by lz1988** [beego/beego#2778]
1.When I start, the tips?
2017/07/21 23:00:57 INFO     ▶ 0001 Using 'xx' as 'appname'
2017/07/21 23:00:57 FATAL    ▶ 0002 Failed to create watcher: function not implemented

2.beego version:
├── Beego     : 1.9.0
├── GoVersion : go1.8.1
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 1
├── GOPATH    : /usr/local/go/project
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 21 Jul 2017

**Comment by astaxie** [comment]
maybe you need to reinstall the bee. From the error information show: it comes from `fsnotify.NewWatcher`.

**Comment by lz1988** [comment]
I reinstall it, still prompted

**Comment by astaxie** [comment]
No idea
