### ISSUE TITLE
interface{} fields produce an error in swagger docs

### ISSUE THREAD

**Issue by apremalal** [beego/beego#2783]
1. Bee version information

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.4

├── Beego     : 1.8.2
├── GoVersion : go1.8.3
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/ag/workspace
├── GOROOT    : /usr/local/Cellar/go/1.8.1/libexec
├── Compiler  : gc
└── Date      : Tuesday, 25 Jul 2017

2. Problem

I have a model definition as below.

type Log struct {
	ID          string    `json:"id" `
	Type        string    `json:"type"`
	Content    map[string]interface{}  `json:"content"`
	Created     int64     `json:"created"`
	Updated     int64     `json:"updated"`
}

When I try to include this as the response object
```
// @Success 200 {object}  controllers.LogsPaginatedResponse
```

It throws an error 

```
 WARN     ▶ 0001 Cannot find the object: 47095.0xc4204d8db0.false
```
It works without the interface{} field.  Is there a way to store generic fields in the swagger docs.?

**Comment by dodocat** [comment]
same issue here

**Comment by apremalal** [comment]
@astaxie  could this be solved with object types in swagger?

**Comment by marcelo-limori-globant** [comment]
Yes, this is highly problematic. 

A workaround is to alias the type (type newinterface = interface{} and then use newinterface on the struct), but then again, that's even more problematic. :)
