### ISSUE TITLE
您好多进程部署写日志，在日志切割时会丢日志

### ISSUE THREAD

**Issue by wangjianzhou** [beego/beego#2793]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
多个进程同时写一个日志文件？然后所有进程都进行logrotate吗？
