### ISSUE TITLE
日志文件夹内日志超过999个或1000个时程序就会报 Rotate: Cannot find free log number to rename

### ISSUE THREAD

**Issue by xdxiaodong** [beego/beego#2799]
日志文件夹内日志超过999个或1000个时程序就会报 Rotate: Cannot find free log number to rename

**Comment by arthur-xie** [comment]
不个没有实际意义，没有人在现实中会让一个进程保留1000个日志文件的。你出现这个问题，应该是日志中的maxlines或者maxsize设置的太小，要么就是日志级别太详细。往文件中写的日志，一般不要写DEBUG信息，DEBUG只用console就行了。

**Comment by xdxiaodong** [comment]
好的，明白了，非常感谢
