### ISSUE TITLE
Download static files failed

### ISSUE THREAD

**Issue by Oceankenny** [beego/beego#2807]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.9.0
├── GoVersion : go1.7
├── GOOS      : windows
├── GOARCH    : 386
├── NumCPU    : 2
├── GOPATH    : C:\workspace
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Friday, 4 Aug 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
I created a new web app via 'bee new ' and put several files under '/static' folder. Then I started the app and tried to download the file through IE and Chrome simultaneously, and saved it to different local paths.

But the sizes of downloaded two files were different and both less than the origin file. 

4. What did you expect to see?
Downloaded files are integrated.

5. What did you see instead?
Simultaneously downloading the same file, but got two interrupted files.

**Comment by Oceankenny** [comment]
Same issue exists on linux

├── Beego     : 1.9.0
├── GoVersion : go1.8.3
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 2
├── GOPATH    :
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Monday, 7 Aug 2017

**Comment by Oceankenny** [comment]
Seems downloading right files if running file server via "bee server ..." which sets up a fileServer. However, I wonder if such issue exists when downloading js/css files. @astaxie

**Comment by flycash** [comment]
It has been fixed
