### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by Tom-Kail** [beego/beego#2809]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

├── Beego     : 1.9.0
├── GoVersion : go1.8
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 1
├── GOPATH    : /home/go
├── GOROOT    : /go
├── Compiler  : gc
└── Date      : Monday, 7 Aug 2017

3. What did you do?
Enable graceful in conf/app.conf
```
Graceful = true
```

4、Error

Where I kill the process , I get info below
```
2017/08/07 22:42:07 5226 Received SIGINT.
2017/08/07 22:42:07 5226 [::]:9001 Listener closed.
2017/08/07 22:42:07 5226 Waiting for connections to finish...
2017/08/07 22:42:07.361 [C] [asm_amd64.s:2197] ListenAndServe:  accept tcp [::]:9001: use of closed network connection 5226
```

**Comment by Tom-Kail** [comment]
这个会有问题吗

**Comment by HYY-yu** [comment]
不会，这个是说当前使用的连接被关闭了。[详细解释](https://juejin.im/post/5aa61f74f265da237b21ba59)
