### ISSUE TITLE
bee new 生成的示例项目，reload.min.js里的websocket无法连上？

### ISSUE THREAD

**Issue by garming** [beego/beego#2818]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
├── Beego     : 1.9.0
├── GoVersion : go1.8.3
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

3. What did you do?
用 `bee new hello` 生成了一个示例项目，跑起来的时候，一直报websocket连接不上
```
WebSocket connection to 'ws://localhost:12450/reload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
`app.conf`配置如下：
```
appname = hello
httpport = 8080
runmode = dev
```

**Comment by pengliheng** [comment]
同求，我也是这样
> WebSocket connection to 'ws://localhost:12450/reload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
b @ reload.min.js:1
(anonymous) @ reload.min.js:1

**Comment by arfaWong** [comment]
同求，我也是这样

**Comment by kamilgregorczyk** [comment]
Hi, I'm having the same problem. Why does `bee new` create a js file which then doesn't have any websocket endpoint to connect to ?

**Comment by junngit** [comment]
思路：修改bee项目源码，重新编译！亲测修改bee.json或Beefile配置文件（"enable_reload": true）不生效，如果确实想启动websocket服务可以修改源代码run.go文件：
```
//if config.Conf.EnableReload {
if true {
	startReloadServer()
}
```
重新编译即可解决问题！
备注：bee版本为v1.10.0，仅供参考、不喜勿喷~

**Comment by krissss** [comment]
bee 版本 v1.10.0,Beego v1.11.1
测试修改 bee.json 有效，不需要修改源码
```json
{
    "enable_reload": true
}
```
