### ISSUE TITLE
下载静态文件，hash码会变

### ISSUE THREAD

**Issue by ha666** [beego/beego#2823]
系统：win7 sp1 x64
beego版本：1.9.0
360极速浏览器版本：8.7.0.306

使用beego，在static目录下放一个zip文件，直接访问网址下载这个zip文件，360极速浏览器下载下来的文件hash码错了，其它浏览器没有问题，后来查下来发现，360极速浏览器中的“使用下载加速模块”导致的。
上面的情况我判断是360极速浏览器的下载加速模块有问题，但是我用其它语言写个web服务器下载，却没有这个问题。

**Comment by astaxie** [comment]
你有对比360浏览器和其他浏览器请求的header不一样吗？

**Comment by ha666** [comment]
我用Fiddle看了，主要的差别在于，chrome浏览器只发起单线程下载，而360极速浏览器，发起了10个线程下载。

**Comment by ha666** [comment]
header确实有差别，不过差别不大。

**Comment by astaxie** [comment]
多线程下载的话发送的header应该有一个range之类的吧

**Comment by ha666** [comment]
刚才又仔细看了一遍，部分下载线程确实有Range头。

**Comment by astaxie** [comment]
你把这些header信息发出来，我才好模拟测试呢

**Comment by chenyu3050** [comment]
如何查看static目录下的zip文件的hash值？

**Comment by chenyu3050** [comment]
就是原哈希值？？？

**Comment by flycash** [comment]
要通过http的header来查看。如果你已经下载下来了，就只能通过再次计算。但是这并不能保证，计算的结果和下载过程中在header里面是一致的。

比较好的实践是，在下载之后立刻计算一个hash值并且和header里面的匹配以确保中间过程没有出错。
