### ISSUE TITLE
Static file and 404 status code

### ISSUE THREAD

**Issue by vadimi** [beego/beego#284]
Hi, when static file is not found beego does not set response code to 404, but 200 instead.

**Comment by shshxy98** [comment]
bee   :1.4.1
beego :1.6.0
Go    :go version go1.5rc1 linux/amd64
测试问题仍然存在
![image](https://cloud.githubusercontent.com/assets/10886204/12702756/686b36d4-c86c-11e5-8a5e-59a0d2f1d584.png)
