### ISSUE TITLE
How to using Parseform to parse relationship model

### ISSUE THREAD

**Issue by mytc** [beego/beego#2847]
1. What version of Go and beego are you using (`bee version`)?
GO 1.8.3, Beego 1.8.1

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu 64bit

I have a model struct that has relationship with other model, So upon submitting form how can I parse the form automatically without set the struct field manually.

For eg:
```
type Posts struct {
	Id        int         `form:"-"`
	Title     string      `form:"title"  valid:"Required"`
	Category  *Categories `orm:"rel(fk)" form:"category"`
	Content   string      `form:"content,textarea"`	
	Created   time.Time   `orm:"auto_now_add;type(date)"`
	Edited    time.Time   `orm:"auto_now;type(datetime)"`
	User      *Users      `orm:"rel(fk)"`
}
```

This `Posts` struct has `User` and `Category` fields which are from other model. 

So when I parse the form, the `Category` value (which is the category id) did not parse into the struct, and I cannot insert the struct to the database.  

As for the `User`, since it is not part of the form input, I can manually assign the struct by getting current user struct.  Do I need to do this to my Category as well? Any automatic method to do so?

**Comment by bogh** [comment]
:+1:
