### ISSUE TITLE
session 有时会丢失

### ISSUE THREAD

**Issue by yanllllk** [beego/beego#2851]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.90

2. What operating system and processor architecture are you using (`go env`)?
win 2008 x64
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
session 储存方式为 file,有时会丢失..session失效时间为 31536000
在两台机器上登陆同一个账号,有时会丢失,需要重新登陆.

4. What did you expect to see?

5. What did you see instead?

**Comment by minicase** [comment]
我也遇到同样问题，保存session为文件时候

**Comment by AlwaysKO** [comment]
我也遇到这个问题，存储引擎为memory的时候。
只要一编译，session就丢失
