### ISSUE TITLE
Beego的ORM中，mysql的字段都是大写怎么定义数据模型？

### ISSUE THREAD

**Issue by zmisgod** [beego/beego#2902]
环境
├── Beego     : 1.9.0
├── GoVersion : go1.9
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/zmisgod/go
├── GOROOT    : /usr/local/Cellar/go/1.9/libexec
├── Compiler  : gc
└── Date      : Sunday, 22 Oct 2017

请问大写的mysql字段怎么建数据模型？搜了好多，都没有搜到解决办法！

**Comment by wangchong666** [comment]
为字段设置 db 字段的名称
Name string `orm:"column(user_name)"`

**Comment by zmisgod** [comment]
@wangchong666 我已经使用了原生sql查询了.
刚过试了下您的方法，还是不行。mysql字段名为ID, post_status 
`type Posts struct{
Id int `orm:"column(ID)"`
PostStatus string
}`

**Comment by wangchong666** [comment]
@zmisgod  我这边试了没有问题哦
type Test struct {
	Id int `orm:"column(ID)"`
	Name string `orm:"column(user_name)"`
}


create table `test`
    -- --------------------------------------------------
    --  Table Structure for `ws/models.Test`
    -- --------------------------------------------------
    CREATE TABLE IF NOT EXISTS `test` (
        `ID` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
        `user_name` varchar(255) NOT NULL DEFAULT ''
    ) ENGINE=InnoDB;

**Comment by jpca999** [comment]
does it support mongo orm ?

**Comment by DennisMao** [comment]
@jpca999  Not support

**Comment by DennisMao** [comment]
@zmisgod  问题解决?

**Comment by zmisgod** [comment]
> @zmisgod 问题解决?

没有，我直接用原生sql的，可以完美避开这个问题

你可以试一下 @wangchong666 的方案，我没有试，不清楚可不可以:)

**Comment by DennisMao** [comment]
@zmisgod  好的。这个属性是没问题,你这边用到的话可以测试一下,如果不行的话回头贴上是哪个数据库 然后是啥版本,我再判断是否要修复。谢谢！
