### ISSUE TITLE
httplib中的params问题

### ISSUE THREAD

**Issue by rongyi** [beego/beego#2903]
type BeegoHTTPRequest struct {
	url     string
	req     *http.Request
	**params  map[string][]string**
	files   map[string]string
	setting BeegoHTTPSettings
	resp    *http.Response
	body    []byte
	dump    []byte
}

个人觉得这里的params可以用url.Values替代，像这种函数：
func (b *BeegoHTTPRequest) Param(key, value string) *BeegoHTTPRequest {
	if param, ok := b.params[key]; ok {
		b.params[key] = append(param, value)
	} else {
		b.params[key] = []string{value}
	}
	return b
}

和诸如这样的代码：

	if b.req.Method == "GET" && len(paramBody) > 0 {
		if strings.Contains(b.url, "?") {
			b.url += "&" + paramBody
		} else {
			b.url = b.url + "?" + paramBody
		}
		return
	}

完全可以用标准库的Encode函数，所以这里还有优化的空间，建议优化下，否则这些代码看起来太low了。

**Comment by DennisMao** [comment]
@rongyi  http包中的PostForm底层其实本质还是type Values map[string][]string,Add/Set/Del和Encode其实看一下实现并无太大差异。
