### ISSUE TITLE
something like Set parameter

### ISSUE THREAD

**Issue by vikram-rawat** [beego/beego#2913]
I learned web app through revel framework. They have a template function called set which defines a variable at the beginning of importing a template like.

`{{set . "something" "home"}}
{{set . "cssstyle" "css/style.css"}}
{{set . "homeactive" "active"}}
{{template "header.html" .}}

<div class="row">
    {{template "hometab/sidebar.html" .}}
    {{template "hometab/mainpanel.html" .}}
</div>

<div class="container-fluid">
  <div class="row">
    <div class="span6">
      {{template "flash.html" .}}
    </div>
  </div>
</div>

{{template "footer.html" .}}
`

here set defines the something variable from any of the templates imported to home. This is a very nice functionality is there anything similar in beego. This is very useful in designing the layout. an example is like say. I want to make sure that the current tab is active.  all I have to do is set the variable active in the current template rather than using a if statement. 

**This is very handy trust me. Beego should have this.**

I would love to know if you have it or if you have anything similar to it. Please do reply.

**Comment by vvelikodny** [comment]
@vikram-rawat 

Try

```
{{ $Something := "home"}}
```
