### ISSUE TITLE
Log files use by another process when rotating

### ISSUE THREAD

**Issue by t-walker-wei** [beego/beego#2924]
"GoVersion": "go1.8.1",
    "GOOS": "windows",
    "GOARCH": "amd64",
    "Compiler": "gc",
    "BeeVersion": "1.9.1",
    "BeegoVersion": "1.9.0"

Error:FileLogWriter("logs/unit-test.log"): Rotate: rename logs/unit-test.log logs/unit-test.2017-11-10.log: The process cannot access the file because it is being used by another process.

**Comment by arthur-xie** [comment]
Facing the same issue!!

**Comment by dictShuang** [comment]
Facing the same issue!!
