### ISSUE TITLE
go test -cover coverage: 0.0% of statements

### ISSUE THREAD

**Issue by imiskolee** [beego/beego#2933]
i generated a new api project,
and try go test into project/tests

outputs:
coverage: 0.0% of statements

how to coverage api code ?

**Comment by ybouzekri** [comment]
Hello, same question here, just tried it and 0.0% of statements.
Would be much appreciated to know have I can get the coverage

**Comment by imiskolee** [comment]
@ybouzekri beacuse use http server for test,so i try  make a tool:  https://github.com/imiskolee/beetest

**Comment by wjlight** [comment]
Hello, same question here，0.0% of statements.
have any solutions？

**Comment by imiskolee** [comment]
@wjlight  please try https://github.com/imiskolee/beetest.
