### ISSUE TITLE
token auth support ?

### ISSUE THREAD

**Issue by jpca999** [beego/beego#2936]
We want to use the framework to run it as a backend for our app. How can we use token based authentication with Beego ?

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by astaxie** [comment]
https://godoc.org/github.com/astaxie/beego/plugins/apiauth

**Comment by jpca999** [comment]
@astaxie    i see a  lot of places    f AppIDToAppSecret.    Does it refer to the facebook app id ?

I dont see anywhere how it will provide a user Token upon loggin in and similar stuff.

**Comment by niranjan92** [comment]
@astaxie any code example which shows how to use it?

**Comment by leopragi** [comment]
@niranjan92 @astaxie ...Have you found how to use apiauth? Please post it
