### ISSUE TITLE
html  \" &#34;  Htmlquote not found

### ISSUE THREAD

**Issue by hsw409328** [beego/beego#2956]
templatefunc.go

// Htmlquote returns quoted html string.
func Htmlquote(text string) string {
	//HTML编码为实体符号
	/*
	   Encodes `text` for raw use in HTML.
	       >>> htmlquote("<'&\\">")
	       '& lt;& #39;& amp;& quot;& gt;'
	*/

	text = strings.Replace(text, "&", "& amp;", -1) // Must be done first!
	text = strings.Replace(text, "<", "& lt;", -1)
	text = strings.Replace(text, ">", "& gt;", -1)
	text = strings.Replace(text, "'", "& #39;", -1)
	text = strings.Replace(text, "\"", "& quot;", -1)
	text = strings.Replace(text, "“", "& ldquo;", -1)
	text = strings.Replace(text, "”", "& rdquo;", -1)
	text = strings.Replace(text, " ", "& nbsp;", -1)

	return strings.TrimSpace(text)
}

funcs.go

// HTML escaping.
var (
	htmlQuot = []byte("& #34;") // shorter than "&quot;"
	htmlApos = []byte("& #39;") // shorter than "&apos;" and apos was not in HTML until HTML5
	htmlAmp  = []byte("& amp;")
	htmlLt   = []byte("& lt;")
	htmlGt   = []byte("& gt;")
	htmlNull = []byte("\uFFFD")
)
// HTMLEscape writes to w the escaped HTML equivalent of the plain text data b.
func HTMLEscape(w io.Writer, b []byte) {
	last := 0
	for i, c := range b {
		var html []byte
		switch c {
		case '\000':
			html = htmlNull
		case '"':
			html = htmlQuot
		case '\'':
			html = htmlApos
		case '&':
			html = htmlAmp
		case '<':
			html = htmlLt
		case '>':
			html = htmlGt
		default:
			continue
		}
		w.Write(b[last:i])
		w.Write(html)
		last = i + 1
	}
	w.Write(b[last:])
}

templatefunc.go Htmlquote Lose & #34; Escape

**Comment by sunnyregion** [comment]
"\""替换成 `"` 试试

**Comment by hsw409328** [comment]
先用template.HTMLEscape 转义，输出的时候用beego.Htmlquote ，发现img标签针对双引号的的一个问题。
现在已经用golang标准html.Escape html.UnEscape解决了。
