### ISSUE TITLE
Serving html page with JS templating library

### ISSUE THREAD

**Issue by ymg** [beego/beego#297]
Hello,

I've been trying to use my MainController to serve a html page without any rendering of the double curly braces (I'm using AngularJS templating library which uses the same notation as Beego).
So every time I try this I just end up with warnings from Beego trying to parse my views, and then when I request my controller I get panic message like the following one.

```
beego:can't find templatefile in the path:index.html

Request Method:    GET
Request URL:    /
RemoteAddr: 127.0.0.1:36759
Stack
/usr/local/go/src/pkg/runtime/panic.c 229
/home/ymg/gocode/src/github.com/astaxie/beego/controller.go 158
/home/ymg/gocode/src/github.com/astaxie/beego/controller.go 106
/usr/local/go/src/pkg/reflect/value.go 474
/usr/local/go/src/pkg/reflect/value.go 345
/home/ymg/gocode/src/github.com/astaxie/beego/router.go 707
/usr/local/go/src/pkg/net/http/server.go 1517
/usr/local/go/src/pkg/net/http/server.go 1096
/usr/local/go/src/pkg/runtime/proc.c 1223
beego 0.9.9 (beego framework)

golang version: go1.1.2
```

And the parsing warnings I get are usually are like this one:

```
[T] parse template err: index.html template: index.html:5: function "Blog" not defined
```

So the only solution that I managed to find (and it's pretty ugly and unjustified in my opinion) is to use a redirect from my MainController to my <code>index.html</code> . of course in this case I have defined my static content entry points and the html file can be reached directly.

Is there any way that I can get Beego templating engine to serve my html page without attempting to parse it?

**Comment by korykim** [comment]
conf->app.conf 里写入beego.TemplateLeft = "<<<"    beego.TemplateRight = ">>>" 对吗？

**Comment by zweite** [comment]
是的
