### ISSUE TITLE
嵌套路由不能生成API自动化文档

### ISSUE THREAD

**Issue by qifanrui** [beego/beego#2977]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego     : 1.9.0

2. What operating system and processor architecture are you using (`go env`)?
GoVersion : go1.9

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
ns := beego.NewNamespace("/api",
		beego.NSNamespace("/v1",
			beego.NSNamespace("/device",
				beego.NSInclude(
					&controllers.DeviceController{},
				),
			),
		),
		beego.NSNamespace("/v2",
			beego.NSNamespace("/device",
				beego.NSInclude(
					&controllers.DeviceControllerV2{},
				),
			),
		),
	)
beego.AddNamespace(ns)
```
4. What did you expect to see?
我期望能通过注释生成API自动化文档

5. What did you see instead?
"paths": null,

**Comment by gyf19** [comment]
ping? @astaxie

**Comment by cloudshen** [comment]
@gyf19 这问题解决了吗？

**Comment by gyf19** [comment]
@cloudshen  没有关注了
