### ISSUE TITLE
accept4: too many open files; retrying in 5ms

### ISSUE THREAD

**Issue by ha666** [beego/beego#2991]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.9.0

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GOPATH\libs;C:\GOPATH\ha666;C:\GOPATH\ha666web
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
我用beego和自带的logs模块，做了一个api服务，今天重启进程以后，出现大量报错：
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 5ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 10ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 20ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 40ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 5ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 5ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 5ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 5ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 10ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 20ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 40ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 80ms
2017/12/21 13:10:08 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 160ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 5ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 10ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 20ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 40ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 80ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 160ms
2017/12/21 13:10:09 [log.go:179] [HTTP] http: Accept error: accept tcp [::]:30004: accept4: too many open files; retrying in 320ms

在这种情况下，日志暴涨

4. What did you expect to see?
不希望写出这些日志

5. What did you see instead?

**Comment by hunterhug** [comment]
你的log包可能使用不当吧 你应该贴出你的代码, 而且这种问题应该不是框架问题.

试试ulimit可以调高.

**Comment by luzhuqun** [comment]
我也遇到这个问题，我是这样写的：
`import (
	"github.com/astaxie/beego/logs"
)

var (
	log *logs.BeeLogger
)

func Log() *logs.BeeLogger {
  	log := logs.NewLogger()
  	log.SetLogger(logs.AdapterMultiFile, `{"filename":"/tmp/wencai.log","separate":["emergency", "alert", "critical", "error", "warning", "notice", "info", "debug"]}`)
  	return log
}`
然后每次打印日志的时候 用 `log :=Log()   log.error()`.

**Comment by flycash** [comment]
不能一直创建 Log()，因为你的理解是正确的，log应该是单例模式，而不能一直用 NewLogger。
