### ISSUE TITLE
关于map并发的问题

### ISSUE THREAD

**Issue by icowan** [beego/beego#3002]
错误信息:`fatal error: concurrent map writes`

```go

go func() {
    c.Data["key"] = "world"
}()

c.Data["key"] = "hello"
```

可能会产生 并发冲突
 go  1.9.2 有一个 sync.Map 类型 可以解决这个问题

可以更新吗？

**Comment by ckahi** [comment]
可以~

**Comment by icowan** [comment]
现在用的上go 1.9.2 我是说，让框架调整一下。我就不修改框加源码了。@ckahi

**Comment by ShSacywn** [comment]
是你的使用方式有毒

**Comment by icowan** [comment]
@ShSacywn 协程处理 当一边在写，另一边在读的时候真会有问题，上面只是简单的例子，实际会比这更复杂些，还有就是上下文交互的时候。目前使用的方案是 `sync.Map` 解决了。

**Comment by chenhui225** [comment]
请问这个问题修复好了吗

**Comment by flycash** [comment]
貌似这是一个古老的问题。@chenhui225 你还碰到了这个问题？

**Comment by chenhui225** [comment]
是的，beego 1.9.2版本出现了你这个问题，不知道新版本有没有解决



---原始邮件---
发件人: "Ming Deng"<notifications@github.com&gt;
发送时间: 2020年7月7日(周二) 晚上8:05
收件人: "astaxie/beego"<beego@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"chenhui225"<7219059@qq.com&gt;;
主题: Re: [astaxie/beego] 关于map并发的问题 (#3002)




 
貌似这是一个古老的问题。@chenhui225 你还碰到了这个问题？

**Comment by flycash** [comment]
你更新到新版本试试？说实在的，我还不知道这个问题描述的是框架哪段代码。

**Comment by icowan** [comment]
@flycash 
```
// github.com/astaxie/beego/controller.go
type Controller struct {
	// context data
	Ctx  *context.Context
	Data map[interface{}]interface{}
}
```

建议提供一个 SetData() 的方法，通过SetData 将数据写入data，在SetData 进行map并发控制

**Comment by flycash** [comment]
我仔细考虑一下，我突然觉得，一个set data也未能解决问题

**Comment by flycash** [comment]
我想到，这个问题难点就在于，Data是一个共有字段，已经暴露出去了。即便我们增加get, set方法也用处不大。因为用户会直接使用map而忘记加锁。而如果我们修改为使用sync.Map，则这是一个不兼容的修改。
目前我的建议是，用户在使用的时候自己加锁作为一个临时解决方案。至于更好的方案，坦白说，我还没想到。
