### ISSUE TITLE
Postgres function in ORM

### ISSUE THREAD

**Issue by RevProg** [beego/beego#3010]
1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.7.2
├── GoVersion : go1.9.2
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Projects\Go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Thursday, 28 Dec 2017

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Projects\Go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

3. What did you do?
I need to use postgres function in query filtering(I use QuerySetter Filter method), is this possible? I didn`t find the way to do it. 

4. What did you expect to see?
Filter function to generate condition like this:
string_to_array(value,',') <@ string_to_array('columnName',',')
Where string_to_array is a postgres function.

5. What did you see instead?
Handler crashed with error unknown field/column name `string_to_array(columnName)`

**Comment by Movebytes** [comment]
Are there any updates concerning this issue?
