### ISSUE TITLE
m2m 查询的中间模型问题

### ISSUE THREAD

**Issue by ali322** [beego/beego#302]
案例:

```
type Post struct{
    Id  uint64
    Name string
    ...
    Tags []*Tag 'orm:"rel(m2m);rel_through(myApp/models.RelPostTag)"'
}

type Tag struct {
    Id  uint64
    Name string
    ....
    Posts []*Post 'orm:"reverse(many)"'
}
```

中间模型定义

```
type RelPostTag struct {
    Id  uint64
    PostsId uint64
    TagsId  uint64
}

func (RelPostTag)TableName(){
    return "prefix_rel_post_tag"
}
```

在Controllers中使用查询post.Tags 错误提示
    `wrong rel_through value 'myApp/models.RelPostTag' cannot find table`

原因:中间模型的表定义不能包含前缀 "prefix_"

分析models_boot.go 里面的代码 `modelCache.get(tn)` 返回值为 `nil`
打印 `modelCache.all()`得到相应的 `table` 字段为 `prefix_rel_post_tag`
而在 models_boot.go的 `bootStrap()` 里面110行处的 变量 tn的值为 `rel_post_tag`
故 110行 `modelCache.get(tn)` 返回值为 `nil`

解决:表改名为 rel_post_tag,去掉自定义表名的函数

希望能修复下,支持中间模型自定义表名前缀

**Comment by linkerlin** [comment]
这里也反映出一文档的问题, rel_through(myApp/models.RelPostTag)
myApp后面的分隔符是 /
文档中是 `[eg: app.models.PostTagRel](https://beego.me/docs/mvc/model/models.md)`

**Comment by netscrt** [comment]
这个模块路径尝试用好几种方法都提示找不到。
