### ISSUE TITLE
mac下交叉编译问题

### ISSUE THREAD

**Issue by liup1211** [beego/beego#3025]
go 1.9.2
sublime Text3
mac下开发
要部署到centos下
该如何交叉编译呢？CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build这个命令吗？

**Comment by linux-mac** [comment]
其实只要 export GOOS=linux 即可编译出linux版的二进制文件

**Comment by beshrek** [comment]
bee pack -be GOOS=linux
