### ISSUE TITLE
ManyToMany relation with custom table names generates panic

### ISSUE THREAD

**Issue by antony66** [beego/beego#3034]
1. What version of Go and beego are you using (`bee version`)?
2. What operating system and processor architecture are you using (`go env`)?

```
├── Beego     : 1.9.2
├── GoVersion : go1.9.2
├── GOOS      : darwin
```
But the same applies to linux as well.

3. What did you do?

There's an article about [querying post and tags with m2m relation in the documentation](https://beego.me/docs/mvc/model/query.md#post-and-tag-are-manytomany-relation). This example works well if one uses autogenerated table names for models. However, if table names were redefined with `TableName()` methods of corresponding structs, such call:

    num, err := dORM.QueryTable("post").Filter("Tags__Tag__Name", "golang").All(&posts)

generates panic:

    panic: unknown field/column name `Tags__Tag__Name`

Here's the complete example of test program:

```
package main

import (
	"log"

	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

type User struct {
	Id    int
	Name  string
	Posts []*Post `orm:"reverse(many)"`
}

func (u *User) TableName() string {
	return "users"
}

type Post struct {
	Id    int
	Title string
	User  *User  `orm:"rel(fk)"`
	Tags  []*Tag `orm:"rel(m2m);rel_table(mt)"`
}

func (p *Post) TableName() string {
	return "posts"
}

type Tag struct {
	Id    int
	Name  string
	Posts []*Post `orm:"reverse(many)"`
}

func (t *Tag) TableName() string {
	return "tags"
}

func main() {
	orm.RegisterDriver("mysql", orm.DRMySQL)
	if err := orm.RegisterDataBase("default", "mysql", "root:@tcp(127.0.0.1:3306)/m2m?charset=utf8", 0, 50); err != nil {
		log.Fatalf("Error registering database: %s", err)
	}
	orm.Debug = true
	orm.RegisterModel(new(User), new(Post), new(Tag))
	if err := orm.RunSyncdb("default", true, true); err != nil {
		log.Fatal(err)
	}
	user := &User{Name: "me"}
	post := &Post{Title: "my post"}
	tag1 := &Tag{Name: "tag1"}
	tag2 := &Tag{Name: "tag2"}
	tag3 := &Tag{Name: "tag3"}
	o := orm.NewOrm()
	if _, err := o.Insert(user); err != nil {
		log.Fatal(err)
	}
	post.User = user
	if _, err := o.Insert(post); err != nil {
		log.Fatal(err)
	}
	if _, err := o.Insert(tag1); err != nil {
		log.Fatal(err)
	}
	if _, err := o.Insert(tag2); err != nil {
		log.Fatal(err)
	}
	if _, err := o.Insert(tag3); err != nil {
		log.Fatal(err)
	}
	m2m := o.QueryM2M(post, "Tags")
	if _, err := m2m.Add(tag1); err != nil {
		log.Fatal(err)
	}
	if _, err := m2m.Add(tag3); err != nil {
		log.Fatal(err)
	}
	var posts []*Post
	num, err := o.QueryTable(new(Post)).Filter("Tags__Tag__Name", "tag3").RelatedSel().All(&posts)
	log.Println(num, err)
}
```

However, if this portion of code is commented out:

```
func (t *Tag) TableName() string {
	return "tags"
}
```

everything works as expected. If one wants to get rid of panic, `Tags__Tag__Name` needs to be replaced with `Tags__tags__Name` which is definitely a bug.

**Comment by wubin1989** [comment]
I encounter the same problem. Thank you for your solution.

**Comment by Rechardone** [comment]
there is another problem , i change tags to mgr_tag.
`	num, err := o.QueryTable(new(Post)).Filter("Tags__mgr_tag__Name", "tag3").RelatedSel().All(&posts)
`
it dose not work.
