### ISSUE TITLE
panic: time: missing Location in call to Time.In

### ISSUE THREAD

**Issue by TaoMonkey** [beego/beego#3038]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
├── Beego     : 1.9.2

2. What operating system and processor architecture are you using (`go env`)?
set GOHOSTOS=windows
set GOOS=windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I use beego/orm to update pg database,but there is an error 

code example

	type dataTest struct {
		Id   	int    		`pk:"auto"`
		Data    time.Time 	`orm:"auto_now;type(timestamp);null"`
	}
	local, _ := time.LoadLocation("UTC")
	test_time, err := time.ParseInLocation("2006-01-02 15:04:05", "1111-01-25 14:27:07", local)

	temp := new(dataTest)
	temp.Id = 1
	temp.Data = test_time
	o.Update(temp)
error:
        panic: time: missing Location in call to Time.In

4. What did you expect to see?
       update date successfully.

5. What did you see instead?
      panic: time: missing Location in call to Time.In

Hope for your reply!

**Comment by icowan** [comment]
@TaoMonkey 
DB is Mysql? 

mysql: 
```go
type dataTest struct {
	Id   	int    		`pk:"auto"`
	Data    time.Time 	`orm:"auto_now;type(datetime);null"`
}

// init register database and connection.
orm.RegisterDataBase("default", "mysql", "user:password@tcp(host:3306)/dbname?charset=utf8&loc=Asia%2FShanghai")
```

**Comment by TaoMonkey** [comment]
@icowan 
DB is PG.I have solved this problem through adding the following code.

	local, _ := time.LoadLocation("UTC")
	orm.SetDataBaseTZ(alias,local)

Thanks for your reply.
