### ISSUE TITLE
commentsRouter_controllers.go changes will auto gone!

### ISSUE THREAD

**Issue by chenyangguang** [beego/beego#3045]
Please answer these questions before submitting your issue. Thanks!

1. 
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1

├── Beego     : 1.9.2
├── GoVersion : go1.8.3
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/v/gopath
├── GOROOT    : /home/v/Downloads/go
├── Compiler  : gc
└── Date      : Sunday, 28 Jan 2018

2. 
(1) first, I use bee cli tool to create a restful api.
(2) second, mantual create a model in models/country.go, a controller in models/country.go.
(3) then,   add  country namespace  to router.go

`
		beego.NSNamespace("/country",
			beego.NSInclude(
				&controllers.CountryController{},
			),
		),
`
(4)
and add 

`	beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"] = append(beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"],
		beego.ControllerComments{
			Method:           "GetAll",
			Router:           `/get_all`,
			AllowHTTPMethods: []string{"get"},
			MethodParams:     param.Make(),
			Params:           nil})

	beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"] = append(beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"],
		beego.ControllerComments{
			Method:           "Get",
			Router:           `/:id`,
			AllowHTTPMethods: []string{"get"},
			MethodParams:     param.Make(),
			Params:           nil})

	beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"] = append(beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"],
		beego.ControllerComments{
			Method:           "Put",
			Router:           `/:id`,
			AllowHTTPMethods: []string{"put"},
			MethodParams:     param.Make(),
			Params:           nil})

	beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"] = append(beego.GlobalControllerRouter["github.com/chenyangguang/go-country/controllers:CountryController"],
		beego.ControllerComments{
			Method:           "Delete",
			Router:           `/:id`,
			AllowHTTPMethods: []string{"delete"},
			MethodParams:     param.Make(),
			Params:           nil})
}
`  
to the commensRouter_Controllers.go file.
(5) First time i run 

`bee run `

and send a request like 'http://127.0.0.1:8080/api/country/get?id=1'
the response works well, 
but the second time i flash the request , the step (4) file change had gone by itself! And the response to "http://127.0.0.1:8080/api/country/get?id=1" take out to 404 status. 

why?

**Comment by yimiaodaren** [comment]
+1
