### ISSUE TITLE
setting maximum life time for a session

### ISSUE THREAD

**Issue by shanmugapriyav** [beego/beego#305]
I have set up the session. I have to modify the session age to 30 minutes.
I tried changing the sessiongcmaxlifetime in config file. Even then the beegosessionid cookies life time remains to be 1 hour. what could be probable issues

**Comment by u007** [comment]
as of latest beego, its inside:
beego.BConfig.WebConfig.Session.SessionProvider = file
beego.BConfig.WebConfig.Session.SessionProviderConfig = ./tmp/sessions
beego.BConfig.WebConfig.Session.SessionCookieLifeTime = 60 * 60 * 24 * 365//1year
beego.BConfig.WebConfig.Session.SessionGCMaxLifetime = 60 * 60 * 24 * 365//90days

can be set in conf/app.conf
example:
sessionon = true
SessionProvider = file
SessionProviderConfig = ./tmp/sessions
SessionCookieLifeTime = 31536000
SessionGCMaxLifetime = 31536000

can someone update the doc?
thanks
