### ISSUE TITLE
utils.GetGOPATHs在go1.10中在没设置GOPATH的情况下将不会工作

### ISSUE THREAD

**Issue by free1139** [beego/beego#3050]
https://github.com/astaxie/beego/blob/master/utils/utils.go

// GetGOPATHs returns all paths in GOPATH variable.
func GetGOPATHs() []string {
	gopath := os.Getenv("GOPATH")
	if gopath == "" && strings.Compare(runtime.Version(), "go1.8") >= 0 {
		gopath = defaultGOPATH()
	}
	return filepath.SplitList(gopath)
}

// 如果系统变量没设定GOPATH，这个判断在go1.10中将出现问题。
strings.Compare(runtime.Version(), "go1.8") >= 0

**Comment by h3chanchao** [comment]
你好，想请问一下，这个issue是一个问题，还是beego就是这样设计的呢？个人感觉应该是当go的版本大于1.8时，可以不用设置GOPATH，但是代码中strings.Compare(runtime.Version(), "go1.8")，go1.10是小于go1.8，go1.11，go1.12等等也会有这样的问题。

**Comment by free1139** [comment]
@h3chanchao 这个是一个问题，不知道现在改了没有。在刚出go1.10时我就遇到了，只是我不怎么使用beego，后面就没有深入了。

**Comment by h3chanchao** [comment]
@free1139 非常感谢，看了一下最新的源码1.11，还没有修改。因为我们需要使用beego，准备自己修改一下源码，否则就无法升级go的版本了。

**Comment by guhan121** [comment]
@free1139 这个问题已经修了，你可以关闭issue了
