### ISSUE TITLE
Enum type support in swagger

### ISSUE THREAD

**Issue by apremalal** [beego/beego#3077]
I tried to use enum types with swagger docs using a struct definition like below.

```
type TokenRequest struct {
	Username  string `json:"username"  required:"true"`
	GrantType string `json:"grantType" enum:"['client_credentials','authorization_code']" required:"true"`
}
```
However this didn't generate the enum tags in the yaml/json files

I can see  few changes for this in the latest release https://github.com/astaxie/beego/commit/bf5c5626ab429e66d88602e1ab1ab5fbf4629a01

Can someone provide details on how to use this feature?

**Comment by vk496** [comment]
Any solution?
