### ISSUE TITLE
When using ORM in goroutine context, under certain conditions QueryTable.One() returns no row found

### ISSUE THREAD

**Issue by zhujiaqi** [beego/beego#3086]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.9.2 bee1.9.1 
beego:
"checksumSHA1": "g+4AgCjxvotVLox53tnXxjXuBnQ=",
"path": "github.com/astaxie/beego",
"revision": "3162da131da68f38e85765781c9d1cc419963e67",
"revisionTime": "2017-09-08T22:29:59Z"

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build205600924=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I have a http webserver

Assume there are two request A & B, which belongs to the same user.
when A is called, multiple data D1s are created and are inserted into MySQL(Percona 5.7), using ORM's preparedInsert. then the ids are assigned to D2 which is insert right after insertion of D1 returned. For all insertions a new orm object is created by calling newOrm.
In a split second, B is called on the same user. It looks for D2 using ORM's QueryTable and found lucky, the row is there. It gets the ids of D1s. For each D1's id it fires up a goroutine to retrieve D1. Again in each goroutine a new orm object is created.
In the goroutines there are no race conditions and crashes. Mostly the program works, however when it goes online in some of the goroutines the orm will throw no row found error, and the program crashes. 

I tried to fix this by manually commit, but the problem won't go away. As soon as I replaced the goroutines with a for loop, the program can now run without without any issue.

..but i want to use goroutines, and a for loop is none of concurrency, and too slow. 

I want to know the root cause of this problem and I hope there will be a solution for fixing it.

Many Thanks!

4. What did you expect to see?

5. What did you see instead?

**Comment by asu126** [comment]
is ok, i use it
```
func FindUserBySshKeyId(key_id int) (user *User) {
	o := orm.NewOrm()
	user = &User{}
	err := o.QueryTable("users").Filter("Key__Id", 100).Limit(1).One(user)

	if user.Id == 0 || err != nil {
		return nil
	} else {
		return user
	}
}
```
