### ISSUE TITLE
Http2 with beego

### ISSUE THREAD

**Issue by brainplusplus** [beego/beego#3113]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.9.10

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/brainplusplus/Project/nbs/dana/middleware"
GORACE=""
GOROOT="/usr/local/go/1.9.1"
GOTOOLDIR="/usr/local/go/1.9.1/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/s2/l6p06yn54h7d8vbddj27xz4m0000gn/T/go-build112677850=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

 i want to configure http2 with beego, but i dont know how to do it

4. What did you expect to see?
http2 with beego

5. What did you see instead?

--------
how to configure beego to work with http2

**Comment by pathbox** [comment]
mark

**Comment by apremalal** [comment]
@astaxie Golang doesn't provide HTTP2 support for none TLS connections. We need to explicitly configure it https://github.com/golang/go/issues/14141. This is useful for many users who do the SSL termination at the load balancer.
