### ISSUE TITLE
how to use session value in custom template function?

### ISSUE THREAD

**Issue by kuzicala** [beego/beego#3116]
After read the document, there are to ways to use session value 
1. In Controller can use GetSession

2. contenx  ctx.Input.Session

how to use Session in custom template function?

**Comment by yesEric** [comment]
I have the same issues, do you have any solution?

**Comment by yesEric** [comment]
I have the solution. That is:
1. create a base clas for your controller
2. implement the prepare() method and set the session value to input.Data
3. after then you can read the data value

have fun.
