### ISSUE TITLE
how to parse requestUri to map or struct ？

### ISSUE THREAD

**Issue by netstat1grep80** [beego/beego#3117]
for example " http://xxx.com/?a=1&b=2&c=3&d=4&.....&n=N"  ,I want to parse it to map like parse_str in php 

$str = "first=value&arr[]=foo+bar&arr[]=baz";
parse_str($str, $output);
echo $output['first'];  // value
echo $output['arr'][0]; // foo bar
echo $output['arr'][1]; // baz

because of I'm not confirm the length of parameters , so I can't use parse form to struct method in context . 

Use split result of ctx.request.requestUri by '&'  that only i can do . have any better method ? thx!

**Comment by NSObjects** [comment]
beego暂时没这个功能吧， 我想你用这个会更开心，

```
https://echo.labstack.com/guide/request
```
