### ISSUE TITLE
关于GET POST ...限定的问题

### ISSUE THREAD

**Issue by peggypig** [beego/beego#3121]
假设
beego.Router("/user",&controllers.RegisterController{},"post:Register")

请求：
http://localhost:8080/user   GET

为什么返回的是404而不是405？按照Http状态码规范来看，应该返回的是405.
如果返回404，对检错会造成迷惑啊

**Comment by shihp** [comment]
我今天刚好做了一个测试,对同一个 route
`beego.Get("/hello",func(ctx *context.Context){
		ctx.Output.Body([]byte("hello world get"))
})

beego.Post("/hello",func(ctx *context.Context){
		ctx.Output.Body([]byte("hello world post"))
})`

这两个可以同时存在,且正常访问.不知道标准的设计原则是什么.但是如果上述路由可以设置的话,你这个返回404应该没毛病.

**Comment by shihp** [comment]
我今天刚好做了一个测试,对同一个 route
```
beego.Get("/hello",func(ctx *context.Context){
ctx.Output.Body([]byte("hello world get"))
})

beego.Post("/hello",func(ctx *context.Context){
ctx.Output.Body([]byte("hello world post"))
})
```

这两个可以同时存在,且正常访问.不知道标准的设计原则是什么.但是如果上述路由可以设置的话,你这个返回404应该没毛病.

**Comment by ZJHFYQ** [comment]
@shihp  我觉得我就这个问题换一个表述，可能更容易理解一点，对于同一个路由: /hello ，不管限定是get /hello 或者post /hello或者其他的方法访问，首先因为存在这个路由/hello ，所以404就显得不科学了，但是由于限定了method ，所以用其他method的时候，405（Method not allowed） 更为科学

**Comment by lovelock** [comment]
我是之前关注的beego, 自己没用过. 

在PHP的Slim框架中这种情况就是返回405的. 

如果按Restful的思想来理解, 一条路由就是对"一个资源"(对应路由中的path或者叫pattern)的"访问方式"(对应路由的Method). 那么, 如果已经存在一条路由, 也就表示对应的资源类型是存在的, 而该路由对应的方法也就是能对外提供的访问方式, 如果用目前不支持的方式来访问该资源, 应该返回的结果是"405 Method Not Allowed"而不是"404 Not Found".

那么404适用于什么状况呢? 一种是访问用的path和method都不存在, 也就表明不存在这种类型的资源. 或者path是有占位符的,`/path/to/resource/{resource_id} GET`, 这时如果访问对应的`resource_id`不存在, 才应该报404.
