### ISSUE TITLE
如何在Prepare终止执行直接输出？

### ISSUE THREAD

**Issue by wearecs** [beego/beego#313]
比如自动路由访问App/All
在prepare在
ServerJson（）
return
之后，还是会执行All的方法啊！不能在prepare就结束流程么？
难道还要在每个业务接口的方法前检查一下c.Data["json"],非空就return？

**Comment by ikenchina** [comment]
为什么 controller.Abort("400")
如果没有定义模板，则会返回200,这是什么逻辑？
这让人吐槽到不行。

**Comment by JessonChan** [comment]
@ikenchina https://github.com/astaxie/beego/pull/1805 this bug has been fixed
