### ISSUE TITLE
使用bee api创建数据库自动化是出现的问题

### ISSUE THREAD

**Issue by Men-Z** [beego/beego#3136]
E:\2018\GoDev\src>bee generate appcode -driver="mysql" -conn="root:root@tcp(127.
0.0.1:3306)/test" -level=3
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2018/04/26 10:08:54 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2018/04/26 10:08:54 INFO     ▶ 0002 Using 'root:root@tcp(127.0.0.1:3306)/test' a
s 'SQLConn'
2018/04/26 10:08:54 INFO     ▶ 0003 Using '' as 'Tables'
2018/04/26 10:08:54 INFO     ▶ 0004 Using '3' as 'Level'
2018/04/26 10:08:54 INFO     ▶ 0005 Analyzing database tables...
2018/04/26 10:08:54 FATAL    ▶ 0006 Could not show tables: The authentication pl
ugin is not supported.

我在使用时一直报错，在指定了tables以后依然报错，如下：

E:\2018\GoDev\src>bee api appcode -tables="test1" -conn="root:root@tcp(127.0.0.1
:3306)/test"
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2018/04/26 10:19:22 INFO     ▶ 0001 Creating API...
        create   E:\2018\GoDev\src\appcode
        create   E:\2018\GoDev\src\appcode\conf
        create   E:\2018\GoDev\src\appcode\controllers
        create   E:\2018\GoDev\src\appcode\tests
        create   E:\2018\GoDev\src\appcode\conf\app.conf
        create   E:\2018\GoDev\src\appcode\main.go
2018/04/26 10:19:22 INFO     ▶ 0002 Using 'mysql' as 'driver'
2018/04/26 10:19:22 INFO     ▶ 0003 Using 'root:root@tcp(127.0.0.1:3306)/test' a
s 'conn'
2018/04/26 10:19:22 INFO     ▶ 0004 Using 'test1' as 'tables'
2018/04/26 10:19:22 INFO     ▶ 0005 Analyzing database tables...
2018/04/26 10:19:22 FATAL    ▶ 0006 Could not query INFORMATION_SCHEMA for PK/UK
/FK information

我看大家在用的时候，直接使用 bee api -conn “xxxxx” 就能用了呀，请大神们帮我找找原因？

**Comment by Men-Z** [comment]
E:\2018\GoDev\src>bee api appcode -conn="root:root@tcp(127.0.0.1:3306)/test"
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2018/04/26 10:37:33 INFO     ▶ 0001 Creating API...
        create   E:\2018\GoDev\src\appcode
        create   E:\2018\GoDev\src\appcode\conf
        create   E:\2018\GoDev\src\appcode\controllers
        create   E:\2018\GoDev\src\appcode\tests
        create   E:\2018\GoDev\src\appcode\conf\app.conf
        create   E:\2018\GoDev\src\appcode\main.go
2018/04/26 10:37:33 INFO     ▶ 0002 Using 'mysql' as 'driver'
2018/04/26 10:37:33 INFO     ▶ 0003 Using 'root:root@tcp(127.0.0.1:3306)/test' a
s 'conn'
2018/04/26 10:37:33 INFO     ▶ 0004 Using '' as 'tables'
2018/04/26 10:37:33 INFO     ▶ 0005 Analyzing database tables...
2018/04/26 10:37:33 FATAL    ▶ 0006 Could not show tables: The authentication pl
ugin is not supported.
用这个方法也是一样的，是我的数据库的问题吗？可我用命令行和navicat都能够正常访问的

**Comment by Men-Z** [comment]
E:\2018\GoDev\src>bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1

├── Beego     : 1.9.2
├── GoVersion : go1.10
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : E:\2018\GoDev
├── GOROOT    : D:\Go\
├── Compiler  : gc
└── Date      : Thursday, 26 Apr 2018

**Comment by Men-Z** [comment]
不好意思大神，没有按照模板发布，实在是问题着急，给忘了

**Comment by uighurbabbage** [comment]
@Men-Z  首先 我是没使用过windows ，也没遇到过此类问题 所以这个问题没法解
但是我为你百度 得到了  这个信息
[别人的问题描述](https://stackoverflow.com/questions/49974372/go-mysql-authentication-plugin-not-supported-while-connecting-from-go-app-conta)

貌似是数据库版本有关。 建议你换不同版本数据库试试。 你先抛开beego  找个脚本去连接试试先
然后别的都行 beego 不行了才来这里折腾。
预测 第一根数据库版本有关  第二 有可能你对应数据库版本go的mysql驱动处理有缺陷（我觉得概率几乎很低）
第三 beego 可能没考虑你的版本。
如果是你大家都使用的版本 而且都正常就这块不行 那以别的方式先做了 然后提新的issue出来吧

最后 人生苦短 早点放弃使用windows吧  哈哈  祝你好运

**Comment by Men-Z** [comment]
@uighurbabbage 首先多谢大神指导！
1. 我原本就是linux的，用的中标麒麟，然后数据库装在windows上了mysql 服务器版8.0，因为麒麟那个弄mysql老是卸载不干净。
2. 先是问题出现在linux，结果跟现在一样，我就想是不是我linux版本出问题了，我就在windows上也搞了一套beego，结果问题还是一样
3.我觉得你说三种可能的问题是这样的
   a）这个最有可能，是不是我mysql版本太新了
   b）我分别用python、go语言的mysql连接写了demo，都是能够成功的，所以我觉得可能不是
   c）第三个也有可能，跟第一个有点像

我这个说事情老是分一二三，嗯哪，我卸载数据库试试吧，windows我已经尽量在抛弃了[捂脸]，我再搞搞数据库去，估计beego我也不知道咋改了，哈哈哈

**Comment by uighurbabbage** [comment]
@Men-Z 
你吧你的那个错误提示贴百度 或者必应 应该得到相关消息  我刚才看到的多部分都提了是mysql版本
其中一个是 最新版统统出现的问题，然后Mysql 官网里也有这个Bug的文章


https://bugs.mysql.com/bug.php?id=89382

不知道你是何种需求必须用最新版 但是我不觉得这是好主意 哈哈
我们还在5.6 这次准备升级5.7

**Comment by Men-Z** [comment]
@uighurbabbage 好滴，我这就去换版本，之前是认为最新版本兼容性会更好一些

**Comment by zkhzkhz** [comment]
https://github.com/beego/bee/issues/540问题解决

**Comment by HaoQinLandv** [comment]
bee api appcode -conn="root:root@tcp(127.0.0.1:3306)/test" 这样可以
