### ISSUE TITLE
How to set a default value for body params by swagger? 

### ISSUE THREAD

**Issue by xhan742** [beego/beego#3161]
beego 1.9.1
How to set default value for body params by swagger? 
For example, 
// @Param	bodyParam   body 	models.Object	
where models.Object is defined as 
type Object struct {
	ObjectId   string
	Score      int64
	PlayerName string
}
Then what should I do if I want to give bodyParam a default value as
 type{ObjectId="asdf"   Score=1    PlayerName="user"}

**Comment by ivan-ru** [comment]
i faced the same problem,  figured it out to make it work this way

// @Param     bodyParam     body     models.Object     "{
// 	"object_id": "asdf",
// 	"score": 1,
// 	"player_name": "user"
// }"     true "Player Object"

**Comment by lifeblood** [comment]
没人回答？
