### ISSUE TITLE
panic: sql: Register called twice for driver mysql

### ISSUE THREAD

**Issue by ghost** [beego/beego#3413]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.9.2 linux/amd64;
Beego     : 1.11.0

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
使用 mysql 做数据库和存储 session 时，运行 bee run ，会有如下异常抛出
```
panic: sql: Register called twice for driver mysql

goroutine 1 [running]:
database/sql.Register(0xa2a72c, 0x5, 0xcf1800, 0xd576d8)
        /usr/local/go/src/database/sql/sql.go:50 +0x1ad
github.com/astaxie/beego/vendor/github.com/go-sql-driver/mysql.init.0()
        /home/gopath/src/github.com/astaxie/beego/vendor/github.com/go-sql-driver/mysql/driver.go:168 +0x5c
github.com/astaxie/beego/vendor/github.com/go-sql-driver/mysql.init()
        <autogenerated>:1 +0xd5d
github.com/astaxie/beego/session/mysql.init()
        <autogenerated>:1 +0x5d
goKougaBlog/controllers.init()
        <autogenerated>:1 +0x69
goKougaBlog/routers.init()
        <autogenerated>:1 +0x49
main.init()
        <autogenerated>:1 +0x49
```

4. What did you expect to see?
please fix it

5. What did you see instead?
我目前是注释掉一行代码：
file path：/home/gopath/src/github.com/astaxie/beego/session/mysql/sess_mysql.go
```
import (
	"database/sql"
	"net/http"
	"sync"
	"time"

	"github.com/astaxie/beego/session"
	// import mysql driver
       // 注释掉这行代码
	// _ "github.com/go-sql-driver/mysql"
)
```

**Comment by gdroid7** [comment]
Just delete the migrate folder from vendor directory and reinstall it again.

i deleted my whole vendor directory and did
`dep ensure`

this fixed this issue for me.

**Comment by shanedetsch** [comment]
Had a similar issue.

The error I had was 
panic: sql: Register called twice for driver mssql

The problem was when I switched from using 
_ "github.com/minus5/gofreetds"
to 
_ "github.com/denisenkom/go-mssqldb"
in one file 
I was still referencing a gofreetds in another file.

The solution was to change all instances of gofreetds to go-mssqldb and not reference both.

**Comment by flycash** [comment]
It looks like that this error is from dependency `sql`, and beego can do nothing to it. 

[panic: sql: Register called twice for driver mysql](https://github.com/go-sql-driver/mysql/issues/256)
