### ISSUE TITLE
SetStaticPath,Why is it wrong

### ISSUE THREAD

**Issue by lvv787** [beego/beego#3504]
env:
├── Beego     : 1.11.1
├── GoVersion : go1.11.4
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8

directory:
├── MybeeApp
    ├── down1
        │   ├── download1
             |    │   ├── 123.txt
        │   ├── 333.txt
    ├── static
        │   ├── css
        │   ├── img
        │   └── js

run code:
func main() {
	beego.SetStaticPath("/down1", "download1")//http://localhost:8080/down1/123.txt
	beego.SetStaticPath("/down1", "down1")

	beego.Run()
}

cmd:
curl -I http://localhost:8080/down1/123.txt

results:
HTTP/1.1 404 Not Found

expect:
123123123

**Comment by JessonChan** [comment]
beego.SetStaticPath("/down1", "down1/download1")
