### ISSUE TITLE
HTTP GET request with body arrives to the controller empty

### ISSUE THREAD

**Issue by jrg909** [beego/beego#3521]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go version: go1.11.1
Beego version: 1.10.1

2. What operating system and processor architecture are you using (`go env`)?

I'm using Kubuntu 16.04.5 LTS 64 bits (amd64).

3. What did you do?

I'm testing a REST Api using Beego and for a particular endpoint I need to send a GET request with a JSON body whose only field is a token that permits retrieving some data. My problem is that the request body arrives to the controller empty and I'm not sure why.

These are the things I've tried:
- I made sure that in the configuration of the project copyrequestbody is set to true.
- I sent the request with curl to check if there is a problem with my testing code and the same problem exists.
- According to the answer of this question if I set the header Content-Length it should work, but I did and the problem persists (I also added the header Content-Type but still no luck).

This is my code:

```
// --- Struct used in the JSON encoding and decoding

type BodyGetAllClientes struct {
    Token string
}

// --- Test code for the endpoint

// Code used to create the HTTP request
cliente := &http.Client{}
cuerpoToken := new(bytes.Buffer)
// casoDePrueba.cuerpoSolicitud has type BodyGetAllClientes
json.NewEncoder(cuerpoToken).Encode(casoDePrueba.cuerpoSolicitud)
solicitudCreada, errorCreacionSolicitud := http.NewRequest("GET", "http://localhost:8080/v1/CLIENTES"+casoDePrueba.querySolicitud, cuerpoToken)

// Ignoring lines for error handling of http.NewRequest (it's not reporting anything wrong)

// Setting some HTTP headers
solicitudCreada.Header.Set("Content-Type", "application/json")
solicitudCreada.Header.Set("Content-Length", strconv.Itoa(cuerpoToken.Len()))

// Code used to send the HTTP request
respuestaObtenida, errorEnvioSolicitud := cliente.Do(solicitudCreada)

// The error handling of cliente.Do isn't reporting a problem either

// --- Decoding JSON in the controller for the endpoint

var v BodyGetAllClientes
errorConversionJSON := json.Unmarshal(c.Ctx.Input.RequestBody, &v)
```

4. What did you expect to see?
- **c.Ctx.Input.RequestBody** should have a non zero length.
- **errorConversionJSON** should be equal to nil.

5. What did you see instead?
- **c.Ctx.Input.RequestBody** has zero length.
- **errorConversionJSON** is not nil and when printing the error it says: "unexpected end of JSON input".

**Comment by guhan121** [comment]
like #3526

**Comment by Demontf** [comment]
@guhan121 Not the same thing. In #3526 is post method.

**Comment by Demontf** [comment]
In Get Request can use this method to get body "ctx.Input.CopyBody(MaxMemory)"
