### ISSUE TITLE
beego作为golang成熟的web框架，有考虑协程池吗？在golang之上封装net.http.server，提供可配置协程数量，总不能无限制创建，依靠操作系统来限制。即使协程开辟也就几Kb的大小

### ISSUE THREAD

**Issue by didiaodecainiao** [beego/beego#3615]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by jianzhiyao** [comment]
考虑在beegov2.*加入此特性，已在日程中

**Comment by AllenX2018** [comment]
是否可以考虑在utils里加入一个独立的协程池模块供beego框架本身及用户使用？

对于处理请求的`func (srv *Server) Serve(l net.Listener) error`， 可对其进行重写，首先初始化一个协程池，并将最后的`go c.serve(connCtx)` 修改为由协程池实例调度执行`c.serve(connCtx)`

**Comment by jianzhiyao** [comment]
> 是否可以考虑在utils里加入一个独立的协程池模块供beego框架本身及用户使用？
> 
> 对于处理请求的`func (srv *Server) Serve(l net.Listener) error`， 可对其进行重写，首先初始化一个协程池，并将最后的`go c.serve(connCtx)` 修改为由协程池实例调度执行`c.serve(connCtx)`

net/http底层是起一个协程去处理的，应该从这个角度去重写或者其他操作

**Comment by AllenX2018** [comment]
>net/http底层是起一个协程去处理的，应该从这个角度去重写或者其他操作
是的。我也打算从这个角度去重写 `Serve`函数。
你可以将这个特性分配给我~
