### ISSUE TITLE
Beego的Controller里面有没有方法可以中止输出

### ISSUE THREAD

**Issue by fingerQin** [beego/beego#367]
比如，我现在判断密码错误之后，我输入一个json，然后下面的代码就不执行了。按照我现在所熟知的方式就是直接在后面写一个return，

有没有像PHP一样的exit方法一样，直接结束掉当前后面的输入。因为，我写了一个公共方法来管理操作提示，在提示里面就结束掉当前的后面的代码执行。

**Comment by One2r** [comment]
@astaxie 调用ServeJSON后，我是不想再写行代码调StopRun去中止了。为什么不在ServeJSON里面帮忙中止呢？
