### ISSUE TITLE
Beego ORM不支持IN()里面传递字符串

### ISSUE THREAD

**Issue by fingerQin** [beego/beego#368]
如代码：
sql = "SELECT \* FROM v_test WHERE id IN (?)"
num, err := o.Raw(sql, ids).QueryRows(&test)

ids是：1,2,3,4这种格式，结果只得到了第一个ID的数据。

这是BUG还是本身就是这样设计的呢。

**Comment by GannicusLiu** [comment]
这个功能确实有点儿纠结，不接受字符串，只能自己转换一次。

**Comment by pq-dong** [comment]
beego版本 1.11.0
不支持字符串解析；
当qbs增大时，大量的，不同的原生 in子句，会导致预编译资源耗尽问题，Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)
