### ISSUE TITLE
how to get the logger from beego-logs？

### ISSUE THREAD

**Issue by miscomputer** [beego/beego#3698]
初始化beego logs之后，如果将已经配置的logger返回，提供给其它框架的SetLogger？

Translate:
How could we get the initiated logger from logs module? We want to pass it to other frameworks.

**Comment by IamCathal** [comment]
`beego.SetLogger()` 只接受一个beego日志适配器（如控制台、文件等），而不接受其他框架的自定义日志器。
用户定义的日志格式将在2.0版本中引入。这是一个如何工作的例子 https://github.com/astaxie/beego/pull/4157

------------------------------------------------------------------------------------------------------------------------------------------------------

`beego.SetLogger()` only accepts a log adapter (such as console, file etc.) and not a custom logger from another framework.

User defined logging formats are going to be introduced in the 2.0 release. This is an example of how it will work https://github.com/astaxie/beego/pull/4157

**Comment by flycash** [comment]
we could provide method `GetLogger(adapter...) Logger`.
