### ISSUE TITLE
在app.conf配置了https，编辑器直接运行可以用https访问，打包运行日志不提示https server Running on https://:，也https也访问不了。

### ISSUE THREAD

**Issue by huohuo0319** [beego/beego#3909]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.13.5 windows/amd64      bee version v1.10.0

2. What operating system and processor architecture are you using (`go env`)?
win7   intel(R) i5-4460

3. What did you do?
appname = MyBeegoAPI
httpport = 8080
HttpsPort = 10443
HTTPSCertFile = "conf/1_wwwcn_bundle.crt"
HTTPSKeyFile = "conf/2_wwwcn.key"
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
EnableHTTPS = true
EnableHttpTLS = true
EnableHTTP = true
为了能用https访问，配置如上，直接在goland编辑器运行，可以得到如下两句日志
http server Running on http://:8080
https server Running on https://:10443
并且可以用https://127.0.0.1:10443和http://127.0.0.1:8080访问
停掉刚才运行的服务。
接着我用go build打包exe得到可执行文件，拿出来直接双击运行，日志只提示
http server Running on http://:8080
并且https://127.0.0.1:1044访问不了，只有http://127.0.0.1:8080可以访问。

4. What did you expect to see?
我想打包之后得到的可执行文件也能用https访问

5. What did you see instead?
打包之后直接运行exe，https访问不了。

**Comment by Qianggggg** [comment]
https你带证书访问了吗

**Comment by flycash** [comment]
没有回应，我先关了
