### ISSUE TITLE
模版中嵌套循环，里面无法取外部值

### ISSUE THREAD

**Issue by yfeng** [beego/beego#3918]
Data 类似是"a,b,c"..  
split返回数组
{{range .rows}}
{{range $i,$e := split .Data}}
                    <input type="checkbox" name="{{$.Id}}" title="{{$e}}" >
                    {{end}}
{{end}}
{{$.Id}} 这个无法获取rows中的Id

**Comment by flycash** [comment]
我是不是理解错了？为何我觉得你提供的这个代码片段，最后的这个{{$.Id}}已经不是循环内的了？
