### ISSUE TITLE
beego中model里的ORM映射，如果设置pg数据库里的Text[]数组类型？

### ISSUE THREAD

**Issue by xuyao91** [beego/beego#3952]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.10.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/xuyao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xuyao/Workspaces/mygo"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/75/ccnsq2ps1f12y795kv144s5h0000gn/T/go-build393898542=/tmp/go-build -gno-record-gcc-switches -fno-common"

3. What did you do?
我beego使用的是pg数据库，我有个表里有个字段是数组类型（text[]），但是我没找到方法如何使用ORM来映射它，比如
type Block struct {
  Transactions []string  `orm:"???"` 
}
transactions 字段在pg数据库里是text[]类型，那么上面orm里的???我应该怎么写呢？

**Comment by flycash** [comment]
除非是外键关联对象，否则目前我们不支持在ORM里面使用数组。
