### ISSUE TITLE
SSL and redirection

### ISSUE THREAD

**Issue by ymg** [beego/beego#401]
Is there any way to make beego force redirect any request to non-secure ports to https i.e. port 443 ? the only way I see this happening right now is by creating another app that listens to port 80 requests and redirect them.

Is this something that could be implemented in future like some other frameworks? I mean having https redirects by default whenever TLS is enabled.

Thanks

**Comment by bclermont** [comment]
I did it that way

```
package redirect

import (
	"fmt"
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/context"
	"net/http"
)

var (
	https_baseUrl string
	isProd        bool
)

const httpsConfigKey = "https_base"

func Https(ctx *context.Context) {
	if isProd {
		if ctx.Input.Request.TLS == nil {
			ctx.Redirect(http.StatusTemporaryRedirect, https_baseUrl+ctx.Input.Request.URL.String())
		}
	}
}

func init() {
	if beego.RunMode == "prod" {
		https_baseUrl = beego.AppConfig.String(httpsConfigKey)
		if len(https_baseUrl) == 0 {
			panic(fmt.Errorf("missing configuration '%s'", httpsConfigKey))
		}
	}
}
```

and then use this in routers:

```
	ns := beego.NewNamespace("/xxx",
		beego.NSBefore(redirect.Https),
		beego.NSInclude(
			// do some stuff here
		),
	)
	beego.AddNamespace(ns)
```

**Comment by ZloiBubr** [comment]
thank you, i put everything together: https://github.com/ZloiBubr/go-example-001-autoswitch-to-https
