### ISSUE TITLE
orm InsertOrUpdate Only Want To Update certain raw and remain the rest unchanged

### ISSUE THREAD

**Issue by B8kingS0ga** [beego/beego#4013]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.12.1

2. What operating system and processor architecture are you using (`go env`)?
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=D:\Language\go\bin
set GOCACHE=C:\Users\WIN10\AppData\Local\go-build
set GOENV=C:\Users\WIN10\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=git.domob-inc.cn
set GONOPROXY=git.domob-inc.cn
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\WIN10\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=D:\Language\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Language\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\WorkProject\mp_ringme\idol_event_stats_collector\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\WIN10\AppData\Local\Temp\go-
build869589442=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
_ , err = o.InsertOrUpdate(&data,
		"CardNums=CardNums+1",
	)
```

4. What did you expect to see?
Only Update CardNums As CardNums +1 and remain the rest unchanged

5. What did you see instead?
all column changed.

just in my opinion, in most of my cases, the first insert only containes default prameter, but when the raw got update more and more, it is not very likely we wan't to update all with insert colomn but only some perticular columns, at least we can have another method does this

**Comment by flycash** [comment]
Now I think it's not very necessary to do this enhancement.  It's a tradeoff. If we want to only update columns that are updated by the user. We should resolve the key problem, how to identify changed columns? It will introduce much complexity.

**Comment by B8kingS0ga** [comment]
yeah, I see, but what I think I can pass more params to define certain colomn to be updated, just like the update method

**Comment by flycash** [comment]
Specifying the columns to be updated in InsertOrUpdate method looks strange. In this case, maybe using Update method is the best solution. Could you provide more information about why you prefer to using InsertOrUpdate?

**Comment by B8kingS0ga** [comment]
Just for my user cases: I have a statistic table for accumulating different type of processing, like this 
`
create table stat
(
    id int
    check_total int
    comment_total int
)
`
when there is a user try check, I want to update stat.check_total by one, but if the row is not exist I want to init a row, like below 
`
select id, check_total from stat on duplicated key update check_total = check_total + 1
` 
but I want to leave comment_total un changed, 

but if I use the insert or update now, It will generate a sql like

`
select id, check_total from stat on duplicated key update check_total = check_total + 1, comment_total = comment_total ... 

`

that didn't seems right to me,

**Comment by flycash** [comment]
Ok, I understand. Would you like to issue a PR to do this enhancement? Now we are focusing on V2 refactor, we don't want to pay much attention to do this. But when we refactor ORM module, this enhancement will be taken into consideration.
