### ISSUE TITLE
The primary key is mandatory but sometimes we don't actually have one, could it be optional?

### ISSUE THREAD

**Issue by zuzuviewer** [beego/beego#4060]
go version：1.13.5            beego version:1.12

windows 10 64bit 

beego中的orm模型一定要设置一个主键，但是其实数据库不一定是有主键的，这样导致一些问题，比如我需要删除一个没有主键的数据库数据时，在beego中用orm的Delete方法会根据在模型中设置的主键去筛选，其他的过滤条件没有用，导致多删

我希望beego的orm能放开这一限制或者有更好的方案来做限制，至少不要给开发带来困扰，如果一定要设置主键，那么删除的时候也应该正确删除数据

**Comment by flycash** [comment]
目前来说，主键是必须的。我们后面会考虑放松这个限制，但是目前来看，必要性和紧迫性都不是特别高。不过你说的误删除的问题，可以提供一点demo代码和数据库表结构么？

**Comment by zuzuviewer** [comment]
> 目前来说，主键是必须的。我们后面会考虑放松这个限制，但是目前来看，必要性和紧迫性都不是特别高。不过你说的误删除的问题，可以提供一点demo代码和数据库表结构么？

建表时实际没有主键

`create table user( name varchar(100), age int);`

`package main

import (
    "fmt"
    "github.com/astaxie/beego/orm"
    _ "github.com/go-sql-driver/mysql"
)

type User struct{
	Name string `orm:"pk"`
	Age int
}

func init(){
	orm.RegisterModel(new(User))
	orm.RegisterDriver("mysql", orm.DRMySQL)
    orm.RegisterDataBase("default", "mysql", "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8")
}

func main(){
	var (
		o = orm.NewOrm()
		num int64
	)
	user := &User{
		Name: "yk",
		Age: 12,
	}
	o.Insert(user)
	user.Age = 21
	o.Insert(user)
	num,_ = o.QueryTable("user").Filter("name","yk").Filter("age",12).Delete()
	fmt.Printf("num : %d\n",num)
}`

最后显示的删除个数为2个。
限制可以不放松，但是必须考虑到某些表是没有主键或者联合主键的情况

**Comment by zuzuviewer** [comment]
> 目前来说，主键是必须的。我们后面会考虑放松这个限制，但是目前来看，必要性和紧迫性都不是特别高。不过你说的误删除的问题，可以提供一点demo代码和数据库表结构么？

现在暂时还只发现Delete有这个问题，Count可以正常得到1个的结果

**Comment by flycash** [comment]
#4300 里面放开了主键的限制

**Comment by liaoyijun** [comment]
> #4300 里面放开了主键的限制

为什么要先查后删

**Comment by liaoyijun** [comment]
试试这样
`
var u User
u.Name = "yk"
u.Age = 12
o.Delete(&u, "name", "age")
`
