### ISSUE TITLE
Javascript里面显示beego传来的值被转义了，求解决

### ISSUE THREAD

**Issue by fingerQin** [beego/beego#407]
代码如下：

<script type="text/javascript">
var videourl = "{{.videourl}}"
</script>

渲染之后的结果如下：

var videourl = "http:\/\/studyresource.u.qiniudn.com\/demo1.flv?e=1387762060\x26token=bbnyISD29weVthTXAOT5lcJ-ftYrNjuAO-m8cnvQ:9xiMQmw9ubh-ttFBZRyPgbnJz3Q"

这个URL为什么会被斜线自动处理呢。通过几次测试，只有在JS里面才会这样处理。好纠结。template能不能不要这么BT。这完全干涉太深了。求各种解决方案。百度谷歌找不到类似的文章。只能求助Beego社区了。谢了。

**Comment by greatbsky** [comment]
eval(xxx)
