### ISSUE TITLE
Proposal: Field serializer and json implementation

### ISSUE THREAD

**Issue by flycash** [beego/beego#4088]
Many users store the json in one column. Though I think it's not a good practice, but it's very convinient. In such cases, users want a feature that we can sirialize the value to json and then store into DB. When desialize record from DB, we can convert the json value to object.

Here is an example:

```go
type User struct {
    Name string
    Attributes []Attribute `serializer: json`
}
```
The `[]Attribute` will be converted to json string before storing it into DB. 

The `serializer` represents one implementation of interface:
```go
type FieldSerializer interface {
    Serialize(obj interface{}) string
    Deserialize(str interface) interface{}
}
```

We can allow user to register their own implementation:
```go
orm.RegisterFieldSerializer("my-s", sri)
```

They can use it in their structure:

```go
type User struct {
   SomeField XXX `serializer: "my-s"`
}
```

**Comment by tayoogunbiyi** [comment]
I'd work on this. You can assign it to me.

**Comment by flycash** [comment]
Please checkout branch from develop-2.0 and put your code in pkg/orm

**Comment by tayoogunbiyi** [comment]
I've been working on this but there are some blockers involving how to restore the JSON stored in the DB back to the original model's field type.
I'm going to link my PR so far here (in case someone wants to continue here), and come back to it some other time.)

https://github.com/astaxie/beego/pull/4118

**Comment by flycash** [comment]
> I've been working on this but there are some blockers involving how to restore the JSON stored in the DB back to the original model's field type.

My idea is that you can add more parameter in `deserialize` method, like `field reflect.Field` or `fi fieldInfo`

**Comment by jianzhiyao** [comment]
Hey guys!
@flycash @tayoogunbiyi 
### @flycash 's proposal
I think that proposal is not a good idea!
That could limit data format in many using case.
```
type User struct {
    Name string
    Attributes []Attribute `serializer: json`
}
```

### My proposal
Implementing ``encoding.BinaryMarshaler`` and ``encoding.BinaryUnmarshaler`` for model struct.
And return error when struct not implements then.
```
type User struct {
	Name           string
	JsonAttributes []JsonAttribute
	XmlAttributes  []XmlAttribute
}

type JsonAttribute struct {
	Key   string
	Value string
}

var _ encoding.BinaryMarshaler = new(JsonAttribute)
var _ encoding.BinaryUnmarshaler = new(JsonAttribute)

func (a *JsonAttribute) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, a)
}

func (a *JsonAttribute) MarshalBinary() (data []byte, err error) {
	return json.Marshal(a)
}

type XmlAttribute struct {
	Key   string
	Value string
}

var _ encoding.BinaryMarshaler = new(XmlAttribute)
var _ encoding.BinaryUnmarshaler = new(XmlAttribute)

func (a *XmlAttribute) UnmarshalBinary(data []byte) error {
	return xml.Unmarshal(data, a)
}

func (a *XmlAttribute) MarshalBinary() (data []byte, err error) {
	return xml.Marshal(a)
}
```

**Comment by flycash** [comment]
> Implementing `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` for model struct.

That is too complicated for most users. 

And what they need is "declaring they will store json into the column", and then we do all things for them.

They are not required to do more things.

**Comment by jianzhiyao** [comment]
> > Implementing `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` for model struct.
> 
> That is too complicated for most users.
> 
> And what they need is "declaring they will store json into the column", and then we do all things for them.
> 
> They are not required to do more things.

But it is very useful.
We can encode a struct  to any format we need. Such as msgpack, json, xml and so on.
