### ISSUE TITLE
A Suggestion - Creating new project for session module to make it independent

### ISSUE THREAD

**Issue by Blank-Xu** [beego/beego#4095]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

Latest

2. What operating system and processor architecture are you using (`go env`)?

Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Just a suggestion.

4. What did you expect to see?

Would you mind to create a new project at ( https://github.com/beego/session ) and move  ( https://github.com/astaxie/beego/session ) codes to the new project.

5. What did you see instead?

Nothing

**Comment by flycash** [comment]
This a good advice. We are thinking about support it. 

We have discussed about this question. We plan to create new project for every module, including session module, orm module...

But our concern is that, most users like one-stop solution. They may not like importing many modules in their project. 

So we need to keep beego, which contains all modules and many independent modules.

It need much effort to maintains those projects.

But I want to try it.
