### ISSUE TITLE
Proposal: How to register models with same table name?

### ISSUE THREAD

**Issue by flycash** [beego/beego#4105]
Related issues: #3874, #3916 

Now beego uses `modelCache` to maintain all models. But beego supports using multiple DBs. So there is a problem: if DBs contain some tables which have different schema but the same name. For example:
```go
type User strut {
   Name string
}
type AUser struct {
  FirstName string
  LastName string
}
func (a *AUser)TableName() {
    return "User"
}
```
We can not register these two models because they have the same name "User". In some cases, we cannot rename tables. So we should think about how to solve this problem.

I think we have two ways:

1. decouple table name and model name. Now `modelCache` uses `table` (the table name) as key:
```go
func registerModel(PrefixOrSuffix string, model interface{}, isPrefix bool) {
        // ...
	modelCache.set(table, mi)
}
```
We can add a new field in `modelInfo` named `modelName` and use this field as key:
```go
modelCache.set(modelName, mi)
```
The default value is the table name;

2. Support DB specific models. In this way, a DB contains its models' definition which can not be accessed by other DB.
Thus we will have `modelCache`, the global models and DB's models.
It looks like:
```go
modelCache = ...

type DB struct {
    modelCache ...
}

```

**Comment by WenyXu** [comment]
we can register the db connection metadata ( or other identifiable ) at same time

```go
func registerModel(...) {
        // ...
	modelCache.set(table, connection_metadata,...)
}

```
```go
func registerModel(...) {
        // ...
	modelCache.set(token_generator(table, connection_metadata),...)
}

```
then the usage will like:
```go
// using reflect get the struct name
model:=modelCache.getWithMetadata(User,connection_metadata)
// get the model by key
model:= modelCache.get(token_generator("table name",connection_metadata))

```

**Comment by WenyXu** [comment]
We also can provide a hook interface, let user define their own token_generator 

```go
func token_generator(ctx context, model interface{},db_metadata something_no_idea) string {
    //...
    return 
}
```
register the generator
```go
db:=register(..., token_generator)
```

then the usage will like
```go
model:= modelCache.get(token_generator(ctx,"table name",connection_metadata))

```

**Comment by flycash** [comment]
> We also can provide a hook interface, let user define their own token_generator

Token generator is a good idea. We can extract current logic as its default implementation. But it cannot resolve this problem.

Assume that we have two DB named db1 and db2. Both of them have table named "My_USER_TABLE". Even we define the `token_generator`, the return value must be "My_USER_TABLE" because we use the table name as modelCache's key.

As long as all models sharing one `modelCache`, it cannot be resolved. We should design something like namespace.

**Comment by WenyXu** [comment]
> > We also can provide a hook interface, let user define their own token_generator
> 
> Token generator is a good idea. We can extract current logic as its default implementation. But it cannot resolve this problem.
> 
> Assume that we have two DB named db1 and db2. Both of them have table named "My_USER_TABLE". Even we define the `token_generator`, the return value must be "My_USER_TABLE" because we use the table name as modelCache's key.
> 
> As long as all models sharing one `modelCache`, it cannot be resolved. We should design something like namespace.

Yep, Maybe I didn't explain clearly. I think the DB connection metadata should be a identifiable information, as if with namespace.

**Comment by flycash** [comment]
> Yep, Maybe I didn't explain clearly. I think the DB connection metadata should be a identifiable information, as if with namespace.

For now, I don't see the scenario that needs more metadata. So maybe introduce `modelName` is enough.
