### ISSUE TITLE
Proposal: Move admin service files to admin directory

### ISSUE THREAD

**Issue by flycash** [beego/beego#4122]
Beego provides useful admin services to expose the internal status of the application.

But there is a big problem: The admin service is coupled with the web module.  The key files are admin.go, admin_ui.go, admin_test.go. Now the structure is:
```
beego
    -- pkg
        -- admin.go
        -- hook.og
        -- router.go
```

We want to create a directory named `admin` and it should be an independent module. The structure looks like:
```
beego
    -- pkg
        -- admin 
             - admin.go
             - ...
        - hook.go
        - router.go
```

I have a try but those files use many package-scope parameters defined in hook.go or router.go. So we need to decouple them from the web module.

**Comment by IamCathal** [comment]
Could you give some example code to use to test this. I moved them into their own folder in pkg and ran my test api and no errors were given (obviously because I didn't use any admin related files). I've not used this part of beego before but if I had some starting code that used the admin files I could give this refactor a go :)

**Comment by flycash** [comment]
Sorry, I don't have more tests. I think you could start the admin service to test or add more unit tests.

**Comment by IamCathal** [comment]
I don't mean more tests I just mean some example code someone would use that would need to use the beego admin files. I'm not sure when a user would interact with it

**Comment by flycash** [comment]
You can assume that users will not use the admin service's codes. They can only start the admin-service with port 8081 to check admin-service.
