### ISSUE TITLE
Proposal-Cache usage pattern: cache-aside, write-through, read-through and more...

### ISSUE THREAD

**Issue by flycash** [beego/beego#4166]
Some common usage like
```
if Get(key) == nil {
    value := LoadFromDB(key)
    Put(key, value)
}

return Get(key)
```
I think we can provide some cache plugins to solve similar problems.
The above example is "cache-aside pattern". 

And there are many other patterns.
1. write-through pattern:  write cache firstly and then write storage;
2. read-through pattern: read from cache and if not found, cache load value from storage;
3. write-back pattern: write cache firstly and return. Cache will write data to storage asynchronously;
4. write-around pattern: write storage and then remove the key from cache;

All of those patterns may cause inconsistent data, but it's very useful.

**Comment by AllenX2018** [comment]
It seems that current version doesn't support write/read between cache and database.
So this proposal is going to create new interface including method such as  `func Get(key string) string`, `func Put(key string, val  string)` and so on? 
And we will implement the interface to realize differnt patterns, such as "cache-aside pattern", "write-through pattern" and so on ?

**Comment by flycash** [comment]
> It seems that current version doesn't support write/read between cache and database.
> So this proposal is going to create new interface including method such as `func Get(key string) string`, `func Put(key string, val string)` and so on?
> And we will implement the interface to realize differnt patterns, such as "cache-aside pattern", "write-through pattern" and so on ?

Actually we have methods:
```go
type Cache interface {
	// get cached value by key.
	Get(key string) interface{}
	// GetMulti is a batch version of Get.
	GetMulti(keys []string) []interface{}
	// set cached value with key and expire time.
	Put(key string, val interface{}, timeout time.Duration) error
	// delete cached value by key.
	Delete(key string) error
	// increase cached int value by key, as a counter.
	Incr(key string) error
	// decrease cached int value by key, as a counter.
	Decr(key string) error
	// check if cached value exists or not.
	IsExist(key string) bool
	// clear all cache.
	ClearAll() error
	// start gc routine based on config string settings.
	StartAndGC(config string) error
}
```
In fact, I think we need something like, taking `read-through` as example:
```go
type ReadThroughCache struct {
     dataReader XXXXType
     cache Cache
}
```

When we could not find the value with a specific key, we will use `dataReader.Read(key)`.
Usually, it means that `dataReader` read data from DB.

I think using `decorator` design pattern is pretty good.

**Comment by AllenX2018** [comment]
If load from db,  establishing the relationship between a key value and an SQL statement is needed.

A simple solution is using a complete sql statement as a key when user passed a key to `Cache.Get(key string)`, and it may store as a hash in `map` for compare. If loading from db is needed, the key(sql statement, not a hash) passed by the user can directly used for db operation.  However, the sql statement passed maybe too long and make this method not very elegant.

**Comment by AllenX2018** [comment]
> A simple solution is using a complete sql statement as a key

The simple solution above also has problem. When there is a key `select * from table1 where A=a and B=b` in cache,  use key `select * from table1 where B=b and A=a` will cause a cache miss, though these two keys have same queried result.

**Comment by AllenX2018** [comment]
When user used `Cache.Get(key string)` and there is no key-value in cache, which `Cache.Get(key string)` should load data from db,  establishing the relationship between a key value and an SQL statement is needed. 
The relationship may have multiple possibilities, so we can consider providing a user-defined interface for user sql query and update.

Consider a more general scenario, using `key` and operating db can defined as an interface, like
```go
type CacheOrm interface {
	Query(key string) (interface{}, error)
	Update(key string, val interface{}) error
}
```

A simple example implement of the interface can be:
```go
type CacheOrmBase struct {
	orm orm.Ormer
	cacheTable string
}

func (c *CacheOrmBase) NewCacheOrmBase(orm orm.Ormer, cacheTable string) {
	c.orm = orm
	c.cacheTable = cacheTable
}

func (c *CacheOrmBase) Query(key string) (interface{}, error) {
	var lists []orm.ParamsList
	_, err := c.orm.Raw(fmt.Sprintf("select val from %s WHERE id = ?", c.cacheTable), key).ValuesList(&lists)
	if err != nil {
		return nil, err
	}
	return lists, nil
}

func (c *CacheOrmBase) Update(key string, val interface{}) error {
	// ...
}
```
And the `CacheOrmBase.Query()` can be used in `ReadThrough.Cache.Get()`

**Comment by flycash** [comment]
`CacheOrm` could be one of the implementations.

We need more general abstraction. For example, in some cases, we will read local cache, and then read remote cache( redis), and then read the database.

So in general, we need some interface like:
```go
// pkg cache
type ValueReader interface {
    Query(key string) (interface{}, error)
}

type ValueWriter interface {
    Update(key string, val interface{}) error
}
```

So for ORM, we define
```
// pkg orm
type CacheOrm interface {
    ValueReader
    ValueWriter
    // I prefer that CacheOrm and (ValueReader, ValueWriter) have same methods, so we don't import cache module to ORM module
}
```

If we want to support multiple layer cache:
```go
type ReadThroughCache struct {
    Cache
    reader ValueReader
}

func Init(cache Cache, reader ValueReader) Cache{
    return &ReadThroughCache{
     Cache: cache,
     reader: reader
    }
}

var twoLayerCache = Init(Init(memoryCache, redisReader), dbReader)
```

The keypoint is that cache module provide the abstraction: How to read the data from data source, and how to write data to data souce.

And DB is a data source, but we could have more data source.

**Comment by AllenX2018** [comment]
If `ValueRead` and `ValueWrite` are divided into two interfaces, I think the interface `CacheOrm` is discardable. 

For example,  class `ReadThroughCache` can be defined as:
```go
type ReadThroughCache struct {
	Cache
	reader ValueReader
	lifeSpan time.Duration
}

func NewReadThroughCache(cache Cache, reader ValueReader, lifeSpan time.Duration) *ReadThroughCache {
	return &ReadThroughCache{Cache:cache, reader: reader, lifeSpan: lifeSpan}
}

func (c *ReadThroughCache) Get(ctx context.Context, key string) (interface{}, error) {
	if val, _ := c.Cache.Get(ctx, key); val != nil {
		return val, nil
	}
	val, err := c.reader.Query(key)
	if err != nil {
		return nil, err
	}

	if err := c.Cache.Put(ctx, key, val, c.lifeSpan); err != nil {
		return nil, err
	}

	return c.Cache.Get(ctx, key)
}
```

The code above is written in beego framework. The using of `ReadThroughCache` and implements of `ValueReader` are writtern in user code.
User can implement different `ValueReader`, like a db reader:
```go
// model.go
type OrmValueReader struct {
	orm orm.Ormer
	cacheTable string
}

func NewOrmValueReader(orm orm.Ormer, cacheTable string) *OrmValueReader {
	return &OrmValueReader{orm: orm, cacheTable: cacheTable}
}

func (rd *OrmValueReader) Query(key string) (interface{}, error) {
	// ...
}
```
And `ReadThroughCache` can be called like:
```go
func main() {
	mc, err := cache.NewCache("memory", `{"interval":1}`)
	// ...
	o := orm.NewOrm()
	rt := cache.NewReadThroughCache(mc, NewOrmValueReader(o, "cache"), 2*time.Second)
	val, err := rt.Get(context.Background(), "1")
        // ...
}
```

Similarly，`WriteThroughCache` and `CacheAside` can be defined like:
```go
type WriteThroughCache struct {
	Cache
	writer ValueWriter
	lifeSpan time.Duration
}

type CacheAside struct {
	Cache
	reader ValueReader
	writer ValueWriter
	lifeSpan time.Duration
}
```

**Comment by flycash** [comment]
Yes! I believe it's more scalable.
