### ISSUE TITLE
用SaveToFile文件上传后，一直占着虚拟内存没有释放

### ISSUE THREAD

**Issue by mrcuix** [beego/beego#42]
发现在windows中用SaveToFile保存上传后的文件，一直占着虚拟内存没有释放，再上传多几次C盘就满了
有什么方法比较优化的呢？
代码如下：

```
package main

import (
    "github.com/astaxie/beego"
)

type UploadController struct {
    beego.Controller
}
func (this *UploadController) Post() {
    _, h, _ := this.GetFile("uploadfile")
    this.SaveToFile("uploadfile", "./static/files/"+h.Filename)
    this.Ctx.Redirect(302, "/upload")

}

func main() {
    beego.Router("/upload", &UploadController{})
    beego.Run()
}
```

**Comment by YouZhengChuan** [comment]
f, h, _ := this.GetFile("uploadfile")
defer f.Close()
最好改成这样
defer func() {
		if err := f.Close(); err != nil {
			log.Fatal("f.Close(): ", err.Error())
			return
		}
	}()

如果用户POST里面的Header中，name不等于“uploadfile”，那么f.Close()会触发这个报错：
[C] [asm_amd64.s:514] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
[C] [asm_amd64.s:514] /usr/local/go/src/runtime/asm_amd64.s:514
... ...

**Comment by bestplay** [comment]
@YouZhengChuan  

f, h, _ := this.GetFile("uploadfile")

自己把 error 处理省掉了。 

defer 之前处理 error 不就好了

beego 的文档里关于文件上传的章节，也写的有问题。没有把错误处理放到前面去
