### ISSUE TITLE
beego写test测试用例问题

### ISSUE THREAD

**Issue by Icedroid** [beego/beego#424]
写测试用例子代码如下：

``` ruby
    b, err := json.Marshal(＆Req{Username:"test", Passoword:"123456"})
    r, _ := http.NewRequest("POST", "/user/login", bytes.NewBuffer(b))
    r.Header.Set("User-Agent", "beego_server")
    r.Body = ioutil.NopCloser(bytes.NewBuffer(b))
    r.ContentLength = int64(len(b))
    r.Header.Set("Content-Type", "application/json")

    w := httptest.NewRecorder()
    beego.BeeApp.Handlers.ServeHTTP(w, r)
```

1、controllers中的使用this.Ctx.Input.RequestBody取不到整个POST的值，但this.Ctx.Input.Body()却可以取到。
2、models包中如果有使用beego.AppConfig.String()的这样获取配置值，会报错如下：
2013/12/30 22:08:42 [C] Handler crashed with error runtime error: invalid memory address or nil pointer dereference

**Comment by toplinuxsir** [comment]
No fixed! In the latest version ,

**Comment by sunwenli** [comment]
> No fixed! In the latest version ,

yes , i also see this problem.

```
panic: not implement in the fakeConfigContainer
```
