### ISSUE TITLE
Module latest found, but does not contain package beego/server/web

### ISSUE THREAD

**Issue by thitami** [beego/beego#4308]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
 Go version : go1.15.4
 Bee version: v1.12.0
2. What operating system and processor architecture are you using (`go env`)?

```GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/theo/Library/Caches/go-build"
GOENV="/Users/theo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/theo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/theo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zl/4vn0pm8x4lz1h2bm6y5kkdnm0000gn/T/go-build854159209=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?

I created a new installation of Beego using the `bee api my-api` command and then I add this code into `controllers/object.go`:

```
package controllers

import (
	"my-app/models"
	"encoding/json"

	beego "github.com/astaxie/beego/server/web"
)

// Operations about object
type ObjectController struct {
	beego.Controller
}
```

4. What did you expect to see?
I am expecting to see the messages `Built successfully` and `app is running`

5. What did you see instead?
```
2020/11/11 15:33:47 INFO     ▶ 0002 Initializing watcher...
go: finding module for package github.com/astaxie/beego/server/web
controllers/object.go:7:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package github.com/astaxie/beego/server/web
2020/11/11 15:33:49 ERROR    ▶ 0003 Failed to build the application: go: finding module for package github.com/astaxie/beego/server/web
controllers/object.go:7:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package github.com/astaxie/beego/server/web
```

**Comment by ignitum** [comment]
Same issue here. Hope it gets fixed ASAP

**Comment by flycash** [comment]
`beego/server/web` is beego v2.0's package. Please try `go get -u github.com/astaxie/beego` or `go get github.com/astaxie/beego@v2.0.0-beta`

**Comment by ignitum** [comment]
> `beego/server/web` is beego v2.0's package. Please try `go get -u github.com/astaxie/beego` or `go get github.com/astaxie/beego@v2.0.0-beta`

Tried that so many times but go get always install beego 1.12.3 which is not being detected by bee tool. Followed the step by step installation but i always end up seeing same error everytime i run bee

**Comment by flycash** [comment]
Could you share your commands?

**Comment by flycash** [comment]
Here is my command:
```shell
bee api helloapi
cd helloapi
go get -u github.com/astaxie/beego@develop
```

**Comment by ignitum** [comment]
$ go get github.com/astaxie/beego
$ go get -u github.com/astaxie/beego
$ go get github.com/beego/bee
$ go get -u github.com/beego/bee

$ bee version

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.0

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego. If you are using go mod, and you don't install the beego under $GOPATH/src/github.com/astaxie, just ignore this.
├── GoVersion : go1.15.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : C:\Users\USERPC\go
├── GOROOT    : c:\go
├── Compiler  : gc
└── Date      : Thursday, 12 Nov 2020

(Beego is not detected. Dont know why?! But I proceed anyway hopes miracle happens)

$ bee new mrms

2020/11/12 21:47:59 INFO     ▶ 0001 generate new project support go modules.
2020/11/12 21:47:59 INFO     ▶ 0002 Creating application...
        create   C:\Users\MIS\go\src\mrms\go.mod
        create   C:\Users\MIS\go\src\mrms\
        create   C:\Users\MIS\go\src\mrms\conf\
        create   C:\Users\MIS\go\src\mrms\controllers\
        create   C:\Users\MIS\go\src\mrms\models\     
        create   C:\Users\MIS\go\src\mrms\routers\    
        create   C:\Users\MIS\go\src\mrms\tests\      
        create   C:\Users\MIS\go\src\mrms\static\     
        create   C:\Users\MIS\go\src\mrms\static\js\
        create   C:\Users\MIS\go\src\mrms\static\css\
        create   C:\Users\MIS\go\src\mrms\static\img\
        create   C:\Users\MIS\go\src\mrms\views\
        create   C:\Users\MIS\go\src\mrms\conf\app.conf
        create   C:\Users\MIS\go\src\mrms\controllers\default.go
        create   C:\Users\MIS\go\src\mrms\views\index.tpl
        create   C:\Users\MIS\go\src\mrms\routers\router.go
        create   C:\Users\MIS\go\src\mrms\tests\default_test.go
        create   C:\Users\MIS\go\src\mrms\main.go
2020/11/12 21:47:59 SUCCESS  ▶ 0003 New application successfully created!


$ bee run
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.0
2020/11/12 21:54:57 INFO     ▶ 0001 Using 'mrms' as 'appname'
2020/11/12 21:54:57 INFO     ▶ 0002 Initializing watcher...
go: finding module for package github.com/astaxie/beego/server/web
main.go:5:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package github.com/astaxie/beego/server/web
2020/11/12 21:54:58 ERROR    ▶ 0003 Failed to build the application: go: finding module for package github.com/astaxie/beego/server/web
main.go:5:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package github.com/astaxie/beego/server/web     


Been used Beego in my previous small project and i loved it. So many features compared to other golang fw. Thanks in advance for your assistance.

**Comment by ignitum** [comment]
> Here is my command:
> 
> ```shell
> bee api helloapi
> cd helloapi
> go get -u github.com/astaxie/beego@develop
> ```

Will try. Hope this is the answer. Thanks man

**Comment by thitami** [comment]
@ignitum Does `bee api helloapi` or `bee new helloapi` work for you ?

**Comment by flycash** [comment]
The structure is different. From my understanding, `bee api` creates RESTful server and `bee new` create a general web server. In fact, I think you could use any of them.

And you are using beego 2.0.0-beta, please check https://github.com/beego/beego-example for more examples.

**Comment by flycash** [comment]
> The structure is different. From my understanding, `bee api` creates RESTful server and `bee new` create a general web server. In fact, I think you could use any of them.
> 
> And you are using beego 2.0.0-beta, please check https://github.com/beego/beego-example for more examples.

I believe that 
```
cd helloapi
go get -u github.com/astaxie/beego@develop
```
works.

And if you guys don't want to try with v2.0.0,
run
```
go get github.com/beego/bee@1.12.3
bee api helloapi
```

**Comment by ignitum** [comment]
It works now!! Thanks man. Tried go get -u github.com/astaxie/beego@develop after bee new, run and IT WORKS!! Been wasting several days just missing @develop at the of go get -u

The classic beego i know is, simply installing the package, then the bee tool, bee new, bee run and voila it will work.

But anyway thanks for the help. Didn't find that @develop in the docu though

**Comment by thitami** [comment]
It did work for me with `go get github.com/beego/bee@v1.12.3` but not `v2.0.0` or `develop`. 

Thanks for your continuous assistance with this one @flycash .

**Comment by ignitum** [comment]
Does updating the package at the beginning just after installing it contributes on the issue?

$ go get github.com/astaxie/beego
$ go get -u github.com/astaxie/beego
$ go get github.com/beego/bee
$ go get -u github.com/beego/bee

**Comment by thitami** [comment]
No, unfortunately. @ignitum .

**Comment by flycash** [comment]
we have two totally different beego. v1.x and v2.x(now 2.0.0-beta released)
1. bee with version 1.x are compatible with beego 1.x. The latest stable version is bee@v1.12.3 and beego@v1.12.3
2. If you are using the newest bee(NOT STABLE VERSION) and the newest beego (NOT STABLE VERSION), they are beta version. and we will release v2.0.0 next month.

So when got a similar error, just check the version of bee and beego. 
If you want to use v1.x
using
```
go get github.com/beego/bee@v1.12.3
bee xxxx
..
cd your-project
go get github.com/astaxie/beego@v1.12.3
```
If you want to try beego 2.0.0-beta
```
go get -u github.com/beego/bee // install the last commit 
bee xxx
...
go get -u github.com/astaxie/beego@develop
```

**Comment by flycash** [comment]
I will keep this issue open and if someone got errors, show me the error info and the beego's version( Or beego's structure).

**Comment by ignitum** [comment]
Tried your suggestion

$ go get github.com/beego/bee@v1.12.3
go: cannot use path@version syntax in GOPATH mode

What does this mean? Thanks!

**Comment by flycash** [comment]
`GOPATH` mode.
You need to use go mod mode. 
Please try
```
export GO111MODULE="on"
```

**Comment by ignitum** [comment]
One last concern, everything works fine until i noticed that when i hover to beego.Controller, it says that `field Controller invalid type` and there is no suggestion everytime I access the 'c' variable inside the controller function. How to reference the beego v1.12.3 in $GOPATH/pkg/mod? I think that is the problem.

**Comment by flycash** [comment]
> One last concern, everything works fine until i noticed that when i hover to beego.Controller, it says that `field Controller invalid type` and there is no suggestion everytime I access the 'c' variable inside the controller function. How to reference the beego v1.12.3 in $GOPATH/pkg/mod? I think that is the problem.

Sorry, I don't understand what you mean. 

Could you share the code to me?

**Comment by coolfranksun** [comment]
我使用上面的解决办法解决了运行问题，但是在使用orm包的时候，又出现了这个问题
github.com/astaxie/beego/orm: package provided by github.com/astaxie/beego at latest version v1.12.3 but not at required version v1.12.4-0.20201114080429-05d8e293f7f3
ERROR    ▶ 0004 Failed to build the application: go: finding module for package github.com/astaxie/beego/orm

**Comment by shwanliu** [comment]
> Here is my command:
> 
> ```shell
> bee api helloapi
> cd helloapi
> go get -u github.com/astaxie/beego@develop
> ```

it's work for me

**Comment by flycash** [comment]
> 我使用上面的解决办法解决了运行问题，但是在使用orm包的时候，又出现了这个问题
> github.com/astaxie/beego/orm: package provided by github.com/astaxie/beego at latest version v1.12.3 but not at required version v1.12.4-0.20201114080429-05d8e293f7f3
> ERROR ▶ 0004 Failed to build the application: go: finding module for package github.com/astaxie/beego/orm

如果你一直使用v1.x的版本，就直接在go.mod文件里面指定使用v1.12.3 版本

**Comment by thitami** [comment]
Can we keep the communication in english please? That way everyone will be capable of following the topic.

**Comment by ismayilov1995** [comment]
I tried every line but still notworking, two day I working on.
whe switch GO111MOD=on I can download:
go get github.com/beego/beego/v2 and with -u
go get github.com/beego/bee/v2 and with -u
but when I add import line: **import "github.com/beego/beego/v2/server/web"**
can't saw v2 inside beego and bee folder becouse never created. 
when go111mod=off then got error:
```
cannot find package "github.com/beego/beego/v2" in any of:
        c:\go\src\github.com\beego\beego\v2 (from $GOROOT)
        E:\Site\go\src\github.com\beego\beego\v2 (from $GOPATH)
```
and when try bee version:
`Beego is not installed. Please do consider installing it first
`
I have fresh install go and gopath. Just want to use **ONLY latest Beego**

**Comment by flycash** [comment]
@ismayilov1995 
try
```go
go get github.com/beego/beego/v2@v2.0.1
go get github.com/beego/bee/v2@v2.0.2
```

**Comment by ismayilov1995** [comment]
> @ismayilov1995
> try
> 
> ```go
> go get github.com/beego/beego/v2@v2.0.1
> go get github.com/beego/bee/v2@v2.0.2
> ```

I tried that:
`go: cannot use path@version syntax in GOPATH mode`
if set GO111MOD=on
downloaded successfully but stil not create directory v2/and child...

When run bee version:
`Beego     : Beego is not installed. Please do consider installing it first:` - got this message.

but can use bee new blablaproject then can run project and build. only this way works.

**Comment by flycash** [comment]
> > @ismayilov1995
> > try
> > ```go
> > go get github.com/beego/beego/v2@v2.0.1
> > go get github.com/beego/bee/v2@v2.0.2
> > ```
> 
> I tried that:
> `go: cannot use path@version syntax in GOPATH mode`
> if set GO111MOD=on
> downloaded successfully but stil not create directory v2/and child...
> 
> When run bee version:
> `Beego : Beego is not installed. Please do consider installing it first:` - got this message.
> 
> but can use bee new blablaproject then can run project and build. only this way works.

Just ignore that message. Bee look up Beego based on GOPATH. In fact, it read source file under GOPATH/src to parse the version info. I think the feature checking beego version should be removed because if users use GOMOD, we don't know how to get the Beego version information.

And, those commands work well on my computer:
```shell
mkdir hello
cd hello
go mod init hello
go get github.com/beego/beego/v2@v2.0.1
```

**Comment by guwang139** [comment]
go env -w GO111MODULE=on

$ go get -u github.com/beego/beego/v2
$ go get -u github.com/beego/bee/v2
