### ISSUE TITLE
Array type for a column in model related to Postgres DB

### ISSUE THREAD

**Issue by shahalpk** [beego/beego#431]
Although Postgresql supports Array type for columns, beego orm doesn't support it currently. This would be a very nice addition to the postgresql driver.

Currently beego throws error if an array is mentioned as the type for a column in model definition (Unless a relationship exists for the column). This doesn't allow developers to write custom sql script for CRUD operation. It would be nice if the check is disregarded for Postgres driver.

**Comment by NDevox** [comment]
:+1: To this.

Has there been any further discussion in the last 3 years?

We frequently use Arrays in pq at work and would love to use it with this framework.

**Comment by RevProg** [comment]
Same issue. Any updates?

**Comment by AndriiDidkivsky** [comment]
Same issue.

**Comment by prslash** [comment]
Same issue

**Comment by mytc** [comment]
same issue

**Comment by Bulusideng** [comment]
Any update on this?

**Comment by AvoncourtPartners** [comment]
Did someone make fork and implement it?

**Comment by xuyao91** [comment]
Same issue.

**Comment by mohammad-vito** [comment]
same here
