### ISSUE TITLE
Appending Custom String to Query Seter Query

### ISSUE THREAD

**Issue by gnanakeethan** [beego/beego#4317]
Currently the Query Seter implementation is working as expected, however, I would like to suggest a slight improvement on the final query output. 

Cockroach DB, a Postgres wire-protocol compatible DB works excellent using the lib/pq supports an additional constraint of "AS OF SYSTEM TIME <TIMESTAMP / INTERVAL" as documented here. https://www.cockroachlabs.com/docs/stable/as-of-system-time.html
This feature improves performance of queries spanning entire tables on cockroachdb. 

If it would be possible to arbitrarily inject a string to the very last of the query-seter's output would enable to use the functionality. Or even specifically inject the corresponding timestamp / interval. 

I am ready to contribute to the relevant change, but I am unsure where I should contribute as it has been quite sometime I last contributed, and most look changed. 

Thank you.

**Comment by gnanakeethan** [comment]
@flycash is this possible to achieve? I can clearly see with my database, the performance improvement is pretty good?

**Comment by gnanakeethan** [comment]
@flycash I have found the edit location and made the relevant change. Can this feature be available in v1.12 series? 

I can see develop branch has diverged in directory structure from v1. Kindly let me know how I should proceed. 

Thanks,
Keethan

**Comment by flycash** [comment]
> @flycash I have found the edit location and made the relevant change. Can this feature be available in v1.12 series?
> 
> I can see develop branch has diverged in directory structure from v1. Kindly let me know how I should proceed.
> 
> Thanks,
> Keethan

You could make a PR to branch develop-1.x (checkout your feature from this branch too). And I will release it in Jan 2021 because we just released v1.12.13.

I checked the `QuerySetter` interface, I think is not suitable to add such a method to it. 

So, could you give more details about your solution?

**Comment by flycash** [comment]
And, sorry for the late reply because I was so busy these days.

**Comment by gnanakeethan** [comment]
I have checked the mechanism of the "FOR UPDATE" implementation, which just appends the string to the last based on a local boolean value inside the queryseter. Hence replicating that for the implementation, adding a method which can set the "AS OF SYSTEM TIME"  to any other value than "nil". It will allow us to compare the string to inject. 

Can this be implemented into a specific driver if possible ? Coz this is much specific to CockroachDB.

**Comment by flycash** [comment]
> Can this be implemented into a specific driver if possible ? Coz this is much specific to CockroachDB.

Yes, that would be fine. We don't have any CockroachDB-specific implementation. You could do it!

**Comment by gnanakeethan** [comment]
Okay great. I will look into this. I will comeback with a PR.
