### ISSUE TITLE
fail to generate routers/commentsRouter_xxx.go file when the project outside of $GOPATH/src

### ISSUE THREAD

**Issue by zhangjun03402** [beego/beego#4330]
I  use command  `bee api test` to generate a default project,  and then use `bee run`,  it can not generate commentsRouter_xxx.go under routers folder. 

But when i did this under $GOPATH/src, it worked

beego 1.12.3, the lastest one

**Comment by yrh79** [comment]
If I am understaing it correctly, placing the source code tree in something like ~/go/src/<github.com>/<user>/project_name is a formal way to plan the project folder. Then yes, I see the same bug in my tests. Please beego team fix it.

**Comment by flycash** [comment]
> If I am understaing it correctly, placing the source code tree in something like ~/go/src/<github.com>/<user>/<project_name> is a formal way to plan the project folder. Then yes, I see the same bug in my tests. Please beego team fix it.

You are correct. We fixed this problem in v2.x

**Comment by davidPalechor** [comment]
I'm having this issue using Beego 2.0.2 and `golang 1.18` i'm placing my project under $GOPATH/src but still this file is not being generated when I run the project with `bee run`

**Comment by yrh79** [comment]
> I'm having this issue using Beego 2.0.2 and `golang 1.18` i'm placing my project under $GOPATH/src but still this file is not being generated when I run the project with `bee run`

yea, same issue happens under 2.0.2. in Linux, it works (even out side of $GOPATH with bee/beego 2.0.2 installed), but when I use Mac, it doesn't work.

**Comment by yrh79** [comment]
I git clone the latest development version of bee tool (https://github.com/beego/bee.git) and built it (go build), then by using the 'bee generate routers' command I successfully generate the commentsRouter.go file. 这问题出了这么久，一而再再而三反复出现，就没有人管一下的吗？

**Comment by yrh79** [comment]
> I'm having this issue using Beego 2.0.2 and `golang 1.18` i'm placing my project under $GOPATH/src but still this file is not being generated when I run the project with `bee run`

mee too

**Comment by yrh79** [comment]
> I'm having this issue using Beego 2.0.2 and `golang 1.18` i'm placing my project under $GOPATH/src but still this file is not being generated when I run the project with `bee run`

beego v2.0.1 should work fine. it seems it is also depending on the beego version, not only the bee version.

**Comment by maxproc** [comment]
> > I'm having this issue using Beego 2.0.2 and `golang 1.18` i'm placing my project under $GOPATH/src but still this file is not being generated when I run the project with `bee run`
> 
> beego v2.0.1 should work fine. it seems it is also depending on the beego version, not only the bee version.

me too,  but  I read source code of beego v2 under beego/beego/v2/server/web/router.go{func (p *ControllerRegister) Include(cList ...ControllerInterface)}, I find that it lost function that  generate commentsRouter_xxx.go under routers folder

**Comment by Laurel-rao** [comment]
beego v2.0.4 still have this bug, must put in GOPATH/src/github.com
