### ISSUE TITLE
How can I use beego without ‘go mod’

### ISSUE THREAD

**Issue by joy-yjl** [beego/beego#4336]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
GoVersion : go1.15.6
BeeVersion：v2.0.0

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04

3. What did you do?

go get github.com/astaxie/beego
go build hello.go

code：
package main

import "github.com/astaxie/beego"

func main() {
    beego.Run()
}

4. What did you expect to see?
build success

5. What did you see instead?
./hello.go:7:5: undefined: beego.Run

How can I use beego without ‘go mod’

**Comment by flycash** [comment]
You are using Beego v2.x, please check https://github.com/beego/beedoc to learn how to use Beego v2.x.
