### ISSUE TITLE
xsrf一直过不去

### ISSUE THREAD

**Issue by eworthcms** [beego/beego#4337]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
goversion:go1.13.5
beego:v1.12.3

2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/smiler/Library/Caches/go-build"
GOENV="/Users/smiler/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/smiler/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/smiler/Learning/go/beeblog/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x1/lk8z1f6d6w78brbx6n96_5vh0000gn/T/go-build504047589=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
func (this *RegisterController) Get() {
	this.Data["xsrfdata"]=template.HTML(this.XSRFFormHTML())
	this.TplName = "user/register.html"
}
```
```
<form class="ui large form" method="post" action="/register">
{{ .xsrfdata }}
...省略
<input type="submit" value="Post">
</form>
```

4. What did you expect to see?
出现问题，一直提示 expected XSRF not found，期望通过。不明白是啥问题，按照文档来的。

5. What did you see instead?
expected XSRF not found
![](https://s.i9u.cc/markdown/011724.png)

**Comment by eworthcms** [comment]
我发现每次刷新 `<input type="hidden" name="_xsrf" value="vvJeOXRx0R5z3VyGLV4AhERIje4eRg8l" />` 这里的value值就会变，请问是什么原因呢？

**Comment by flycash** [comment]
![image](https://user-images.githubusercontent.com/9923838/101585544-ede99100-3a1a-11eb-9536-8bcff8824d0b.png)
你在这个方法里面打断点，看看从context里面拿到的token和从请求里面拿到的token，各自是什么。

这个错误是以为这里不匹配。我猜测可能是前端没有返回。

**Comment by eworthcms** [comment]
![](https://s.i9u.cc/markdown/062657.png)
确实是不一样的

**Comment by eworthcms** [comment]
出现问题的版本是：beego v1.12.3
我改成：beego v1.12.2，这个问题就没有了，帮忙查看一下是咋回事。

**Comment by flycash** [comment]
v1.12.3里面，有人报上来一个安全问题，是xsrf放在token里面存在暴露被人篡改的风险。后来我们加了http only和secure两个flag。
https://github.com/astaxie/beego/pull/4126/files

你可以看看这个PR。

我考虑一下怎么解决问题。

**Comment by flycash** [comment]
你可以说一下你拿到的两个token里面，是不是有一个是空字符串？

**Comment by eworthcms** [comment]
是的，空的，又重新生成了一个，导致不一样了

**Comment by flycash** [comment]
> 是的，空的，又重新生成了一个，导致不一样了

我没理解错的话，应该是加了这两个flag之后无法从参数或者body里面获得了，只能从cookie里面获得。

原有的文档应该不适用了，我更新一下，然后提供一个例子出来。

**Comment by eworthcms** [comment]
好的，非常感谢

**Comment by flycash** [comment]
我确认过，你用form的例子，只需要启用https协议就可以了。因为加了`secure`选项，所以`http`协议不会带上cookie。

不过我觉得这个用户体验很不好，我会在下一个版本里面将`secure`和`httponly`都改为配置项。

感谢反馈。

**Comment by eworthcms** [comment]
谢谢，期待更新

**Comment by amirhs712** [comment]
Guys, please use English.

**Comment by ShenTong-2050** [comment]
> 我确认过，你用form的例子，只需要启用https协议就可以了。因为加了`secure`选项，所以`http`协议不会带上cookie。
> 
> 不过我觉得这个用户体验很不好，我会在下一个版本里面将`secure`和`httponly`都改为配置项。
> 
> 感谢反馈。

你好，关于beego2.X开启xsrf验证的post请求报错：expected XSRF not found我按照上方步骤分别打印出接收到的_xsrf与储存的token请问这是什么原因，

**Comment by ShenTong-2050** [comment]
> 我确认过，你用form的例子，只需要启用https协议就可以了。因为加了`secure`选项，所以`http`协议不会带上cookie。
> 
> 不过我觉得这个用户体验很不好，我会在下一个版本里面将`secure`和`httponly`都改为配置项。
> 
> 感谢反馈。

你好，关于beego2.X开启xsrf验证的post请求报错：expected XSRF not found      我按照上方步骤分别打印出接收到的_xsrf与储存的token并进行对比确实不一致，请问这是什么原因。。

**Comment by ShenTong-2050** [comment]
> 我确认过，你用form的例子，只需要启用https协议就可以了。因为加了`secure`选项，所以`http`协议不会带上cookie。
> 
> 不过我觉得这个用户体验很不好，我会在下一个版本里面将`secure`和`httponly`都改为配置项。
> 
> 感谢反馈。

你好，关于beego2.X开启xsrf验证的post请求报错：expected XSRF not found 我按照上方步骤分别打印出接收到的_xsrf与储存的token并进行对比确实不一致，请问这是什么原因。。（注：我测试环境用的https）

**Comment by flycash** [comment]
Please provide a demo. I can't reproduce this issue.

**Comment by ShenTong-2050** [comment]
> Please provide a demo. I can't reproduce this issue.

这是一个测试站点，https://www.wsst.vip/staticblock/asdfasd，我的逻辑是这样：在 beego 全局配置文件 app.conf 中开启 xsrf 验证并设置过期时间为 60秒（但 hidden 域中的 value 值似乎一直不变），通过 post 提交至一个接口提示：expected XSRF not found，猜测是 beego 框架也需要开启 https 配置，但又不知道beego中https配置的端口与nginx的ssl配置是什么关系。。。。

**Comment by ShenTong-2050** [comment]
> Please provide a demo. I can't reproduce this issue.

这是一个测试站点：https://github.com/beego/beego/issues/4337#issuecomment-835316615

**Comment by ShenTong-2050** [comment]
> Please provide a demo. I can't reproduce this issue.

这是一个测试站点：https://www.wsst.vip/staticblock/asdfasd

这个页面的表单一直无法通过beego的 xsrf 验证，感觉是框架没有开启 https 的原因，但又不知道 beego框架的 https 端口、 nginx 监听的https端口是怎样一个关系

**Comment by flycash** [comment]
> > Please provide a demo. I can't reproduce this issue.
> 
> 这是一个测试站点：https://www.wsst.vip/staticblock/asdfasd
> 
> 这个页面的表单一直无法通过beego的 xsrf 验证，感觉是框架没有开启 https 的原因，但又不知道 beego框架的 https 端口、 nginx 监听的https端口是怎样一个关系

这方面我没有研究。不过你可以把beego看成一个普通的web应用。
