### ISSUE TITLE
panic: http: multiple registrations for /metrics

### ISSUE THREAD

**Issue by chenyangguang** [beego/beego#4338]
Please answer these questions before submitting your issue. Thanks!

beego 1.13.2

GOOS="darwin"
GOARCH="amd64"

bee run 
and write a go func(){
// open a 9090 port for health_check     
} ()

 localhost:9090/health_check 
 localhost:9090/metrics

unit test for post router 

Then is fail

**Comment by flycash** [comment]
You do not use the Beego admin service? 
Please try to set `EnableAdmin = true`. 

![image](https://user-images.githubusercontent.com/9923838/101585815-82ec8a00-3a1b-11eb-8590-3504bc817d88.png)

**Comment by chenyangguang** [comment]
EnableAdmin is difficult to use. And i need my custom difinition prometheus struct and healthy-check

**Comment by flycash** [comment]
If you do not use Beego's admin, it won't start admin web service. 

Could you check this code to confirm that Beego start the admin service.
```go
func registerAdmin() error {
	if BConfig.Listen.EnableAdmin {

		c := &adminController{
			servers: make([]*HttpServer, 0, 2),
		}

		// copy config to avoid conflict
		adminCfg := *BConfig
		beeAdminApp = &adminApp{
			HttpServer: NewHttpServerWithCfg(&adminCfg),
		}
		// keep in mind that all data should be html escaped to avoid XSS attack
		beeAdminApp.Router("/", c, "get:AdminIndex")
		beeAdminApp.Router("/qps", c, "get:QpsIndex")
		beeAdminApp.Router("/prof", c, "get:ProfIndex")
		beeAdminApp.Router("/healthcheck", c, "get:Healthcheck")
		beeAdminApp.Router("/task", c, "get:TaskStatus")
		beeAdminApp.Router("/listconf", c, "get:ListConf")
		beeAdminApp.Router("/metrics", c, "get:PrometheusMetrics")

		go beeAdminApp.Run()
	}
	return nil
}
```

My suggestion is that you could listen to different port and use other path to avoid this issue.
