### ISSUE TITLE
1.2版本下不到

### ISSUE THREAD

**Issue by Key-CN** [beego/beego#4342]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.12.4

2. What operating system and processor architecture are you using (`go env`)?
mac go version go1.15.6 darwin/amd64
GOPROXY="https://proxy.golang.org,direct"
go env -w GOPROXY=https://goproxy.io,direct
还有七牛云的也试了

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
更新不到1.2

5. What did you see instead?
go get -u github.com/astaxie/beego@develop
go: downloading github.com/astaxie/beego v1.12.4-0.20201204012239-b6d6571e9910
用官方的和换了几个国内的，develop始终都是1.12.4，更新不到1.2，是1.2没发吗？

**Comment by flycash** [comment]
1.2 是很古老的版本。如果你是指v2.0.0，那么的确，现在还是beta版本，你可以去看release。近期就要发布v2.0.0了，只剩下一点点文档工作了。

**Comment by flycash** [comment]
1.12.4-xxxxxxx实际上就是v2.0.0-beta

**Comment by Key-CN** [comment]
是的，我是想说2.0版本
今天看到发布了，还是更新不到么，beego可以更新到2.0.1，bee还是只有v1.12.3
```
 go get -u github.com/beego/bee
go: github.com/beego/bee upgrade => v1.12.3
go: github.com/lib/pq upgrade => v1.9.0
go: github.com/hashicorp/golang-lru upgrade => v0.5.4
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: github.com/pelletier/go-toml upgrade => v1.8.1
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: github.com/astaxie/beego upgrade => v1.12.3
go: github.com/mitchellh/mapstructure upgrade => v1.4.0
go: golang.org/x/arch upgrade => v0.0.0-20201207233722-1e68675e650f
go: github.com/flosch/pongo2 upgrade => v0.0.0-20200913210552-0d938eb266f3
go: gopkg.in/ini.v1 upgrade => v1.62.0
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: golang.org/x/text upgrade => v0.3.4
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: go.starlark.net upgrade => v0.0.0-20201210151846-e81fc95f7bd5
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/spf13/pflag upgrade => v1.0.5
go: golang.org/x/sys upgrade => v0.0.0-20201214210602-f9fddec55a1e
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: github.com/peterh/liner upgrade => v1.2.1
go: github.com/spf13/viper upgrade => v1.7.1
go: github.com/spf13/afero upgrade => v1.5.1
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/magiconair/properties upgrade => v1.8.4
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/mattn/go-runewidth upgrade => v0.0.9
```

**Comment by flycash** [comment]
bee 还没发布 v2...你可以用更新到最新的。
因为go mod的限制，我们要先把bee的module name改成xxx/bee/v2，这个不可怕。可怕的是我们好多文档里面写了xx/bee，得等我改完……
