### ISSUE TITLE
注解路由直接go build时不生效

### ISSUE THREAD

**Issue by hhstu** [beego/beego#4362]

**Comment by flycash** [comment]
注解路由是在启动的时候生成的，打包其实不会触发。我们考虑提供一个新的命令，bee xxx 来生成路由。

**Comment by flycash** [comment]
要不试试bee run.

**Comment by hhstu** [comment]
不太想用工具哈

**Comment by nanjishidu** [comment]
2.0  bee run 生成的注解路由后，启动访问提示路由不存在。需要修改引入方法？

**Comment by flycash** [comment]
run只是生成了路由。你依旧需要使用Include方法引入进去。参考beego.me里面路由的章节。
