### ISSUE TITLE
BUG: AddNamespace in adapter module doesn't work

### ISSUE THREAD

**Issue by imfe888** [beego/beego#4363]
1.2升级到2.0后，使用bee工具升级，原路由当中的使用beego.AddNamespace ，beego.NSInclude,beego.NSNamespace添加的路由全部失效，访问接口404，需要将beego.改成web.才行。希望官方修复一下这个bug

Translate: running bee command to upgrade beego to v2.0.1, we found that beego.AddNamespace, beego.NSInclude, beego.NSNamespace don't work.

**Comment by flycash** [comment]
=。=当初前天发2.0的时候改了module name之后，我Bee工具应该还没完全更新，我来试试。

**Comment by guchengwuyue** [comment]
为啥还是404

**Comment by nathubs** [comment]
需要将beego.改成web.才行?改哪里的beego.全场都是beego.!!!

**Comment by lynzhen** [comment]
> 1.2升级到2.0后，使用bee工具升级，原路由当中的使用beego.AddNamespace ，beego.NSInclude,beego.NSNamespace添加的路由全部失效，访问接口404，需要将beego.改成web.才行。希望官方修复一下这个bug
> 
> Translate: running bee command to upgrade beego to v2.0.1, we found that beego.AddNamespace, beego.NSInclude, beego.NSNamespace don't work.



> 1.2升级到2.0后，使用bee工具升级，原路由当中的使用beego.AddNamespace ，beego.NSInclude,beego.NSNamespace添加的路由全部失效，访问接口404，需要将beego.改成web.才行。希望官方修复一下这个bug
> 
> Translate: running bee command to upgrade beego to v2.0.1, we found that beego.AddNamespace, beego.NSInclude, beego.NSNamespace don't work.

升级到2.0，router.go文件中的 beego 改成 web 也是不行的，访问还是404

**Comment by hanson-wen** [comment]
> 

+1，用了别名可以不用改，但还是404
