### ISSUE TITLE
Cannot start the server when using runmode=dev if application missing controllers or router directory

### ISSUE THREAD

**Issue by Golong-me** [beego/beego#4365]
当指定 runmode ="dev" 的时候.项目启动后,不显示打印的日志,一片空白
并且访问对应的端口也访问不了(没有监听到端口)
只有runmode ="dev"会这样,="prod" or  ="haha" 都没有问题.
![image](https://user-images.githubusercontent.com/72813193/102229211-6b157a00-3ee3-11eb-9384-48cc8eb79fd5.png)

```
runmode ="dev"  #只有写dev的时候有问题

[dev]
httpport = 8081
[hhh]
httpport = 8088
[test]
httpport = 8888

```

When using runmode=dev, I can not start the server and app output nothing.

But using prod or any except dev works well.

I found that starting application failed due to missing controllers and routers directory

**Comment by flycash** [comment]
我在mac环境下测试没有问题。求发一下你的测试代码，测试环境。
我直接用 `bee new` 创建了一个新项目，而后修改原本的配置文件：
```ini
appname = t4365
httpport = 8080
runmode = "dev"

[dev]
httpport=8081
```

输出日志：

![image](https://user-images.githubusercontent.com/9923838/102231713-3cba8d80-3f29-11eb-9728-b9c51459bdfa.png)

有点怀疑是端口竞争的问题，不过端口竞争应该直接启动失败才对。

**Comment by Golong-me** [comment]
@flycash 经过了再次的测试.我发现,

在指定了dev后
```
appname = beego-h
httpport = 8080
runmode = "dev"

[dev]
appname = hhhh
httpport = 9001
[myprod]
httpport = 9002
[mytest]
httpport = 9003
```

必须要要有这2个目录,controllers和routers,名称必须是这2个固定(修改后会报错)
如果这2个文件其中一个不存在,则会报错,如果2个都不存在,则会出现我最开始提到的情况
runmode = "xxxx" 都不会出现这种情况.只有当 runmode = "dev" 这3个字符的时候,才会出现这种情况
![image](https://user-images.githubusercontent.com/72813193/102250123-0f56eb00-3efb-11eb-95e6-06c17bcf599a.png)


这也能解释为什么你的用bee生成的项目是可以的.

**Comment by flycash** [comment]
这种限制……很神奇，我来看看
