### ISSUE TITLE
controllers/default.go:8:2: undefined: beego.Controller

### ISSUE THREAD

**Issue by einsli** [beego/beego#4366]
I just use the following command  

```shell
bee new firstproj 
```
to create my projects, and when I just run the server,  an error occured

```shell
controllers/default.go:8:2: undefined: beego.Controller
```

**Comment by flycash** [comment]
Please check the version of beego. 
I think the bee version you use is v1.x and the version of beego is v2.x.

Or you can try:
```
go get -u -f github.com/beego/bee
bee new firstapp
```
