### ISSUE TITLE
Beego v2.0.1 Cooke SameSite feature not found...

### ISSUE THREAD

**Issue by osmanmakal** [beego/beego#4367]
Hello,

Beego v2.0.1 Thanks for the version.

While starting to use the version I noticed that there are no sameSite cookies. I was surprised that this feature was available in the old version but not in the newer version.

Has the usage pattern changed?

Am I wrong or is the feature forgotten?

The sameSite cookie in Session is a vital feature for e-commerce sites.

@flycash  @astaxie

**Comment by flycash** [comment]
It looks like I only support v1.x but I copy the release note. So sorry, I will support it next version.
