### ISSUE TITLE
Methods GetAllXxxAPI generated from bee api got error

### ISSUE THREAD

**Issue by Key-CN** [beego/beego#4368]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
GoVersion : go1.15.6
beego: 1.12.3

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
新创建的API，给struct加了json

4. What did you expect to see?
GetAllXXX函数fields可以使用json tag定义的命名

5. What did you see instead?
只能使用struct中的字段名，且返回也是struct中的大写开头的字段名，非json tag中的字段名
用json字段名请求，报错信息如下
```
2020/12/16 17:31:53.368 [D] [server.go:2843]  |            ::1| 200 |     61.615µs|   match| GET      /v1/invoice/   r:/v1/invoice/
[ORM]2020/12/16 17:32:10  -[Queries/default] - [  OK /    db.Query /     5.3ms] - [SELECT T0.`title` FROM `invoice` T0 LIMIT 10]
2020/12/16 17:32:10.357 [C] [panic.go:969]  the request url is  /v1/invoice/
2020/12/16 17:32:10.357 [C] [panic.go:969]  Handler crashed with error reflect: call of reflect.Value.Interface on zero Value
2020/12/16 17:32:10.357 [C] [panic.go:969]  /usr/local/go/src/runtime/panic.go:969
2020/12/16 17:32:10.357 [C] [panic.go:969]  /usr/local/go/src/reflect/value.go:1021
2020/12/16 17:32:10.357 [C] [panic.go:969]  /usr/local/go/src/reflect/value.go:1016
2020/12/16 17:32:10.357 [C] [panic.go:969]  /Users/key/go/src/CompanyCrmBeego/models/invoice.go:129
2020/12/16 17:32:10.357 [C] [panic.go:969]  /Users/key/go/src/CompanyCrmBeego/controllers/invoice.go:122
2020/12/16 17:32:10.357 [C] [panic.go:969]  /Users/key/go/pkg/mod/github.com/astaxie/beego@v1.12.3/controller.go:218
2020/12/16 17:32:10.357 [C] [panic.go:969]  /Users/key/go/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:893
2020/12/16 17:32:10.357 [C] [panic.go:969]  /usr/local/go/src/net/http/server.go:2843
2020/12/16 17:32:10.357 [C] [panic.go:969]  /usr/local/go/src/net/http/server.go:1925
2020/12/16 17:32:10.357 [C] [panic.go:969]  /usr/local/go/src/runtime/asm_amd64.s:1374
2020/12/16 17:32:10.357 [server.go:3093]  [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)
```
![image](https://user-images.githubusercontent.com/23090834/102330604-b81d4d00-3fc4-11eb-847c-4f39b1c46222.png)

**Comment by flycash** [comment]
求提供一下可以复现的简单demo.

**Comment by Key-CN** [comment]
不知道怎么提供可以保证复现，直接打包生成出来的整个项目吧，每个controllers中的GetAll都会出现这个错误
[CompanyCrmBeego.zip](https://github.com/beego/beego/files/5709811/CompanyCrmBeego.zip)

**Comment by Key-CN** [comment]
![image](https://user-images.githubusercontent.com/23090834/102495544-293a2e80-40b1-11eb-9f77-7c0aade5f34c.png)
我猜应该是这段代码通过字段名寻找没有办法通过json字段来吧，只能通过struct字段名
反射拿到的应该只有struct字段名吧，go新人，很多方法和类还不认识，凭经验猜的，还是你确认一下吧

**Comment by flycash** [comment]
我直接启动了你的项目，而后在我的电脑上无法复现这个问题。

我的操作步骤是：
POST: http://localhost:8080/v1/invoice
```json
{
  "title": "MY_NAME",
  "issued_date": "2018-09-22T12:42:31Z",
  "receiving_time": "2018-09-22T12:42:31Z"
}
```
而后：
GET：
```json
http://localhost:8080/v1/invoice
```
我拿到了正确响应。
```json
[
  {
    "id": 1,
    "title": "MY_NAME",
    "code": "",
    "number": 0,
    "check_code": "",
    "sub_total": 0,
    "issued_date": "2018-09-22T00:00:00+08:00",
    "cid": 0,
    "state": 0,
    "quota": "",
    "nature": "",
    "type": "",
    "receiver": "",
    "receiving_time": "2018-09-22T12:42:31+08:00",
    "fill_id": 0,
    "filled_at": 0,
    "created_at": "2020-12-19T14:33:05+08:00",
    "updated_at": "2020-12-19T14:33:05+08:00"
  }
]
```

所以我感觉，是不是我mock的数据不对？你可以试试我这个简单的例子，如果发现它可以运作的话，可能和你的数据有关，你可以把数据脱敏之后给我试试。

**Comment by Key-CN** [comment]
不好意思，这周比较忙，没有及时回复，不是你掉的这些参数
报错的是fields这个参数，你可以试试这样调，我试过，应该不是数据问题，每张表都会报错，只能使用struck字段名才会不报错，用json就会报错，但是实际使用中，调用方肯定是使用json，而不可能知道struck的字段名
/v1/company?fields=name
/v1/invoice?fields=title

**Comment by Key-CN** [comment]
这样调用报错的就是我上次截图的那个行号（FieldByName那段代码），字段名不正确的报错

**Comment by flycash** [comment]
> fields=name

我没看懂你是怎么发起调用的……可以提供一个请求样例么？

**Comment by Key-CN** [comment]
这不是bee api自动生成的代码中的一种调用方式吗？我部署到测试服务器你试试。
[swagger](http://106.75.254.63:8080/swagger/)

![image](https://user-images.githubusercontent.com/23090834/103153965-7adc6a80-47cf-11eb-8441-1cc40b3619dc.png)

* curl
```
curl -X GET "http://106.75.254.63:8080/v1/invoice/?fields=title" -H  "accept: application/json"
```

* Response body 截取一部分
```
<pre>/usr/local/go/src/runtime/panic.go:969
/usr/local/go/src/reflect/value.go:1021
/usr/local/go/src/reflect/value.go:1016
/Users/key/go/src/CompanyCrmBeego/models/invoice.go:129
/Users/key/go/src/CompanyCrmBeego/controllers/invoice.go:122
/Users/key/go/pkg/mod/github.com/astaxie/beego@v1.12.3/controller.go:218
/Users/key/go/pkg/mod/github.com/astaxie/beego@v1.12.3/router.go:893
/usr/local/go/src/net/http/server.go:2843
/usr/local/go/src/net/http/server.go:1925
/usr/local/go/src/runtime/asm_amd64.s:1374
</pre>
```

![image](https://user-images.githubusercontent.com/23090834/103154018-d4449980-47cf-11eb-8107-7e95cc082370.png)

**Comment by Key-CN** [comment]
## 升级到bee beego v2之后依旧存在这个错误
![image](https://user-images.githubusercontent.com/23090834/103154611-7914a600-47d3-11eb-9c83-97af84716ea5.png)

**Comment by flycash** [comment]
我大概明白了。

**Comment by flycash** [comment]
我大概可以确定，按照我们代码的逻辑，在使用这种查询方式的时候，这个字段名字，其实既不是指数据库字段名字，也不是指json tag的设置，而是指你定义的结构体的字段的名字。例如，我查询使用：
```
http://localhost:8080/v1/invoice?fields=ReceivingTime
http://localhost:8080/v1/invoice?fields=Title
```
都是运作良好的。

**Comment by flycash** [comment]
从良好的用户体验上来说，支持使用`title`会更好，所以如果你有兴趣，可以帮我们完成这个优化。
