### ISSUE TITLE
自动化文档类型样例controllers包的类型不生效

### ISSUE THREAD

**Issue by A1311981684** [beego/beego#4376]
package controllers

import (
	beego "github.com/beego/beego/v2/server/web"
	"log"
)

type MainController struct {
	beego.Controller
}

//这是我自己定义的一个controllers包下的返回类型
type CCC struct {
	C int
}

//在这里使用CCC，swagger上显示的是"{}"，但是把CCC移动到models并改为modles.CCC就可以
//@Success 200 {object} CCC
//@router /aaa [post]
func (c *MainController) AAAAA() {
	log.Println("weeeeeeee")
}

**Comment by flycash** [comment]
我们只会扫描models下面的结构体=。=
