### ISSUE TITLE
beego.AppConfig.String Multiple-value return

### ISSUE THREAD

**Issue by Key-CN** [beego/beego#4393]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
GoVersion : go1.15.6

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
今天刚升级的bee和beego测试2.0版本，使用bee api 新创建的项目
使用GOPROXY=https://goproxy.io,direct下载的依赖

4. What did you expect to see?
* v1.12.3
```
func (b *beegoAppConfig) String(key string) string {
	if v := b.innerConfig.String(BConfig.RunMode + "::" + key); v != "" {
		return v
	}
	return b.innerConfig.String(key)
}
```
![image](https://user-images.githubusercontent.com/23090834/103154322-b5470700-47d1-11eb-8d96-8f567821620f.png)

5. What did you see instead?
  这个问题以前在1.12.3之前的版本也出现过，我知道可以处理，只是觉得自动创建的API这样写，应该有一定的道理，不确定哪个版本更正确
* 2.0.1
```
func (b *beegoAppConfig) String(key string) (string, error) {
	if v, err := b.innerConfig.String(BConfig.RunMode + "::" + key); v != "" && err == nil {
		return v, nil
	}
	return b.innerConfig.String(key)
}
```
![image](https://user-images.githubusercontent.com/23090834/103154145-a9a71080-47d0-11eb-900d-a50f0f11f176.png)
![image](https://user-images.githubusercontent.com/23090834/103154336-c4c65000-47d1-11eb-9e97-27c779c7c23f.png)

### 目前处理方案
![image](https://user-images.githubusercontent.com/23090834/103154496-909f5f00-47d2-11eb-84e4-d484d647ae7e.png)

### 用v1的项目fix到2之后，不存在这个问题
![image](https://user-images.githubusercontent.com/23090834/103156230-89338200-47e1-11eb-8f2e-3d5f01bfe1bd.png)

**Comment by Key-CN** [comment]
# 疑问：关于新创建的beeApi和bee fix -t 2的区别，导入的包不一样
* 感觉应该不算issue，我就借这个bee2的issue问一下吧
新创建的controllers包中的类使用的是`beego "github.com/beego/beego/v2/server/web"`
fix上来的包名是`beego "github.com/beego/beego/v2/adapter"`
同样models包下的也是这样
新创建的使用的是`"github.com/beego/beego/v2/client/orm"`
从1fix到2的是`"github.com/beego/beego/v2/adapter/orm"`

请问这两者是有区别吗？

**Comment by flycash** [comment]
有区别的。因为v1.x和v2.x实际上项目结构被调整过，所以我们需要提供一个方便升级的手段。为此我们开发了完整的adapter模块，即适配器模块，用于适配v1.x到v2.x 。所以你看到含有adapter就代表是我们在使用适配器来辅助，而没有的，也就是我们真的v2的API。
我们建议直接使用V2的 API 因为adapter我们会在下一个大版本，例如3.x的时候彻底删除。

**Comment by flycash** [comment]
String()返回的error 使我们这一次特意增加的，因为之前不返回error，会导致部分用户不知道这个配置是没有，还是读取出错了，所以需要返回error。如果希望不处理error，可以考虑使用`DefaultString`。2.0.1 是我们期望的做法。

**Comment by Key-CN** [comment]
> String()返回的error 使我们这一次特意增加的，因为之前不返回error，会导致部分用户不知道这个配置是没有，还是读取出错了，所以需要返回error。如果希望不处理error，可以考虑使用`DefaultString`。2.0.1 是我们期望的做法。

嗯，明白了。怎么处理我知道，这个问题不大，我的意思是，new api出来的不应该是一个报错的程序，至少应该是一个可以直接run的程序。
算提个意见吧

**Comment by flycash** [comment]
谢谢你的建议。
同时我刚才用bee创建了项目，好像都能直接启动成功。不知道你说的，报错的程序是哪一步出错的？
