### ISSUE TITLE
beeV2 pack之后，运行错误

### ISSUE THREAD

**Issue by Key-CN** [beego/beego#4395]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee 2.0.2
beego 2.0.1

2. What operating system and processor architecture are you using (`go env`)?
1.15

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
bee api name -driver=mysql -conn="xxxxxxxxxx"
bee pack -be GOOS=linux
上传
tar 解压
./name 执行报错
```

4. What did you expect to see?
我回退到v1版本测试正常

5. What did you see instead?
![image](https://user-images.githubusercontent.com/23090834/103200595-b8a0d680-4928-11eb-969e-f316bd1799b9.png)

**Comment by jianzhiyao** [comment]
看着像是go的PATH配置问题，执行go env结果麻烦发一下看看

**Comment by jianzhiyao** [comment]
这边把环境变量go的删掉时候，完美复现你描述的问题，可以试试把go执行路径放到环境变量里面试试
![image](https://user-images.githubusercontent.com/6133860/103225753-a09b7800-4965-11eb-8dd7-fc1ac9fb19e3.png)

**Comment by Key-CN** [comment]
> 这边把环境变量go的删掉时候，完美复现你描述的问题，可以试试把go执行路径放到环境变量里面试试
> ![image](https://user-images.githubusercontent.com/6133860/103225753-a09b7800-4965-11eb-8dd7-fc1ac9fb19e3.png)

服务器上本来就没有go环境，我运行的是编译后的可执行文件，go编译之后怎么会需要环境来运行，你试试，你用beegoV1，pack之后是正常的，beegoV2才会报错，而且报错的路径也不对，直接报来我本地的环境路径，编译之后不应该是这样的

**Comment by jianzhiyao** [comment]
> > 这边把环境变量go的删掉时候，完美复现你描述的问题，可以试试把go执行路径放到环境变量里面试试
> 
> 服务器上本来就没有go环境，我运行的是编译后的可执行文件，go编译之后怎么会需要环境来运行，你试试，你用beegoV1，pack之后是正常的，beegoV2才会报错，而且报错的路径也不对，直接报来我本地的环境路径，编译之后不应该是这样的
> `bee pack -be GOOS=linux` 服务器上一直都没有配过go环境

看样子是你的``mode``设置为``dev``了，尝试把``runmode``设置为``prod``

**Comment by jianzhiyao** [comment]
beego用户群有人反馈：最后提出的解决方案能够解决问题
暂时选择关闭issue，有问题可以继续反馈，感谢支持！

**Comment by Key-CN** [comment]
最后提出的解决方案是这个吗？

> 看样子是你的mode设置为dev了，尝试把runmode设置为prod

这在本机打包肯定是dev啊。
runmode写在app.conf中`runmode = ${BeegoRunMode||dev}`
不可能为了打包去改一下吧，而且这个打包的问题在V1版本中是不存在的

**Comment by flycash** [comment]
我的理解是，当你要在服务器部署的时候，要么是测试环境，要么是生产环境，run mode都不应该是dev。dev只指向你本地开发使用。
