### ISSUE TITLE
beego 1.12 升级到 V2.0 启动报错

### ISSUE THREAD

**Issue by wpliang** [beego/beego#4396]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2

├── Beego     : 1.12.0
├── GoVersion : go1.13.4
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /home/work/gopath
├── GOROOT    : /home/work/go
├── Compiler  : gc
└── Date      : Monday, 28 Dec 2020

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
升级到2.0 启动失败了，日志如下：
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2
2020/12/28 17:01:35 INFO     ▶ 0001 Using 'eops-go' as 'appname'
2020/12/28 17:01:35 INFO     ▶ 0002 Initializing watcher...
build git.timevale.cn/zhulei/eops-go: cannot load github.com/beego/beego/v2/adapter/context/param: module github.com/beego/beego/v2@latest found (v2.0.1), but does not contain package github.com/beego/beego/v2/adapter/context/param
2020/12/28 17:01:39 ERROR    ▶ 0003 Failed to build the application: build git.timevale.cn/zhulei/eops-go: cannot load github.com/beego/beego/v2/adapter/context/param: module github.com/beego/beego/v2@latest found (v2.0.1), but does not contain package github.com/beego/beego/v2/adapter/context/param

4. What did you expect to see?

5. What did you see instead?

**Comment by wpliang** [comment]
[root@localhost context]# pwd
/home/work/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.1/adapter/context
[root@localhost context]# ls
acceptencoder.go  context.go  input.go  output.go  renderer.go  response.go
[root@localhost context]# 
在这个目录下没有param这个文件。。。

**Comment by flycash** [comment]
我来看看，最近稍微有点忙，见谅。

**Comment by flycash** [comment]
我特么是个大沙雕了……我之前测试完之后，看到这个param，我就觉得目测没人用，于是又删了-。-

**Comment by Cassuis** [comment]
w我也遇到这个问题了。好难受

**Comment by Cassuis** [comment]
> 我特么是个大沙雕了……我之前测试完之后，看到这个param，我就觉得目测没人用，于是又删了-。-

啥时候能加回来啊 大爷
