### ISSUE TITLE
Propoal: Convenient way to generate mock object

### ISSUE THREAD

**Issue by flycash** [beego/beego#4397]
Now, we focus on writing unit tests easier. 

We are building mock feature on each module. And we need a solution that user could generate mock object easier.

The proposal is that:
```go
type MockSubObject struct {
	SubA bool `mock:"false"`
}

type MockObject struct {
	A string          `mock:"aaaaa"`
	B int             `mock:"12"`
	C []MockSubObject `mock:"length:1;"`
}
```
Using tht tag and reflection, we could provide the API looks like:
```go
mockObj := bean.Mock(&MockObject{})
```
the mockObj is the same as:
```go
mockObj= &MockObject {
    A: "aaaaa",
    B: 12,
    C: []MockSubObject {
    {
        SubA: false
    }
}
}
```

I hope that we could use this API to generate mock response to help users to build mock server.

**Comment by iabetor** [comment]
I can try it
