### ISSUE TITLE
Incorrect message for the default address (empty)

### ISSUE THREAD

**Issue by ilyapisany** [beego/beego#4400]
1. Go version: 1.15.2

2. KUbuntu 20.04.01 LTS

3. Start bego server (readme doc)

4. Expected console log message: `http server Running on http://127.0.0.1:8080`

5. `http server Running on http://:8080` actually

**Comment by changsongl** [comment]
It is not an issue, because "127.0.0.1:8080" means listen on  loopback NIC for 8080 port. It can be  only accessed by itself. ":8080" means listening all NIC, so it can be accessed by others computers. This is just what happen when you leave address empty. ":8080" is equal to "0.0.0.0:8080".

**Comment by ilyapisany** [comment]
> > 1. Go version: 1.15.2
> > 2. KUbuntu 20.04.01 LTS
> > 3. Start bego server (readme doc)
> > 4. Expected console log message: `http server Running on http://127.0.0.1:8080`
> > 5. `http server Running on http://:8080` actually
> 
> It is not an issue, because "127.0.0.1:8080" means listening on loopback NIC for 8080 port. It can be only accessed by itself. ":8080" means listening all NIC, so it can be accessed by others computers. This is just what happen when you leave address empty. ":8080" is same as "0.0.0.0:8080".

But I think that showing a message with a protocol and port but no direct address is wrong

**Comment by changsongl** [comment]
> > > 1. Go version: 1.15.2
> > > 2. KUbuntu 20.04.01 LTS
> > > 3. Start bego server (readme doc)
> > > 4. Expected console log message: `http server Running on http://127.0.0.1:8080`
> > > 5. `http server Running on http://:8080` actually
> > 
> > 
> > It is not an issue, because "127.0.0.1:8080" means listening on loopback NIC for 8080 port. It can be only accessed by itself. ":8080" means listening all NIC, so it can be accessed by others computers. This is just what happen when you leave address empty. ":8080" is same as "0.0.0.0:8080".
> 
> But I think that showing a message with a protocol and port but no direct address is wrong

````golang
// Listen announces on the local network address.
//
// The network must be "tcp", "tcp4", "tcp6", "unix" or "unixpacket".
//
// For TCP networks, if the host in the address parameter is empty or
// a literal unspecified IP address, Listen listens on all available
// unicast and anycast IP addresses of the local system.
// To only use IPv4, use network "tcp4".
// The address can use a host name, but this is not recommended,
// because it will create a listener for at most one of the host's IP
// addresses.
// If the port in the address parameter is empty or "0", as in
// "127.0.0.1:" or "[::1]:0", a port number is automatically chosen.
// The Addr method of Listener can be used to discover the chosen
// port.
//
// See func Dial for a description of the network and address
// parameters.
func Listen(network, address string) (Listener, error) {
	var lc ListenConfig
	return lc.Listen(context.Background(), network, address)
}
````
net/dial.go

This is the code from golang official net package. From the comment, you can see the comment "For TCP networks, if the host in the address parameter is empty or a literal unspecified IP address". Net package is actually implemented by that way. There is one thing I didn't  mention is that ":8080" will listen on both ipv4 and ipv6, but "0.0.0.0:8080" will be only listen ipv4.
