### ISSUE TITLE
ORM中多对多中间表不能自动生成

### ISSUE THREAD

**Issue by xyzgamestudios** [beego/beego#4410]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0
2. What operating system and processor architecture are you using (`go env`)?
Mac 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

create table `user` 
create table `post` 
create table `profile` 
create table `tag` 
panic: reflect: call of reflect.Value.MethodByName on zero Value

goroutine 1 [running]:
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x4541d8d, 0x16, 0xc00015c640, 0x128, 0x0)
        /usr/local/go/src/reflect/value.go:1354 +0x1b9
github.com/beego/beego/v2/client/orm.isApplicableTableForDB(0x0, 0x0, 0x0, 0x453ca54, 0x7, 0x0)
        /Users/xwszt/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_utils.go:112 +0x6f
github.com/beego/beego/v2/client/orm.(*commandSyncDb).Run(0xc000052eb0, 0xc0000121b0, 0x0)
        /Users/xwszt/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:146 +0xb1d
github.com/beego/beego/v2/client/orm.RunCommand()
        /Users/xwszt/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:66 +0x17a
main.main()
        /Users/xwszt/workspace/beego-ORM-study/lesson-1/main.go:34 +0x25
exit status 2

4. What did you expect to see?
beego.io文档中有提到多对多的中间表会自动生成

5. What did you see instead?

```
type Post struct {
    Id    int
    Title string
    User  *User  `orm:"rel(fk)"`    //设置一对多关系
    Tags  []*Tag `orm:"rel(m2m)"`
}

type Tag struct {
    Id    int
    Name  string
    Posts []*Post `orm:"reverse(many)"` //设置多对多反向关系
}
```
post_tags这个中间表不能自动生成

**Comment by AllenX2018** [comment]
@xyzgamestudios 感谢你的反馈，你这问题已经解决，如有还有其他问题，可以随时反馈哈~

**Comment by AI4UXP** [comment]
> @xyzgamestudios 感谢你的反馈，问题已经解决，如有还有其他问题，可以随时反馈哈~

我也遇到这个问题，请问需要更新beego到最新版本还是？

**Comment by flycash** [comment]
在develop分支的代码已经解决了
