### ISSUE TITLE
ORM type(text)，mysql数据库生成的表结构对应字段不是longtext

### ISSUE THREAD

**Issue by xyzgamestudios** [beego/beego#4414]
beego最新版2.0.1
数据库mysql，版本5.7

go结构体中字段
```
Address       string `json:"address" orm:"type(text)"`
```
对应到数据库表中为address varchar(255)

**Comment by AllenX2018** [comment]
这是关系表：
![image](https://user-images.githubusercontent.com/38368409/103603619-febdf180-4f49-11eb-9a49-0b4368ef3b4f.png)

如果你想为`Address`字段设置`varchar(255)`直接用`string`类型就行了

**Comment by xyzgamestudios** [comment]
文档中有提到
在go结构体中类型string，并且设置type(text)时，mysql中对应的是longtext

string - 设置 type(text) 时 | longtext

难道是我理解错误了吗？

**Comment by xyzgamestudios** [comment]
> 这是关系表：
> ![image](https://user-images.githubusercontent.com/38368409/103603619-febdf180-4f49-11eb-9a49-0b4368ef3b4f.png)
> 
> 如果你想为`Address`字段设置`varchar(255)`直接用`string`类型就行了

文档中有提到
在go结构体中类型string，并且设置type(text)时，mysql中对应的是longtext

string - 设置 type(text) 时 | longtext

难道是我理解错误了吗？

**Comment by AllenX2018** [comment]
你用orm操作，DB生成字段 address varchar(255)类型吗？

**Comment by xyzgamestudios** [comment]
> 你用orm操作，DB生成字段 address varchar(255)类型吗？

是的

**Comment by AllenX2018** [comment]
@xyzgamestudios 可否提供复现代码？

**Comment by xyzgamestudios** [comment]
> @xyzgamestudios 可否提供复现代码？

我本地开发的时候使用的是sqlite3，生产环境是mysql，生产环境不好删表重现。也有可能是我自己搞错了，您这边是不是不能重现？那就先关闭这个问题吧，非常感谢你的努力。

**Comment by AllenX2018** [comment]
对，我没有复现此问题，后续有问题随时提问哈
