### ISSUE TITLE
cannot find package "github.com/beego/beego/v2"

### ISSUE THREAD

**Issue by BigLight-H** [beego/beego#4421]
[root@server home]# go get github.com/beego/beego/v2
cannot find package "github.com/beego/beego/v2" in any of:
	/usr/local/go/src/github.com/beego/beego/v2 (from $GOROOT)
	/home/go/src/github.com/beego/beego/v2 (from $GOPATH)

**Comment by flycash** [comment]
try 
```go
go get github.com/beego/beego/v2@v2.0.1
```

**Comment by cnn007** [comment]
#4497
