### ISSUE TITLE
Failed to watch directory: bad file descriptor

### ISSUE THREAD

**Issue by moqimoqidea** [beego/beego#4423]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.15
bee 1.12.0
mac os version 11.1

2. What operating system and processor architecture are you using (`go env`)?
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/someone/Library/Caches/go-build"
GOENV="/Users/someone/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/someone/.gvm/pkgsets/go1.15/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/someone/.gvm/pkgsets/go1.15/global"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/Users/someone/.gvm/gos/go1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/someone/.gvm/gos/go1.15/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bq/d525bbp57776p5l17j_q12s80000gp/T/go-build680542612=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
in main.go dir, execute "bee run"

4. What did you expect to see?
the program can run normally.

5. What did you see instead?
```shell
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.12.0
2021/01/08 17:56:45 WARN     ▶ 0001 Running application outside of GOPATH
2021/01/08 17:56:45 INFO     ▶ 0002 Using 'magma' as 'appname'
2021/01/08 17:56:45 INFO     ▶ 0003 Initializing watcher...
2021/01/08 17:56:45 FATAL    ▶ 0004 Failed to watch directory: bad file descriptor
```

6. What solutions you tried?
reinstall go.
reinstall bee.
read: [golang-bad-file-descriptor](https://stackoverflow.com/questions/33851692/golang-bad-file-descriptor).
read beego realease note bug fix.
read beego issues and find "bad file descriptor"
read [Linux 运行 go 项目报错：copy_file_range: bad file descriptor](https://www.mdeditor.tw/pl/pjuQ)

**Comment by flycash** [comment]
Please provide your application work directory path.

**Comment by moqimoqidea** [comment]
> Please provide your application work directory path.

/Users/someone/Code/my_application/

**Comment by flycash** [comment]
I cannot reproduce this problem. could you share a demo with this issue?

**Comment by moqimoqidea** [comment]
> I cannot reproduce this problem. could you share a demo with this issue?

I will try to reduce my project to the smallest demo that can be reproduced on my machine.

**Comment by moqimoqidea** [comment]
Running `ulimit -S -n 2048` fixed this error for me.

From [Building on macOS Big Sur](https://github.com/grafana/grafana/issues/29121#issuecomment-729020013).
