### ISSUE TITLE
Proposal: Easy cron support for Task module

### ISSUE THREAD

**Issue by flycash** [beego/beego#4429]
Now we have method:
```
func NewTask(tname string, spec string, f TaskFunc) *Task {
}
```
In fact, users are always trouble with writing exact `spec`, the cron expression. 

We could provide methods:
```go
func Schdule(taskFunc, taskName, time.Duration, ... opts)

// user's code, it means running this task every 30 minutes
Schedule(mytask, "myTask", time.Minute * 30)
```

If user wants the task be scheduled on specific datetime:
```go
func ScheduleOn(taskFunc, taskName, type, opts...) 

// users code, it means that this task run every day on 01:30, 13:30
ScheduleOn(mytask, 'mytask', daily, DailyStartAt(1, 30), DailyStartAt(13, 30)))

// every moday 01:30 
ScheduleOn(mytask, 'mytask', weekly, WeeklyStartAt(MODAY, 1, 30))
```

**Comment by changsongl** [comment]
Do we need to implement all the features of cron expression? I think we just need add some common features. Since we keep the cron expression, they can still use it for some complicated ones.

**Comment by flycash** [comment]
> Do we need to implement all the features of cron expression? I think we just need add some common features. Since we keep the cron expression, they can still use it for some complicated ones.

Yes
