### ISSUE TITLE
Error handler status code

### ISSUE THREAD

**Issue by vadimi** [beego/beego#443]
When some code panics in application beego doesn't set response code correctly during recovering. It returns error page with 200 status. I think it's necessary to set it to 500 by default. When I trigger panic through `Ctx.Abort` - everything is set as expected.

**Comment by bclermont** [comment]
my controller:

```
func (this *MyController) Get() {
	panic(fmt.Errorf("!"))
}
```
```
$ wget -q -O /dev/null -S http://127.0.0.1:8081/
  HTTP/1.1 200 OK
  Server: beegoServer:1.4.3
  Date: Tue, 05 May 2015 04:18:43 GMT
  Content-Length: 1804
  Content-Type: text/html; charset=utf-8
```

now I can't write reliable API client because I can't assume that ``200`` is really ok
