### ISSUE TITLE
Proposal: Timeout support for Task module

### ISSUE THREAD

**Issue by flycash** [beego/beego#4430]
In task module, when Beego schecule a task, user are not able to specific timeout configuration.

For example, I have a task, usually it take less than 10 minute to finish job. So I want Beego to kill the task if the task is beeing executed more than 10 minutes.

Now I had to do it like:

```
func mytask() error {
    ctx := contex.WithDeadline()
    ...
}
```

But I think Beego should be responsible for this feature.

So I propose that:

```go
func WithTimeOut() TaskOpt {
}
```
And the method `run` need to be refactored too.
```go
func (m *taskManager) run() {...}
```

**Comment by changsongl** [comment]
I just read the code about task. It seems like task function actually have a context param. We can use this context with timeout. User task function can check deadline is due, and stop their job ASSP.

**Comment by flycash** [comment]
> I just read the code about task. It seems like task function actually have a context param. We can use this context with timeout. User task function can check deadline is due, and stop their job ASSP.

we do have ctx parameter, but when we schedule the task,

![image](https://user-images.githubusercontent.com/9923838/104127148-6eddd480-539b-11eb-9a3e-cca00044e092.png)

we do not build pass valid context to task.

I think we could passs a `ctx := contex.WithDeadline()` to it
