### ISSUE TITLE
v2.0.2 TODO List (Updating)

### ISSUE THREAD

**Issue by flycash** [beego/beego#4431]
[RoadMap](https://github.com/beego/beego/wiki/RoadMap)

1. Add new method `RollbackIfNotCommit` to `TxOrm` interface. #4428  done
2. Easy cron support for Task module. #4429
3. Timeout support for Task module #4430  done 
4. Refactor httplib: Add LogFilter #4440 done 
5. Easy way to communitate with multiple HTTP downstream by httplib. #4455
6. Refactor: Better Audit for web module #4471 
7. Help to fix sonar problem. #4434
9. Refactor: Remove all goto statement. #4488 This is a big task and any enhancement is very welcome.
10. Proposal: Add Bind() method for web.Controller #4491 done
11. Proposal: Add Resp() method for web.Controller #4492 done
12. Proposal: Generate exceptMethod by using AppStartHook #4572 done

Feel free to  comment if you want to help us 😄 done

**Comment by changsongl** [comment]
I can do #4429 and #4430.

**Comment by osmanmakal** [comment]
#4370

**Comment by roberChen** [comment]
currently the documents hasn't changed compared with v1, which will confuse the developers. Could this be fixed?

**Comment by Joe3160** [comment]
suggest add function bellow
1. route middleware 
2. route group
that can make route namespace easyer to use
建议 下个版本 新加个 路由中间件 或 路由群组，或可以大大简化  路由命名空间

**Comment by Joe3160** [comment]
suggest add function bellow
1. route middleware 
2. route group
that can make route namespace easyer to use
建议 下个版本 新加个 路由中间件 或 路由群组，或可以大大简化  路由命名空间

**Comment by flycash** [comment]
> currently many documents haven't changed compared with v1, which will confuse the developers. Could this be fixed?

we are working on new documents

**Comment by flycash** [comment]
> suggest add function bellow
> 
> 1. route middleware
> 2. route group
>    that can make route namespace easier to use

could you please make a new issue and give us more details about this suggestion. And please provide some demo code or example, so that we can understand what you need. Now, I think the namespace feature of Beego is not hard for users. :)

**Comment by Joe3160** [comment]
> > suggest add function bellow
> > 
> > 1. route middleware
> > 2. route group
> >    that can make route namespace easier to use
> 
> could you please make a new issue and give us more details about this suggestion. And please provide some demo code or example, so that we can understand what you need. Now, I think the namespace feature of Beego is not hard for users. :)

ok! 
[ issue #4552 ](https://github.com/beego/beego/issues/4552)

**Comment by byene0923** [comment]
I want  to try [#4491](https://github.com/beego/beego/issues/4491)
