### ISSUE TITLE
runmode = dev的情况下   beeV2 pack之后，无法运行，报错找不着controllers

### ISSUE THREAD

**Issue by songyangper** [beego/beego#4435]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
求提交一下你的目录结构和报错信息。

可能的解决方案是，目前会扫描controllers的目录，尝试解析注解路由，所以你可以创建一个空的controllers目录。
