### ISSUE TITLE
旧版本beego升级2.0路由问题

### ISSUE THREAD

**Issue by A1311981684** [beego/beego#4438]
bee fix -t 2 成功之后，beego替换成了adapter，这种情况下，没法在一个namespace里添加多个NSInclude换成server
/web就行

**Comment by flycash** [comment]
这个问题我隐约好像修复了。不过你可以提供更加详细的说明吗？我看看是不是之前有人报过的一个issue

**Comment by flycash** [comment]
无反馈，先关闭。
