### ISSUE TITLE
Cannot install beego because TPC dial timetou

### ISSUE THREAD

**Issue by rockywu** [beego/beego#4439]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
2. 
go version go1.15.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?

macOS 10.15.7

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

出现无法安装问题，请帮忙解决

4. What did you expect to see?
```
go get -u github.com/beego/beego/v2@v2.0.0
```
print

```
go get github.com/beego/beego/v2@v2.0.0: github.com/beego/beego/v2@v2.0.0: Get "https://proxy.golang.org/github.com/beego/beego/v2/@v/v2.0.0.info": dial tcp 172.217.160.81:443: i/o timeout
```

5. What did you see instead?

**Comment by flycash** [comment]
You need proxy. If you are in China, please use `export GOPROXY=https://goproxy.cn`
And please use 
```go
go get -u github.com/beego/beego/v2@v2.0.1
```
beacuse checksum of  `v2.0.0` is invalid.
