### ISSUE TITLE
Refactor httplib: Remove debug code to a filter

### ISSUE THREAD

**Issue by flycash** [beego/beego#4440]
The httplib.BeegoHTTPSettings has field `ShowDebug        bool`
It only be used in method `doRequest`:
```go
	if b.setting.ShowDebug {
		dump, err := httputil.DumpRequest(b.req, b.setting.DumpBody)
		if err != nil {
			log.Println(err.Error())
		}
		b.dump = dump
	}
```
But I don't see any code use `b.dump`. So I think we could remove `b.dump` and this part.

And  then we provide a filter named `LogFilter`. It's default filter and its reponsibility is to log request and response. And if the request.ShowDebug = true, it logs request and response:

```go
log.Debug(request)
next()
log.Debug(response)
```

**Comment by anoymouscoder** [comment]
If you do not hurry, I want to complete this task. Because I am not familiar with the source code of beego project, so I need a few days to get familiar with it. If all goes ok, I will submit a pr next week. Do you think this is ok?

**Comment by anoymouscoder** [comment]
@flycash `DumpRequest()` uses `b.dump`, so I think we can not remove it directly?

https://github.com/beego/beego/blob/develop/client/httplib/httplib.go#L184

**Comment by anoymouscoder** [comment]
I found that there is no place to call `DumpRequest()`.  What scenarios will call this method at present? If not, consider deleting `DumpRequest()` and `b.dump`

**Comment by flycash** [comment]
Thank you @anoymouscoder . This is not an urgent issue, and I assigned it to you. 

> I found that there is no place to call DumpRequest(). What scenarios will call this method at present? If not, consider deleting DumpRequest() and b.dump

I think we could remove both `DumpBody  bool`,  `b.dump`, method `DumpRequest` and `DumpBody` because users are able to call `GetRequest` to get original http.Request and then dump request by themselves.

The scenario is that users want to log request and response when they use httplib. In the future, they could use this `LogFilter` to log request.

**Comment by anoymouscoder** [comment]
@flycash Thank you for your detailed instrutions, I will start now!
