### ISSUE TITLE
Q & A (Updating...)

### ISSUE THREAD

**Issue by flycash** [beego/beego#4442]
Do not leave comment here.  If you are confused about some questions, please make a new issue.

**Comment by flycash** [comment]
Q: XSRF didn't work. #4369 

A: From Beego v1.12.3, we set two more flags for XSRF cookie, `secure` and `http-only`. `secure` means that it only works for HTTPS protocol. `http-only` means that you could not read `XSRF` token in frontend.

We suggest that disable XSRF when you are developing and enable it in production environment.

The key point is why we add these two flags?

Because it's not safe if missing these two flags. Someone told us that they were attacked. :(

**Comment by flycash** [comment]
Q: Could I use zipkin, jeaguar or other tracing framework?

A: In Beego v2.x, we build full-chain tracing by using opentracing API. It means that  you could use any framework that support opentracing API. Zipkin, jeaguar and skywalking support opentracing API. What you need to do is inject the Tracer instance to opentracing. Please check those frameworks' official doc to learn how to use opentracing API.

**Comment by flycash** [comment]
Q: How to resolve problem  `Can not find pakage "github.com/beego/beego/v2"`
A: Usually it means that you use GOPATH. Now Beego requires GO MOD, which requires you must set `GO111MODULE=on` in your environment. 
try to run:
```shell
export GO111MODULE=on
go get -u github.com/beego/beego/v2@master
```
#4497 #4421

**Comment by flycash** [comment]
Q: Why running `go get github.com/beego/beego/v2` always get timeout exception, the message is "dial tcp 172.x.x.x i/o timeout" ??
A: When you got this error, you could set `GORPOXY`. In general, if you are in China, you could run
```shell
export GOPROXY=https://goproxy.cn
``` 
Then try again!

**Comment by sheep-yang** [comment]
check you go.mod file, add  require github.com/beego/beego v2
