### ISSUE TITLE
Prometheus | panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by awalvie** [beego/beego#4444]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go Version: 1.15.2
Bee Version: 2.0.2

2. What operating system and processor architecture are you using (`go env`)?
OS: Pop OS (Linux)
Architecture: x64

3. What did you do?
Added the prometheus filter using the following code:
```go
	pmetrics := &prometheus.FilterChainBuilder{}
	web.InsertFilterChain("/*", pmetrics.FilterChain)
```

To scrape data using the `/metrics` endpoint.

4. What did you see instead?
When starting up the server and trying to log in. The server crashes with a panic.

```go
panic: interface conversion: interface {} is nil, not string

goroutine 139 [running]:
github.com/beego/beego/v2/server/web/filter/prometheus.report(0x86028, 0xc032eee870, 0xc19bafc028)
        /home/awalvie/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/filter/prometheus/filter.go:84 +0x2a5
created by github.com/beego/beego/v2/server/web/filter/prometheus.(*FilterChainBuilder).FilterChain.func1
        /home/awalvie/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/filter/prometheus/filter.go:56 +0xc9
```

**Comment by flycash** [comment]
We forget to handle corner cases. :(

**Comment by flycash** [comment]
Please change to use master branch. We will keep fix bug to master branch.

**Comment by awalvie** [comment]
Late reply but thanks a lot @flycash
