### ISSUE TITLE
CommentRouterPath unsupport monitoring for multiple path

### ISSUE THREAD

**Issue by yellbuy** [beego/beego#4448]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
不懂你的意思，给个demo？

**Comment by yellbuy** [comment]
目前只能监控一个文件夹，controllers，pulugs/插件1路径/controllers，pulugs/插件2路径/controllers，类似这种结构的多个路径可以同时监控生成注解路由

**Comment by yellbuy** [comment]
目前通过修改hook.go来解决了这个问题：
func registerCommentRouter() error {
	if BConfig.RunMode == DEV {
		pathList := strings.Split(BConfig.WebConfig.CommentRouterPath, ",")
		for _, path := range pathList {
			if err := parserPkg(filepath.Join(WorkPath, path)); err != nil {
				return err
			}
		}

	}

	return nil
}

**Comment by flycash** [comment]
在2.0里面我们是会递归扫描下面的子目录。不过组织方式不是你这样设想的，而是controllers/a, controllers/b这种
