### ISSUE TITLE
Binding query parameter

### ISSUE THREAD

**Issue by xwinie** [beego/beego#4449]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
![image](https://user-images.githubusercontent.com/3609288/105297888-2ae99b80-5bf5-11eb-83b0-4e2b7247655b.png)

db.ExecContext(ctx, `
    delete from Invoice
    where
        TimeCreated < :end
        and TimeCreated >= :start;`,
    sql.Named("start", startTime),
    sql.Named("end", endTime),
)

5. What did you see instead?

**Comment by changsongl** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What version of Go and beego are you using (`bee version`)?
> 2. What operating system and processor architecture are you using (`go env`)?
> 3. What did you do?
>    If possible, provide a recipe for reproducing the error.
>    A complete runnable program is good.
> 4. What did you expect to see?
>    ![image](https://user-images.githubusercontent.com/3609288/105297888-2ae99b80-5bf5-11eb-83b0-4e2b7247655b.png)
> 
> db.ExecContext(ctx, ` delete from Invoice where TimeCreated < :end and TimeCreated >= :start;`,
> sql.Named("start", startTime),
> sql.Named("end", endTime),
> )
> 
> 1. What did you see instead?

Hello,xwinie. Thank you for writing this issue. Are you using Mysql as your db driver? From my knowledge, mysql doesn't support Named Parameters. Because orm is using golang mysql package(go-sql-driver/mysql), so it doesn't support as well. 

````golang
func main() {

	db, err := orm.GetDB()
	if err != nil {
		panic(err)
	}

	result, err := db.ExecContext(
		context.Background(),
		"DELETE FROM test WHERE id = :id LIMIT 1;", sql.Named("id", 1),
	)
	if err != nil {
		panic(err)
	}

	fmt.Println(result)
}

// panic: mysql: driver does not support the use of Named Parameters
````

[reference: go-sql-driver Issue](https://github.com/go-sql-driver/mysql/issues/561)

**Comment by xwinie** [comment]
tks
