### ISSUE TITLE
添加跨域支持报错

### ISSUE THREAD

**Issue by jolleybin** [beego/beego#4450]
| ___
| |/ / ___ ___
| ___ \ / _ \ / _
| |/ /| /| /
_/ _| __| v2.0.2

├── Beego : Beego is not installed. Please do consider installing it first: https://github.com/beego/beego/v2. If you are using go mod, and you don't install the beego under $GOPATH/src/github.com/astaxie, just ignore this.
├── GoVersion : go1.15.6
├── GOOS : linux
├── GOARCH : amd64
├── NumCPU : 4
├── GOPATH : /datas/e_drive/goproject
├── GOROOT : /home/sakura/apphome/go
├── Compiler : gc
└── Date : Monday, 11 Jan 2021

“GO ENV“
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sakura/.cache/go-build"
GOENV="/home/sakura/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/datas/e_drive/goproject/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/datas/e_drive/goproject"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/sakura/apphome/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/sakura/apphome/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build843580340=/tmp/go-build -gno-record-gcc-switches"

大佬好，我又来了。。

这次是这样的，我用beego写了接口，需要添加支持跨域请求
查了下资料后发现源码里有样例，就根据源码里的样例添加了跨域支持
添加上跨域设置后启动就报错了，麻烦大佬再帮忙看看。
参考的源码地址：https://github.com/beego/beego/blob/develop/adapter/plugins/cors/cors.go

错误信息
![图片](https://user-images.githubusercontent.com/28995630/105297447-0f7e9080-5bf5-11eb-9f5b-bca1e3bd3421.png)

只是在mian.go引入了cors包和添加跨域设置的代码，以下是我mian.go的内容

`package main

import (
	"archer/routers"

	"github.com/beego/beego/v2/adapter/plugins/cors"
	beego "github.com/beego/beego/v2/server/web"
)

func main() {
	if beego.BConfig.RunMode == "dev" {
		beego.BConfig.WebConfig.DirectoryIndex = true
		beego.BConfig.WebConfig.StaticDir["/swagger"] = "swagger"
	}
	routers.Init()

	beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins:     []string{"https://*.foo.com"},
		AllowMethods:     []string{"PUT", "PATCH"},
		AllowHeaders:     []string{"Origin"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))

	beego.Run()
}
`

**Comment by flycash** [comment]
You are trying to pass `adapter.cors` to BeegoV2 API.

Here is my code, please try:
```go
	"github.com/beego/beego/v2/server/web/filter/cors"
	"github.com/beego/beego/v2/server/web/filter/prometheus"

	beego.InsertFilter("/*", beego.BeforeRouter, cors.Allow(&cors.Options{
		AllowOrigins:     []string{"https://*.foo.com"},
		AllowMethods:     []string{"PUT", "PATCH"},
		AllowHeaders:     []string{"Origin"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
	}))
```
Please import `github.com/beego/beego/v2/server/web/filter/cors`, adapter module's filter only work for adapter module.
