### ISSUE TITLE
beego v2.0 ORM 的 QuerySeter 建议增加事务Begin()方法，以方便控制事务启动的时机

### ISSUE THREAD

**Issue by yellbuy** [beego/beego#4451]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
这是一个很难而且收益不是很大的事情。开启事务的难点，其实在于要保证在后面的，提交事务之前的SQL都要在这个事务内执行完毕。这个有点绕口，核心就是我们要维护一个事务，而后确保在后面的SQL，无论从哪里开启的，都是使用这个事务的，直到事务提交。你可以看到我们Orm的实现，就是用TxOrm来维持了一个事务，而后使用TxOrm执行的语句，都是在这个事务之内。

然后使用QuerySeter的问题，就在于我们认为QuerySeter是一次性的，它就是一个语句的执行。比如说 QuerySeter.Begin()之后，用什么来继续维持这个事务呢？还是说依旧返回一个TxOrm。如果依旧返回TxOrm，那么和现在比起来，看起来没特别大的收益。

实际上，QuerySeter在我们的设想中，应该是在开启事务之后，很容易就构建好的一个东西。我猜测你的出发点，是因为你遇到了说很难构建QuerySeter的场景，所以你希望在QuerySeter尽量构建完整之后再开启事务。

在我想来，你可以考虑将准备构建QuerySeter的上下文和真正构建QuerySeter分离开。在开启事务之前，将所需的数据准备好，而后开启事务。

**Comment by yellbuy** [comment]
QuerySeter主要是代码重用性问题，beego 2.0下，必须使用TxOrm创建QuerySeter才能用事务，但有这样一个场景，在进行事务控制之前，需要做一些查询工作，根据结果在事务中使用原有的QuerySeter进行Update或Delete等操作。如果在事务之前创建了QuerySeter，就必须重新使用TxOrm创建QuerySeter，很多代码就重复了。如果在事务中创建QuerySeter进行查询，事务的执行时间就会大大增加。

**Comment by yellbuy** [comment]
package orm

func (o querySet) SetOrm(orm *ormBase) QuerySeter {
	o.orm = orm
	return &o
}
目前增加的这个代码，需要事务的使用传TxOrm进行进行事务控制

**Comment by flycash** [comment]
> QuerySeter主要是代码重用性问题，beego 2.0下，必须使用TxOrm创建QuerySeter才能用事务，但有这样一个场景，在进行事务控制之前，需要做一些查询工作，根据结果在事务中使用原有的QuerySeter进行Update或Delete等操作。如果在事务之前创建了QuerySeter，就必须重新使用TxOrm创建QuerySeter，很多代码就重复了。如果在事务中创建QuerySeter进行查询，事务的执行时间就会大大增加。

这个场景实际上是，我如何在一个事务内复用一个事务外的QuerySeter。从设计上来说，QuerySeter应该是一次性的，用完就丢。所以实际上复用的应该是构建QuerySeter的代码。
你可以稍微尝试：
```go
func build(o orm.DQL, ...params) {
   qs := o.QueryTable()
   // ... 其余构造步骤
   return qs
}
```
TxOrm和Orm都是实现了这个接口的。

使用DQL有点奇怪，是因为
```go
type ormer interface {
	DQL
	DML
	DriverGetter
}
```
是私有的。

之前我在实际中遇到过类似的场景，我在考虑将`ormer`暴露成为公共的接口。

我要坚持的一点就是，querySeter不应该被复用，而是构建QuerySeter的过程应该被复用。

所以暴露 `SetOrm` 违背了设计初衷。

**Comment by jianzhiyao** [comment]
目前已经确认了相关方案，在执行中

**Comment by jianzhiyao** [comment]
### Relative pull request
https://github.com/beego/beego/pull/4461

after that pr closed, i think this issue can be closed

### How to use
```
package main

import "github.com/beego/beego/v2/client/orm"

func main() {
	//非事务
	o1 := orm.NewOrm()
	_, _ = Select(o1)
	_ = Update(o1)

	//事务
	o2 := orm.NewOrm()
	tx, _ := o2.Begin()
	if _, err := Select(tx); err != nil {
		_ = tx.Rollback()
	} else if err = Update(tx); err != nil {
		_ = tx.Rollback()
	} else {
		tx.Commit()
	}

}

type User struct {
	Id   int
	Name string
}

func Select(query orm.QueryExecutor) (*User, error) {
	user := User{Id: 1}

	if err := query.Read(&user); err != nil {
		return &user, nil
	} else {
		return nil, err
	}
}

func Update(query orm.QueryExecutor) error {
	user := User{Id: 1}
	user.Name = "MyName"
	if _, err := query.Update(&user); err != nil {
		return err
	}
	return nil
}

```

**Comment by jianzhiyao** [comment]
pr 已经合并，没啥问题的话一周后关闭此issue

**Comment by yellbuy** [comment]
还是不方便，QuerySetter这个还是老样子，其实beego v1的挺好。v2的复杂的查询后启动事务，直接重用QuerySetter，甚至追加些Filter然后直接进行Update在v2中始终不方便，v1则没有这个问题，挺好用。v2下，涉及事务的地方都要前移至查询之前，或者就得重新构造一个一模一样只是包含TxOrm的QuerySetter，否则Update就没有使用事务，但是导致事务执行时间比以前的代码执行长得多。

**Comment by jianzhiyao** [comment]
> 还是不方便，QuerySetter这个还是老样子，其实beego v1的挺好。v2的复杂的查询后启动事务，直接重用QuerySetter，甚至追加些Filter然后直接进行Update在v2中始终不方便，v1则没有这个问题，挺好用。v2下，涉及事务的地方都要前移至查询之前，或者就得重新构造一个一模一样只是包含TxOrm的QuerySetter，否则Update就没有使用事务，但是导致事务执行时间比以前的代码执行长得多。

有没有代码参考一下，提供一个demo我们会更好对症下药

**Comment by flycash** [comment]
我先关了。后面有更新再说。
