### ISSUE TITLE
beego v2 Orm MaxOpenConnections 高并发下连接貌似不会自动关闭

### ISSUE THREAD

**Issue by yellbuy** [beego/beego#4462]
原来用的v1的没发现存在这个问题，但在beego v2下，短时间连续执行查询达到MaxOpenConnections的上限后，orm查询会卡死，使用的是orm.Raw的QueryRows方法，这时只能重启程序。
新的orm查询执行结束后链接貌似不会自动关闭，很容易就会达到MaxOpenConnections的上限，应该怎么关闭？

**Comment by flycash** [comment]
我们之前v1到v2，没有变过maxOpenConnections的逻辑。你v1用的是哪个版本？

**Comment by flycash** [comment]
你设置`StmtCacheSize`参数了么？

**Comment by flycash** [comment]
可以来个可以复现的查询吗？我们可以本地压测一下。

**Comment by yellbuy** [comment]
我这边再检查下，好像事务上控制有问题，后面有啥问题再反馈

**Comment by jianzhiyao** [comment]
> 我这边再检查下，好像事务上控制有问题，后面有啥问题再反馈

可以的，如果有问题可以在此issue提供demo给我们复现，我们也很乐意为你提供帮助。
如果没有回复此issue将在一周后关闭。

**Comment by struggle0119** [comment]
> 你设置`StmtCacheSize`参数了么？

这个值应该如何设置呢，设置的标准是什么

**Comment by flycash** [comment]
没有性能问题就不要设置这个值……
