### ISSUE TITLE
Update some codes, comments and README lines

### ISSUE THREAD

**Issue by jihoon-seo** [beego/beego#4463]
Related issue: #4457 

---

These should be updated:

[As-is]
https://github.com/beego/beego/blob/326fc5dd9cf8989bbc68b93ce9718435130897ba/adapter/config/config.go#L17

[To-be]
I cannot determine which one is right:
1. `//  import "github.com/beego/beego/v2/adapter/config"`
2. `//  import "github.com/beego/beego/v2/core/config"`

---

![image](https://user-images.githubusercontent.com/46767780/106073223-faea4d00-614c-11eb-89d7-16d5dc8669fe.png)

![image](https://user-images.githubusercontent.com/46767780/106072969-8c0cf400-614c-11eb-924b-13bbd7bb4028.png)

![image](https://user-images.githubusercontent.com/46767780/106073290-1b1a0c00-614d-11eb-8d77-6a297809ef25.png)

![image](https://user-images.githubusercontent.com/46767780/106073342-31c06300-614d-11eb-8165-3e96bae58aeb.png)

![image](https://user-images.githubusercontent.com/46767780/106073394-4e5c9b00-614d-11eb-9877-7dbaa6361557.png)

![image](https://user-images.githubusercontent.com/46767780/106073009-a2b34b00-614c-11eb-882e-dd853ccc2d86.png)

![image](https://user-images.githubusercontent.com/46767780/106073449-6fbd8700-614d-11eb-8d22-3bc24ba86d4c.png)

![image](https://user-images.githubusercontent.com/46767780/106074027-7c8eaa80-614e-11eb-9108-abe0a6737b2d.png)

![image](https://user-images.githubusercontent.com/46767780/106074553-6b926900-614f-11eb-8083-ad3ccd61ea32.png)

![image](https://user-images.githubusercontent.com/46767780/106073074-b65eb180-614c-11eb-94ce-d60452f87173.png)

![image](https://user-images.githubusercontent.com/46767780/106073168-e1e19c00-614c-11eb-838c-61b6455980eb.png)

**Comment by flycash** [comment]
`adapter` is used to help to upgrade Beegov1.x to v2.x

Usually you should not use this.
