### ISSUE TITLE
Update README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by jihoon-seo** [beego/beego#4466]
[README.md]

Go Report Card badge is broken.

![image](https://user-images.githubusercontent.com/46767780/106092920-a3f76e80-6172-11eb-9d16-b9f6e6ca85bd.png)

---

[CONTRIBUTING.md]

The doc says `docker-compose -f scripts/test_docker_compose.yml up -d`,
but I cannot find `test_docker_compose.yml` in anywhere.

**Comment by flycash** [comment]
We should remove `build` and `go report card` and add others. Let me check it this week.

Sonar scan, coverage and other badges should be added into README.

**Comment by jianzhiyao** [comment]
It will be fixed in https://github.com/beego/beego/pull/4461, thx for your notification!

**Comment by jihoon-seo** [comment]
@jianzhiyao Could you re-open this issue?
Since the below issue is not fixed in #4461.


---

> [CONTRIBUTING.md]
> 
> The doc says `docker-compose -f scripts/test_docker_compose.yml up -d`,
> but I cannot find `test_docker_compose.yml` in anywhere.

**Comment by jianzhiyao** [comment]
> @jianzhiyao Could you re-open this issue?
> Since the below issue is not fixed in #4461.
> 
> > [CONTRIBUTING.md]
> > The doc says `docker-compose -f scripts/test_docker_compose.yml up -d`,
> > but I cannot find `test_docker_compose.yml` in anywhere.

sorry, i ignore the problem or missing test_docker_compose.yml
