### ISSUE TITLE
audit log support

### ISSUE THREAD

**Issue by maxfy1992** [beego/beego#4468]

**Comment by flycash** [comment]
please provide more details

**Comment by maxfy1992** [comment]
web system always need audit log, maybe like  nginx's access log,

**Comment by flycash** [comment]
`BConfig.LogConfig.AccessLogs=true`, it will record web requests. 

Let me create a issue to improve this feature because I think `AccessLog` looks not good, it should be logged by `Filter`.
It's a typical AOP logic.

**Comment by flycash** [comment]
I closed this and please follow #4471 
Thank you!
You remind me that we should do better in audit feature.
