### ISSUE TITLE
部署编译后的程序还需要controller？

### ISSUE THREAD

**Issue by A1311981684** [beego/beego#4470]
我在编译之后尝试运行，报出了这个：
17:55:19 optical.go:105: stat ./calibrations/: no such file or directory
panic: err: chdir /home/A/AA/controllers: no such file or directory: stderr:

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
/home/wzj/dev/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:83 +0x224
sync.(*Once).doSlow(0x1b19728, 0x10207e8)
/home/wzj/requirements/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
/home/wzj/requirements/go/src/sync/once.go:57
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
/home/wzj/dev/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:69 +0x4d
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc00000f1c0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/wzj/dev/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/server.go:85 +0x34
github.com/beego/beego/v2/server/web.Run(0x0, 0x0, 0x0)
/home/wzj/dev/gopath/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:57 +0x62
main.main()
/home/wzj/dev/gopath/src/prj/A/AA/main.go:46 +0x2f2

**Comment by A1311981684** [comment]
在配置文件中 更改为prod模式somehow解决了

**Comment by flycash** [comment]
这个问题已经修复了。
原因是在非prod模式下，我们会扫描controllers文件目录，以生成注解路由文件。找不到的时候就会报错。

你改为prod的确是可以的。实际上只要不是dev就可以。

#4452
