### ISSUE TITLE
Refactor: Better Audit for web module

### ISSUE THREAD

**Issue by flycash** [beego/beego#4471]
There is a config item `Config.LogConfig.AccessLogs`, if it was true, Beego log web request and response.

Actually, it's not a good design. As we all known, `Log` is a typical AOP logic, it should not couple with "business" logic. But now, audit couple with Beego logic.

The relative code:
```go
// AccessLogRecord is astruct for holding access log data.
type AccessLogRecord struct {
	RemoteAddr     string        `json:"remote_addr"`
	RequestTime    time.Time     `json:"request_time"`
	RequestMethod  string        `json:"request_method"`
	Request        string        `json:"request"`
	ServerProtocol string        `json:"server_protocol"`
	Host           string        `json:"host"`
	Status         int           `json:"status"`
	BodyBytesSent  int64         `json:"body_bytes_sent"`
	ElapsedTime    time.Duration `json:"elapsed_time"`
	HTTPReferrer   string        `json:"http_referrer"`
	HTTPUserAgent  string        `json:"http_user_agent"`
	RemoteUser     string        `json:"remote_user"`
}

func (app *HttpServer) LogAccess(ctx *beecontext.Context, startTime *time.Time, statusCode int) {
	// Skip logging if AccessLogs config is false
	if !app.Cfg.Log.AccessLogs {
		return
	}
	// Skip logging static requests unless EnableStaticLogs config is true
	if !app.Cfg.Log.EnableStaticLogs && DefaultAccessLogFilter.Filter(ctx) {
		return
	}
	var (
		requestTime time.Time
		elapsedTime time.Duration
		r           = ctx.Request
	)
	if startTime != nil {
		requestTime = *startTime
		elapsedTime = time.Since(*startTime)
	}
	record := &logs.AccessLogRecord{
		RemoteAddr:     ctx.Input.IP(),
		RequestTime:    requestTime,
		RequestMethod:  r.Method,
		Request:        fmt.Sprintf("%s %s %s", r.Method, r.RequestURI, r.Proto),
		ServerProtocol: r.Proto,
		Host:           r.Host,
		Status:         statusCode,
		ElapsedTime:    elapsedTime,
		HTTPReferrer:   r.Header.Get("Referer"),
		HTTPUserAgent:  r.Header.Get("User-Agent"),
		RemoteUser:     r.Header.Get("Remote-User"),
		BodyBytesSent:  r.ContentLength,
	}
	logs.AccessLog(record, app.Cfg.Log.AccessLogsFormat)
}

```

I think we should move this to a new filter named `LogFilter` or `AuditFilter`. And then mark these structures and functions as deprecated.

We could remove it in the future. 

From this refactoring, we could achieve better desgin, and make the logic of serving HTTP more simple.

Using `Filter` we could expose more option to allow users to custom the audit behavior.

**Last but not least, we should check all modules, and add audit feature or refactor it.**

**Comment by flycash** [comment]
#4468

**Comment by anoymouscoder** [comment]
I think that violate the AOP design pattern is mainly included in `router.go` under `web` package. https://github.com/beego/beego/blob/develop/server/web/router.go#L1219

**Comment by flycash** [comment]
> I think that violate the AOP design pattern is mainly included in `router.go` under `web` package.
> eg. https://github.com/beego/beego/blob/develop/server/web/router.go#L1219

Yes, so we must remove this if we could.
