### ISSUE TITLE
Proposal: rate limit filter for web service

### ISSUE THREAD

**Issue by flycash** [beego/beego#4476]
Several users proposed that we should add some governance function, the most important thing is **rate limit**.

API providers are facing the problem that consumers may send too many request and make servers overload. In this case, we will think about using "rate limit" to protect our application.

But it's a little bit complicate for many users to implement a correct rate limit filter.  There are too many rate limit algorithms! 

I propose that we could provide a general rate limit filter.  And if users need some special rate limit strategy,  I believe that they should do it by themselves.

In this general filter, it only take those parameters:
- pattern: the urls matched this patter will be controlled by this filter.
- count and duration: it means that cout/(per duration). For example, when users pass <100, 1 min>, it means that this servers only accept 100 request in one minute.
- rejection handler: When the request count is over limitation, users could custom the rejection behavior. By default, we only return 500 http code, error code and error message in response body.

The question is that:  Are users able to pass algorithm enum? For example, if user passes "SlidingWindow", we use "sliding window" to do rate limit. 

In my opinion, we don't need to do this because we provide **general filter**. I think if users want to config algorithm, it means that they understand those rate limit algorithem, so they could do it by themselves. 

But we should make this filter more scalable so that we could change to use other algorithms.

And if anyone want to do this, we could have online discussion.

**Comment by anoymouscoder** [comment]
I'd like to try it, please allow me to investigate about rate limit algorithms, and then we can disscuss it.

**Comment by anoymouscoder** [comment]
I drew a diagram of the components of `RateLimitFilter`：
- Configuration Store - to keep all the rate limit configurations
- Request Store - to keep all the requests made against one configuration key
- Decision Engine - it uses data from the Configuration Store and Request Store and makes the decision
![image](https://user-images.githubusercontent.com/39330606/108062744-336ab000-7095-11eb-886e-2a9161bac105.png)

Decision Engine contains some rate limit algotithms, user can choose the algorithm and rejection strategy to be used through Configuration Store Builder. The rejection strategies include returning http response or placing the request in a queue for processing later. The policy like a hashmap, whose keys are regex pattern of the url, and the values are some request count restrictions. 
Ideally, Request Store can support multiple storage systems, such as memory, db or redis, etc. However, considering the complexity of adaptation of different storage systems, do not consider this for now.

**Comment by anoymouscoder** [comment]
@flycash  If you think my above design is reasonable, then I will start coding.

**Comment by flycash** [comment]
> @flycash If you think my above design is reasonable, then I will start coding.

That looks goo! :)
