### ISSUE TITLE
swagger中，httpstatus不为200时，请求结果没有显示response body信息

### ISSUE THREAD

**Issue by wpliang** [beego/beego#4477]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.16rc1 darwin/arm64 
bee version v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
darwin/arm64

3. What did you do?
请求返回的http status 设为为401（非200），swagger中请求没有response body信息，现象如下：

![image](https://user-images.githubusercontent.com/18420903/106612215-d4407200-65a3-11eb-86b4-99ced31526f7.png)

4. What did you expect to see?
当httpstatus为非200时，和200一样， swagger中请求能显示response body信息，如下：
![image](https://user-images.githubusercontent.com/18420903/106612695-5466d780-65a4-11eb-9bfd-954ceeb42500.png)

5. What did you see instead?

**Comment by jianzhiyao** [comment]
想请问一下结束方法用的是Abort吗

**Comment by jianzhiyao** [comment]
正常运行代码
```
package main

import (
	"github.com/beego/beego/v2/server/web"
	"github.com/beego/beego/v2/server/web/context"
	"net/http"
)

func main() {
	web.Get("/", func(ctx *context.Context) {
		ctx.ResponseWriter.WriteHeader(http.StatusUnauthorized)
		ctx.ResponseWriter.Write([]byte("111231"))
	})
	web.Run(`0.0.0.0:8845`)
}
```

**Comment by wpliang** [comment]
谢谢，升级了下swagger后就ok了
