### ISSUE TITLE
beego-orm-adapter  这个适配器需要更新下了，目前只支持beego1.x版本的，需要支持下beego2.x

### ISSUE THREAD

**Issue by wpliang** [beego/beego#4478]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by jianzhiyao** [comment]
adapter原本就是为了从v1无缝升级到v2设计的，v2用新api就可以了

**Comment by wpliang** [comment]
> adapter原本就是为了从v1无缝升级到v2设计的，v2用新api就可以了

我是指casbin的adapter, https://github.com/casbin/beego-orm-adapter/tree/master
不知道是不是你们这边在维护？

**Comment by hsluoyz** [comment]
Hi @wpliang , https://github.com/casbin/beego-orm-adapter is maintained by the Casbin community instead of Beego official. Please send a GitHub issue to: https://github.com/casbin/beego-orm-adapter/issues . We will help you solve it there. Thanks!
