### ISSUE TITLE
Incorrect format in logs module

### ISSUE THREAD

**Issue by wpliang** [beego/beego#4480]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.16rc1 darwin/arm64
bee version v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
darwin/arm64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
`Log = logs.NewLogger(10000)
	logConfig := `{
		"filename":"logs/cmdb-api.log",
		"separate":["error", "warning", "info", "debug"],
		"maxdays":30,
		"perm":"755"
	}`
	Log.SetLogger(logs.AdapterMultiFile, logConfig)
	Log.EnableFuncCallDepth(true)

Log.Debug("\n\tVersion:\t%v\n\tGoVersion:\t%v\n\tCommitID:\t%v\n\tBuildTime:\t%v\n",
		Version, GoVersion, CommitID, BuildStamp)
`
In cmdb-api.log the log msg is not correcnt because placeholders are still in msg ，it looks like：
2021/02/03 20:18:55.640  [D] [proc.go:225]  
	Version:	%v
	GoVersion:	%v
	CommitID:	%v
	BuildTime:	%v
But in cmdb-api.debug.log, output is correct：
2021/02/03 20:18:55.640  [D] [proc.go:225]  
	Version:	Unknown
	GoVersion:	go1.16
	CommitID:	Unknown
	BuildTime:	Unknown

4. What did you expect to see?
Hope output in cmdb-api.log is correct

5. What did you see instead?

**Comment by flycash** [comment]
After merged #4482, you could change your beego's version to master branch laster commit id.
