### ISSUE TITLE
Why the arcchive log files' Perm is 0440? It's better to be configurable

### ISSUE THREAD

**Issue by struggle0119** [beego/beego#4481]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego2.0

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
It's alreay configurable, check `RotatePerm` config item.
```go
type fileLogWriter struct {
// ...
 RotatePerm string `json:"rotateperm"`
//...
}
```
