### ISSUE TITLE
beego logs can not be built

### ISSUE THREAD

**Issue by nous23** [beego/beego#4483]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.15.8
github.com/beego/beego/v2 v2.0.1

2. What operating system and processor architecture are you using (`go env`)?
set GOHOSTARCH=amd64
set GOHOSTOS=windows

3. What did you do?

```
package main

import (
	"github.com/beego/beego/v2/core/logs"
)

func main() {
	logs.Info("hello beego")
}
```

4. What did you expect to see?
logs "hello beego" in console

5. What did you see instead?
C:\Users\nous23\Desktop\awesomeProject>go build -o log.exe main.go
go build command-line-arguments: copying C:\Users\nous23\AppData\Local\Temp\go-build577796122\b001\exe\a.out.exe: open log.exe: Access is denied.

BTW, when "github.com/beego/beego/v2/server/web" are also imported, it can be built and run, but when only "github.com/beego/beego/v2/core/logs" is imported, it does not work.

**Comment by flycash** [comment]
I try it on my MAC, it works as expected. Could you provide the file mode of log.exe ?

**Comment by flycash** [comment]
@jianzhiyao could you help to try this issue?

**Comment by jianzhiyao** [comment]
I can't reproduce what you described.

That tips only showing up when you use beego?
```
# It seems your account are not under permissions
go build command-line-arguments: copying C:\Users\nous23\AppData\Local\Temp\go-build577796122\b001\exe\a.out.exe: open log.exe: Access is denied.
```

**Comment by nous23** [comment]
I found it is because of anti-virus software.
Thanks for everyone.
