### ISSUE TITLE
go新手对v2版本提一些建议

### ISSUE THREAD

**Issue by ayamzh** [beego/beego#4487]
最近简单用了用口碑很好的goframe框架，对比现在v2版本的简介，提一些改进建议。
1、goframe更像用laravel写php的感觉，很爽，大而全，能想到的组件全部内置好了，很少需要第三方的轮子了。同时内置了很多方便的数据结构gmap gset glist  gtree对go的基本数据类型做了个补充。业务部分官方建议做controller service dao model四层结构的小拆分，比beego多了service层很好的解耦了controller和dao层，dao层做数据访问,model只做对象映射，属于datamapper类的orm设计，比activerecord类的orm更适合大型项目。这块可以借鉴下。

2、希望bind和render方法提供对常用数据格式的支持，现在大部分项目都是用protobuf了。

3、我们自己公司内部的框架，可以自适应json和protobuf，根据header判断用哪种方式unmarshal。方便调试。

4、增加对短链接项目的保序功能，放到中间件里，防止短时间内客户端重复发送请求或者弱网重试导致同样请求被重复处理

5、支持客户端请求合批，比如某些场景要同时访问2个接口，常见的做法就是客户端发送两次请求，或者服务器端一个conttoller里聚合两个请求的数据。前者性能不好后者业务耦合。接口职责不单一了。希望可以支持一次httprequest 通过协议里包上请求数据的数组，聚合两个请求，服务器一并处理后返回。同时后端也能支持主动返回多条response，也是利用数组。主要用于Areqeust修改了 其他模块的属性，但两个模块又都又各自的response，这样批量反回，客户端可以监听不同的response做处理，类似一个事件机制

**Comment by flycash** [comment]
很好的建议。一些比较容易达成的，我会在接下来创建出来issue。感谢。可以后续关注TODO List。

**Comment by ayamzh** [comment]
收到 ,老大辛苦，年后我找下我们这边中间件初始化依赖的接口和通信协议的设计，我感觉要比gf设计的外层协议合理一些

**Comment by flycash** [comment]
#4491 #4492 这两个对应到2和3，我们一直在努力提高Beego框架的方便性，这也算是一个不错的改进了如果你有兴趣，你可以考虑帮我们实现。

1 我们已经在设计新的模板了，不过主要是依据golang的官方标准模板来设计，参考 https://github.com/golang-standards/project-layout
4 我的理解是，这是一种业务需求，我们中间件不方便做这种事情，它本质上类似于表单重复提交问题，一般需要生成唯一ID来处理，还需要引入持久化等机制，对中间件来说，这是不可接受的。如果你使用Beego，你可以考虑使用Beego的Filter机制，在入口处统一做这种唯一性校验；
5 这种需求更加罕见，我们同样认为这是一种业务强相关的东西。绝大多数用户并不会遇到这种问题，而要支持这种模式，对于Beego来说需要重构很多地方——它从根源上违背了我们的设计原则——代价高而收益比较小。
