### ISSUE TITLE
The QuerySetter.FilterRaw doesn't support specify parameters which may cause sql injection

### ISSUE THREAD

**Issue by ywk253100** [beego/beego#4489]
Currently the definition of `FilterRaw` of `QuerySetter` is:
```
FilterRaw(string, string) QuerySeter
```

We need to use it like this:
```
FilterRaw("id", fmt.Springf("in (select id from table1 where column1='%s')", input))
```

When concatting the sql `fmt.Springf("in (select id from table1 where column1='%s')", input)`, the attacker may do injection via `input`.

So is possible to pass parameters to `FilterRaw` just like other methods of `QuerySetter`?
```
FilterRaw(string, string, ...interface{}) QuerySeter
```

**Comment by flycash** [comment]
I agree with you that this may casue SQL injection. But I think that change to  
```go
FilterRaw(string, string, ...interface{}) QuerySeter
```
could not resolve this problem.

From your porposl, I guess that you want Beego do string concating, looks like:
```go
FilterRaw(name string, value string, args...interface{}) QuerySeter {
    filterRaw(name, fmt.Sprint(value, args...))
}
```
If users pass `args` like "; Drop table user;", it's not safe either.

For example, 
```go
FilterRaw("id", "in (select id from table1 where column1= 's%' ", "s' and column1 !='; drop table user"))
```

**Comment by ywk253100** [comment]
@flycash I'm not saying beego should do the string concatting. String concatting cannot avoid the sql injection issue no matter who do that.

What I mean is that we can implement the passing argument logic just like what other methods of `QuerySetter` do(using the sql prepare statement rather than concatting string).
e.g. we can passing args to `Filter(expr string, args ...interface{}) QuerySeter` without worrying the sql injection

**Comment by flycash** [comment]
Ok, I got your point.

I just checked Beego's code, it's not a easy task. 

I think it worth to do this enhancement.

**Comment by ywk253100** [comment]
Please remove the `inactive-issue` label
