### ISSUE TITLE
orm 增加hooks 功能

### ISSUE THREAD

**Issue by xwinie** [beego/beego#4490]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
在有的情况下 需要添加前，添加后 做部分操作需要hooks 功能

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
你可以尝试使用ORM的filter功能。不过因为早期接口设计没有考虑AOP，所以你需要在Filter内部判断是不是插入操作，而且只能依赖于ORM接口的方法名来判断。

Filter我们全面引入的用于解决AOP的方案，也包括你说的hooks。

**Comment by xwinie** [comment]
filter 是 查询的filter还是中间件的filter？如果中间件 做不到同样的效果。我还是建议增加这个功能

**Comment by flycash** [comment]
Orm接口的filter。你可以参考 orm/filter 下面的几个实现。我觉得应该是满足你的需求的。

**Comment by xwinie** [comment]
好的，谢谢 我研究下
