### ISSUE TITLE
Proposal: Add Resp() method for web.Controller

### ISSUE THREAD

**Issue by flycash** [beego/beego#4492]
Now, if we want to output response, we have to do:
```go
c.Data["json"]
c.ServeJSON()
```
In fact, we could provide some simple APIs.

I propose adding several new function to `web.controller`.

```go
func (c *Controller) JSONResp(data interface{}) error {
    j := json.Marshal
 // ... 
}

func (c *Controller) XmlResp(data interface{}) error {

}

func (c *Controller) ProtobufResp(data interface{}) error {

}

func (c *Context) Resp(data interface{}) error {
   accept = Header("Accecpt")
   switch accept {
     case json: return JSONResp()
     // ...
     default:
       return err
   }
}

// user
c.JSONResp(user)

```

**Comment by preetham** [comment]
@flycash  I'd like to work on this, can you please explain a bit more on the requirement here? Are these methods expected to marshal the data into respective formats and set it somewhere? A little context would be great.

**Comment by maneeshbabu** [comment]
@flycash Can I pick this one? Or someone else is already working on this request?

**Comment by flycash** [comment]
> @flycash Can I pick this one? Or someone else is already working on this request?

Thanks, now I assigned it to you
