### ISSUE TITLE
beego 2.01 pack打包后报错

### ISSUE THREAD

**Issue by barryzxy** [beego/beego#4494]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee 2.0.2

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
打包后，放入其他位置执行报错。
PS C:\devchat.tar> .\devchat.exe
2021/02/14 08:51:54.955 [I] [main.go:37]  host:localhost|port:3306|db:ions_zhiliao

panic: err: chdir C:\devchat.tar\controllers: The system cannot find the file specified.: stderr:

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
        Z:/gowork/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:83 +0x21f
sync.(*Once).doSlow(0x1b50be8, 0x13125e0)
        C:/Go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
        C:/Go/src/sync/once.go:59
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
        Z:/gowork/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:69 +0x54
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc00050eff0, 0x0, 0x0, 0x0, 0x0, 0x0)
        Z:/gowork/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/server.go:85 +0x3b
github.com/beego/beego/v2/server/web.Run(0x0, 0x0, 0x0)
        Z:/gowork/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:57 +0x6b
main.main()
        Z:/gowork/src/tmaitech/devchat/main.go:72 +0xec
PS C:\devchat.tar>

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
Do not use "dev" as runmode when you use bee pack. Bee pack should be used in test, or prod mode.

**Comment by xyzgamestudios** [comment]
可以直接使用go build来打包
例如：
go build -ldflags "-s -w" -o .

**Comment by flycash** [comment]
这个BUG我已经修复了。 #4486

**Comment by flycash** [comment]
下一次发版将会带上。往后将不会自动生成注解路由，依赖于用户手工执行bee命令。我觉得这是一个更好的体验。
