### ISSUE TITLE
quickstart go get failed

### ISSUE THREAD

**Issue by htmlrust** [beego/beego#4497]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.15.8 windows/amd64
no install bee

2. What operating system and processor architecture are you using (`go env`)?
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\windows10go\AppData\Local\go-build
set GOENV=C:\Users\windows10go\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\windows10go\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\windows10go\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebu=0 -fdebug-prefix-map=C:\Users\WINDOW~1\AppData\Local\Temp\go-build655678970=/tmp/go-buiecord-gccld -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
open https://beego.me/quickstart
open ms vs code
终端-新终端

$ go get -u github.com/beego/beego/v2
cannot find package "github.com/beego/beego/v2" in any of:
        C:\Program Files\Go\src\github.com\beego\beego\v2 (from $GOROOT)    
        C:\Users\windows10go\go\src\github.com\beego\beego\v2 (from $GOPATH)

4. What did you expect to see?

go get no error

5. What did you see instead?
go get installed successfully

**Comment by xyzgamestudios** [comment]
try it with setting => GOPROXY="https://goproxy.cn,direct"

**Comment by htmlrust** [comment]
My windows10 uses linux TPROXY router


git can download beego without a proxy

```
$ time git clone https://github.com/beego/beego
Cloning into 'beego'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (43/43), done.
Rremote: Total 21223 (delta 14), reused 30 (delta 11), pack-reused 21168Receiving objects: 100% (21223/21223), 9.78 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (13045/13045), done.


real    0m8.432s
user    0m0.000s
sys     0m0.015s
```

I think the error may be related to go get

```
$ go get -u github.com/beego/beego/v2
cannot find package "github.com/beego/beego/v2" in any of:
        C:\Program Files\Go\src\github.com\beego\beego\v2 (from $GOROOT)    
        C:\Users\windows10go\go\src\github.com\beego\beego\v2 (from $GOPATH)
```

**Comment by flycash** [comment]
do you set GOMODULE111 = on ?

**Comment by htmlrust** [comment]
> do you set GOMODULE111 = on ?

Sorry to follow the settings you said, and then run go get to get the same error

```
$ set GO111MODULE=on

$ go get -u github.com/beego/beego/v2
cannot find package "github.com/beego/beego/v2" in any of:
        C:\Program Files\Go\src\github.com\beego\beego\v2 (from $GOROOT)    
        C:\Users\windows10go\go\src\github.com\beego\beego\v2 (from $GOPATH)
```

**Comment by htmlrust** [comment]
I refer to the quick start and found that you need to use export GO111MODULE=on to set environment variables

```
# 如果您还没添加 $GOPATH 变量
$ echo 'export GOPATH="$HOME/go"' >> ~/.profile # 或者 ~/.zshrc, ~/.cshrc, 您所使用的sh对应的配置文件

# 如果您已经添加了 $GOPATH 变量
$ echo 'export PATH="$GOPATH/bin:$PATH"' >> ~/.profile # 或者 ~/.zshrc, ~/.cshrc, 您所使用的sh对应的配置文件
$ exec $SHELL
```

I installed it
```

$ go env | grep GO111
set GO111MODULE=

$ export  GO111MODULE=on

$ go env | grep GO111
set GO111MODULE=on

$ go get -u github.com/beego/beego/v2
go: downloading github.com/beego/beego v1.12.3
go: downloading github.com/beego/beego/v2 v2.0.1
go: github.com/beego/beego/v2 upgrade => v2.0.1
```

**Comment by flycash** [comment]
So you resolve your problem?

**Comment by htmlrust** [comment]
Yes, this problem has been solved, thank you very much beego author
