### ISSUE TITLE
How to use the Success and Failure field in a commentsRouter.

### ISSUE THREAD

**Issue by xinyuwang-hotstar** [beego/beego#4499]
beego 2.0.2
go1.15.7

Hi,

I'm using commentsRouter to generate API and swagger. And I want to know how to use the `Success` and `Failure` in the comments.

For example, if I abort with 400, it returns `HTTP/1.1 400 Bad Request`, there is no info about ` Invalid email supplied`.
How can I get this info in response? Or the comments are just for docs?

```
// @Title getStaticBlock
// @Description get all the staticblock by key
// @Param   key     path    string  true        "The email for login"
// @Success 200 {object} models.ZDTCustomer.Customer 
// @Failure 400 Invalid email supplied
// @Failure 404 User not found
// @router /staticblock/:key [get]
func (c *CMSController) StaticBlock() {
    c.Abort("400")
}
```

Thanks in advance.

**Comment by flycash** [comment]
I think you got something misunderstand. The `Success` and `Failure` were used to generate swagger file, not for router.
You should do this by yourself:
```go
CustomAbort(400, "invalid email supplied")
```

**Comment by xinyuwang-hotstar** [comment]
@flycash many thanks.
