### ISSUE TITLE
beego 会支持 embed 方式打包吗

### ISSUE THREAD

**Issue by barryzxy** [beego/beego#4505]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

beego 2.01
2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
不会。目前来看，embed的更加大的价值在于工具，所以我们考虑使用embed的手段，改造我们的bee工具。
