### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by SlippyJimmy** [beego/beego#4509]
There are mistake in `core/validation`
![image](https://user-images.githubusercontent.com/45062658/108709754-1bd86f00-754e-11eb-9736-c553f33a338c.png)
![image](https://user-images.githubusercontent.com/45062658/108709777-2266e680-754e-11eb-88f3-37786b3a7ea9.png)

**Comment by flycash** [comment]
Could you make a pull request to fix it?
