### ISSUE TITLE
使用QueryRows获取对象列表, 外键的属性怎么获取ID

### ISSUE THREAD

**Issue by tuyula** [beego/beego#4510]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
没看懂问题

**Comment by flycash** [comment]
没反馈，我先关了
