### ISSUE TITLE
beego.AppConfig does not exist in Bee v2.0.2

### ISSUE THREAD

**Issue by Kavita4601** [beego/beego#4512]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.15.8

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64

3. What did you do?
[root@shadings1 appliance-management-api]# bee run
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2
2021/02/24 09:19:42 INFO     ▶ 0001 Using 'appliance-management-api' as 'appname'
2021/02/24 09:19:42 INFO     ▶ 0002 Initializing watcher...
appliance-management-api/utils
# appliance-management-api/utils
utils/utils.go:67:25: undefined: beego.AppConfig
utils/utils.go:77:3: undefined: beego.Info

beego.Info or beego.AppConfig does not exist in beev2.0.2. 

As beego.Info has changed to logs.Info. beego.AppConfig has changed to something else in Bee v2.0.2 ?
How to use beego.AppConfig in Beev2.0.2

**Comment by flycash** [comment]
If your project is based on Beegov2, you are able to find `AppConfig` under `web` package
