### ISSUE TITLE
 orm is failed to synchronize the database and the table's structure

### ISSUE THREAD

**Issue by crochee** [beego/beego#4515]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
golang:1.14
beego:1.12.2

2. What operating system and processor architecture are you using (`go env`)?
linux x86

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

When the current ORM synchronizes the table, only the alias of default is recognized, and the registered alias cannot be registered repeatedly. When I want to refresh his value, no method is provided for this value, resulting in the failure to synchronize the database and the table's structure if the remote database is suddenly switched.

4. What did you expect to see?
i want to have a pubic method to flush dataBaseCache's default value

5. What did you see instead?
The source code is as follows:
// add database alias with original name.
func (ac *_dbCache) add(name string, al *alias) (added bool) {
	ac.mux.Lock()
	defer ac.mux.Unlock()
	if _, ok := ac.cache[name]; !ok {
		ac.cache[name] = al
		added = true
	}
	return
}

// get database alias if cached.
func (ac *_dbCache) get(name string) (al *alias, ok bool) {
	ac.mux.RLock()
	defer ac.mux.RUnlock()
	al, ok = ac.cache[name]
	return
}

// get default alias.
func (ac *_dbCache) getDefault() (al *alias) {
	al, _ = ac.get("default")
	return
}

but RunSyncdb->BootStrap() method only takes effect in default

**Comment by flycash** [comment]
You could pass database name:
```go
// RunSyncdb run syncdb command line.
// name: Table's alias name (default is "default")
// force: Run the next sql command even if the current gave an error
// verbose: Print all information, useful for debugging
func RunSyncdb(name string, force bool, verbose bool) error {
```

**Comment by crochee** [comment]
this method only takes effect once,i want to flush when change

**Comment by flycash** [comment]
> this method only takes effect once,i want to flush when change

It will update schema. But in some cases it won't. For example, when you remove a field from your entity definition, it won't delete the column.
