### ISSUE TITLE
ORM，rel(m2m)报错

### ISSUE THREAD

**Issue by a285277906** [beego/beego#4516]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.1

2. What operating system and processor architecture are you using (`go env`)?
windows/amd64

3. What did you do?

遇到了点麻烦，一直在报错
panic: reflect: call of reflect.Value.MethodByName on zero Value

后来检查了一下，确认rel(m2m)的情况下会报错这个，刚刚更新的v2.0.1，mod。

用去年的版本没有报错，也不知道是什么原因导致的。

下面是报错的全部信息

panic: reflect: call of reflect.Value.MethodByName on zero Value

goroutine 1 [running]:
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x1253fcd, 0x16, 0xc000119722, 0x1170c9b, 0x9)
	C:/Program Files/Go/src/reflect/value.go:1354 +0x205
github.com/beego/beego/v2/client/orm.isApplicableTableForDB(0x0, 0x0, 0x0, 0x12467d2, 0x7, 0xc00011cf01)
	E:/GoProject/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_utils.go:112 +0x76
github.com/beego/beego/v2/client/orm.(*commandSyncDb).Run(0xc0000c1c50, 0x7, 0xc00012c000)
	E:/GoProject/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:146 +0xb58
github.com/beego/beego/v2/client/orm.RunSyncdb(0x12467d2, 0x7, 0x1240100, 0x5, 0xc00011e000)
	E:/GoProject/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:298 +0x90
main.initDatabase()
	E:/GoProject/operation_service/main.go:56 +0x4fc
main.init.0()
	E:/GoProject/operation_service/main.go:21 +0xaf

**Comment by a285277906** [comment]
panic: reflect: call of reflect.Value.MethodByName on zero Value

goroutine 1 [running]:
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x1253fcd, 0x16, 0xc000119722, 0x1170c9b, 0x9)
	C:/Program Files/Go/src/reflect/value.go:1354 +0x205
github.com/beego/beego/v2/client/orm.isApplicableTableForDB(0x0, 0x0, 0x0, 0x12467d2, 0x7, 0xc00011cf01)
	E:/GoProject/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_utils.go:112 +0x76
github.com/beego/beego/v2/client/orm.(*commandSyncDb).Run(0xc0000c1c50, 0x7, 0xc00012c000)
	E:/GoProject/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:146 +0xb58
github.com/beego/beego/v2/client/orm.RunSyncdb(0x12467d2, 0x7, 0x1240100, 0x5, 0xc00011e000)
	E:/GoProject/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:298 +0x90
main.initDatabase()
	E:/GoProject/operation_service/main.go:56 +0x4fc
main.init.0()
	E:/GoProject/operation_service/main.go:21 +0xaf

**Comment by flycash** [comment]
Please update to master branch. We had resolved this problem. 
You could use master branch because only bug fix will be merged into it. New features are in develop branch.

**Comment by flycash** [comment]
go get -u xxx@master，就是最后版本号指定master就可以

**Comment by a285277906** [comment]
在mod中指定的是版本号吧？

go 1.16

require github.com/beego/beego/v2 v2.0.1

**Comment by flycash** [comment]
不是，你直接在命令行里面执行
```shell
go get -u github.com/beego/beego/v2/beego@master
```

你修改mod文件需要找到对应的commit号，我建议你直接执行上面的命令。

**Comment by a285277906** [comment]
好的，明天去公司试试，这个问题着实困扰我几天了，万分感谢您的回复和解答，以及十分佩服您写的beego框架。

**Comment by flycash** [comment]
哈哈哈，我是后面维护的，这是谢大写的。我先关了，你有问题继续留言，我如果不是这两天特别忙，我基本上每天看github的
