### ISSUE TITLE
关于RelatedSel在列表查询中的层次问题

### ISSUE THREAD

**Issue by a285277906** [beego/beego#4518]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2-0.20210221043946-45ab79249aab

2. What operating system and processor architecture are you using (`go env`)?
windows/amd64

3. What did you do?
有个问题需要咨询一下，

orm.QueryTable(Bean{}).Filter("id",1).RelatedSel().One(&v)
在这种查询下可以查到一条数据所关联的最大五层的其他对象

orm.QueryTable(Bean{}).Filter("id__gte",1).RelatedSel().All(&vList)
在这种查询下却是一层都不关联

这种问题是有解决方式么？

**Comment by flycash** [comment]
你可以提供一个简单的复现的例子吗？按照道理来说，这样执行就可以的。我需要看看发生了什么问题。

**Comment by a285277906** [comment]
可以复现这个问题

以下代码是我目前正在用的在列表中逐个LoadRelated
直接.RelatedSel()这个是返回不出userModuleList和userList的
构造都是m2m
反向构造是不是不可以RelatedSel()

type PermissionGroup struct {
	Id             int           `orm:"unique;column(id);auto;pk" description:"id" json:"id"`
	GroupName      string        `orm:"column(groupName)" description:"权限组名" json:"groupName"`
	Remark         string        `orm:"column(remark);null" description:"备注" json:"remark"`
	UserModuleList []*UserModule `orm:"column(userModuleList);reverse(many);null" json:"userModuleList,omitempty"`
	UserList       []*User       `orm:"column(userList);reverse(many);null" json:"userList,omitempty"`
}

func init() {
	orm.RegisterModel(new(PermissionGroup))
}

func (u *PermissionGroup) TableName() string {
	return "permission_group"
}

//获得所有权限组
func GetAllPermissionGroup(index, page int) (permissionGroupList []*PermissionGroup, count, recordsFiltered int64, err error) {
	o := orm.NewOrm()
	qs := o.QueryTable(PermissionGroup{})

	if count, err = qs.Limit(index, (page-1)*index).RelatedSel().All(&permissionGroupList); err != nil {
		return nil, 0, 0, err
	}
	if recordsFiltered, err = qs.Count(); err != nil {
		return nil, 0, 0, err
	}
	for _, value := range permissionGroupList {
		_, _ = o.LoadRelated(value, "userModuleList")
		_, _ = o.LoadRelated(value, "userList")
	}
	return permissionGroupList, count, recordsFiltered, nil
}

**Comment by flycash** [comment]
我需要研究一下，这一堆代码，略微有点复杂
