### ISSUE TITLE
How to rename the default session cookie name: beegosessionID ?

### ISSUE THREAD

**Issue by hsluoyz** [beego/beego#4521]
Beego uses `beegosessionID` as session cookie key by default. Is there any way to change this cookie name? (like change it to mySessionId)

![image](https://user-images.githubusercontent.com/3787410/110141860-86bc5c80-7e10-11eb-8ed2-80ad4cf0000c.png)

**Comment by flycash** [comment]
![Screenshot from 2021-03-07 19-02-51](https://user-images.githubusercontent.com/9923838/110237582-c5b8f200-7f77-11eb-8262-80fe2a4e7912.png)
Please check the `BConfig.WebConfig.Session.SessionName`

**Comment by hsluoyz** [comment]
Thanks!
