### ISSUE TITLE
“方法表达式路由”例子报错

### ISSUE THREAD

**Issue by liuts** [beego/beego#4527]
复制文档里面的代码，build的时候报错“undefined: web.RouterGet”。
文档地址https://beego.me/docs/mvc/controller/router.md

beego 版本：github.com/beego/beego/v2 v2.0.1

下面是测试代码：

package main

import "github.com/beego/beego/v2/server/web"

type BaseController struct {
	web.Controller
}

func (b BaseController) Ping() {
	b.Data["json"] = "pong"
	b.ServeJSON()
}

func (b *BaseController) PingPointer() {
	b.Data["json"] = "pong_pointer"
	b.ServeJSON()
}

func main() {
	web.RouterGet("/ping", BaseController.Ping)
	web.RouterGet("/ping_pointer", (*BaseController).PingPointer)
	web.Run()
}

**Comment by flycash** [comment]
This methods are in develop branch, and it's not released yet. if you want to use it, please update your version to develop latest commit.
