### ISSUE TITLE
go 协程中panic 会导致服务crash掉，RecoverFunc 对协程不起作用

### ISSUE THREAD

**Issue by struggle0119** [beego/beego#4530]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
2

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by jianzhiyao** [comment]
golang协程中的panic需要自行解决，有需要可以搜索相关的panic处理的库
