### ISSUE TITLE
beego logs添加自定义日志格式后，输出的日志级别错误，无法正确格式化

### ISSUE THREAD

**Issue by forgetST** [beego/beego#4532]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2@v2.0.0

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```go
package main

import (
    "github.com/beego/beego/v2/core/logs"
)

func main() {
    f := &logs.PatternLogFormatter{
        Pattern:    "%F:%n|%w (%t-%T) >> %m",
        WhenFormat: "2006-01-02",
    }

    logs.RegisterFormatter("pattern", f)
    _ = logs.SetGlobalFormatter("pattern")

    log := logs.NewLogger()
    _ = log.SetLogger(logs.AdapterConsole, `{"formatter": "pattern"}`)
    log.EnableFuncCallDepth(false)

    log.Info("hello, %v", "world")
    log.Warn("hello")
}

/ *
D:\Project\Go\win_agent\myscript>go run ts_logs.go
E:/Environment/Go1.15.6/src/runtime/proc.go:204|2021-03-10 ([N]-notice) >> hello, %v
E:/Environment/Go1.15.6/src/runtime/proc.go:204|2021-03-10 ([E]-error) >> hello
*/
```

4. What did you expect to see?
```log
D:\Project\Go\win_agent\myscript>go run ts_logs.go
E:/Environment/Go1.15.6/src/runtime/proc.go:204|2021-03-10 ([N]-notice) >> hello, %v
E:/Environment/Go1.15.6/src/runtime/proc.go:204|2021-03-10 ([E]-error) >> hello
```

5. What did you see instead?

**Comment by flycash** [comment]
你切换到master版本，再试试。我们应该修复了这个问题。

**Comment by forgetST** [comment]
具体是怎么操作的，我直接将beego那版代码全部删掉，然后用master分支代码替换后，结果还是一样的。
![image](https://user-images.githubusercontent.com/53183034/111253944-fe7b5a00-864e-11eb-896f-ee7cdbb28349.png)

**Comment by flycash** [comment]
抱歉，没合并过去master。我单独摘出来合并过去了，你可以从新更新代码试试了。非常抱歉，记错了。：）
