### ISSUE TITLE
beego/goroutine/net.DialTimeout()

### ISSUE THREAD

**Issue by demingry** [beego/beego#4534]
[v1.12.0]
[windows 10 | centos 7]

要做一个在线端口扫描器，beego起goroutine去做net.DialTimeout操作，当端口数量小时，可以正常运行检测端口是否开启，但检测端口一多就报错,报错信息主要如下:
goroutine 58 [IO wait]:
goroutine 46 [select]:  
goroutine 418 [running]:

写了两套代码，不在beego上运行时go build 执行文件后全部正常运行.

**Comment by flycash** [comment]
没理解，你说的beego 起 goroutine 做 ne.DialTimeout是什么场景？
