### ISSUE TITLE
路由无法完全匹配，可能会给路由权限验证带来安全隐患

### ISSUE THREAD

**Issue by Bearki** [beego/beego#4536]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
![image](https://user-images.githubusercontent.com/59725082/111114115-c23bf100-859d-11eb-847d-c8151d9532e1.png)

2. What operating system and processor architecture are you using (`go env`)?
![image](https://user-images.githubusercontent.com/59725082/111114196-dc75cf00-859d-11eb-87a7-dbbdb6e8d381.png)

3. What did you do?
![image](https://user-images.githubusercontent.com/59725082/111114277-fc0cf780-859d-11eb-9d37-9626d99d3f62.png)

4. What did you expect to see?
希望路由在不影响正则规则条件下能完全匹配

5. What did you see instead?
![image](https://user-images.githubusercontent.com/59725082/111114309-07602300-859e-11eb-872f-47a77793c788.png)

**Comment by flycash** [comment]
没看懂……

**Comment by Bearki** [comment]
在”/api/v1/user/signout“后面加N个”/“仍然可以访问到该路由，能不能完全匹配，使”/api/v1/user/signout///////“不能被访问到

**Comment by flycash** [comment]
我理解你的意思了。我感觉这似乎挺正常的，我试了很多网站，貌似这种后面加/都能匹配上去，包括国内外很多大厂的网站都是。所以我觉得，可能这样并不会带来什么问题。

你能给个具体的这样带来危害的例子吗？
