### ISSUE TITLE
I found a 'bug' easy to mixuse,  beego have two orm package

### ISSUE THREAD

**Issue by 4kzeng** [beego/beego#4537]
two orm path:
	"github.com/beego/beego/v2/adapter/orm"
	"github.com/beego/beego/v2/client/orm"

on the editor would auto import first path bcz the prefix 'a'.  In my   models have a func like that:
     func GetUserList(page int64, page_size int64) (ms []orm.Params, count int64)
It report's compile error: wrong type parameters,.  I waste time and time,  found that error is import wrong package path.

**Comment by flycash** [comment]
Yes, we could not avoid this because we want to make upgrading from v1 to v2 easier. So we use `adapter/orm` as adapter layer that help tp upgrade. But actually, if you don't work with V1 API, please use `client/orm`.

Sorry about that. And if you have better idea, please tell us :)

**Comment by roberChen** [comment]
I'm currently migrating beego from v1 to v2 for mindoc, and I suggest you DON'T USE adapter package! And DON'T MIX USE adapter and other packages.
