### ISSUE TITLE
prod模式下静态文件访问不打印日志？

### ISSUE THREAD

**Issue by SloanAufderstrase** [beego/beego#4543]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2@2.0.0

2. What operating system and processor architecture are you using (`go env`)?
**app.conf**
```
appname = bapi
httpport = 8092
runmode = prod
autorender = false
copyrequestbody = true
EnableDocs = true
```
```
package main
import (
	_ "bapi/routers"
	"github.com/beego/beego/v2/core/logs"
	beego "github.com/beego/beego/v2/server/web"
)

func main() {
	beego.BConfig.Log.AccessLogs = true
	beego.SetStaticPath("/fun", "fun")
	beego.Run()
}
```
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

我没有设置输出访问信息到日志文件中，默认只打印在终端上。但结果是一样的，就是prod模式下，静态访问没有日志打印。
无论beego.BConfig.Log.AccessLogs 为true或者false。

`curl "http://127.0.0.1:8092/fun/funplayer.txt"`,获得了结果，但无日志输出。非静态访问可以看到日志。

4. What did you expect to see?
希望静态访问也能够打印日志.

5. What did you see instead?

**Comment by SloanAufderstrase** [comment]
我知道了：beego.BConfig.Log.EnableStaticLogs = true 即可，我没有在文档中看到关于这个配置项的说明

**Comment by flycash** [comment]
> 我知道了：beego.BConfig.Log.EnableStaticLogs = true 即可，我没有在文档中看到关于这个配置项的说明

求发个PR，帮我们完善一下文档，到beego/beedoc下
