### ISSUE TITLE
server doesn't start when runmode = "dev"

### ISSUE THREAD

**Issue by BenAtIBM** [beego/beego#4545]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
require github.com/beego/beego/v2 v2.0.1
go version go1.16 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Create a simple hello world app:
```
package main

import (
	"github.com/beego/beego/v2/core/logs"
	"github.com/beego/beego/v2/server/web"
)

type MainController struct {
	web.Controller
}

func (this *MainController) Get() {
	this.Ctx.WriteString("hello world")
}

func main() {
	logs.SetLogger(logs.AdapterConsole, `{"level":1}`)
	web.Router("/", &MainController{})
	web.Run()
}
```
Create a config file `conf/app.conf`
```
appname = test_serv
[dev]
httpport = 9090
```
See it start running properly using default port of 8080.
```
go run serv.go
2021/03/23 13:59:18.538 [I] [server.go:241]  http server Running on http://:8080
```
**Now set runmode = "dev"**
```
runmode = "dev"
appname = test_serv
[dev]
httpport = 9090
```
And try to run again:
```
go run serv.go

```
And nothing happens.  No errors/warnings and the server does not start.

4. What did you expect to see?
I expected to see it start the server on port 9090 instead of 8080

5. What did you see instead?
Nothing.  It didn't give in output and the server did not start.

**Comment by flycash** [comment]
I can not reproduce this question. 
```
appname = test_serv
[dev]
httpport = 9090
``` 
won't work because you need to specific your `runmode`.
But I run test with:
```
runmode = "dev"
appname = test_serv
[dev]
httpport = 9090
```
It worked as expected.Could you try again? 
Here is part of my `go env`
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"

```

**Comment by BenAtIBM** [comment]
It seems the problem was that I didn't have "routers" and "controllers" subdirectories.  If I create them `runmode = "dev"` works as expected.

**Comment by flycash** [comment]
> controllers

Yes, I had fixed this problem last month. :)

**Comment by BenAtIBM** [comment]
Thanks, closing.
