### ISSUE TITLE
There is a bug of log format

### ISSUE THREAD

**Issue by DDDrop** [beego/beego#4546]
I just run `web.Run()` , and get some logs like:

```
0001/01/01 00:00:00.000 [M] [log.go:191]  [HTTP] http: superfluous response.WriteHeader call from github.com/beego/beego/v2/server/web/context.(*Response).WriteHeader (context.go:230)
```
the timestamp is so weird.

**Comment by flycash** [comment]
How do you print this log? It seems that we had resolved similar issues. Did you use `logs.XXX` ?

**Comment by DDDrop** [comment]
no, I didn't use any `logs.XXX`. This's a default output.

**Comment by flycash** [comment]
let me check it.

**Comment by DDDrop** [comment]
btw, I update my go to 1.16.2.

**Comment by flycash** [comment]
I use golang 1.16 but failed to reproduce the problem. Could you share us the simple code that is able to reproduce the issue? 
I could update my golang to 1.16.2

**Comment by flycash** [comment]
need feekback
