### ISSUE TITLE
go get: module github.com/beego/beego/v2@upgrade found (v2.0.1), but does not contain package github.com/beego/beego/v2/logs

### ISSUE THREAD

**Issue by end-e** [beego/beego#4547]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.16

2. What operating system and processor architecture are you using (`go env`)?
Part of my configuration
 ```
GO111MODULE=on
GOPROXY=https://goproxy.cn
```

3. What did you do?
When I run `go get github.com/beego/beego/v2/logs`,
The console returns
```
go get: module github.com/beego/beego/v2@upgrade found (v2.0.1), but does not contain package github.com/beego/beego/v2/logs
```

**Comment by flycash** [comment]
try this
```
go get github.com/beego/beego/v2/core/logs
```
Sorry, the documents are not right, I corrected it just now.

https://github.com/beego/beedoc/pull/924

**Comment by end-e** [comment]
> try this
> 
> ```
> go get github.com/beego/beego/v2/core/logs
> ```
> 
> Sorry, the documents are not right, I corrected it just now.
> 
> [beego/beedoc#924](https://github.com/beego/beedoc/pull/924)

thanks, It works now.
