### ISSUE TITLE
beego app.conf  配置切片 

### ISSUE THREAD

**Issue by ZhiQiangCoding** [beego/beego#4549]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

v2.0.1
2. What operating system and processor architecture are you using (`go env`)?
1.16

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

key ="a","b",c“”
4. What did you expect to see?
keys,_:=beego.AppConfig.Strings("key")
![image](https://user-images.githubusercontent.com/16265105/112948289-7a56c580-916a-11eb-85ea-df3667ace7e3.png)

运行结果：
![image](https://user-images.githubusercontent.com/16265105/112948479-b12cdb80-916a-11eb-9697-301f620cba85.png)

5. What did you see instead?

**Comment by flycash** [comment]
你这里的配置，是什么格式的？ini吗？

**Comment by ZhiQiangCoding** [comment]
是的，ini方式，老版本这么配置可以正常获取，新版本有问题

**Comment by flycash** [comment]
嗯嗯嗯，让我们看看。新老版本，这个应该没有改动过才对。

**Comment by flycash** [comment]
貌似应该写成：
```
key="a;b;c"
```
老版本也是用`;`作为分隔符的。

**Comment by ZhiQiangCoding** [comment]
可以了，是我搞错了，谢谢！

**Comment by ZhiQiangCoding** [comment]
> 貌似应该写成：
> 
> ```
> key="a;b;c"
> ```
> 
> 老版本也是用`;`作为分隔符的。

可以了，谢谢，是我搞错了
