### ISSUE TITLE
An exception occurred while starting the web application  if it runnig under dev mod

### ISSUE THREAD

**Issue by Joe3160** [beego/beego#4553]
when we use `bee pack` to build the package runngin on the server.
there is the package direction

├── blog.exe
├── conf
│   └── app.conf
├── static
│   ├── js
│   │   └── reload.min.js
│   └── upload
└── views

if We need the project running on "**dev**" mode, then  congratulation, there is a **Panic**
for the reason , the package **missing** the `controller` folder file
file:`github.com\beego\beego\v2@v2.0.1\server\web\hooks.go:99`
```golang
func registerCommentRouter() error {
	if BConfig.RunMode == DEV {
		if err := parserPkg(filepath.Join(WorkPath, BConfig.WebConfig.CommentRouterPath)); err != nil {
			return err
		}
	}

	return nil
}
```
**`BConfig.WebConfig.CommentRouterPath` (`controller`) not exists!**

**Comment by flycash** [comment]
https://github.com/beego/beego/pull/4452, let me move this fix to master branch
