### ISSUE TITLE
httplib开启Debug(true)之后不打印信息

### ISSUE THREAD

**Issue by Bearki** [beego/beego#4554]
Beego v2.0.1版本

httplib包中，httplib.go文件
原来是这样的
![283d67c32b45e01a7bf1e731151bb8c](https://user-images.githubusercontent.com/59725082/113250795-c08b6080-92f3-11eb-8939-3e08ea458c58.png)

我改成这样了
![920c2259fc2595af6912ce95effe2bc](https://user-images.githubusercontent.com/59725082/113250682-8b7f0e00-92f3-11eb-9ae2-b99b25a64dee.png)

**Comment by flycash** [comment]
这是一个误会……按照原本的设计，他们就只是想把这个request dump出来，后面你可以拿到这个`b.dump`。
在`develop`分支上，我们做了一个改进，
你可以看看：
https://github.com/beego/beego/issues/4440
