### ISSUE TITLE
bug(orm): crash by type int when value large than int32

### ISSUE THREAD

**Issue by a631807682** [beego/beego#4555]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11.1

2. What operating system and processor architecture are you using (`go env`)?
> GOARCH="amd64"
GOBIN="/data/go/bin"
GOCACHE="/home/work/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/data/gopath/src"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/data/go"
GOTMPDIR=""
GOTOOLDIR="/data/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build641402558=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
Defined int field and query by orm 

4. What did you expect to see?
Crashed by strconv.ParseInt when value larger than int32

5. What did you see instead?
> int is a signed integer type that is at least 32 bits in size. It is a distinct type, however, and not an alias for, say, int32.  

http://golang.org/pkg/builtin/#int

So int could be bigger than 32 bit in future or on some systems.
But beego will convert to int32. 
https://github.com/beego/beego/blob/develop/client/orm/models_utils.go#L160
https://github.com/beego/beego/blob/develop/client/orm/db.go#L1383

**Comment by flycash** [comment]
It seems that we could not do more thing with this.
In my opinion, users define their field with type int, they should keep in mind that it could be overflow.

**Comment by a631807682** [comment]
@flycash  So in beego orm ,  `int` and `int32` is corresponds to the mysql `integer` .
But i have an `bee` question, i generate model by `generate appcode` cmd , but the pk type is `int` although in `mysql` it's `int64`
https://github.com/beego/bee/blob/develop/generate/g_appcode.go#L454
Now `int` in beego orm means `int32` that's why it overflowed.

**Comment by flycash** [comment]
> @flycash So in beego orm , `int` and `int32` is corresponds to the mysql `integer` .
> But i have an `bee` question, i generate model by `generate appcode` cmd , but the pk type is `int` although in `mysql` it's `int64`
> https://github.com/beego/bee/blob/develop/generate/g_appcode.go#L454
> Now `int` in beego orm means `int32` that's why it overflowed.

I think this is Bee's bug, let me fix it.
