### ISSUE TITLE
orm查询时间时自动补00:00:00

### ISSUE THREAD

**Issue by pingProMax** [beego/beego#4557]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
windows

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```golang
o := orm.NewOrm()
var context Context
o.QueryTable(new(Context)).Filter("create_at__istartswith", "2021-04-02").All(&context)
```
>sql log: WHERE T0.`create_at` LIKE ? ] - `2021-04-02 00:00:00%`

4. What did you expect to see?
>WHERE T0.`create_at` LIKE ? ] - `2021-04-02%`

5. What did you see instead?
>sql log: WHERE T0.`create_at` LIKE ? ] - `2021-04-02 00:00:00%`

我使用的数据库是mysql5.7

model中的字段
```golang
CreateAt      time.Time `orm:"column(create_at);type(datetime);auto_now_add" description:"创建时间"`
```

查询日期的时候自动补 00:00:00 
如果这样 也补了00:00:00 如下：
```golang
o.QueryTable(new(Context)).Filter("create_at__istartswith", "2021-04-02 10:25:25").All(&context)
```
>sql log: WHERE T0.`create_at` = ? ] - `2021-04-02 00:00:00`

是我的问题吗？
在线等

再次
如果我是用原生sql查询如何做到关系查询？
像这样
```golang
o := orm.NewOrm()
	contextArr := make([]Context, 0)
	o.Raw(想像的sql).QueryRows(&contextArr)
	for _, v := range contextArr {
		fmt.Println(v.SortId)
	}
```

SortId在我的Context（model）中是这样的
```golang
	SortId        *Sort     `orm:"column(sort_id);rel(fk)"`
```
似乎这样查询， SortId 只有id有值，其他没有值

**Comment by pingProMax** [comment]
我是用的是mysql

**Comment by flycash** [comment]
1. datetime是会加上时间的，你应该使用date，即 `type(date)`
2. 如果你使用原生查询=。=那么就得自己处理所有的东西。包括怎么递归查询出来引用数据。

**Comment by flycash** [comment]
https://beego.me/docs/mvc/model/models.md

**Comment by pingProMax** [comment]
> 1. datetime是会加上时间的，你应该使用date，即 `type(date)`
> 2. 如果你使用原生查询=。=那么就得自己处理所有的东西。包括如何递归查询出来引用数据。

好的 非常感谢 谢谢
