### ISSUE TITLE
文档中的快速入门无法成功

### ISSUE THREAD

**Issue by haxifang-aircos** [beego/beego#4559]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.16.3 
bee version v2.0.0

2. What operating system and processor architecture are you using (`go env`)?
darwin/amd64

3. What did you do?
 - go get -u github.com/beego/beego/v2
 - go get -u github.com/beego/bee/v2
 - cd $GOPATH/src
 - bee new hello
 - cd hello
 - bee run

4. What did you expect to see?
快速入门能够成功闭环

5. What did you see instead?
![image](https://user-images.githubusercontent.com/61681123/113394439-d3bd2f80-93ca-11eb-9178-dea4c95924a2.png)

**Comment by jianzhiyao** [comment]
There is no need to build new project in gopath :)
![image](https://user-images.githubusercontent.com/6133860/113395068-e126e980-93cb-11eb-9622-1dc952c79951.png)

**Comment by haxifang-aircos** [comment]
> 无需在gopath中构建新项目:)
> ![图像](https://user-images.githubusercontent.com/6133860/113395068-e126e980-93cb-11eb-9622-1dc952c79951.png)

我通过执行 `go mod tidy` 解决了这个问题，我又尝试在 ${gopath} 之外，通过 bee new xxx，但是在 bee run 后仍然有相同的错误，我不得不执行  `go mod tidy`
![image](https://user-images.githubusercontent.com/61681123/113396221-be95d000-93cd-11eb-8bad-2d483ebf4148.png)

**Comment by jianzhiyao** [comment]
看样子已经提供了解决方案给到你了
![image](https://user-images.githubusercontent.com/6133860/113396531-3fed6280-93ce-11eb-8a0d-4ca1ddf218e5.png)

**Comment by haxifang-aircos** [comment]
> 看样子已经提供了解决方案给到你了
> ![image](https://user-images.githubusercontent.com/6133860/113396531-3fed6280-93ce-11eb-8a0d-4ca1ddf218e5.png)

是的，但是我通过提示的解决方案，无法解决这个问题。对不起，我是一个 go 新手
![image](https://user-images.githubusercontent.com/61681123/113397549-cce4eb80-93cf-11eb-8b60-a8b8b46a79c7.png)

**Comment by jianzhiyao** [comment]
PTAL @flycash

**Comment by flycash** [comment]
这个提示不能说基本没用，也可以说是相当没用了。其实是指，在你使用go1.16的情况下，如果go.sum文件没有对应依赖，它就报错。执行
```shell
go mod tidy
```
记得开启GOPROXY，不然可能拉不下来依赖。
