### ISSUE TITLE
Remove beego log in the log file

### ISSUE THREAD

**Issue by zafer06** [beego/beego#4564]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee 2.02

2. What operating system and processor architecture are you using (`go env`)?
linux

I save my log data in the file and I want only my log in the log file. But beego also save system request logs. How can I remove beego request logs in the file?

**Comment by flycash** [comment]
You need to create new `BeeLogger`.
Here is a simple demo:
```go
customLogger := logs.NewLogger()

customLogger.SetLogger("your adapter, file, console, or others", "your config")
```
Here is the `log.go` key methods:
```go
// SetLogger provides a given logger adapter into BeeLogger with config string.
// config must in in JSON format like {"interval":360}}
func (bl *BeeLogger) SetLogger(adapterName string, configs ...string) error {
	bl.lock.Lock()
	defer bl.lock.Unlock()
	if !bl.init {
		bl.outputs = []*nameLogger{}
		bl.init = true
	}
	return bl.setLogger(adapterName, configs...)
}

// NewLogger returns a new BeeLogger.
// channelLen: the number of messages in chan(used where asynchronous is true).
// if the buffering chan is full, logger adapters write to file or other way.
func NewLogger(channelLens ...int64) *BeeLogger {
	bl := new(BeeLogger)
	bl.level = LevelDebug
	bl.loggerFuncCallDepth = 3
	bl.msgChanLen = append(channelLens, 0)[0]
	if bl.msgChanLen <= 0 {
		bl.msgChanLen = defaultAsyncMsgLen
	}
	bl.signalChan = make(chan string, 1)
	bl.setLogger(AdapterConsole)
	return bl
}
```

**Comment by zafer06** [comment]
Thank you @flycash. How do I definition global log variable in my app? For use with other files.

**Comment by flycash** [comment]
> Thank you @flycash. How do I definition global log variable in my app? For use with other files.

you could define your own `logs` module in your app and in this module, it uses custome `BeeLogger` which use other other files.

You could not put your custom `BeeLogger` to Beego's `logs` module

**Comment by zafer06** [comment]
Thank you @flycash
