### ISSUE TITLE
bug(web): panic by access url which exculde in exceptMethod and include in beego.controllers

### ISSUE THREAD

**Issue by a631807682** [beego/beego#4566]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.11.1

2. What operating system and processor architecture are you using (`go env`)?
```
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jdk\AppData\Local\go-build
set GOENV=C:\Users\jdk\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\project\go-project\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\project\go-project
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=C:\project\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\project\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\project\go-project\src\jdk_bushu\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\jdk\AppData\Local\Temp\go-build2105752974=/tmp/go-build -gno-record-gcc-switches
```
3. What did you do?
access `ctrl/getuint16` will panic

4. What did you expect to see?
response 404

5. What did you see instead?
Fill full `exceptMethod` or generate it in `init`, and warning if has the same name method in user's controller.
[router.go#L72](https://github.com/beego/beego/blob/develop/server/web/router.go#L72)
[outer.go#L728](https://github.com/beego/beego/blob/develop/server/web/router.go#L728)
I fix it in the business code
```
var cm beego.Controller
reflectVal := reflect.ValueOf(&cm)
rt := reflectVal.Type()
for i := 0; i < rt.NumMethod(); i++ {
beego.ExceptMethodAppend(rt.Method(i).Name)
}
```

**Comment by flycash** [comment]
I am not sure if it was fixed in later version. Let me check it.

**Comment by flycash** [comment]
I use 1.12.3 and it has been fixed. Here is my code:
```go
type PanicController struct {
	Controller
}

func (c *PanicController) GetUint16() {
	c.Ctx.WriteString("hello, world")
}

func TestName(t *testing.T) {
	ctrl := &PanicController{}
	AutoPrefix("ctrl", ctrl)
	Run()
}
```
get url:`localhost:8080/ctrl/panic/getuint16`

**Comment by a631807682** [comment]
Sorry, i miss some infomation.
I use `AutoRouter` to regist route, and it will regist `beego.Controller.GetUint16` if it not defined in `PanicController `

**Comment by flycash** [comment]
> Sorry, i miss some infomation.
> I use `AutoRouter` to regist route, and it will regist `beego.Controller.GetUint16` if it not defined in `PanicController `

Sorry for late reply, could you provide demo that could reproduce this issue?
When I used `AutoRouter`, it worked as expected.
```go
type PanicController struct {
	Controller
}

func (c *PanicController) GetUint16() {
	c.Ctx.WriteString("hello, world")
}

func TestName(t *testing.T) {
	ctrl := &PanicController{}
	AutoRouter(ctrl)
	Run()
}
```
url: GET `localhost:8080/panic/getuint16`

**Comment by a631807682** [comment]
@flycash 
```
type PanicController struct {
	Controller
}

// func (c *PanicController) GetUint16() {
//	c.Ctx.WriteString("hello, world")
// }

func TestName(t *testing.T) {
	ctrl := &PanicController{}
	AutoRouter(ctrl)
	Run()
}
```

url: GET localhost:8080/panic/getuint16

My point is this route `getuint16` is not regist by user, it's regist by framwork, and when someone accesss that, the program will panic.

**Comment by flycash** [comment]
> My point is this route `getuint16` is not regist by user, it's regist by framwork, and when someone accesss that, the program will panic.

I could get your point. So could you please provide a demo that could reproduce this issue?

**Comment by a631807682** [comment]
https://github.com/a631807682/beegoi4566
