### ISSUE TITLE
bee new创建的 项目后用 bee run 运行后，爆出json解析错误

### ISSUE THREAD

**Issue by sunnnnnner** [beego/beego#4567]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go的版本是1.15.11  beego 是v2 版本  bee的版本是 v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
window10 64
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\meoadmin\AppData\Local\go-build
set GOENV=C:\Users\meoadmin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\meoadmin\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\meoadmin\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\meoadmin\go\src\test\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\meoadmin\AppData\Local\Temp\go-build547649826=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

使用go get下载 beego和bee工具后，直接使用bee new test 创建项目；然后在test 中 执行 bee run命令报错
panic: JSON decoding failed: invalid character 'x' after array element

4. What did you expect to see?

2021/04/09 17:40:03 SUCCESS  ▶ 0003 Built Successfully!
2021/04/09 17:40:03 INFO     ▶ 0004 Restarting 'test.exe'...
2021/04/09 17:40:03 SUCCESS  ▶ 0005 './test.exe' is running...
panic: JSON decoding failed: invalid character 'x' after array element

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
        C:/Users/meoadmin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:83 +0x20f
sync.(*Once).doSlow(0xe1f2b0, 0x93a388)
        C:/go/src/sync/once.go:66 +0xf7
sync.(*Once).Do(...)
        C:/go/src/sync/once.go:57
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
        C:/Users/meoadmin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:69 +0x54
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc000207a00, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/meoadmin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/server.go:85 +0x3b
github.com/beego/beego/v2/server/web.Run(0x0, 0x0, 0x0)
        C:/Users/meoadmin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/beego.go:57 +0x6b
main.main()
        C:/Users/meoadmin/go/src/test/main.go:9 +0x39

5. What did you see instead?
no

**Comment by jianzhiyao** [comment]
是不是配置文件错了，看起来是加载配置文件之类的格式错误

**Comment by sunnnnnner** [comment]
> 是不是配置文件错了，看起来是加载配置文件之类的格式错误

bee 是直接从go git直接下载的，你说的配置文件 是哪个配置文件？

**Comment by jianzhiyao** [comment]
> > 是不是配置文件错了，看起来是加载配置文件之类的格式错误
> 
> bee 是直接从go git直接下载的，你说的配置文件 是哪个配置文件？

是用``bee new``命令创建出来的全新目录吗，不介意的话，可以打包给我看看

**Comment by sunnnnnner** [comment]
> > > 是不是配置文件错了，看起来是加载配置文件之类的格式错误
> > 
> > 
> > bee 是直接从go git直接下载的，你说的配置文件 是哪个配置文件？
> 
> 是用`bee new`命令创建出来的全新目录吗，不介意的话，可以打包给我看看

是的，使用 bee new testone  直接创建的，我把 文件上传的共享连接，放到下方：
http://111.229.218.84:8282/down/LlWFwhPYLwNP   此链接有效期7天

**Comment by jianzhiyao** [comment]
> > > > 是不是配置文件错了，看起来是加载配置文件之类的格式错误
> > > 
> > > 
> > > bee 是直接从go git直接下载的，你说的配置文件 是哪个配置文件？
> > 
> > 
> > 是用`bee new`命令创建出来的全新目录吗，不介意的话，可以打包给我看看
> 
> 是的，使用 bee new testone 直接创建的，我把 文件上传的共享连接，放到下方：
> http://111.229.218.84:8282/down/LlWFwhPYLwNP 此链接有效期7天

我这边是正常的，你可能要通过命令强制更新一下beego v2
```
go get -u github.com/beego/beego/v2
```

**Comment by sunnnnnner** [comment]
> > > > > 是不是配置文件错了，看起来是加载配置文件之类的格式错误
> > > > 
> > > > 
> > > > bee 是直接从go git直接下载的，你说的配置文件 是哪个配置文件？
> > > 
> > > 
> > > 是用`bee new`命令创建出来的全新目录吗，不介意的话，可以打包给我看看
> > 
> > 
> > 是的，使用 bee new testone 直接创建的，我把 文件上传的共享连接，放到下方：
> > http://111.229.218.84:8282/down/LlWFwhPYLwNP 此链接有效期7天
> 
> 我这边是正常的，你可能要通过命令强制更新一下beego v2
> 
> ```
> go get -u github.com/beego/beego/v2
> ```
已经试过了，并且 尝试 删除所有的beego，重新go get ，还是这样，目前这个电脑 就暂停，我试一下别的电脑

**Comment by jianzhiyao** [comment]
如何了，最后结果成功？

**Comment by flycash** [comment]
有回复再重新打开。
