### ISSUE TITLE
panic: reflect: call of reflect.Value.MethodByName on zero Value

### ISSUE THREAD

**Issue by longkeyy** [beego/beego#4570]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

Beego     : 1.12.0

2. What operating system and processor architecture are you using (`go env`)?
GoVersion : go1.15.5
GOOS      : darwin
GOARCH    : amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
type User struct {
	ID          int64     `orm:"unique"`               
	Name        string    `json:"ExpertName,omitempty"` 
	Tags        []*Tag    `orm:"rel(m2m)"` 
}

type Tag struct {
	Id    int64
	PID   int64
	Name  string
	Level int
	Users []*User `orm:"reverse(many)"` 
}

func init() {
	orm.RegisterModel(new(User), new(Tag))
}

orm.RunSyncdb("default", true, false)

4. What did you expect to see?

5. What did you see instead?
panic: reflect: call of reflect.Value.MethodByName on zero Value

goroutine 1 [running]:
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x49dfe6c, 0x16, 0xc0002ba300, 0x175, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/value.go:1354 +0x1b9
github.com/beego/beego/v2/client/orm.isApplicableTableForDB(0x0, 0x0, 0x0, 0x49d398c, 0x7, 0x0)
        /Users/longkeyy/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_utils.go:112 +0x6f
github.com/beego/beego/v2/client/orm.(*commandSyncDb).Run(0xc000185e40, 0x7, 0xc0000be480)
        /Users/longkeyy/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:146 +0xb1d
github.com/beego/beego/v2/client/orm.RunSyncdb(0x49d398c, 0x7, 0x49d0001, 0x7, 0xc000037af0)

**Comment by flycash** [comment]
it was fixed. please change to master branch:
```go
go get -u github.com/beego/beego/v2@master
```

**Comment by karngyan** [comment]
> it was fixed. please change to master branch:
> 
> ```go
> go get -u github.com/beego/beego/v2@master
> ```

I switched to master for `m2m` and can't generate commentsRouter file. Where did the `parser.go` go from master?

**Comment by karngyan** [comment]
> > it was fixed. please change to master branch:
> > ```go
> > go get -u github.com/beego/beego/v2@master
> > ```
> 
> I switched to master for `m2m` and can't generate commentsRouter file. Where did the `parser.go` go from master?

If anyone comes looking for it. Switch to bee/v2@develop and run `bee generate routers`

Had to really look into the changelog. You guys really need an updated documentation.
