### ISSUE TITLE
请问如何在swagger文档的返回值中加入注释

### ISSUE THREAD

**Issue by jy418** [beego/beego#4575]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.01

2. What operating system and processor architecture are you using (`go env`)?
win10

3. What did you do?
type Response struct {
	LoginParams
	Id         int    `json:"id"`                    // 主键
	Status     int    `json:"status"`                // 状态
	CreateTime int64  `json:"createTime"`            // 创建时间
	Name       string `json:"name" ` 			// 名称
	Avatar     string `json:"avatar"`                // 头像
}

4. What did you expect to see?
我希望能够在文档的返回值中有注释
![R`%GPP 6G9CUKZV(Z SRJXJ](https://user-images.githubusercontent.com/30037487/114744474-50172180-9d80-11eb-818c-ee4aa0527786.png)

5. What did you see instead?

**Comment by flycash** [comment]
用Tag，`description`：
```go
A int `description:"aaa"`
```
你可以试试。

**Comment by EddyLee1010** [comment]
> 用Tag，`description`：
> 
> ```go
> A int `description:"aaa"`
> ```
> 
> 你可以试试。

请问swagger具体的语法有没有文档

**Comment by flycash** [comment]
https://beego.me/docs/advantage/docs.md

这里有一部分，我发现文档缺了一部分描述模型内部的怎么定义的。后面我们补一下
