### ISSUE TITLE
bee pack 打包命令

### ISSUE THREAD

**Issue by barryzxy** [beego/beego#4585]
linux打包: bee pack -be GOOS=linux
windows打包: bee pack -be GOOS=windows
以上命令是打包时指定了 GOOS，那怎么指定 GOARCH  
在golang中是
go env -w  CGO_ENABLED=0
go env -w GOOS=linux
go env -w  GOARCH=arm
go env -w GOARM=7

那么beego中打包怎么指定？

**Comment by flycash** [comment]
`bee pack -be GOARCH=arm` 试试？

**Comment by barryzxy** [comment]
> `bee pack -be GOARCH=arm` 试试？

可以打包，不过还是得先编译好main.go然后打包，我这边还是用1.x版本

**Comment by flycash** [comment]
这个应该就是1.x就支持的。我没太理解你说的，先编译好`main.go`？
`beee pack` 命令不是直接编译完么？
