### ISSUE TITLE
模板渲染时前后多了两个双引号

### ISSUE THREAD

**Issue by pingProMax** [beego/beego#4587]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
windows10 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
js:
```js
url: "/{{.admin}}/context/get", // 表格数据来源
```
```conf
[webconfig]
#后台登录地址
admin="admin"
```
```golang
admin, _ := beego.AppConfig.String("webconfig::admin")
c.Data["admin"] = admin //后台路径
```

4. What did you expect to see?
Uncaught SyntaxError: Unexpected identifier:
url: "/"admin"/context/get_context_card", // 表格数据来源

5. What did you see instead?
url: "/admin/context/get_context_card", // 表格数据来源

这个bug 不知道什么条件复现
因为它在同一个项目中  只有一个模板出现了这种问题 并且这个模板有多个这样的`url: "/{{.admin}}/context/get",`
如果你需要复现我可以提供远程

**Comment by jianzhiyao** [comment]
I can't reproduce what you described.
May the example project on below can be helpful.
[api2.zip](https://github.com/beego/beego/files/6374116/api2.zip)

**Comment by jianzhiyao** [comment]
没什么问题的话，我们暂时关闭此issue，有需要可以提供相关demo例子，欢迎再次提交issue交流！
