### ISSUE TITLE
How to use "bee run -runargs"

### ISSUE THREAD

**Issue by EddyLee1010** [beego/beego#4591]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego v1.12
2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?

        for example:  "go run main.go -c a.conf"   "bee run -runargs ??????"

4. What did you expect to see?
    ????

5. What did you see instead?

**Comment by jianzhiyao** [comment]
```
PS C:\Users\User\Desktop\null\api2> bee help run
USAGE
  bee run [appname] [watchall] [-main=*.go] [-downdoc=true]  [-gendoc=true] [-vendor=true] [-e=folderToExclude] [-ex=extraPackageToWatch] [-tags=goBuildTags] [-runmode=BEEGO_RUNMODE]

OPTIONS
  -downdoc
      Enable auto-download of the swagger file if it does not exist.

  -e=[]
      List of paths to exclude.

  -ex=[]
      List of extra package to watch.

  -gendoc
      Enable auto-generate the docs.

  -ldflags
      Set the build ldflags. See: https://golang.org/pkg/go/build/

  -main=[]
      Specify main go files.

  -runargs
      Extra args to run application

  -runmode
      Set the Beego run mode.

  -tags
      Set the build tags. See: https://golang.org/pkg/go/build/

  -vendor=false
      Enable watch vendor folder.

DESCRIPTION
  Run command will supervise the filesystem of the application for any changes, and recompile/restart it.
```

**Comment by EddyLee1010** [comment]
> ```
> PS C:\Users\User\Desktop\null\api2> bee help run
> USAGE
>   bee run [appname] [watchall] [-main=*.go] [-downdoc=true]  [-gendoc=true] [-vendor=true] [-e=folderToExclude] [-ex=extraPackageToWatch] [-tags=goBuildTags] [-runmode=BEEGO_RUNMODE]
> 
> OPTIONS
>   -downdoc
>       Enable auto-download of the swagger file if it does not exist.
> 
>   -e=[]
>       List of paths to exclude.
> 
>   -ex=[]
>       List of extra package to watch.
> 
>   -gendoc
>       Enable auto-generate the docs.
> 
>   -ldflags
>       Set the build ldflags. See: https://golang.org/pkg/go/build/
> 
>   -main=[]
>       Specify main go files.
> 
>   -runargs
>       Extra args to run application
> 
>   -runmode
>       Set the Beego run mode.
> 
>   -tags
>       Set the build tags. See: https://golang.org/pkg/go/build/
> 
>   -vendor=false
>       Enable watch vendor folder.
> 
> DESCRIPTION
>   Run command will supervise the filesystem of the application for any changes, and recompile/restart it.
> ```

e....... 
我问的是 -runargs  后面怎么写啊。。。

**Comment by EddyLee1010** [comment]
> ```
> PS C:\Users\User\Desktop\null\api2> bee help run
> USAGE
>   bee run [appname] [watchall] [-main=*.go] [-downdoc=true]  [-gendoc=true] [-vendor=true] [-e=folderToExclude] [-ex=extraPackageToWatch] [-tags=goBuildTags] [-runmode=BEEGO_RUNMODE]
> 
> OPTIONS
>   -downdoc
>       Enable auto-download of the swagger file if it does not exist.
> 
>   -e=[]
>       List of paths to exclude.
> 
>   -ex=[]
>       List of extra package to watch.
> 
>   -gendoc
>       Enable auto-generate the docs.
> 
>   -ldflags
>       Set the build ldflags. See: https://golang.org/pkg/go/build/
> 
>   -main=[]
>       Specify main go files.
> 
>   -runargs
>       Extra args to run application
> 
>   -runmode
>       Set the Beego run mode.
> 
>   -tags
>       Set the build tags. See: https://golang.org/pkg/go/build/
> 
>   -vendor=false
>       Enable watch vendor folder.
> 
> DESCRIPTION
>   Run command will supervise the filesystem of the application for any changes, and recompile/restart it.
> ```

额。。。。
我问的是  -runargs 后面怎么写， help谁都会呀

**Comment by jianzhiyao** [comment]
这里不是写得很清楚吗``See: https://golang.org/pkg/go/build/``。
看起来是``go build``命令中，bee命令提供对于原生参数``ldflags``的封装。


### 样例代码
具体使用请自行google
```go
//bee run -ldflags "-X main.VERSION=1.0.0 -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'"
package main

import (
	_ "api2/routers"
	"fmt"
	beego "github.com/beego/beego/v2/server/web"
)

var (
    VERSION    string
    BUILD_TIME string
    GO_VERSION string
)

func main() {
	fmt.Println(VERSION)
	fmt.Println(BUILD_TIME)
	fmt.Println(GO_VERSION)
	beego.Run()
}


```

**Comment by jianzhiyao** [comment]
这个参数用于传参给到你的可执行文件

### 运行代码
```go
package main

import (
	_ "api2/routers"
	"flag"
	beego "github.com/beego/beego/v2/server/web"
)

func main() {
	_ = flag.String("word", "foo", "astring")
	_ = flag.Int("numb", 42, "anint")
	_ = flag.Bool("fork", false, "abool")
	flag.Parse()
	beego.Run()
}

```

### 执行命令
```bash
C:\Users\User\Desktop\null\api2>bee run -runargs "--help"
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2
2021/04/27 18:09:27 WARN     ▶ 0001 Running application outside of GOPATH
2021/04/27 18:09:27 INFO     ▶ 0002 Using 'api2' as 'appname'
2021/04/27 18:09:27 INFO     ▶ 0003 Initializing watcher...
2021/04/27 18:09:30 SUCCESS  ▶ 0004 Built Successfully!
2021/04/27 18:09:30 INFO     ▶ 0005 Restarting 'api2.exe'...
2021/04/27 18:09:30 SUCCESS  ▶ 0006 './api2.exe' is running...
Usage of ./api2.exe:
  -fork
        abool
  -graceful
        listen on open fd (after forking)
  -numb int
        anint (default 42)
  -socketorder string
        previous initialization order - used when more than one listener was started
  -word string
        astring (default "foo")
```

**Comment by jianzhiyao** [comment]
没什么问题的话我们先关闭此issue，有问题欢迎再次提出

**Comment by wangqianwei** [comment]
-tags 这个参数不生效，有配置示例么
