### ISSUE TITLE
注解路由问题：beego/server/web/parser.go 文件在最新Develop 分支中不见了

### ISSUE THREAD

**Issue by Lockeysama** [beego/beego#4592]
beego 版本：v2.0.2-0.20210426133951-511714d616c8
问题：beego/server/web/parser.go 文件在最新 Develop 分支中不见了，导致不生成 commentsRouter_controllers.go 文件。请问这个是设计上的变更吗？

**Comment by jianzhiyao** [comment]
看起来是改造新的filter的时候去掉了，具体遇到事什么问题吗，能够一些截图参考一下吗？

**Comment by Lockeysama** [comment]
这个现象比较简单，截图可能还不如打字解释的清楚😂。
具体问题就是：我项目如果使用上面这个版本（v2.0.2-0.20210426133951-511714d616c8）的 beego 的时候，不会生成任何 commentsRouter 文件。
我是在找不到原因的情况下，使用了 2.0.1 版本进行测试，从日志中发现了 "2021/04/27 17:50:56.552 [I] [parser.go:413]  generate router from comments" 这样的日志输出，对两个版本进行对比，发现新的这个版本确实没有这个日志输出，然后找了源码，发现没有 parser.go 这个文件，所有才有了这个 issues 的。

**Comment by flycash** [comment]
不是，我删除了。
现在挪过去了`bee`命令。你需要安装开发版本的bee。
```shell
go get -u xxx/bee/v2@develop
```
而后执行
```go
bee generate routers [-ctrlDir=/path/to/controller/directory] [-routersFile=/path/to/routers/file.go] [-routersPkg=myPackage]
```

**Comment by flycash** [comment]
当时的考量是：生成注解路由，本身属于代码生成的一部分，那么应该是工具类的一部分，不应该包含在`beego`本体中。

之前用户也反馈过，希望挪过去`bee`命令里面。这样可以控制什么时候生成以及生成的源文件和目标文件。

后续我们会考虑逐步把所有的工具性质的功能都搬走。

**Comment by Lockeysama** [comment]
@jianzhiyao @flycash 👌了解，感谢回复！
