### ISSUE TITLE
windows平台bee new 报错

### ISSUE THREAD

**Issue by blue110** [beego/beego#4594]
命令：bee new hehe

报错如下：

2021/04/30 15:55:51 INFO    panic: write /dev/stdout: A device attached to the system is not functioning.

goroutine 1 [running]:
github.com/beego/bee/v2/logger.(*BeeLogger).mustLog(0xc000096000, 0x6, 0xdbb4a2, 0x28, 0x0, 0x0, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/beego/bee/v2@v2.0.2/logger/logger.go:186 +0x32b
github.com/beego/bee/v2/logger.(*BeeLogger).Info(...)
        C:/Users/Administrator/go/pkg/mod/github.com/beego/bee/v2@v2.0.2/logger/logger.go:226
github.com/beego/bee/v2/cmd/commands/new.CreateApp(0x12f9580, 0xc00005e060, 0x1, 0x2, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/beego/bee/v2@v2.0.2/cmd/commands/new/new.go:286 +0xef
main.main()
        C:/Users/Administrator/go/pkg/mod/github.com/beego/bee/v2@v2.0.2/main.go:61 +0x297

C:\Users\Administrator\go\src>set DEBUG_ENABLED = 1

**Comment by flycash** [comment]
这种情况多数是因为权限问题引起的，你需要检查一下你所在目录的权限。
这是我在我windows上执行命令的结果：
```shell
![image](https://user-images.githubusercontent.com/9923838/116709820-e6089a00-a985-11eb-8ae8-fa25099e0ad5.png)

```
