### ISSUE TITLE
开启了go mod，使用beego2.0.1，接口全部404了

### ISSUE THREAD

**Issue by chenlixiang0430** [beego/beego#4597]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.16.3，beego2.0.1

项目要改用go mod管理依赖，然后项目运行重新生成了commentsRouter_.go，接口就全部404了
![SRRABHA$U MADM_GG316RZN](https://user-images.githubusercontent.com/43659392/117246211-cd5d2000-ae6e-11eb-82ec-f49fb88b5006.png)

请问大佬要怎么弄才行？
只能手动改了吗？

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by chenlixiang0430** [comment]
我自己操作有问题，弄好了

**Comment by tuoling805** [comment]
@chenlixiang0430 你怎么操作的，我也遇到了

**Comment by peipeiguo** [comment]
我也遇到了同样问题。
我觉得注解路由文件的生成依赖先运行一次才能生成，用起来不方便，而且生成的文件名后面带了包名和路径，看起来很长，也不方便，最好名字固定，这样运行一次后，可以归档到代码仓库，避免404问题。
