### ISSUE TITLE
注解路由需要编译两次

### ISSUE THREAD

**Issue by whmmm** [beego/beego#4598]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

v2.0.1

2. What operating system and processor architecture are you using (`go env`)?

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\94258\AppData\Local\go-build
set GOENV=C:\Users\94258\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\94258\go\pkg\mod
set GONOPROXY=gitee.com
set GONOSUMDB=gitee.com
set GOOS=windows
set GOPATH=C:\Users\94258\go
set GOPRIVATE=gitee.com
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\whmmm\项目-测试\book-manager\book-manager\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\94258\AppData\Local\Temp\go-build1347080329=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

注解路由需要编译两次才能生效

4. What did you expect to see?

注解路由第一次编译后的 可执行文件 没有生效

5. What did you see instead?

注解路由第一次编译后的 可执行文件 路由没有生效， 再次编译后 路由生效,
疑似原因是第一次编译只是生成了 `commentsRouter_controllers.go` ，但是生成的 `commentsRouter_controllers.go` 
文件 没有参与编译, 当第二次编译时, 文件已存在, 因此 注解路由生效。

**Comment by flycash** [comment]
是的。我们已经彻底移除了这个功能，改为由bee命令生成注解路由。目前的话，就还是运行两次。
#4486
