### ISSUE TITLE
bug: utils file.go FileExists function return true when the user has no permission on default conf

### ISSUE THREAD

**Issue by AgainstWind** [beego/beego#4603]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
goalng 1.15.1 linux
begoo 1.12.0

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build334964252=/tmp/go-build -gno-record-gcc-switches"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
start begoo

4. What did you expect to see?
start begoo server success

5. What did you see instead?
run begoo failed with non-root user

**Comment by flycash** [comment]
I think `FileExists ` doesn't need to check the permission because its name is "FileExists".
