### ISSUE TITLE
bug: beego auto generated tests/default_test.go has not beego.Trace (unresolved reference)

### ISSUE THREAD

**Issue by anagramteat** [beego/beego#4604]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
macos

3. What did you do? 
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

just follow the official website, and run "bee new quickstart" to generate a demo project

4. What did you expect to see?

default_test.go should work

5. What did you see instead?

line 28
 beego.Trace (unresolved reference)

**Comment by flycash** [comment]
It was resolved, please update `bee` to newest `master` branch.
