### ISSUE TITLE
beego logger was write to rotate file

### ISSUE THREAD

**Issue by ideamean** [beego/beego#4606]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
	github.com/astaxie/beego v1.12.0

2. What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/root/go"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build471820974=/tmp/go-build -gno-record-gcc-switches"

3. this is my code
func InitLog() error {
	makeLog(logger, "system.log")
	return nil
}

func makeLog(l *logs.BeeLogger, fileName string) error {
	err := l.SetLogger(logs.AdapterMultiFile, fmt.Sprintf(`{"filename":"%s/log/%s", "daily":true,"maxdays":7,"rotate":true}`, GetCurrPath(), fileName))
	if err != nil {
		return errors.New("init log error:" + err.Error())
	}
	l.Async(10000)
	return nil
}

4. Bug Description:
system.log was rotated to system.2021-05-13.002.log，all new logs are written to this file, I think new logs should write to system.log? 
This happens occasionally during log rotating。

![image](https://user-images.githubusercontent.com/824662/118073966-998a7900-b3df-11eb-8fdf-f073beee4196.png)

**Comment by ideamean** [comment]
@flycash need help

**Comment by cugxuan** [comment]
> @flycash need help

I have tested the case for **hourly rotation**. But I didn't find the error.
I notice that you said this happens occasionally, could you reproduce this error?

**Comment by cugxuan** [comment]
And this is my test code.
```go
package main

import (
	"errors"
	"fmt"
	"github.com/beego/beego/v2/core/logs"
	"time"
)

func GetCurrPath() string {
	return "/Users/xuan/go/test"
}

var logger *logs.BeeLogger

func InitLog() error {
	logger = logs.NewLogger()
	//logger.EnableFuncCallDepth(true)
	makeLog(logger, "system.log")
	return nil
}

func makeLog(l *logs.BeeLogger, fileName string) error {
	//err := l.SetLogger(logs.AdapterMultiFile, fmt.Sprintf(
	//	`{"filename":"%s/log/%s", "daily":true, "maxdays":7, "rotate":true}`, GetCurrPath(), fileName))
	err := l.SetLogger(logs.AdapterMultiFile, fmt.Sprintf(
		`{"filename":"%s/log/%s", "hourly":true, "maxhours":7, "rotate":true}`, GetCurrPath(), fileName))
	if err != nil {
		return errors.New("init log error:" + err.Error())
	}
	l.Async(10000)
	return nil
}

func main() {
	InitLog()
	i := 1
	for {
		logger.Debug("%d", i)
		i += 1
		time.Sleep(time.Minute)
	}
}
```

**Comment by cugxuan** [comment]
I have tested the rotation function for daily rotate, and I can not reproduce the error either.
![image](https://user-images.githubusercontent.com/23120372/120088712-0b73f980-c126-11eb-9363-5d24916d7764.png)

In your situation, are there lots of goroutines writing the log concurrently in the rotate time？
