### ISSUE TITLE
logs output empty line when using console provider

### ISSUE THREAD

**Issue by lcexc** [beego/beego#4625]
the logger output empty line, code:
```
package main

import "github.com/beego/beego/v2/core/logs"

func main() {
	log := logs.NewLogger()
	log.SetLogger("console", `{"color":false}`) 

	log.Debug("debug 0000")
	log.Info("info 0000")
}
```
output: 
![image](https://user-images.githubusercontent.com/12669549/119116779-2a55fa00-ba5b-11eb-85f9-c5debc5bf5b5.png)

**Comment by cugxuan** [comment]
I have found the error.
`func (c *consoleWriter) Format(lm *LogMsg)`  add `\n`
https://github.com/beego/beego/blob/develop/core/logs/console.go#L64-L66
and `func (c *consoleWriter) WriteMsg(lm *LogMsg)` also add '\n'
https://github.com/beego/beego/blob/develop/core/logs/console.go#L107-L115

Should we delete the \n in Format?

**Comment by flycash** [comment]
yes, please

**Comment by flycash** [comment]
you could checkout branch from master and then make a pull request to master branch.

**Comment by flycash** [comment]
Thank you @cugxuan !

**Comment by lcexc** [comment]
it works, thanks.
