### ISSUE TITLE
task manager feature support

### ISSUE THREAD

**Issue by optimistic9527** [beego/beego#4631]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
V2.0.1

2. What operating system and processor architecture are you using (`go env`)?
go version go1.13.6 darwin/amd64

3. What did you do?

When the task management program receives the exit signal, the program exits immediately.

4. What did you expect to see?

After the task management receives the signal, wait for the task to complete and exit the program

5. What did you see instead?

The management program can be controlled by warp task to exit the program after waiting for all task to complete

**Comment by flycash** [comment]
It should be part of "graceful shutdown". It's a good suggestion.
