### ISSUE TITLE
Transaction not locking the connection

### ISSUE THREAD

**Issue by mrasif** [beego/beego#4633]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go and beego are you using (`bee version`)?
`github.com/astaxie/beego v1.12.1` and `go 1.13`
2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/src/auth/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build857775357=/tmp/go-build -gno-record-gcc-switches"
```
3. What did you do?
We were trying to save multiple dependent data using transaction. when multiple requests are being sent in parallel, transactions are overlapping instead of one transaction locking the database
Imagine this scenario:
- Req #1 comes & starts a transaction and does not lock access to the db
- Before req #1's transaction is complete, another request comes to run the same query.
- Instead of waiting for Req #1's transaction to finish & then req #2's transaction to start, the ORM tries running the same transaction & gets errored out:
**Example Error Messages:**
For Req #2
`error="<Ormer.Begin> transaction already begin"`
`error="<Ormer.Commit/Rollback> transaction not begin"`
Then after a while, this error starts coming:
`driver: bad connection`
One point to note is that I have a single db single connection that I am reusing across the code if that is useful to know

**Comment by flycash** [comment]
I cannot understand what you mean "lock db" or "lock connection". But I guess that you reuse `Orm` instance. You use the same instance of `Orm` in both two transactions. From the original design, it's not thread safe. 

You could try create `Orm` instance every time when you want to begin a new transaction.
