### ISSUE TITLE
v2.0.1版本下logs模块在多Adapter下，第一个adapter输出没有进行format

### ISSUE THREAD

**Issue by fuzengjie** [beego/beego#4636]
代码：
```go

package main

import (
"github.com/beego/beego/v2/core/logs"
)

var logInstance *logs.BeeLogger

const logChanLen = 4096

func init() {
	logInstance = logs.NewLogger(logChanLen)
	logInstance.SetLevel(logs.LevelError)
	logInstance.EnableFuncCallDepth(true)
	logInstance.SetLogFuncCallDepth(3)
	logInstance.SetLevel(logs.LevelInfo)
	logInstance.SetLogger(logs.AdapterFile,`{"filename":"app.log"}` )
	logInstance.SetLogger(logs.AdapterConsole, `{"color":true}`)

}


func main() {
	logInstance.Info("fuzj %s","dddd")
	logInstance.Info("fuzj1 %s","dddd")
}
```

输出效果
*  file：
```
2021/05/26 10:39:41.161  [I] [proc.go:204]  fuzj %s
2021/05/26 10:39:41.161  [I] [proc.go:204]  fuzj1 %s
```
* console

```
2021/05/26 10:39:41.161 [I] [proc.go:204]  fuzj dddd
2021/05/26 10:39:41.161 [I] [proc.go:204]  fuzj1 dddd
```

经debug追踪逻辑， 发现logs/log_msg.go 下`LogMsg`下OldStyleFormat这个方法 对msg处理有问题
![image](https://user-images.githubusercontent.com/9402808/119595411-1e2dbc00-be10-11eb-850d-26d17d367d8a.png)
![image](https://user-images.githubusercontent.com/9402808/119595439-284fba80-be10-11eb-972a-6cf6aa9f314b.png)
![image](https://user-images.githubusercontent.com/9402808/119595652-7369cd80-be10-11eb-9705-fe218464df2d.png)
![image](https://user-images.githubusercontent.com/9402808/119595667-7a90db80-be10-11eb-821e-6e66a45abf50.png)

改进如下：
```
func (lm *LogMsg) OldStyleFormat() string {
	msg := lm.Msg

	if len(lm.Args) > 0 {
		msg = fmt.Sprintf(lm.Msg, lm.Args...)
	}

	msg = lm.Prefix + " " + msg

	if lm.enableFuncCallDepth {
		filePath := lm.FilePath
		if !lm.enableFullFilePath {
			_, filePath = path.Split(filePath)
		}
		msg = fmt.Sprintf("[%s:%d] %s", filePath, lm.LineNumber, msg)
	}

	msg = levelPrefix[lm.Level] + " " + msg
	return msg
}
```

**Comment by fuzengjie** [comment]
https://user-images.githubusercontent.com/9402808/119595411-1e2dbc00-be10-11eb-850d-26d17d367d8a.png)
https://user-images.githubusercontent.com/9402808/119595439-284fba80-be10-11eb-972a-6cf6aa9f314b.png)
https://user-images.githubusercontent.com/9402808/119595652-7369cd80-be10-11eb-9705-fe218464df2d.png)
https://user-images.githubusercontent.com/9402808/119595667-7a90db80-be10-11eb-821e-6e66a45abf50.png)

**Comment by flycash** [comment]
给我发个PR呀

**Comment by flycash** [comment]
我记得，在develop上，我们修复了这个问题。

**Comment by flycash** [comment]
我看了一下，我们master 分支已经修复了这个问题。
