### ISSUE TITLE
A little bug about function 'FileExists' in utils

### ISSUE THREAD

**Issue by GuardianRain** [beego/beego#4638]
1. What version of Go and beego are you using (`bee version`)?
    v1.12.3

2. What operating system and processor architecture are you using (`go env`)?
    For any enviroment, bug is here anyway.

3. What did you do?
    I start a process using beego, but an error is appeared in config.go:158, meanning failed to open the appConfigPath.
    But I havn't using app.conf in my project. 
    That's the problem: the user of my process has no permission to accessthe 'AppPath'/conf directory, 
    but utils.FileExists return true, so panic is occurred.

// FileExists reports whether the named file or directory exists.
func FileExists(name string) bool {
	if _, err := os.Stat(name); err != nil {
		if os.IsNotExist(err) {
			return false
		}
	}
	return true
}

    I review the code, and find that IsNotExist error is the only error causes to return false, 
    but any other reason that can't access the file, is just like file not exit.

4. What did you expect to see?
I think this way may be better:
func FileExists(name string) bool {
	if _, err := os.Stat(name); err != nil {
		if os.IsNotExist(err) {
			return false
		}
                // other error, log it and return false also.
                log.info(err)
                return false
	}
	return true
}

**Comment by flycash** [comment]
I think this looks good. I know your concern, for example, Beego app cannot read or write the file, but `FileExists` still return true. But in my opinon, `FileExists` means that we only check if the file exists but do not check file mode.

**Comment by GuardianRain** [comment]
> I think this looks good. I know your concern, for example, Beego app cannot read or write the file, but `FileExists` still return true. But in my opinon, `FileExists` means that we only check if the file exists but do not check file mode.

Okay, I see what you mean. But `FileExists` is used in beego `init` , which may leave some hidden dangers. 
For example, my app needn't using file `app.conf` actually, and the app is running without `app.conf` already,
then, attackers which can login the system as another user, may make the app restart failed, by make a `conf` directory in the app bin file path. How do you think?
By the way, I still think can't access the directory or the file, is just like file not exists, because you don't know the file's existence actually.

**Comment by flycash** [comment]
> By the way, I still think can't access the directory or the file, is just like file not exists, because you don't know the file's existence actually.
I agree with you. But now `FileExists` is a public method, and I prefer that add one more method named `FileAccessible`, it will check file mode too.

**Comment by GuardianRain** [comment]
> > I agree with you. But now `FileExists` is a public method, and I prefer that add one more method named `FileAccessible`, it will check file mode too.
That's a good idea.
