### ISSUE TITLE
为什么redis 的Do接口不暴露出来呢？

### ISSUE THREAD

**Issue by Daniel-ccx** [beego/beego#4642]
执行集合相关的命令完全不可行，我只能自己把do放出来了。
还是希望大神能主动一点，你们是基于什么考量写成私有的呢？

**Comment by jianzhiyao** [comment]
可以提供一些详细一些的需求，我们可以做相关的技术支持，后续可以加入todo list

**Comment by flycash** [comment]
这个最开始的人是怎么想的，已经比较难求证了。不过大概率的推测是为了封装，Beego 可能并未考虑到支持自定义操作的场景。
