### ISSUE TITLE
ParseForm to Struct with slice of float32 (float64)

### ISSUE THREAD

**Issue by vladimirschuka** [beego/beego#4665]
Hi all, I try to use` []float32` in my struct to parse but nothing is happening, change it to `string` and everything is working perfectly. After small investigation I found out that in the `ParseForm` function : 
`if fieldT.Type == sliceOfInts {`
and
`} else if fieldT.Type == sliceOfStrings {`
and that is it.

Any plans to have done it?

**Comment by flycash** [comment]
could you help to do it? you could checkout branch from master. I think this is a small hotfix.
