### ISSUE TITLE
A new beego project, copy the build result to a new folder,panic

### ISSUE THREAD

**Issue by bkzy-wangjp** [beego/beego#4669]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
wjp@ubuntu:~/micup$ bee version
2021/06/17 23:03:14 ERROR    ▶ 0001 GOPATH environment is empty,may be you use `go module`
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2

├── Beego     : 
├── GoVersion : go1.16.4
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : 
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Thursday, 17 Jun 2021

```

2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/wjp/.cache/go-build"
GOENV="/home/wjp/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/wjp/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/wjp/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2534845308=/tmp/go-build -gno-record-gcc-switches"

```

3. What did you do?

I creat a new project:
```
bee new micup
```
I build it, I run it, it works.
But when i copy the binary file , static, views to a new folder, it panic!
This is a new project, i do nothing, just move the result to a new folder.
![image](https://user-images.githubusercontent.com/42510334/122425193-e30f4a80-cfc1-11eb-8926-4ce7191247d8.png)

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
Beego reply on GOPATH because it will do something when `runmode` is `dev`. I think if you change the `runmode` to other except `dev`, it will be fine.

**Comment by bkzy-wangjp** [comment]
> Beego reply on GOPATH because it will do something when `runmode` is `dev`. I think if you change the `runmode` to other except `dev`, it will be fine.

Thanks. I change the `runmode` to `prod`, it works well.
