### ISSUE TITLE
Get Error in the task moudle of Live Monitor

### ISSUE THREAD

**Issue by cysnet** [beego/beego#4673]
Task Code
`taskutil.AddTask("tk1", "0/10 * * * * *", func(c context.Context) error {
		blogs.Info("pong")
		return nil
	})`

Error Info
`
<html>
<body>

Request Method: | GET
-- | --
Request URL: | /task
RemoteAddr: | 192.168.43.94

<div class="stack" style="padding: 0px; margin: 0px; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="padding: 0px; margin: 0px; font-size: 13px; color: red;">Stack</b><pre style="padding: 0px 0px 0px 10px; margin: 0px;">/usr/local/src/go/src/runtime/panic.go:965
/usr/local/src/go/src/runtime/panic.go:212
/usr/local/src/go/src/runtime/signal_unix.go:734
/home/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/task/task.go:160
/home/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/task/govenor_command.go:36
/home/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/admin_controller.go:106
/usr/local/src/go/src/reflect/value.go:476
/usr/local/src/go/src/reflect/value.go:337
/home/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/router.go:883
/home/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/filter.go:81
/home/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web/router.go:664
/usr/local/src/go/src/net/http/server.go:2887
/usr/local/src/go/src/net/http/server.go:1952
/usr/local/src/go/src/runtime/asm_amd64.s:1371</pre></div>
</body>
</html>`

![image](https://user-images.githubusercontent.com/35944271/123193143-d1a0d380-d4d6-11eb-83f7-da1b4700f25b.png)

**Comment by flycash** [comment]
Do you run `task.StartTask` ?
It's a little big change that only after `task.StartTask`, the task module register its monitor command to admin module.

**Comment by cysnet** [comment]
> Do you run `task.StartTask` ?
> It's a little big change that only after `task.StartTask`, the task module register its monitor command to admin module.

sure. I think have run starttask

**Comment by flycash** [comment]
From this case, let me check if we can move this to `init` method to avoid run `StartTask`

**Comment by cysnet** [comment]
> From this case, let me check if we can move this to `init` method to avoid run `StartTask`

what do you mean? you mean I need execute starttask in the init method？

**Comment by flycash** [comment]
No, you just need to invoke `StartTask`. I mean, we want to do some optimizations

**Comment by KaiJunYan** [comment]
版本信息：
beego 2.0.0 (beego framework)
golang version: go1.16.5

这个问题到现在仍然存在，在初始化任务的时候，创建了一个100容量的切片Errlist ，这个切片Errlist 里面的错误信息都是nil，每次运行后有错误才会更新这个Errlist ，在获取状态的时候，没有判断nil，导致获得了空指针错误。
https://github.com/beego/beego/blob/a1b1248a67b3f252639ed5a60d143675cae10cb7/task/task.go#L160

**Comment by KaiJunYan** [comment]
查了一下，最新的v2.0.2-beta.1 版本更新了。
https://github.com/beego/beego/blob/c6e84d8a5dd3a43417eaaf7fc3419b37f6b07744/task/task.go#L167
