### ISSUE TITLE
beego v2: Tx sql logs are not printed when using orm.NewOrm().DoTx

### ISSUE THREAD

**Issue by mchtech** [beego/beego#4674]
beego v2.0.2-0.20210623154053-2207201e3877 (actually since beego v2):

`COMMIT` / `ROLLBACK` and the SQLs that executed in Tx closure are not printed. The TX orm debug log only contains a `START TRANSACTION` line:

`[ORM]2021/06/25 15:26:55  -[Queries/default] - [  OK /  db.BeginTx /     0.3ms] - [START TRANSACTION]`

```go

orm.Debug = true

orm.NewOrm().DoTx(func(ctx context.Context, txOrm orm.TxOrmer) (txerr error) {
  _, txerr = txOrm.QueryTable(&xxx{}).Count()
  return
})

```

**Comment by flycash** [comment]
@jianzhiyao please help to check this problem

**Comment by mchtech** [comment]
?
