### ISSUE TITLE
从V1切换到V2，logs模块工作不正常

### ISSUE THREAD

**Issue by tobyzxj** [beego/beego#4675]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
beego v2.0.1
go version go1.16.5 

2. What operating system and processor architecture are you using (`go env`)?
windows amd64

3. What did you do?

Test CODE:

**USING beego V2**:

```
package main

import (
	"github.com/beego/beego/v2/core/logs"
)

func main() {
	log := logs.NewLogger(10000)
	log.SetLogger("console", `{"level":7}`)
	log.EnableFuncCallDepth(true)
	log.SetLogFuncCallDepth(3)

	log.Debug("my book is bought in the year of %d", 2016)
	log.Info("this %s cat is %v years old", "yellow", 3)
	log.Warn("json is a type of kv like %v", map[string]int{"key": 2016})
	log.Critical("oh,crash")
}
```

**OUTPUT**:

2021/06/25 17:15:17.905 [D] [proc.go:225]  my book is bought in the year of %d

2021/06/25 17:15:17.971 [I] [proc.go:225]  this %s cat is %v years old

2021/06/25 17:15:17.971 [W] [proc.go:225]  json is a type of kv like %v

2021/06/25 17:15:17.972 [C] [proc.go:225]  oh,crash

**USING beego V1**:

```
package main

import (
	"github.com/astaxie/beego/logs"
)

func main() {
	log := logs.NewLogger(10000)
	log.SetLogger("console", `{"level":7}`)
	log.EnableFuncCallDepth(true)
	log.SetLogFuncCallDepth(3)

	log.Debug("my book is bought in the year of %d", 2016)
	log.Info("this %s cat is %v years old", "yellow", 3)
	log.Warn("json is a type of kv like %v", map[string]int{"key": 2016})
	log.Critical("oh,crash")
}
```

**OUTPUT**:

2021/06/25 17:13:25.614 [D] [proc.go:225]  my book is bought in the year of 2016
2021/06/25 17:13:25.658 [I] [proc.go:225]  this yellow cat is 3 years old
2021/06/25 17:13:25.658 [W] [proc.go:225]  json is a type of kv like map[key:2016]
2021/06/25 17:13:25.658 [C] [proc.go:225]  oh,crash

**Comment by flycash** [comment]
Please update to master branch

**Comment by tobyzxj** [comment]
Solved
