### ISSUE TITLE
SessionRegenerateID not working properly

### ISSUE THREAD

**Issue by Sorin35e** [beego/beego#4678]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version 1.16.5
beego version 2.0.1
I am using only the session module from beego

2. What operating system and processor architecture are you using (`go env`)?
Windows 10 intel i7

3. What did you do?
Calling method SessionRegeneratID  results in sending to browser two cookies with different id's  and the data stored into session before calling sessionregeneratID is lost.

4. What did you expect to see?
To see the id of the session / cookie sent to browser changed but the data stored in session should still be available after session id regeneration.

5. What did you see instead?
I got two cookies with different session ID's in browser instead of one new id and also the data stored in that session was flushed.

**Comment by flycash** [comment]
Due to some secure problems, now session stored in cookie only works for https. We use `secure` and `httponly` flag, so do you use https protocol?

**Comment by Sorin35e** [comment]
Hello.
Thank you for your reply.
It is not about session data stored in cookie.I am storing the session data in Redis not in cookie.But the session id is the same as the cookie id which is sent to the client (browser).When I use sessionregenerateID I expect that the cookie name( ID) stored and sent throught http request to the browser is changed to a new one and so will the sessionID stored in Redis change but the data in inside session remains unmodified.
Thanke you


Trimis din Yahoo Mail pe Android 
 
  Pe dum., iun. 27, 2021 la 19:06, Ming ***@***.***> a scris:   


Due to some secure problems, now session stored in cookie only works for https. We use secure and httponly flag, so do you use https protocol?

**Comment by flycash** [comment]
so, could you please provide the demo to reproduce this problem?

**Comment by Sorin35e** [comment]
How can I achieve following using beego session package?

[https://stackoverflow.com/questions/13446899/php-delete-another-session-given-the-id](url)
php style

```
$session_id_to_destroy = $sessionid;
// 1. commit session if it's started.
if (session_id()) {
    session_commit();
}

// 2. store current session id
session_start();
$current_session_id = session_id();
session_commit();

// 3. hijack then destroy session specified.
session_id($session_id_to_destroy);
session_start();
session_destroy();
session_commit();

// 4. restore current session id. If don't restore it, your current session will refer to the session you just destroyed!
session_id($current_session_id);
session_start();
session_commit();
```

**Comment by nevernet** [comment]
i got same issue
