### ISSUE TITLE
About issue #764 (Add bee generate routers command) Command is missing

### ISSUE THREAD

**Issue by FWangZil** [beego/beego#4681]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.12.3

2. What operating system and processor architecture are you using (`go env`)?
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/wang/go/bin"
GOCACHE="/Users/wang/Library/Caches/go-build"
GOENV="/Users/wang/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wang/go/pkg/mod"
GONOPROXY="e.coding.*"
GONOSUMDB="e.coding.*"
GOOS="darwin"
GOPATH="/Users/wang/go"
GOPRIVATE="e.coding.*"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1f/1pvhwc_x2z78fzht135w5sfh0000gn/T/go-build4266524057=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

https://github.com/beego/bee/pull/762

Run this command "bee generate routers [-ctrlDir=/path/to/controller/directory] [-routersFile=/path/to/routers/file.go] [-routersPkg=myPackage]"
---> FATAL ▶ 0001 Command is missing

4. What did you expect to see?
The commentsRouter_controllers.go update

5. What did you see instead?
bee error "Command is missing"

**Comment by flycash** [comment]
You need to upgrade your `bee` to develop branch. And it works for BeegoV2.

**Comment by jerryrt** [comment]
> You need to upgrade your `bee` to develop branch. And it works for BeegoV2.

Please mention this in the release note of v2.0.2. Hit by this and took hours to dig the issue.
