### ISSUE TITLE
what's the diffrence between adapter/orm and client/orm

### ISSUE THREAD

**Issue by cysnet** [beego/beego#4683]
what's the diffrence between adapter/orm and client/orm

**Comment by flycash** [comment]
You should never using `adapter/orm` directly. It's only used to help users to upgrade their application from v1 to v2.

**Comment by cysnet** [comment]
> You should never using `adapter/orm` directly. It's only used to help users to upgrade their application from v1 to v2.

got it, I think this issue can be closed.
