### ISSUE TITLE
The index of the orm does not work for m2m relationship

### ISSUE THREAD

**Issue by cysnet** [beego/beego#4685]
As title

**Comment by flycash** [comment]
Sorry, could you provide an example? I am confused about this.

**Comment by cysnet** [comment]
> Sorry, could you provide an example? I am confused about this.

as the bellow picture, when I mark the field 'ResearchGroups' as `orm:"rel(m2m);index;null"`, the index can not be successfully created on the column 'research_group_id' of the table ‘class_info_research_groups’
![image](https://user-images.githubusercontent.com/35944271/124361159-3e973480-dc60-11eb-879f-cee893a168d4.png)

![image](https://user-images.githubusercontent.com/35944271/124361224-861dc080-dc60-11eb-9aca-556fb23195a0.png)

**Comment by cysnet** [comment]
> Sorry, could you provide an example? I am confused about this.

so. is it a bug? or it's just a new feature?

**Comment by flycash** [comment]
I think it's not a bug. In my opinion, it should be "one-to-many" among classinfo and researchGroup. So may be you should create index on `ResearchGroup`

**Comment by cysnet** [comment]
> I think it's not a bug. In my opinion, it should be "one-to-many" among classinfo and researchGroup. So may be you should create index on `ResearchGroup`

it's many to many, not 'one-to-many'
