### ISSUE TITLE
beego是否支持grpc，支持的话该怎么调用？

### ISSUE THREAD

**Issue by chenzz11** [beego/beego#4696]
我在beego上，调用grpc时，遇到问题了，调用proto文件时
p2/controllers
controllers/testgrpc.go:31:7: undefined: pb
controllers/testgrpc.go:33:46: undefined: pb
2021/07/17 23:43:16 ERROR    ▶ 0005 Failed to build the application: # p2/controllers
我加了 pb ，就是proto所在位置，说是没找到，该怎么解决

**Comment by chenzz11** [comment]
我的go是作为客户端的，服务端是其他语言

**Comment by flycash** [comment]
不支持

**Comment by flycash** [comment]
这种问题其实不是 beego 的问题，而是你依赖的问题。即编译找不到文件

**Comment by chenzz11** [comment]
> 这种问题其实不是 beego 的问题，而是你依赖的问题。即编译找不到文件

好的，谢谢
