### ISSUE TITLE
tls设置版本tls.VersionTLS12无效

### ISSUE THREAD

**Issue by Qianggggg** [beego/beego#4706]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
GO 1.13
beegov1.12.3
2. What operating system and processor architecture are you using (`go env`)?
linux x86

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
设置tls版本后，不生效，代码设置如下
TLSConfig := &tls.Config{
      MinVersion: tls.VersionTLS12,
}
beego.BeeApp.Server.TLSConfig = TLSConfig

beego.Run()

使用openssl s_client -tls1 -connect xxxxx发现使用tls版本仍可以查到1.0版本
4. What did you expect to see?
tls设置未生效

5. What did you see instead?

**Comment by flycash** [comment]
Any error log?
