### ISSUE TITLE
bee pack打包后单独运行出现panic: err: go command required, not found: exec: "go": executable file not foun d in %PATH%: stderr:

### ISSUE THREAD

**Issue by hexinjun888** [beego/beego#4708]
panic: err: go command required, not found: exec: "go": executable file not foun
d in %PATH%: stderr:

goroutine 1 [running]:
github.com/beego/beego/v2/server/web.initBeforeHTTPRun.func1()
C:/Users/hexinjun/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web
/beego.go:83 +0x21f
sync.(*Once).doSlow(0x211c550, 0x1b3d4c0)
E:/Program Files/Go/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
E:/Program Files/Go/src/sync/once.go:59
github.com/beego/beego/v2/server/web.initBeforeHTTPRun()
C:/Users/hexinjun/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web
/beego.go:69 +0x54
github.com/beego/beego/v2/server/web.(*HttpServer).Run(0xc000004fd8, 0x0, 0x0, 0
x0, 0x0, 0x0)
C:/Users/hexinjun/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web
/server.go:85 +0x3b
github.com/beego/beego/v2/server/web.Run(0x0, 0x0, 0x0)
C:/Users/hexinjun/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/server/web
/beego.go:57 +0x6b
main.main()
D:/program/ISM组态/后端/ISM/main.go:18 +0x39

**Comment by flycash** [comment]
Please do not set `runmode=dev` when you want to deploy your application to test or prod environment

**Comment by oshellhahaha** [comment]
> Please do not set `runmode=dev` when you want to deploy your application to test or prod environment

希望能看到路由被访问的日记，使用prod模式的话就看不到了
