### ISSUE TITLE
orm rawPrepare.Exec  reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by betty0179** [beego/beego#4709]
Please answer these questions before submitting your issue. Thanks!

p,err := o.Raw("INSERT INTO a(at,value,created) VALUES(?,?,NOW())").Prepare()
_,err = p.Exec(111111,nil)
![image](https://user-images.githubusercontent.com/18591329/127645636-8e16509f-a9af-4053-af8e-b9af15f26cbf.png)

beego v1
![image](https://user-images.githubusercontent.com/18591329/127645665-0cfd9dc1-890a-4687-98c0-d727d6d18cf4.png)

beego v2.0.2
![image](https://user-images.githubusercontent.com/18591329/127645754-ecc9091e-6d6b-4483-ab86-f12a75204354.png)

why  add "flatParams := getFlatParams(nil, args, o.rs.orm.alias.TZ)" this code?

**Comment by jianzhiyao** [comment]
I get it. There is a bug in getFlatParams.
I will fix it ASAP.
