### ISSUE TITLE
多个项目beego.BConfig.AppName 获取不到正确的值

### ISSUE THREAD

**Issue by kaolaxiongg** [beego/beego#4719]
假设现在有2个项目 demo 和 demo1
我需要在 demo 项目接收到请求后，
通过 shell 脚本【nohup path > Log.log 2>&1 &】 重启 demo1项目，
但是 demo1 项目的beego.BConfig.AppName 获取的值是 demo的值，而不是demo1的值
无法成功启动

**Comment by flycash** [comment]
我没看懂你的问题。你有两个项目，应该是在不同路径之下，编译好之后，AppName应该就是稳定不变的。
