### ISSUE TITLE
有两个分组 但生成的swagger 中只有一个分组，  main也并到   "/api/v1 下面去了 

### ISSUE THREAD

**Issue by zwinfosoft** [beego/beego#4721]
1.使用  bee 1.12.0

2. 使用操作系统 windows7

3 我这样操作但是 没有得到两个分组，合并到一起了

	api := beego.NewNamespace("/api/v1",
	beego.NSNamespace("/object",
		beego.NSInclude(
			&SystemManager.ObjectController{},
		),
	),

	beego.NSNamespace("/goods",
		beego.NSInclude(
			&SystemManager.GoodsController{},
		),
	),
)
www := beego.NewNamespace("/api/v2",
	beego.NSNamespace("/main",
		beego.NSInclude(
			&SystemManager.MainController{},
		),
	),

)

beego.AddNamespace(www, api)

有两个分组 但生成的swagger 中只有一个分组，  main也并到  
"/api/v1 下面去了 

4. 希望在生成的swagger.json  在swagger 页面中可以看到两个分组，并可以选择只显示那一个组的api

**Comment by flycash** [comment]
请提供一下你脱敏的那些 controller 的定义，我来复现一下

**Comment by zwinfosoft** [comment]
> 
> 
> 请提供一下你脱敏的那些 controller 的定义，我来复现一下


GoodsController

package SystemManager

import (
	"encoding/json"
	"fmt"
	"hlzc/controllers"
	"hlzc/models"
)

// Operations about Goods
type GoodsController struct {
	controllers.BaseController
}

// @Title Create
// @Description create goods
// @Param	body		body 	models.Object	true		"The object content"
// @Success 200 {string} models.Object.Id
// @Failure 403 body is empty
// @router / [post]
func (o *GoodsController) Post() {
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)
	objectid := models.AddOne(ob)
	o.Data["json"] = map[string]string{"ObjectId": objectid}
	o.ServeJSON()
}

// @Title Get
// @Description find object by objectid
// @Param	objectId		path 	string	true		"the objectid you want to get"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [get]
func (o *GoodsController) Get() {
	objectId := o.Ctx.Input.Param(":objectId")
	if objectId != "" {
		ob, err := models.GetOne(objectId)
		if err != nil {
			o.Data["json"] = err.Error()
		} else {
			o.Data["json"] = ob
		}
	}
	fmt.Println(o.GetMySession("1"))
	o.ServeJSON()
}

// @Title GetAll
// @Description get all objects
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router / [get]
func (o *GoodsController) GetAll() {
	fmt.Println(o.GetMySession("1"))
	obs := models.GetAll()
	o.Data["json"] = obs
	o.ServeJSON()
}

// @Title Update
// @Description update the object
// @Param	objectId		path 	string	true		"The objectid you want to update"
// @Param	body		body 	models.Object	true		"The body"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [put]
func (o *GoodsController) Put() {
	objectId := o.Ctx.Input.Param(":objectId")
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)

	err := models.Update(objectId, ob.Score)
	if err != nil {
		o.Data["json"] = err.Error()
	} else {
		o.Data["json"] = "update success!"
	}
	o.ServeJSON()
}

// @Title Delete
// @Description delete the goods
// @Param	objectId		path 	string	true		"The objectId you want to delete"
// @Success 200 {string} delete success!
// @Failure 403 objectId is empty
// @router /:goodsId [delete]
func (o *GoodsController) Delete() {
	objectId := o.Ctx.Input.Param(":goodsId")
	models.Delete(objectId)
	o.Data["json"] = "delete success!"
	o.ServeJSON()
}


MainController 

package SystemManager

import (
	

	"hlzc/controllers"

)

type MainController struct {
	controllers.BaseController
}

// @Title Create 
// @Description create maingoods
// @Param	body		body 	models.Object	true		"The object content"
// @Success 200 {string} models.Object.Id
// @Failure 403 body is empty
// @router / [post]
func (o *MainController) Post() {
	
}

ObjectController
package SystemManager

import (
	"encoding/json"
	"hlzc/controllers"
	"hlzc/models"
)

// Operations about object
type ObjectController struct {
	controllers.BaseController
}

// @Title Create
// @Description create object
// @Param	body		body 	models.Object	true		"The object content"
// @Success 200 {string} models.Object.Id
// @Failure 403 body is empty
// @router / [post]
func (o *ObjectController) Post() {
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)
	objectid := models.AddOne(ob)
	o.Data["json"] = map[string]string{"ObjectId": objectid}
	o.ServeJSON()
}

// @Title Get
// @Description find object by objectid
// @Param	objectId		path 	string	true		"the objectid you want to get"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [get]
func (o *ObjectController) Get() {
	objectId := o.Ctx.Input.Param(":objectId")
	if objectId != "" {
		ob, err := models.GetOne(objectId)
		if err != nil {
			o.Data["json"] = err.Error()
		} else {
			o.Data["json"] = ob
		}
	}
	o.ServeJSON()
}

// @Title GetAll
// @Description get all objects
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router / [get]
func (o *ObjectController) GetAll() {
	obs := models.GetAll()
	o.Data["json"] = obs
	o.ServeJSON()
}

// @Title Update
// @Description update the object
// @Param	objectId		path 	string	true		"The objectid you want to update"
// @Param	body		body 	models.Object	true		"The body"
// @Success 200 {object} models.Object
// @Failure 403 :objectId is empty
// @router /:objectId [put]
func (o *ObjectController) Put() {
	objectId := o.Ctx.Input.Param(":objectId")
	var ob models.Object
	json.Unmarshal(o.Ctx.Input.RequestBody, &ob)

	err := models.Update(objectId, ob.Score)
	if err != nil {
		o.Data["json"] = err.Error()
	} else {
		o.Data["json"] = "update success!"
	}
	o.ServeJSON()
}

// @Title Delete
// @Description delete the object
// @Param	objectId		path 	string	true		"The objectId you want to delete"
// @Success 200 {string} delete success!
// @Failure 403 objectId is empty
// @router /:objectId [delete]
func (o *ObjectController) Delete() {
	objectId := o.Ctx.Input.Param(":objectId")
	models.Delete(objectId)
	o.Data["json"] = "delete success!"
	o.ServeJSON()
}

UserController

package SystemManager

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"hlzc/controllers"
	"hlzc/models"
	"hlzc/utils"
	"time"

	"github.com/dgrijalva/jwt-go"
)

var (
	SignKey string = "????????"
)

type User struct {
	ID       int    `json:"userId"`
	Username string `json:"username"`
	Admin    string `json:"admin"`
}

type LoginResult struct {
	User  interface{} `json:"user"`
	Token string      `json:"token"`
}

// Operations about Users
type UserController struct {
	controllers.BaseController
}

func (u *UserController) GenSha256(str string) string {
	h := sha256.New()
	h.Write([]byte(str))
	sum := h.Sum(nil)
	s := hex.EncodeToString(sum)
	return string(s)
}

// 生成令牌  创建jwt风格的token
func (u *UserController) GenerateToken(user User) LoginResult {
	claims := utils.CustomClaims{
		user.ID,
		user.Username,
		jwt.StandardClaims{
			NotBefore: int64(time.Now().Unix() - 1000),                // 签名生效时间
			ExpiresAt: int64(time.Now().Add(time.Minute * 60).Unix()), // 过期时间 N 秒
			Issuer:    "cfun",                                         //签名的发行者
		},
	}

	token, err := u.GetJwt().CreateToken(claims)
	if err != nil {
		return LoginResult{
			User:  user,
			Token: token,
		}
	}

	data := LoginResult{
		User:  user,
		Token: token,
	}
	return data
}

// @Title CreateUser
// @Description create users
// @Param	body		body 	models.User	true		"body for user content"
// @Success 200 {int} models.User.Id
// @Failure 403 body is empty
// @router / [post]
func (u *UserController) Post() {
	var user models.User
	json.Unmarshal(u.Ctx.Input.RequestBody, &user)
	uid := models.AddUser(user)
	u.Data["json"] = map[string]string{"uid": uid}
	u.ServeJSON()
}

// @Title GetAll
// @Description get all Users
// @Param	token		header  	string	true		"通关令牌"
// @Success 200 {object} models.User
// @router / [get]
func (u *UserController) GetAll() {
	users := models.GetAllUsers()
	//u.Data["json"] = users
	//u.ServeJSON()
	u.SuccessReturnValue("用户信息", users)
}

// @Title Get
// @Description get user by uid
// @Param	uid		path 	string	true		"The key for staticblock"
// @Success 200 {object} models.User
// @Failure 403 :uid is empty
// @router /:uid [get]
func (u *UserController) Get() {
	uid := u.GetString(":uid")
	if uid != "" {
		user, err := models.GetUser(uid)
		if err != nil {
			u.Data["json"] = err.Error()
		} else {
			u.Data["json"] = user
		}
	}
	u.ServeJSON()
}

// @Title Update
// @Description update the user
// @Param	uid		path 	string	true		"The uid you want to update"
// @Param	body		body 	models.User	true		"body for user content"
// @Success 200 {object} models.User
// @Failure 403 :uid is not int
// @router /:uid [put]
func (u *UserController) Put() {
	uid := u.GetString(":uid")
	if uid != "" {
		var user models.User
		json.Unmarshal(u.Ctx.Input.RequestBody, &user)
		uu, err := models.UpdateUser(uid, &user)
		if err != nil {
			u.Data["json"] = err.Error()
		} else {
			u.Data["json"] = uu
		}
	}
	u.ServeJSON()
}

// @Title Delete
// @Description delete the user
// @Param	uid		path 	string	true		"The uid you want to delete"
// @Success 200 {string} delete success!
// @Failure 403 uid is empty
// @router /:uid [delete]
func (u *UserController) Delete() {
	uid := u.GetString(":uid")
	models.DeleteUser(uid)
	u.SuccessReturn("delete success!")
}

// @Title checktoken2
// @Description token用户快速登录
// @Param	token		path 	string	true		"The Token you want to check"
// @Success 200 {string} 快速登录成功
// @Failure 403 token用户快速登录失败
// @router /checktoken2/:token [post]
func (u *UserController) CheckToken2() {
	token := u.GetString(":token")
	if len(token) < 1 {
		u.ErrorReturn("没有带入参数token")
	}
	ok, info := u.TokenCheck(token)
	if !ok {
		u.ErrorReturn(info)
	}
	u.SuccessReturn("Token验证通过")
}

// @Title checktoken
// @Description token用户快速登录
// @Param	token		query 	string	true		"The Token you want to check"
// @Success 200 {string} 快速登录成功
// @Failure 403 token用户快速登录失败
// @router /checktoken [post]
func (u *UserController) CheckToken() {
	token := u.GetString("token")
	if len(token) < 1 {
		u.ErrorReturn("没有带入参数token")
	}
	ok, info := u.TokenCheck(token)
	if !ok {
		u.ErrorReturn(info)
	}
	u.SuccessReturn("Token验证通过")
}

// @Title Login
// @Description 用户登录系统
// @Param	username		query 	string	true		"The username for login"
// @Param	password		query 	string	true		"The password for login"
// @Success 200 {string} 登录失败
// @Failure 403 user not exist
// @router /login [post]
func (u *UserController) Login() {
	username := u.GetString("username")
	password := u.GetString("password")
	if models.Login(username, password) {

		var usr User
		usr.Username = username
		if username == "admin" {
			usr.Admin = "true"
		} else {
			usr.Admin = "false"
		}
		tokens := u.GenerateToken(usr)
		u.DelMySession(username)
		u.SetMySession(username, tokens.Token)
		u.SuccessReturnValue("登录成功", tokens.Token)
	} else {
		u.ErrorReturn("登录失败")
	}

}

// @Title logout
// @Description 注销登录用户
// @Param	token		header  	string	true		"通关令牌"
// @Success 200 {string} logout success
// @router /logout [get]
func (u *UserController) Logout() {
	u.DelMySession(u.GetCurUser())
	u.SuccessReturn("logout success ")
}

**Comment by flycash** [comment]
应该改成：
```go
beego.NewNamespace("/api",
   beego.NsNamespace("/v1"),
  beego.NsNamespace("/v2"),
```
这种写法应该是对的。因为它们共享了一个 api
