### ISSUE TITLE
beego如何设置https中间证书

### ISSUE THREAD

**Issue by zhailianxing** [beego/beego#4724]
设置支持https，我在conf/app.conf 设置如下：
HttpsPort = 8082
EnableDocs = true
EnableHTTPS=true
EnableHttpTLS = true
HTTPSCertFile = "conf/server.crt"
HTTPSKeyFile = "conf/server.key"

=========分割线
但是我还想设置一下 中间证书（fullchain）， 应该怎么设置

**Comment by flycash** [comment]
目前，我们暂时不支持这个参数
