### ISSUE TITLE
XSS in Admin Panel

### ISSUE THREAD

**Issue by omriinbar** [beego/beego#4727]
When navigating to a page, the path is not sanitized in the "Request statistics" in the admin panel, leading to an XSS.

For example, navigating to ```http://beego-site/<script>alert(1)</script>``` leads to an alert when viewed on the admin panel:
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/80689106/129478530-f7b08e49-8dba-4e4f-a122-f2f82c6400dc.png)

**Comment by flycash** [comment]
Please update to newest `master` branch. Be careful, do not use `develop` branch.
