### ISSUE TITLE
v1.12.3 Ctx.Input.URL() and Ctx.Input.URI() return the same result without decoding

### ISSUE THREAD

**Issue by Enokiy** [beego/beego#4733]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
  Go: 
![image](https://user-images.githubusercontent.com/33446650/129995656-b2c4f1cf-d0cc-4443-aed7-fe644b9ce7c6.png)
beego:
![image](https://user-images.githubusercontent.com/33446650/129995723-ebdeeaf5-e6fe-49f4-84d2-df541c2d1b39.png)

2. What operating system and processor architecture are you using (`go env`)?
![image](https://user-images.githubusercontent.com/33446650/129995809-a1528beb-4dc6-4b99-a371-2c734647b59c.png)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
(1) define two route as follow:
![image](https://user-images.githubusercontent.com/33446650/129995885-746b66ef-9d1b-4bcb-8f36-7081aa8bb2b8.png)

(2)send request like this:
![image](https://user-images.githubusercontent.com/33446650/129995990-7a912f0c-891c-408d-8dc2-e147a004ce74.png)

(3) the route result :
![image](https://user-images.githubusercontent.com/33446650/129996131-eedfa13f-c40c-4f01-a57b-57ad1e2d6c4b.png)

the url matched router /v1/user/:user_name/info,not  /v1/user/abc/info

under the beego version 1.12.1 and 1.12.2,the /v1/user/ab%63/info will match the router URL   /v1/user/abc/info
If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
normally,it would print url = /v1/user/abc/info,uri = /v1/user/ab%63/info ,and this request would pick the router : /v1/user/abc/info

5. What did you see instead?

**Comment by flycash** [comment]
could you show me the source code of `func (input *BeegoInput) URI() string {}`?

**Comment by Enokiy** [comment]
sorry to respond too late，this is the source code：
![image](https://user-images.githubusercontent.com/33446650/131937367-bd30d803-3bb4-4559-8b0f-976103473e67.png)
![image](https://user-images.githubusercontent.com/33446650/131937416-522b9fa9-ff65-4677-91e1-552fff86ad76.png)
