### ISSUE TITLE
orm.Delete func unexpectedly erases the ID field

### ISSUE THREAD

**Issue by cavanwang** [beego/beego#4734]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v1.12.3

2. What operating system and processor architecture are you using (`go env`)?
linux arm64

3. What did you do?
        func CleanDevice(dev *Device) error {
	    pkg.LogInfo("dev id before delete is %v", dev.Id) // here I got output dev.Id is 53
	    _, err = o.Delete(dev)
	    if err != nil {
		    return err
	    }
	    pkg.LogInfo("dev id after delete is %v", dev.Id). // here I got output dev.Id is 0
       }

// here is schema definition
type Device struct {
	Id             int64          `json:"id"`
	DeviceAddr     string         `orm:"size(84)" json:"deviceAddr"`
	DeviceName     string         `orm:"size(32)" json:"deviceName"`
	DeviceAddType  int            `json:"deviceAddType"`
	DeviceDetail   *DeviceDetail  `json:"-" orm:"-"`
}

4. What did you expect to see?
I think after o.Delete, the dev.Id should be still 53.

5. What did you see instead?
I got the dev.Id is changed to 0 after o.Delete.

**Comment by cavanwang** [comment]
240 // delete model in database
241 // cols shows the delete conditions values read from. default is pk
242 func (o *orm) Delete(md interface{}, cols ...string) (int64, error) {
243         mi, ind := o.getMiInd(md, true)
244         num, err := o.alias.DbBaser.Delete(o.db, mi, ind, o.alias.TZ, cols)
245         if err != nil {
246                 return num, err
247         }
248         if num > 0 {
249                 o.setPk(mi, ind, 0)
250         }
251         return num, nil
252 }.    why the 248 want to erase my Id key to 0 ???

**Comment by flycash** [comment]
I don't understand it either. But I think it could be removed now.

**Comment by flycash** [comment]
Please update to `github.com/astaxie/beego@master`

**Comment by cavanwang** [comment]
Well, hope it works fine.

**Comment by cavanwang** [comment]
It not fixed: 
I found https://github.com/astaxie/beego/pull/7/files try to fix the bug, but it don't do it.

The orm.Delete will call db.Delete(orm/db.go) and then, Delete func in db.go will do: 

 695         query := fmt.Sprintf("DELETE FROM %s%s%s WHERE %s%s%s = ?", Q, mi.table, Q, Q, wheres, Q)
 696
 697         d.ins.ReplaceMarks(&query)
 698         res, err := q.Exec(query, args...)
 699         if err == nil {
 700                 num, err := res.RowsAffected()
 701                 if err != nil {
 702                         return 0, err
 703                 }
 704                 if num > 0 {
 705                         if mi.fields.pk.auto {
 706                                 if mi.fields.pk.fieldType&IsPositiveIntegerField > 0 {
 707                                         ind.FieldByIndex(mi.fields.pk.fieldIndex).SetUint(0)
 708                                 } else {
 709                                         ind.FieldByIndex(mi.fields.pk.fieldIndex).SetInt(0)
 710                                 }

The line 709 is to delete the ID field to 0.

Please fix the bug.
