### ISSUE TITLE
orm.Delete is still to set ID to 0

### ISSUE THREAD

**Issue by cavanwang** [beego/beego#4741]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
github.com/astaxie/beego v1.12.3-0.20210819135216-34334a52beae

2. What operating system and processor architecture are you using (`go env`)?
I issued the question at https://github.com/beego/beego/issues/4734, you said it is fixed, but the bug is there yet.

3. What did you do?
Refer to above desc.

4. What did you expect to see?
Refer to above desc.

5. What did you see instead?

**Comment by flycash** [comment]
Please update it. I try with Beego2.0, it works well. And I have copied the code to BeegoV1.x.
