### ISSUE TITLE
astaxie/beego 和 beego/beego 是啥关系？我新手被各个例子代码蒙圈了

### ISSUE THREAD

**Issue by paddy235** [beego/beego#4745]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
换了一个组织。beego/beego 包的位置也挪动了，你可以看看 beego.me 或者 https://github.com/beego/beedoc
