### ISSUE TITLE
缺少Using函数|In the "github.com/beego/beego/v2/client/orm" lack of Using function  

### ISSUE THREAD

**Issue by weiliemgodosun** [beego/beego#4746]
在v1.12.3时 orm切换数据库可以使用Using，新版v2.0.1中使用“github.com/beego/beego/v2/client/orm”时只能使用NewOrmUsingDB 创建一个新的orm对象的同时切换数据库，而不能在原有的orm上切换数据库，或者是使用“github.com/beego/beego/v2/adapter/orm/”中有Using,但这又需要另外再做一些额外的一些处理； 
此处能否增加一个兼容Using

**Comment by flycash** [comment]
我们应该不会再提供这个方法了，因为`Using`会引来并发问题。你可以自己尝试封装一个，如果你真的需要的话，就是类似我们在 adapter 中做的那样。
