### ISSUE TITLE
静态目录static中否也支持cors跨域访问

### ISSUE THREAD

**Issue by zwqjoy** [beego/beego#4751]
我设置了
	//beego.InsertFilter("*", beego.BeforeRouter, cors.Allow(&cors.Options{
	//	//AllowAllOrigins:  true,
	//	AllowOrigins:     []string{"http://atlas.duxiaoman-int.com:*", "http://localhost:*", "http://127.0.0.1:*"},
	//	AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
	//	AllowHeaders:     []string{"Origin", "Authorization", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers", "Content-Type"},
	//	ExposeHeaders:    []string{"Content-Length", "Origin", "Authorization", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers", "Content-Type"},
	//	AllowCredentials: true,
	//}))

但是前端使用static 还是出现cors问题

**Comment by barryzxy** [comment]
我最近也发现了这个问题  卡住了

**Comment by flycash** [comment]
`beego.BeforeRouter`肯定不行，因为静态资源是在BeforeRouter之前就被 block了，试试用 beego.BeforeStatic。
另外以后还是用英文提问吧，不然我这边给我们中国开发解释一遍，后面再给老外解释一遍，我感觉要崩溃=。=
