### ISSUE TITLE
beego api生成的项目，直接启动请求url 返回都是404页面，文档又没说明，都不知道怎么解决，无语。

### ISSUE THREAD

**Issue by yeshili** [beego/beego#4752]
这个问题我换了几台电脑，都一样，包括我叫一些朋友安装都一样
![image](https://user-images.githubusercontent.com/24773628/131113981-10236e9a-635c-49f1-b152-9dca970b5c51.png)
然后请求http://localhost:8080/v1/object/
![image](https://user-images.githubusercontent.com/24773628/131114133-1c435e74-d2a9-4939-b9fc-b095a89ae212.png)

那位大神遇到这些问题，如何解决呀，搞了好多天

**Comment by flycash** [comment]
Please translate this issue to English so it could help other users and then provide your code. I had created a similar project but it worked well.

**Comment by Laurel-rao** [comment]
use beego generate a new project，then access a built-in api like "/v1/object", the http status code shows 404.
