### ISSUE TITLE
How to use multiple databases?

### ISSUE THREAD

**Issue by chenzhidongweb** [beego/beego#4754]
看文档有写支持多库查询，但是没有示例

**Comment by chenzhidongweb** [comment]
Sorry, How to use one or more mysql to search.

Please give me a example

**Comment by chenzhidongweb** [comment]
I want to use more mysql in orm

**Comment by flycash** [comment]
You could register multiple database by using:
![image](https://user-images.githubusercontent.com/9923838/131528209-f9ebfd04-5d1f-43d6-943a-6209e2fe63b1.png)

you could change `default` to other name. For example, if you have two databases, user and order, you could register those two databases:
```
orm.RegisterDataBase("user", "mysql", "root:root@/orm_test?charset=utf8")
orm.RegisterDataBase("order", "mysql", "root:root@/orm_test?charset=utf8")
```

After that, you could create `Orm` instance by calling:
![image](https://user-images.githubusercontent.com/9923838/131528559-a2271d93-47e3-4c1c-a6cc-4b836147da13.png)
```go
userOrm := orm.NewOrmUsingDB("user")
orderOrm := orm.NewOrmUsingDB("order")
```
https://beego.me/docs/mvc/model/orm.md

**Comment by chenzhidongweb** [comment]
Ok I trying,

Think you

**Comment by chenzhidongweb** [comment]
I found a new problem

After executing github.com/beego/beego/v2/core/validation found

Please update doc
