### ISSUE TITLE
Can not generate routers when I upgrade beego version v1.12.2 or higher.

### ISSUE THREAD

**Issue by moqimoqidea** [beego/beego#4762]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

```text
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.12.0

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.17
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : /Users/moqi/.gvm/pkgsets/go1.17/global
├── GOROOT    : /Users/moqi/.gvm/gos/go1.17
├── Compiler  : gc
└── Date      : Sunday, 5 Sep 2021
```

2. What operating system and processor architecture are you using (`go env`)?

```text
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/moqi/Library/Caches/go-build"
GOENV="/Users/moqi/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/moqi/.gvm/pkgsets/go1.17/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/moqi/.gvm/pkgsets/go1.17/global"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/Users/moqi/.gvm/gos/go1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/moqi/.gvm/gos/go1.17/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/moqi/.gvm/pkgsets/go1.17/global/src/magma-backend/magma/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ll/bpfz8yks34d19wxnh1jlb3nc0000gn/T/go-build198672406=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

```text
I maintained a legacy project use beego v1.10.0, recently I want set this project use beego v1 last version v1.12.3.

when I upgrade v1.12.3, I saw generate router files is not work.

I used the binary search method to gradually try the version located in the middle of the v1.10.0 and v1.12.3, and finally found that v1.12.1 worked, but v1.12.2 didn't.

I go to https://beego.me/docs/intro/releases.md to see what's different between v1.12.1 and v1.12.2, but I could not find this message, because this page show the version before v1.12.2 is v1.10.0
```

5. What did you see instead?

```text
v1.12.2 could not generate router files.
```

**Comment by moqimoqidea** [comment]
Another related problem is that when I use version v1.12.1, the function of generating routing files when I am under go src is available.

But when I am in another directory, beego will show the following log:

```shell
Running application outside of GOPATH
```

At this time, the function of generating routing files is not available.

I checked some information, it seems that only after upgrading to v2 can the routing file be generated outside the src directory, but no relevant content can be found from https://beego.me/docs/intro/releases.md, I just want to confirm this Is feature v1 unavailable?

thank you.

**Comment by flycash** [comment]
Sorry, `bee generating router` command only works for v2. And in v1.12.1, if you run `bee run` it should generate the router files for you.

**Comment by moqimoqidea** [comment]
thank you for your reply, as I saw, yes, And in v1.12.1, if I run `bee run` it should generate the router files for me.

but when I upgrade to v1.12.2, it couldn't.

I want to figure out, it's something I do wrong? or I need setting something on somewhere? or v1.12.2 and v1.12.3 just could not generate router files? or something else?

thank you again.
