### ISSUE TITLE
The difference between v1 and v2  

### ISSUE THREAD

**Issue by HaoKunT** [beego/beego#4765]
Is there any document introduce how to migrate the project from v1 to v2? Or the v1 wiil also update when there is a new feature release?

**Comment by flycash** [comment]
We will continue fix bugs of v1. And if you want to migrate your project from v1 to v2, we provide the module `adapter` and you can use `bee` command to upgrade Beego:
```shell
Install the latest bee tool go get -u github.com/beego/bee/v2
Upgrading Beego go get -u github.com/beego/beego/v2

Running: bee fix -t 2

If you are working on Windows platform, please run this command in WSL
```
It's helpful. And you'd better update your Beego version to master branch because we had fixed some issues.
