### ISSUE TITLE
Can not use beego default_test.go to test POST request with body data 

### ISSUE THREAD

**Issue by peipeiguo** [beego/beego#4766]
1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
Ubuntu linux amd64

3. What did you do?
I want to test my POST api, so I reference TestGet in default_test.go:
1) copy TestGet as a new test case and change function name to TestUserLogin
2) default a body with json string, and pass it to http.NewRequest, such as:
```
func TestUserLogin(t *testing.T) {
	body := `{
		"username": "beego",
		"passowrd": "beego"
	}`
	r, _ := http.NewRequest("POST", "/login", strings.NewReader(body))
...// other code did not change, same as in TestGet sample
```
3) when I run test case use `go test tests/default_test.go`
4) It triggered my POST function in controller, **but there is no data in c.Ctx.Input.RequestBody, I can not get the test json string.**

4. What did you expect to see?
I expect to get the corrent json string in Post function of controller.

5. What did you see instead?
 There is no data in c.Ctx.Input.RequestBody, I can not get the test json string in controller. So that I can not use beego default_test.go to test POST request with body data.

I checked `beego.BeeApp.Handlers.ServeHTTP(w, r)`, it set the request to ctx.Request, but ctx.Input is reseted. Where to set the c.Ctx.Input.RequestBody?
```
// Reset initializes Context, BeegoInput and BeegoOutput
func (ctx *Context) Reset(rw http.ResponseWriter, r *http.Request) {
	ctx.Request = r
	if ctx.ResponseWriter == nil {
		ctx.ResponseWriter = &Response{}
	}
	ctx.ResponseWriter.reset(rw)
	ctx.Input.Reset(ctx)
	ctx.Output.Reset(ctx)
	ctx._xsrfToken = ""
}
```

Thanks.

**Comment by flycash** [comment]
`ctx.Input.Reset(ctx)` has reset the body:
```go
// Reset initializes the BeegoInput
func (input *BeegoInput) Reset(ctx *Context) {
	input.Context = ctx
	input.CruSession = nil
	input.pnames = input.pnames[:0]
	input.pvalues = input.pvalues[:0]
	input.dataLock.Lock()
	input.data = nil
	input.dataLock.Unlock()
	input.RequestBody = []byte{}
}

```

**Comment by peipeiguo** [comment]
Hi @flycash, I think you did not understand my question. 
I want to send a POST request with body, but the body has been reset by ctx.Input.Reset(ctx).
