### ISSUE TITLE
2.0 模型新增数据 Error 1062: Duplicate entry '' for key 'PRIMARY'

### ISSUE THREAD

**Issue by deepsea-tyy** [beego/beego#4773]
**env**
mac go1.17.1 darwin/amd64

**我执行的操作**
bee generate scaffold user -conn="root:123456@tcp(127.0.0.1:3305)/mysql?charset=utf8mb4" -fields="name:string"
生成的代码

![image](https://user-images.githubusercontent.com/16817929/134110036-e2d74c46-39c4-4e1c-93f9-ebbfbe767a78.png)

添加数据一直报错 Error 1062: Duplicate entry '' for key 'PRIMARY'

**Comment by flycash** [comment]
could you please provide log? and the beego version
