### ISSUE TITLE
Getting error: - Failed to watch directory: bad file descriptor

### ISSUE THREAD

**Issue by pranavamagi** [beego/beego#4774]
Trying to generate swagger docs using this command: -
`bee run -downdoc=true -gendoc=true`

but getting error as: - 
2021/09/21 17:47:15 INFO     ▶ 0001 Using 'epg' as 'appname'
2021/09/21 17:47:15 INFO     ▶ 0002 Downloading 'https://github.com/beego/swagger/archive/v3.zip' to 'swagger.zip'...
2021/09/21 17:47:16 SUCCESS  ▶ 0003 477861 bytes downloaded!
2021/09/21 17:47:16 INFO     ▶ 0004 Unzipping 'swagger.zip'...
2021/09/21 17:47:17 SUCCESS  ▶ 0005 Done! Deleting 'swagger.zip'...
2021/09/21 17:47:17 INFO     ▶ 0006 Initializing watcher...
**2021/09/21 17:47:17 FATAL    ▶ 0007 Failed to watch directory: bad file descriptor**

Any ideas how to fix this?

**Comment by flycash** [comment]
It seems that some had reported similar issue before but I can not reproduce it. So please retry.
