### ISSUE TITLE
ctx.Input.ParseFormOrMultiForm(p.cfg.MaxMemory)  Error parsing request body:invalid URL escape "%\","

### ISSUE THREAD

**Issue by myselfghost** [beego/beego#4775]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
2.0.1

error : [E] [router.go:733]  Error parsing request body:invalid URL escape "%\","

when i post data like:
curl -i '127.0.0.1:12345/events/' -X POST -d '{"unit":"%"}'

**Comment by flycash** [comment]
how about specifying header `Content-Type`?
