### ISSUE TITLE
different route path controller use different http.HandFunc

### ISSUE THREAD

**Issue by lancewz** [beego/beego#4777]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
2.0

2. What operating system and processor architecture are you using (`go env`)?
linux

3. What did you do?
different route path controller（routerTypeBeego not routerTypeHandler） use different middleware like this：
otelHandlerA := otelhttp.NewHandler(http.HandlerFunc(HelloHandler), "a")
http.Handle("a", otelHandlerA)
otelHandlerB := otelhttp.NewHandler(http.HandlerFunc(HelloHandler), "b")
http.Handle("b", otelHandlerB)

4. What did you expect to see?
different route path controller（routerTypeBeego not routerTypeHandler） use different middleware like this：
otelHandlerA := otelhttp.NewHandler(http.HandlerFunc(HelloHandler), "a")
http.Handle("a", otelHandlerA)
otelHandlerB := otelhttp.NewHandler(http.HandlerFunc(HelloHandler), "b")
http.Handle("b", otelHandlerB)

5. What did you see instead?

**Comment by flycash** [comment]
Sorry, I cannot understand. Can you provide a demo?

**Comment by lancewz** [comment]
> Sorry, I cannot understand. Can you provide a demo?

Can I use different middleware with different path？
For example，I can use std http package like this：
otelHandlerA := otelhttp.NewHandler(http.HandlerFunc(HelloHandlerA), "a")
http.Handle("/a", otelHandlerA)
otelHandlerB := otelhttp.NewHandler(http.HandlerFunc(HelloHandlerB), "b")
http.Handle("/b", otelHandlerB)

Here create 2 different handler with name "a" and "b" to handle path "/a" and "/b".

Buy I don't konw how can I use different middleware with different path by beego controller.
