### ISSUE TITLE
Is this a BeeLogger bug ? 

### ISSUE THREAD

**Issue by nonenull** [beego/beego#4781]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
github.com/beego/beego/v2 v2.0.1
```
2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
```
package main

import "github.com/beego/beego/v2/core/logs"

func main()  {
	var logger = logs.GetBeeLogger()
	logger.Debug("my name is : %s", "test")
}
```

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
```
2021/09/29 10:09:52.792 [D]  my name is : test
```

5. What did you see instead?
```
2021/09/29 10:09:52.792 [D]  my name is : %s
```

The source of the problem comes from core/logs/log_msg.go
```
// OldStyleFormat you should never invoke this
func (lm *LogMsg) OldStyleFormat() string {
	msg := lm.Msg

	if len(lm.Args) > 0 {
		lm.Msg = fmt.Sprintf(lm.Msg, lm.Args...)
	}

	msg = lm.Prefix + " " + msg

	if lm.enableFuncCallDepth {
		filePath := lm.FilePath
		if !lm.enableFullFilePath {
			_, filePath = path.Split(filePath)
		}
		msg = fmt.Sprintf("[%s:%d] %s", filePath, lm.LineNumber, msg)
	}

	msg = levelPrefix[lm.Level] + " " + msg
	return msg
}

```

If I change the code to the following, there is no problem
```
// OldStyleFormat you should never invoke this
func (lm *LogMsg) OldStyleFormat() string {
	//msg := lm.Msg

	if len(lm.Args) > 0 {
		lm.Msg = fmt.Sprintf(lm.Msg, lm.Args...)
	}

	msg := lm.Prefix + " " + lm.Msg

	if lm.enableFuncCallDepth {
		filePath := lm.FilePath
		if !lm.enableFullFilePath {
			_, filePath = path.Split(filePath)
		}
		msg = fmt.Sprintf("[%s:%d] %s", filePath, lm.LineNumber, msg)
	}

	msg = levelPrefix[lm.Level] + " " + msg
	return msg
}

```

**Comment by shengzan** [comment]
this is a bug, i meet also, you must modify like follow
``
func (lm *LogMsg) OldStyleFormat() string {
	msg := lm.Msg

	if len(lm.Args) > 0 {
		msg = fmt.Sprintf(lm.Msg, lm.Args...)   // lm.Msg => msg
	}

	msg := lm.Prefix + " " + msg

	if lm.enableFuncCallDepth {
		filePath := lm.FilePath
		if !lm.enableFullFilePath {
			_, filePath = path.Split(filePath)
		}
		msg = fmt.Sprintf("[%s:%d] %s", filePath, lm.LineNumber, msg)
	}

	msg = levelPrefix[lm.Level] + " " + msg
	return msg
}
``

**Comment by flycash** [comment]
It has been fixed, can you update to master newest commit id?

**Comment by shengzan** [comment]
```
func (lm *LogMsg) OldStyleFormat() string {
	msg := lm.Msg

	if len(lm.Args) > 0 {
		msg = fmt.Sprintf(lm.Msg, lm.Args...)   //lm.Msg => msg
	}

	msg := lm.Prefix + " " + msg

	if lm.enableFuncCallDepth {
		filePath := lm.FilePath
		if !lm.enableFullFilePath {
			_, filePath = path.Split(filePath)
		}
		msg = fmt.Sprintf("[%s:%d] %s", filePath, lm.LineNumber, msg)
	}

	msg = levelPrefix[lm.Level] + " " + msg
	return msg
}
```
