### ISSUE TITLE
How to close the connection without any response?

### ISSUE THREAD

**Issue by curiosport** [beego/beego#4799]
Basically I have this code:

```
beego.Router("/home", &home.hController{})

type hController struct { beego.Controller }
func (c *hController) Post() {
	//instructions
	// here I want to close the connection without responding to the user
}
```

Beego always wants to respond with a templatefile but there are situations where I simply want to close the communication, how do I do that?

**Comment by flycash** [comment]
We cannot close the TCP connection manually because we handle the `HTTP` protocol. We only have two major types `http.Request` and `http.ResponseWriter`, both of them didn't expose API which can be used to close the connection

**Comment by curiosport** [comment]
then I should use a firewall, which one do you recommend that integrates well with beego?
