### ISSUE TITLE
Unable to find a common entrypoint for all beego applications.

### ISSUE THREAD

**Issue by MukulLatiyan** [beego/beego#4805]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
```
Go version - 1.16.3 and beego version - v2.0.1
```

2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/immukul/Library/Caches/go-build"
GOENV="/Users/immukul/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/immukul/go_projects/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/immukul/go_projects"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sw/3sf10q9d01g900tpydg1cy780000gn/T/go-build3539884294=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
> I tried building the beego sample applications that are provided in the beego-example repository, none of them worked. Then I tried some examples available on the internet and couldn't find out a proper approach to build and start a beego application. Can anyone here suggest the name of the function that gets invoked almost all the time when making use of the beego framework?

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
N/A

5. What did you see instead?
N/A

**Comment by sdlyingyong** [comment]
Start the project with bee run in the project path.
Maybe your dependencies need to be updated, use go mod init and then go mod tidy , and finally bee run to start the project.
