### ISSUE TITLE
When the table is automatically created, there is no corresponding MySQL 'TEXT' type

### ISSUE THREAD

**Issue by usernameisnull** [beego/beego#4810]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version go1.16.6 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
when create table from orm, no MySQL 'TEXT' type corresponding 
![image](https://user-images.githubusercontent.com/3390414/140709818-983aa49b-6bef-49c5-b967-00880932f937.png)

5. What did you see instead?

**Comment by flycash** [comment]
I think it looks like a typo. It should be text
