### ISSUE TITLE
BEEGO_FLASH cookie has Max-Age of 0

### ISSUE THREAD

**Issue by loelu** [beego/beego#4812]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
Go 1.17.3
Bee v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
Linux, amd64

3. What did you do?
```go
func (c *MainController) Post() {
	flash := web.NewFlash()
	flash.Success("Success")
	flash.Store(&c.Controller)
	c.Redirect("/", 302)
}
```

4. What did you expect to see?
Expect to see the flash message. 

5. What did you see instead?
No flash message, but following error in the console:
`Cookie “BEEGO_FLASH” has been rejected because it is already expired.`
This is because the Max-Age is set to 0 in this File: https://github.com/beego/beego/blob/develop/server/web/flash.go#L88
There was already an issue created for this exact problem, but it has been closed without a solution: https://github.com/beego/beego/issues/1642

**Comment by flycash** [comment]
could you help to fix it? you have already find the root cause
