### ISSUE TITLE
Access Log default level

### ISSUE THREAD

**Issue by mrigesh** [beego/beego#4813]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
Linux/amd64

3. What did you do?
This is not an error, but a query as such. Access logs in beego router have default log level set to -1 via logs.levelLoggerImpl which resolves it to `Emergency` log name. Is this intentional, and if I want to change the access log level to debug/info from emergency, how do I go about it.

4. What did you expect to see?
Log level Info

5. What did you see instead?
Log level `emergency`

**Comment by flycash** [comment]
I didn't get your point. If you want to output info log or debug log, just use `Info` or `Debug` function

**Comment by guhan121** [comment]
```
	logLevel := beego.AppConfig.DefaultInt("LogLevel", logs.LevelInformational)
	logPath := beego.AppConfig.DefaultString("LogPath", "/data/logs/aquaman.log")
	logger.SetLogger(logs.AdapterConsole, fmt.Sprintf(`{"level":%d}`, logLevel))
	if beego.BConfig.RunMode == "prod" || beego.BConfig.RunMode == "test" {
		err := logger.SetLogger(logs.AdapterFile, fmt.Sprintf(`{"level":%d, "filename":"%s"}`, logLevel, logPath))
		if err != nil {
			fmt.Fprint(os.Stderr, "error occurs when initializing log appender,", err.Error())
			os.Exit(1)
		}
	}
```
and set `LogLevel` in your `app.conf`

@mrigesh
