### ISSUE TITLE
How to remove default console color?

### ISSUE THREAD

**Issue by XianwuLin** [beego/beego#4815]
**1. What version of Go and beego are you using (`bee version`)?**
v2.0.2-beta.1.0.20211025154746-82919a08e766

**2. What operating system and processor architecture are you using (`go env`)?**
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/api/src/device/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1562920972=/tmp/go-build -gno-record-gcc-switches"

**3. What did you do?**
I have to set Bconfig, like this:
```go
beego.BConfig.Log.Outputs["console"] = `{"level":7, "color":"false"}`
```
or set global config like this:
```go
import "github.com/beego/beego/v2/core/logs"
f := &logs.PatternLogFormatter{
    Pattern:    "%w [%f:%n] %t - %m",
    WhenFormat: "2006-01-02 15:04:05.000",
}
logs.RegisterFormatter("pattern", f)
logs.SetGlobalFormatter("pattern")
```
but it does't work.

**4. What did you expect to see?**
I want to remove all log color, because I want to redirect log to log file, color output looks confused.

**5. What did you see instead?**
first use beego, I don't know what should I do.

**Comment by JessonChan** [comment]
package main

import "github.com/beego/beego/v2/core/logs"

func main() {
	log := logs.NewLogger()
	log.SetLogger("console", `{"color":false}`)
	log.Debug("hello")
}

**Comment by XianwuLin** [comment]
but I run `beego.Run()` it still output color characters.

**Comment by flycash** [comment]
do you set the color to false?

**Comment by flycash** [comment]
can you share your code?

**Comment by XianwuLin** [comment]
```go
package main

import (
	_ "device/routers"

	"github.com/beego/beego/v2/core/logs"
	beego "github.com/beego/beego/v2/server/web"
	_ "github.com/lib/pq"
)


func main() {
	log := logs.NewLogger()
	log.SetLogger("console", `{"color":false}`)

	// 运行
	beego.Run()
}
```
![image](https://user-images.githubusercontent.com/5524532/142959594-732dc5ef-d246-43ee-9c68-66f20f72aef8.png)

**Comment by XianwuLin** [comment]
Is there any progress?

**Comment by XianwuLin** [comment]
??

**Comment by XianwuLin** [comment]
@flycash ?

**Comment by blue-bird1** [comment]
@XianwuLin  
app.ini
```
LogOutputs = console,{"color":false}
```

**Comment by XianwuLin** [comment]
> @XianwuLin app.ini
> 
> ```
> LogOutputs = console,{"color":false}
> ```

![image](https://user-images.githubusercontent.com/5524532/148888972-4858e3b9-4de8-4a7b-a170-886f776eabe5.png)
![image](https://user-images.githubusercontent.com/5524532/148889185-5d9c9f01-a67f-4625-9a51-155569495893.png)

it don't work.

**Comment by guhan121** [comment]
@XianwuLin 
```
func init()  {
	logs.Reset()
	err := logs.SetLogger(logs.AdapterConsole, `{"color":false}`)
	fmt.Println(err)
}
```

**Comment by guhan121** [comment]
@JessonChan @XianwuLin @flycash 
`logs.NewLogger()`  init a AdapterConsole always use config=`{}`

**Comment by XianwuLin** [comment]
@guhan121

**Comment by XianwuLin** [comment]
@guhan121 
Your solution solved my problem, thanks a lot!
But I don't think this solution is very elegant.
