### ISSUE TITLE
beego v1大版本中的过滤器，会将所有的过滤器插入至一个单例，造成对过滤器的顺序依赖非常严重，ReturnOnOutput参数含义也不明确

### ISSUE THREAD

**Issue by liuyixian123** [beego/beego#4816]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
从设计原则上来说，我们这种注册模式，用户自己控制注册的顺序就好了。ReturnOnOutput 是指，如果已经有了数据，就直接返回。你可以理解为有响应了就直接返回

**Comment by liuyixian123** [comment]
> 从设计原则上来说，我们这种注册模式，用户自己控制注册的顺序就好了。ReturnOnOutput 是指，如果已经有了数据，就直接返回。你可以理解为有响应了就直接返回

那能否做一些改进呢？比如execFilter函数先去匹配pattern，匹配的上然后再执行具体的逻辑。当前的问题是：如果本条过滤器有了响应，此时returnOnOutput为false，那会在遇到下一条同类型的过滤器当其returnOnOutput为true时返回。这样有可能毫不相关的pattern却影响到了本过滤器的执行结果

**Comment by guhan121** [comment]
@liuyixian123  这个有点类似Django的中间件，都是有顺序的，按照你设计的顺序朝下走，有一个失败就会终止。这个不难理解啊。 如果你需要下一个中间件处理，也就是你上一个中间件允许这个uri通过，这个就是你自己要在filter里面实现的逻辑。
