### ISSUE TITLE
beego.me appears down

### ISSUE THREAD

**Issue by GalvinGao** [beego/beego#4818]
*This is not an issue related to the actual `beego` go module, but rather its related documentation site beego.me*

The website located at beego.me is no longer accessible with an error message from UCloud. Screenshot attached as below.

![6ABB54D7-7B13-4745-8BFE-636A896E4E89](https://user-images.githubusercontent.com/12567059/142739848-ef674f4c-729d-48c1-beda-3c4a6c00da0f.png)

Some suggestions for alternatives if you don't want to do ICP Beian for the website: CloudFlare Pages, GitHub Pages, and Netlify. All of those come with nice dashboard UIs along with CI/CD features.

**Comment by jincheng9** [comment]
@GalvinGao the website changes to [beego.vip](beego.vip)

**Comment by GalvinGao** [comment]
> @GalvinGao the website changes to [beego.vip](https://beego.vip/)

I see. Thanks for the reply! I think you might want to change the repo website to the correct one :D. It is currently still beego.me
