### ISSUE TITLE
orm Modal定义中多个Struct，执行LoadRelated的时候第二个会报错

### ISSUE THREAD

**Issue by devon6686** [beego/beego#4819]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2

2. What operating system and processor architecture are you using (`go env`)?

mac
3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

mysql driver
报错信息：runtime error: invalid memory address or nil pointer dereference

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
can you provide table schemas and the reproduce demo?
