### ISSUE TITLE
how to use when beego orm Commit err? 'isTX' is true and cannot release.

### ISSUE THREAD

**Issue by username-lu** [beego/beego#4820]
beego version  v1.12.2
I use orm to handle transaction ，and orm is global. The 'isTx' is setted true after exec BeginTx func.
isTx cannot set false, when orm commit fail. How can I do?

```go
func (o *orm) BeginTx(ctx context.Context, opts *sql.TxOptions) error {
	if o.isTx {
		return ErrTxHasBegan
	}
	var tx *sql.Tx
	tx, err := o.db.(txer).BeginTx(ctx, opts)
	if err != nil {
		return err
	}
	o.isTx = true
```
commit失败之后，isTX 无法重新置为false。
```go
func (o *orm) Commit() error {
	if !o.isTx {
		return ErrTxDone
	}
	err := o.db.(txEnder).Commit()
	if err == nil {
		o.isTx = false
		o.Using(o.alias.Name)
	} else if err == sql.ErrTxDone {
		return ErrTxDone
	}
	return err
}
```

下次事务提交，BeginTx会报错： “<Ormer.Begin> transaction already begin"。
这该如何处理？isTX应该如何释放？

**Comment by flycash** [comment]
Can you give a demo? I don't know what you mean "commit fail".
And if you want to use transaction, you'd better create `Orm` instance every time

**Comment by username-lu** [comment]
> Can you give a demo? I don't know what you mean "commit fail". And if you want to use transaction, you'd better create `Orm` instance every time


非常感谢您的回答。我看到以前的帖子，建议使用全局唯一的Orm吗？ https://github.com/beego/beego/pull/4800 https://github.com/beego/beego/issues/4793

我的orm是全局唯一的，如下定义
```go

func NewPostgresImpl(url string, tableName string, pgKpi *postgresio.PgKpi) error {
	once.Do(func() {
		pgImplTx = &PostgresTx{
			Lock:         sync.Mutex{},
			PostgresImpl: PostgresImpl{
				tableName: tableName,
				pgKpi:     pgKpi,
			},
		}

		orm.RegisterModel(new(ItemInPg))
	})
	err := initPg(url)
	if err != nil {
		return errors.Wrap(err, "initPg")
	}
	pgImplTx.Ormer = orm.NewOrm()
	return nil
}
```

当我在begin和commit之间加sleep(20s)，然后重启pg数据库时（容易复现异常场景），tcp链接断开，调用数据库会报错connection reset by peer，
当下次数据库事务操作再次调用begin时，会报错<Ormer.Begin> transaction already begin。
分析是上次事务断开链接时，commit失败，isTx没有释放；所以这次事务begin操作无法执行。
再分析代码，只有commit和rollback成功可以释放isTx，但是commit失败之后再执行rollback又会引出新的问题，所以无法执行rollback。参考 https://segmentfault.com/a/1190000021650924 ，因此commit失败之后无法释放isTx。

```go
func (this *DbTx) Exec() error {
	this.Context.PgImpl.Lock.Lock()
	defer this.Context.PgImpl.Lock.Unlock()

	if len(this.actions) == 0 {
		return nil
	}

	klog.Debugf("actions: %v", this.actions)
	var err error
	defer func() {
		if e := recover(); e != nil {
			err = errors.Errorf("%v", e)
			klog.Errorf("", err)
			this.rollback()
		} else if err != nil {
			klog.Errorf("", err)
			this.rollback()
		} else {
			klog.Debug("commit")
			err = this.commit()
		}
	}()

	if err = this.Context.PgImpl.Begin(); err != nil {
		return err
	}
        
       //time.Sleep(30*time.Second)
	for _, action := range this.actions {
		if err = action.Action(this.Context); err != nil {
			klog.Errorf("action: %v", err)
			break
		}
	}

	return err
}
```
