### ISSUE TITLE
快去看看，你们的官网挂掉了

### ISSUE THREAD

**Issue by jefferyjob** [beego/beego#4821]
1、官网时常挂掉
2、不刮掉的时候也很慢

**Comment by jianzhiyao** [comment]
访问最新的国内官网吧 [link](http://beego.vip)

**Comment by jincheng9** [comment]
@jefferyjob  the website has changed to [beego.vip](https://beego.vip/)

**Comment by EliotCao** [comment]
beego.vip website not accessible
