### ISSUE TITLE
BUG：In-process monitoring reports an error when obtaining task status, which makes it unusable，The error is shown in the figure below

### ISSUE THREAD

**Issue by Adam-Qiang** [beego/beego#4825]
My English is not very good, please forgive me

1、My version number：2.0
2、My problems：In-process monitoring reports an error when obtaining task status, which makes it unusable，The error is shown in the figure below
![问题](https://user-images.githubusercontent.com/29243617/144064801-50d2647f-e378-4f5b-9251-cc4797208b7a.jpg)
3、Solution
Find the problem by consulting the source code：github.com/beego/beego/v2@v2.0.1/task/task.go:160
The solution is shown in the figure below
![解决](https://user-images.githubusercontent.com/29243617/144066258-a9e42e64-2128-4f3c-96e0-5dc8443d3a55.jpg)
Can use errCnt in the task structure to determine whether there is an error

In addition, I also found the root cause of this problem, as shown in the figure below
![根源](https://user-images.githubusercontent.com/29243617/144067402-a15838f8-54e0-4d1d-87f8-cfbf15bb4d92.png)

**Comment by flycash** [comment]
we have already fix this issue:
#4391 
https://github.com/beego/beego/pull/4391/files#diff-7ef57059a85f7616a1ced12b2ff10d68b0e019da63e7c6a492694dbee66b12b1R160-R162

**Comment by EBDhong** [comment]
I have the same issue, the source code of task.go is the old one which is not updated.

![image](https://user-images.githubusercontent.com/79683782/146149783-3963b563-3e07-484b-a744-488eba750d05.png)

**Comment by Adam-Qiang** [comment]
> 我有同样的问题，task.go的源代码是旧的，没有更新。
> 
> ![image](https://user-images.githubusercontent.com/79683782/146149783-3963b563-3e07-484b-a744-488eba750d05.png)

Yes, I haven't found the updated version either. I have this problem under the latest version. Maybe the patch hasn't been released yet

**Comment by Adam-Qiang** [comment]
> I have the same issue, the source code of task.go is the old one which is not updated.
> 
> ![image](https://user-images.githubusercontent.com/79683782/146149783-3963b563-3e07-484b-a744-488eba750d05.png)

Yes, I haven't found the updated version either. I have this problem under the latest version. Maybe the patch hasn't been released yet

**Comment by xionghao666** [comment]
> we have already fix this issue: #4391 https://github.com/beego/beego/pull/4391/files#diff-7ef57059a85f7616a1ced12b2ff10d68b0e019da63e7c6a492694dbee66b12b1R160-R162

I synchronized the modification records to the local source code, and other problems were exposed
![beego_error](https://user-images.githubusercontent.com/27722952/146298523-a237600d-5ee7-4ce8-804d-cf7efc319926.png)

**Comment by Adam-Qiang** [comment]
> > we have already fix this issue: #4391 https://github.com/beego/beego/pull/4391/files#diff-7ef57059a85f7616a1ced12b2ff10d68b0e019da63e7c6a492694dbee66b12b1R160-R162
> 
> I synchronized the modification records to the local source code, and other problems were exposed ![beego_error](https://user-images.githubusercontent.com/27722952/146298523-a237600d-5ee7-4ce8-804d-cf7efc319926.png)

I found it. I need to update the version to v2.0.1-beta.1.  At present, my version is updated to v2.0.1
