### ISSUE TITLE
I want to add a function to support changing log file permissions 希望能添加支持修改log文件权限的函数

### ISSUE THREAD

**Issue by weiliemgodosun** [beego/beego#4826]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
BeeGo 2.0.1

2. What operating system and processor architecture are you using (`go env`)?
Linux  
 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

In file  core\logs\file.go 
the function:
func newFileWriter() Logger {
	w := &fileLogWriter{
		Daily:      true,
		MaxDays:    7,
		Hourly:     false,
		MaxHours:   168,
		Rotate:     true,
		RotatePerm: "0440",
		Level:      LevelTrace,
		Perm:       "0660",
		MaxLines:   10000000,
		MaxFiles:   999,
		MaxSize:    1 << 28,
	}
	w.formatter = w
	return w
}

I want to change Perm/RotatPerm using "0775" or other permissions, I don't have a function function to set  

I want to add a function to support changing log file permissions

希望能添加支持修改log文件权限的函数

**Comment by flycash** [comment]
you can call `Init` function to change it:
```go
func (w *fileLogWriter) Init(config string) error {
	err := json.Unmarshal([]byte(config), w)
	if err != nil {
		return err
	}
	if w.Filename == "" {
		return errors.New("jsonconfig must have filename")
	}
	w.suffix = filepath.Ext(w.Filename)
	w.fileNameOnly = strings.TrimSuffix(w.Filename, w.suffix)
	if w.suffix == "" {
		w.suffix = ".log"
	}

	if len(w.Formatter) > 0 {
		fmtr, ok := GetFormatter(w.Formatter)
		if !ok {
			return fmt.Errorf("the formatter with name: %s not found", w.Formatter)
		}
		w.logFormatter = fmtr
	}
	err = w.startLogger()
	return err
}
```
