### ISSUE TITLE
Are there any examples about XSRF above the version 1.12.3

### ISSUE THREAD

**Issue by Terence-Cheng** [beego/beego#4828]
1. What version of Go and beego are you using (`bee version`)?

    1.12.3

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?

    When I sent a post request, then got the error.
```
				<div id="content">
					<br>The page you have requested is forbidden.<br>Perhaps you are here because:<br><br><ul><br>'_xsrf' argument missing from POST</ul>
					<a href="/" title="Home" class="button">Go Home</a><br />

					<br>Powered by beego 1.12.3
				</div>

```

4. What did you expect to see?

    Solve the xsrf problem.

    Below are the original docs.

```
这是因为，在 2.x 的时候，我们给存储 XSRF token的 cookie 加上了 secure, http-only.
两个设置，所以只能通过 HTTPS 协议运作。

与此同时，你也无法通过 JS 获取到 XSRF token。
```

     

So how to get `XSRF` token via JS, are there any examples?

**Comment by flycash** [comment]
I think if you wish to access `XSRF` token via JS, you can copy the `XSRF` code and do not use `secure, http-only` flags. I suggest that don't do that because it indicates that attacker can access the `XSRF` token via JS too.

**Comment by Terence-Cheng** [comment]
If I want to use `secure, http-only` flags. How can I do? Any examples?

**Comment by flycash** [comment]
That's simple, you only need to use `HTTPS` protocol.

**Comment by Terence-Cheng** [comment]
So, Do you mean in `HTTPS` protocol, is there no need to get `XSRF token` via JS?

I tried  in `HTTPS` protocol, I also got the same error.

**Comment by flycash** [comment]
We use `http-only` option, so you can not read XSRF token via JS.

**Comment by flycash** [comment]
> If I want to use `secure, http-only` flags. How can I do? Any examples?
In Beego 2.x, we already add these two flags

**Comment by flycash** [comment]
https://github.com/beego/beego-example/tree/master/httpserver/xsrf
