### ISSUE TITLE
Typo in i18n.go file

### ISSUE THREAD

**Issue by pstuashiqcse** [beego/beego#4837]
There is a typo issue in i18n.go file.

**Lang en _alread_ exist** should be **Lang en _already_ exist**

![typo issue in beego](https://user-images.githubusercontent.com/16353063/147321799-e7b608e5-3059-4c05-83c0-8b8225a48c87.png)

**Comment by Vivek-Prajapatii** [comment]
Hii @pstuashiqcse can you assign me this one?
