### ISSUE TITLE
How to achieve this scenario using Beego/JS?

### ISSUE THREAD

**Issue by curiosport** [beego/beego#4848]
I want to do the following:
1) Insert a custom field in the response header. It must have the flags "HTTPOnly" and "Secure".
2) The client cannot read the field using javascript.
3) The client makes a Post request to the beego server but the browser must send the custom field I inserted at the beginning. This is where I don't know whether to use fetch, XMLHttpRequest or what other javascript instruction.

And I want to clarify that I am not sure if this scenario is possible either.

For the moment I have solved it this way:

```
#Response Server
c.Ctx.Output.Header("Set-Cookie","token=xxxxxxxx;SameSite=Strict;Secure;HTTPOnly")
```

```
#Client request

await request("sampleCredentiasl:1hv", "/sampleURL").then(async reply => {
  //blabla
});


function request(toServer, url){
  return new Promise(function(resolve) {
    var xhr = new XMLHttpRequest();
		xhr.open("POST", url, true);
    xhr.onload = function() {
      resolve(this.responseText);
    };
    xhr.send(toServer);
  });
}
```

```
#Receive request
credentials := c.Ctx.GetCookie("token")
```

This meets all my criteria but not in the case of custom fields.

I would really appreciate your help.

**Comment by flycash** [comment]
Or use the `SetSecureCookie` on type `Context`
