### ISSUE TITLE
unable to use the session

### ISSUE THREAD

**Issue by John-1992** [beego/beego#4849]
I was unable to use the session and the following error occurred：Handler crashed with error runtime error: invalid memory add
ress or nil pointer dereference
![image](https://user-images.githubusercontent.com/40137165/150101254-34461827-7981-4be0-9d84-d39f1bf29e2e.png)
![image](https://user-images.githubusercontent.com/40137165/150077917-897a7e4a-f6ab-43a4-82d0-3ae690379c69.png)

**Comment by goldsky** [comment]
Why not try to extend your function from beego.Controller, then use its (*Controller).GetSession("uname") ?
Example: `controllers/user.go`
```go
package controllers

import "strings"

type UserController struct {
	// this already extends beego.Controller, usually contains helper functions
	// for its extended controllers
	MainController 
}

func (c *UserController) Filter() {
	uname := c.GetSession("uname")
	if uname != nil && uname != "johnnie" && !strings.HasPrefix(c.Ctx.Request.RequestURI, "/index") {
		// logic here
	}
}

```

**Comment by guhan121** [comment]
must set like this. in your `app.conf`
```
SessionOn = true
SessionName = sessionId
SessionProvider = redis
SessionConfigPath = 127.0.0.1:6380
```
