### ISSUE TITLE
Some empty keys in the redis-0 library

### ISSUE THREAD

**Issue by DHmc133** [beego/beego#4851]
We found that the harbor-core service will continue to generate some empty keys in the redis-0 library. And if other code calls the harbor interface, it will also generate a lot of  empty keys. What is the purpose of these empty keys?
![image](https://user-images.githubusercontent.com/98294423/150891344-0b73cc31-d79f-49b2-b8ce-a6e8a21963fe.png)

The empty value of some keys indeed from beego mechanism
Is it not necessary to store these empty keys in redis?
Maybe can add judgment to only store non-empty keys in Redis

**Comment by flycash** [comment]
I don't know how do you use the Beego. Can you provide the reproduce code?

**Comment by guhan121** [comment]
@DHmc133 session id ?
