### ISSUE TITLE
2.0.2 注解路由失效

### ISSUE THREAD

**Issue by bbs-v2ex** [beego/beego#4876]
bee update 升级到 2.0.2  
再去写注解代码时，并不会执行创建router路由文件

**Comment by xuing** [comment]
同样问题

**Comment by xuing** [comment]
https://github.com/beego/beego/pull/4486
https://github.com/beego/bee/pull/762
应该是这个原因
最离谱的是，这个pr还没合到master上。然后这边的hook就已经删了。

**Comment by xuing** [comment]
嗯 实测你应该用dev分支的bee。执行bee generate routers 
hhhh

**Comment by bbs-v2ex** [comment]
就是这个问题，谢谢

**Comment by xuing** [comment]
emmm，我觉得没必要close。让维护者们看到更好。

**Comment by xuing** [comment]
> 在追加一个问题，一直无法生成文档是什么鬼 `$ ../bee/bee.exe run -gendoc=true
> 
> | ___ | |_/ / ___ ___ | ___ \ / _ \ / _ | |_/ /| __/| **/ _**_/ ___| ___| v2.0.2 2022/03/07 20:53:23 WARN ▶ 0001 Running application outside of GOPATH 2022/03/07 20:53:23 INFO ▶ 0002 Using 'ark' as 'appname' 2022/03/07 20:53:23 INFO ▶ 0003 Initializing watcher... 2022/03/07 20:53:23 INFO ▶ 0004 Generating the docs... 2022/03/07 20:53:24 ERROR ▶ 0005 Failed to generate the docs. `

`bee generate docs `用这个试试呢

**Comment by CrazyJexon** [comment]
现在还没修复吗？bee release还是不行吗？我试了dev也许不行，有点坑呀

**Comment by xuing** [comment]
> 现在还没修复吗？bee release还是不行吗？我试了dev也许不行，有点坑呀

可以用了呀。执行bee generate routers 就行
