### ISSUE TITLE
Column cannot be found when update

### ISSUE THREAD

**Issue by minchenzz** [beego/beego#4885]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.6.5
beego 2.0.2

2. What operating system and processor architecture are you using (`go env`)?
windows nocgo

3. What did you do?

mysql update

`_, err = o.Update(u, "LastSeen")`

err : Error 1054: Unknown column '' in 'field list'

sql : [UPDATE `user` SET `` = ? WHERE `id` = ?] - `1`

The column in struct  tag is not set.

---

`_, err = o.QueryTable(u).Filter("Id", u.Id).Update(orm.Params{"LastSeen": u.LastSeen})`

The column in struct tag is not set but it successed

why？

struct
LastSeen        time.Time  `orm:"type(datetime);auto_now_add"`

**Comment by flycash** [comment]
Can you provide a demo to reproduce this issue?
