### ISSUE TITLE
配置文件大小写不敏感导致GetSection函数失败(Configuration file case insensitive causes GetSection function to fail)

### ISSUE THREAD

**Issue by Go-Go-Farther** [beego/beego#4893]
当我在配置文件中配置名称有大写字母的section，然后我调用GetSection函数，参数还是使用有大写的section名字，那么获取section就会失败。可能其他的配置文件获取函数也有同样的问题！
section的名字需要在GetSection函数内部转换为小写，来保证配置文件中名称和key大小写不敏感的语义。

version : v2.0.2
OS: windows 10 x86_64
When I configure a section name with uppercase letters in the configuration file, then I call GetSection, the argument with uppercase letters does not get the section contents. Maybe other Get function of config has same problem!
The name of the section needs to be used after the internal conversion of GetSection to ensure that the configuration is case-insensitive.

**Comment by flycash** [comment]
This is by design problem. Originally, the configure in Beego web is not case-sensitive.

**Comment by flycash** [comment]
I am afraid that I can do nothing with this.

**Comment by Go-Go-Farther** [comment]
Here's what I mean.
The configuration file has such a section（app.conf）
```
[MySection]
name1=val1
name2=val2
```
Then calling the following code will fail, get nothing, and return a nonexistent error.
```
web.AppConfig.GetSection("MySection")
```
I think calling this function should not fail, it should do case conversion. So it looks like this
```
// GetSection returns map for the given section
func (c *IniConfigContainer) GetSection(section string) (map[string]string, error) {
	insensitive := strings.ToLower(section)
	if v, ok := c.data[insensitive]; ok {
		return v, nil
	}
	return nil, errors.New("not exist section")
}
```
Since it is case insensitive, it should not be perceived by the user.

**Comment by flycash** [comment]
I understand what you mean, but actually I think this is by-design problem. I don't want to change this behaviour.
In my opinion, all the configure should be case sensitive. 
I think you can use other file as configure file, like `yaml` or `json`. These should be case sensitive.
