### ISSUE TITLE
EnableAdmin  with EnableHTTPS conflict . its a  bug？

### ISSUE THREAD

**Issue by stevenyangecho** [beego/beego#4907]
if the EnableAdmin=true will run  code 
[https://github.com/beego/beego/blob/6255e55fed855675fd73e05ca7c0fd0465e2757c/server/web/admin.go#L103](url)
`		// copy config to avoid conflict
		adminCfg := *BConfig
		beeAdminApp = &adminApp{
			HttpServer: NewHttpServerWithCfg(&adminCfg),
		}`
just copy  BConfig
and then admin module  and the master code both will  run  [https://github.com/beego/beego/blob/047e4a6750f761de7b1b9d612dee5b8cbcac2306/server/web/server.go#L80](url)
so this function will run twice

the problem is [https://github.com/beego/beego/blob/047e4a6750f761de7b1b9d612dee5b8cbcac2306/server/web/server.go#L197](url)
admin module and the master code will use same conf，so `app.Cfg.Listen.HTTPSPort` with the same ,and start twice!

will always error with  ` [C] [server.go:229]  ListenAndServeTLS:  listen tcp :555: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

**Comment by flycash** [comment]
which version did you use? please follow the issue template

**Comment by stevenyangecho** [comment]
version is 2.02
I think tis a logic error,can try with both EnableAdmin =true and EnableHTTPS =true

**Comment by flycash** [comment]
can you try v2.0.4 I think I fixed this one

**Comment by guanginuestc** [comment]
> can you try v2.0.4 I think I fixed this one

EnableAdmin is still conflict with EnableMutualHTTPS

**Comment by flycash** [comment]
Let me try this

**Comment by flycash** [comment]
I will release a new version in this month with other bug fix
