### ISSUE TITLE
bee can not found

### ISSUE THREAD

**Issue by muyline** [beego/beego#4909]
1. What version of Go and beego are you using (`bee version`)?
go: go1.18.1

2. What operating system and processor architecture are you using (`go env`)?
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

3. What did you do?
when i use go get -u github.com/beego/bee/v2
i can not fond the bee in the $GOPATH/bin

4. What did you expect to see?

5. What did you see instead?

**Comment by flycash** [comment]
when you run `go get -u github.com/beego/bee/v2`, did you see any error?
