### ISSUE TITLE
log SetFormatter Bug

### ISSUE THREAD

**Issue by ytd7777** [beego/beego#4912]
core\logs\multifile.go

func (f *multiFileLogWriter) SetFormatter(fmt LogFormatter) {
f.fullLogWriter.SetFormatter(f)
}

fmt args not use 
multiFile SetFormatter not working 
Super big bug pp

**Comment by ytd7777** [comment]
Please be serious

**Comment by flycash** [comment]
which version did you use?

**Comment by flycash** [comment]
I think this is same as the #4911

**Comment by ytd7777** [comment]
Not the same

**Comment by ytd7777** [comment]
f.fullLogWriter.SetFormatter(f)
It should be
f.fullLogWriter.SetFormatter(fmt)

**Comment by ytd7777** [comment]
version beego 2.0.2

**Comment by Jiaoyuanli** [comment]
version beego 2.0.1 自己添加个，没有默认BUG
f := &logs.PatternLogFormatter{
				Pattern:    "%w - %T # [%f:%n] %m\r\n",
				WhenFormat: "2006-01-02 15:04:05.123",
			}
 logs.RegisterFormatter("pattern", f)
