### ISSUE TITLE
原生查询占位符问题

### ISSUE THREAD

**Issue by 313964535** [beego/beego#4917]
ids := []int{1, 2, 3}
p.Raw("SELECT name FROM user WHERE id IN (?, ?, ?)", ids)

这种情况的话,这个占位符的个数 必需要和切片的个数一致? , 那就没办法动态查询了啊,每次都要拼接下字符串么

**Comment by Jiaoyuanli** [comment]
ids := strings.Split("1,2,3,4", ",")，sql  str := "?," idStr:= strings.Repeat(str, cnt) idStr:= strings.TrimRight(idStr, ",")

**Comment by flycash** [comment]
you can do it by yourself. It's very easy.
