### ISSUE TITLE
If the log file is not in the current directory, the creation fails

### ISSUE THREAD

**Issue by Go-Go-Farther** [beego/beego#4922]
The code that outputs the log to the file specifies the filename property of the log,
```
logs.SetLogger(logs.AdapterFile, `{"filename":"log/AicDbAccess.log","level":6,"maxlines":100000,"maxsize":0,"daily":true,"maxdays":14,"perm":"0664"}`)
```
Filename contains a path and a directory needs to be created. The log creation function is as follows.（code file location: /core/logs/file.go）
```
func (w *fileLogWriter) createLogFile() (*os.File, error) {
	// Open the log file
	perm, err := strconv.ParseInt(w.Perm, 8, 64)
	if err != nil {
		return nil, err
	}

	filepath := path.Dir(w.Filename)
	os.MkdirAll(filepath, os.FileMode(perm))

	fd, err := os.OpenFile(w.Filename, os.O_WRONLY|os.O_APPEND|os.O_CREATE, os.FileMode(perm))
	if err == nil {
		// Make sure file perm is user set perm cause of `os.OpenFile` will obey umask
		os.Chmod(w.Filename, os.FileMode(perm))
	}
	return fd, err
}
```
File permissions are also used to create directories.
```
os.MkdirAll(filepath, os.FileMode(perm))
```
The directory cannot be executed, and the log file fails to be created. Therefore, when calling MkdirAll, should add the execution permission to the directory, and do not use the file permissions set by the user.

_Originally posted by @Go-Go-Farther in https://github.com/beego/beego/issues/4898#issuecomment-1094183444_

**Comment by flycash** [comment]
I think now Beego support both:
```go
type fileLogWriter struct {
	// Permissions for log file
	Perm string `json:"perm"`
	// Permissions for directory if it is specified in FileName
	DirPerm string `json:"dirperm"`
}
```
so you can specify the `DirPerm` to create the file
