### ISSUE TITLE
[ORM BUG] create table failed when datasource is postgres

### ISSUE THREAD

**Issue by shanghs** [beego/beego#4932]
1. What version of Go and beego are you using (`bee version`)?
**go version go1.17.3 darwin/arm64
bee version v2.0.2**

2. What operating system and processor architecture are you using (`go env`)?
**GOOS="darwin"
GOARCH="arm64"**

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
**create table with orm on postgres failed, when there has comment on orm tags**

If this is ORM issue, please provide the DB schemas.
just a sample struct like this 
```golang
type Test struct {
	Id int64 `orm:"auto;description(record id)"`
}

func init() {
	orm.RegisterModel(new(Test))
}
```

4. What did you expect to see?
create table success, and we can find it in our database

5. What did you see instead?
when we startup our project, use orm.RunSyncdb to create table, there will have an error occur, err is `pq: syntax error at or near "COMMENT"`

this issue is occur only PostgreSQL. In https://github.com/beego/beego/blob/develop/client/orm/models.go line 478
```golang
if fi.description != "" && al.Driver != DRSqlite {
	column += " " + fmt.Sprintf("COMMENT '%s'", fi.description)
}
```
so the generate SQL will like this
```sql 
-- --------------------------------------------------
--  Table Structure for `train/internal/model.Test`
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "test" (
    "id" serial NOT NULL PRIMARY KEY COMMENT 'record id'
);
```
but in postgres the correct sql like this
```sql 
-- --------------------------------------------------
--  Table Structure for `train/internal/model.Test`
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "test" (
    "id" serial NOT NULL PRIMARY KEY
);
COMMENT ON COLUMN test.id is 'record id';
```

**Comment by flycash** [comment]
> [WeOpen Star]I would like to help Hi @flycash, I would like to work on this issue. If my understanding is correct, `COMMENT` should be used out of `CREATE TABLE` sentence when using pgsql. I want to use array to store indexes of columns which have description, and then iter the array and append comments to the `CREATE TABLE` sentence, what do you think about it?

good idea, you can try it.
