### ISSUE TITLE
基于最新版go1.18安装beego后发现未在磁盘任何地方找到bee命令

### ISSUE THREAD

**Issue by toocf** [beego/beego#4934]
**English Only**. 英文不过关，只能使用中文！

环境： Go1.18  系统windows 10

配置：系统环境只配置GOENV，GOENV内配置了GOPATH、GOCACHE、GOPROXY。

步骤：
   1、go get -u github.com/beego/beego/v2
   2、go get -u github.com/beego/bee/v2
   3、去GOPATH目录中bin目录未发现bee可执行文件，磁盘搜索未找到bee相关命令。

疑问：
    应该是未生成bee可执行文件，多台win10系统都发现没有。

    后来尝试系统配置将GOENV更换成GOPATH配置一下，结果发现仍然找不到bee命令。

（个人对系统干净有洁癖，希望控制所有磁盘产生的文件，故配置了GOENV。并在其中将下载go包和缓存等都统一放在指定位置）

**Comment by Jiaoyuanli** [comment]
安装 go.17 命令好像不是 go get了,go install 试试，bee是源文件自己编译后复制到bin下

**Comment by 77777qazxsw7** [comment]
> 安装 go.17 命令好像不是 go get了,go install 试试，bee是源文件自己编译后复制到bin下

被这个问题卡了好久，感谢大佬！

**Comment by toocf** [comment]
> 安装 go.17 命令好像不是 go get了,go install 试试，bee是源文件自己编译后复制到bin下

go get 是拉取远程包的命令，还是继续使用的
go install 是对项目进行编译并自动拉取所需包并生成 可执行文件的。

还好，你说的编译一下，生成可执行命令了，感谢！

解决步骤：
    1、go get -u github.com/beego/bee/v2
    2、cd 到这个bee/v2版本中
    3、go mod tidy 整理一下
    4、go install
此时在 GOPATH目录bin文件夹下生成了bee.exe 。
测试 ./bee.exe new hello 已正常创建项目，自己将bin目录加入到全局即可。
