### ISSUE TITLE
httplib的retry报错 http: ContentLength=252 with Body length 0

### ISSUE THREAD

**Issue by zhangmengke** [beego/beego#4936]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
latest

2. What operating system and processor architecture are you using (`go env`)?
go1.15.2

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

func (b *BeegoHTTPRequest) sendRequest(client *http.Client) (resp *http.Response, err error) {
	// retries default value is 0, it will run once.
	// retries equal to -1, it will run forever until success
	// retries is setted, it will retries fixed times.
	// Sleeps for a 400ms between calls to reduce spam
	for i := 0; b.setting.Retries == -1 || i <= b.setting.Retries; i++ {
		resp, err = client.Do(b.req)
		if err == nil {
			return
		}
		time.Sleep(b.setting.RetryDelay)
	}
	return nil, berror.Wrap(err, SendRequestFailed, "sending request fail")
}

因为Do关闭了req.closeBody()，所以retry的时候  报错了

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

5. What did you see instead?

**Comment by Wlhet** [comment]
you can copy the req body before to do request .

like:
	if r.req.Body != nil && r.retryTimes != 0 {
		copyBody, _ := ioutil.ReadAll(r.req.Body)
		for i := 0; r.retryTimes == -1 || i <= r.retryTimes; i++ {
			r.req.Body = io.NopCloser(bytes.NewReader(copyBody))
			resp, err = client.Do(r.req)
			if err == nil {
				break
			}
			time.Sleep(r.retryDelay)
		}
	} else {
		resp, err = client.Do(r.req)
	}
	return resp, err

**Comment by jptiancai** [comment]
thanks @Wlhet , I create PR. [https://github.com/beego/beego/pull/5544](url)
