### ISSUE TITLE
Time problem in return json data（关于返回json数据中的time显示问题）

### ISSUE THREAD

**Issue by a285277906** [beego/beego#4941]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.2

2. What operating system and processor architecture are you using (`go env`)?
GoVersion : go1.18.1
GOOS      : windows
GOARCH    : amd64

When the interface returns the JSON data（简单的说在接口返回数据体json的时候）：
res := utils.NewTime()
c.Data["json"] = res
_ = c.ServeJSON()

Data return format（数据返回格式）：
{
  msg: "Success",
  code: 200,
  data: "2022-05-14T19:01:58.1289354+08:00"
}

And I have customized the time type and override【UnmarshalJSON】method（而我已经自定义time重写了time的UnmarshalJSON）:

func (t *Time) MarshalJSON() ([]byte, error) {
	if t.IsZero() {
		return []byte("\"\""), nil
	}
	stamp := fmt.Sprintf("\"%s\"", t.Format("2006-01-02 15:04:05"))
	return []byte(stamp), nil
}

And I used json-itertor when testing（我在测试的时候使用了第三方库json-iterator来序列化json是正常的显示）：

{
  msg: "Success",
  code: 200,
  data: "2022-05-14 19:02:55"
}

 is it my problem？（以上，请问是我个人的问题么，还是需要beego这块内容做点什么？）

Sorry, english is not good, please forgive me...

**Comment by flycash** [comment]
Sorry, I can not reproduce this problem, and please provide a demo.

In theory, Beego just call json.Marshal function.
