### ISSUE TITLE
Orm: support opentelemetry filter

### ISSUE THREAD

**Issue by flycash** [beego/beego#4944]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Now, many companies prefer to use opentelemetry as the tracing framework. So we need to think about support openlemetry in Beego.

You can take these as reference:
- [ORM opentracing filter](https://github.com/beego/beego/tree/develop/client/orm/filter/opentracing)
- [httplib opentelemetry filter](https://github.com/beego/beego/tree/develop/client/httplib/filter/opentelemetry)

**Comment by Dokiys** [comment]
[WeOpen Star]I would like to try this.
