### ISSUE TITLE
Web: support opentelemetry filter

### ISSUE THREAD

**Issue by flycash** [beego/beego#4945]
**English Only**. Please use English because others could join the discussion if they got similar issue!

**English Only**. Please use English because others could join the discussion if they got similar issue!

Now, many companies prefer to use opentelemetry as the tracing framework. So we need to think about support openlemetry in Beego.

You can take these as reference:
- [Web opentracing filter](https://github.com/beego/beego/tree/develop/server/web/filter/opentracing)
- [httplib opentelemetry filter](https://github.com/beego/beego/tree/develop/client/httplib/filter/opentelemetry)

**Comment by selectbook** [comment]
[WeOpen Star]I would like to help

**Comment by pellared** [comment]
FYI https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4059
