### ISSUE TITLE
Refine Comments

### ISSUE THREAD

**Issue by flycash** [beego/beego#4948]
This is a really simple but big task.
As we all known, the Go comments must follow the rule that the comments should start with the type name, function name, or field name. For example:
```go
// User is a demo structure
type User struct {
}
```
Unfortunately, most of comments in Beego do not follow the rule, so you can help us to correct them.

Any improvement is welcome!

And this is a big task, so anyone can join this task.

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by flycash** [comment]
sure, thank you
