### ISSUE TITLE
Refactor dbBase: Using bytebufferpool to build the SQL

### ISSUE THREAD

**Issue by flycash** [beego/beego#4949]
[bytebufferpool](https://github.com/valyala/bytebufferpool)

Now, type `dbBase` in `orm` package utilize the `fmt.Sprint` to build SQL, but it's not a elegant way because the performance is not good.

In general, we prefer to use the buffer to reduce the memory allocation.

So you can check the functions in `dbBase` and try best to use bytebufferpool to refine them.

This is a big task, you need to think about how to write unit tests. The possible way is extracting the SQL building part to be a new function, and use bytebufferpool, and then test this new function.

Besides, you can split this task into several merge requests. One function one merge request is acceptable.

**Comment by flycash** [comment]
I hope you guys can learn how the Beego ORM construct the SQL. It's not very elegant, but now it's very hard for us to refactor ORM completely 😢

**Comment by chaggle** [comment]
[WeOpen Star]I would like to try my best to solve this.

**Comment by chaggle** [comment]
the fmt.Sprintf function contain many subfunction, so I need more time to understand them, and overwrite them from go package to the beego  package orm as orm_sprintf.go file.
