### ISSUE TITLE
Refactor ORM: Rename _modelCache

### ISSUE THREAD

**Issue by flycash** [beego/beego#4952]
In ORM package, there are:
```go
var modelCache = NewModelCacheHandler()

// model info collection
type _modelCache struct {
	sync.RWMutex    // only used outsite for bootStrap
	orders          []string
	cache           map[string]*modelInfo
	cacheByFullName map[string]*modelInfo
	done            bool
}
```
But the name `_modelCache` is not elegant. 

So we can rename it to be `modelCache` and the existing variable `modelCache` can be renamed as `defaultModelCache`

**Comment by greenhandatsjtu** [comment]
[WeOpen Star]I would like to help. 
This seems to be an easy task, I'll try to make a PR tomorrow.
