### ISSUE TITLE
Make commands and Docker compose for ORM unit tests

### ISSUE THREAD

**Issue by flycash** [beego/beego#4955]
In theory, we should not rely on third party when we run unit tests. However, the Beego ORM module's unit tests still rely on MySQL, Postgress, Tidb.
It's very hard for developers to run ORM unit tests.
So I propose that we provide a docker-compose file to setup the unit test environment. But now we only focus on ORM module. 
The docker compose should setup these DB:
- MySQL 5.7
- MySQL 8.0+
- Tidb
- Postgress

After that, we still need to provide some helpful make commands:
- make test_orm mysql5 
- make test_orm mysql8
- make test_orm postgress
- make test_orm tidb  
- make test_orm all

`make test_orm all` will run all other `test_orm` commands.

For example, the `make test_orm mysql5` will run the command
```shell
docker compose up 
export ORM_DRIVER=mysql
export ORM_SOURCE="the DSN of docker compose mysql5"
go test -v github.com/beego/beego/v2/client/orm
docker compose down
```
Similarly, for tidb:
```shell
docker compose up 
export ORM_DRIVER=tidb
export ORM_SOURCE='the DSN of docker compose tidb'
go test -v github.com/beego/beego/v2/client/orm
docker compose down
```

> Sometimes I may think about using the Bee command to help to setup the environment, but finally I realised that most of the developers are more familiar with make commands

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help

**Comment by mangoGoForward** [comment]
Hi @flycash Which volumes we should mount to container, like mysql 5.7, just mkdir a path in root to mount?

**Comment by mangoGoForward** [comment]
> I think we don't need to mount any volumes. Once we want to run the test, we only start the docker compose. For example:
> 
> ```
> docker compose up -d 
> go run test ./...
> docker compose down
> ```

@flycash Thanks. I found a [tidb-docker-compose](https://github.com/pingcap/tidb-docker-compose/blob/master/docker-compose.yml), they mount `config`, `data` and `logs` to container, Do you mean those volumes doesn't need to mount?
