### ISSUE TITLE
Make log tracable

### ISSUE THREAD

**Issue by jianzhiyao** [beego/beego#4956]
Log is very important in product enviroment.

But Beego does not provide tool like trace_id to indetify log in one request.

We hope user can use context to combine logs in a request.

Code Example:
```
log.WithCtx(ctx).Info("123")
log.Info(ctx,"123")
```

**Comment by flycash** [comment]
I think the API:
```go
log.WithCtx(ctx)
```
looks not good, because it indicates that the ctx was stored in some structure

**Comment by jianzhiyao** [comment]
> I think the API:
> 
> ```go
> log.WithCtx(ctx)
> ```
> 
> looks not good, because it indicates that the ctx was stored in some structure

Yes, ``log.Info("123")`` is more acceptable.

**Comment by deepto98** [comment]
Can I pick this up, can someone give a little insight into the change required to be made?

**Comment by flycash** [comment]
I prefer let the users to do this. Beego don't need to support this. Let me close this
