### ISSUE TITLE
Function leafInfo.match()  use path.join() to deal with `wildcardValues`, which may lead to cross directory risk.  

### ISSUE THREAD

**Issue by runner361** [beego/beego#4961]
Function leafInfo.match()  use path.join() to deal with `wildcardValues`, which may lead to cross directory risk.  

- **poc1: route end with `*.*` can use `../` to cross directory and set evil  value for `:path` .**
https://github.com/beego/beego/blob/64cf44d725c8cc35d782327d333df9cbeb1bf2dd/server/web/tree.go#L414
https://github.com/beego/beego/blob/64cf44d725c8cc35d782327d333df9cbeb1bf2dd/server/web/tree.go#L431
For route `/book1/:name/fixPath1/*.*` , urls below  can match, and  set `:path=evil` 
 `/book1/name1/fixPath1/mybook/../evil.txt` =>`:name=name1`
 `/book1/name1/fixPath1/mybook/../././evil.txt` =>`:name=name1`
 `/book1/name1/fixPath1/mybook/../././////evil.txt` =>`:name=name1`
`/book1/../fixPath1/mybook/../././////evil.txt` =>`:name=..`
`/book1/./fixPath1/mybook/../././////evil.txt` =>`:name=.`
![image](https://user-images.githubusercontent.com/5164276/170035449-3060b4f1-9f6f-4ec0-a9c1-b1d2777f3d8a.png)

```go
//Test code as below:
web.Router("/book1/:name/fixPath1/*.*", &controllers.BookController{}, "get:SearchByName")
func (b BookController) SearchByName() {
	fmt.Println(":path=" + b.Ctx.Input.Param(":path"))
	fmt.Println(":name=" + b.Ctx.Input.Param(":name"))
	b.Data["json"] = "OK"
	b.ServeJSON()
}
```

- **poc2: regex route can use `../` to cross directory and replace wildcard with evil value** 
https://github.com/beego/beego/blob/64cf44d725c8cc35d782327d333df9cbeb1bf2dd/server/web/tree.go#L445
For regex route `/book2/:type:string/fixPath1/:name`,urls  below can match and value of `:type`  `:name` can be replaced with evil value.
`/book2/type1/fixPath1/name1/../../evilType/evilName`  => `:type=evilType :name=evilName`
`/book2/type1/fixPath1/name1/../../././evilType/evilName` => `:type=evilType :name=evilName`
`/book2/type1/fixPath1/name1/../../././////evilType/evilName`=> `:type=evilType :name=evilName`
![image](https://user-images.githubusercontent.com/5164276/170036370-a1904944-29fa-4e5e-bbe8-a8c3381ad3b3.png)
```go
//Test code as below:
web.Router("/book2/:type:string/fixPath1/:name", &controllers.BookController{}, "get:SearchByType")
func (b BookController) SearchByType() {
	fmt.Println(":name=" + b.Ctx.Input.Param(":name"))
	fmt.Println(":type=" + b.Ctx.Input.Param(":type"))
	b.Data["json"] = "OK"
	b.ServeJSON()
}
```

**Comment by runner361** [comment]
> yes, can you help to fix it?

Ok, I will try. Url need to be normalized before route, and path.join() should be replaced with string.join().

**Comment by flycash** [comment]
> > yes, can you help to fix it?
> 
> Ok, I will try. Url need to be normalized before route, and path.join() should be replaced with strings.join().

But if you use strings.join, you need to handle the case that different platform use different symbol as path separator
