### ISSUE TITLE
InsertOrUpdate always updates "auto_now_add" fields.

### ISSUE THREAD

**Issue by yourmoonlight** [beego/beego#4963]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
[Version: v1.12.3](https://pkg.go.dev/github.com/astaxie/beego@v1.12.3/orm?tab=versions)

2. What operating system and processor architecture are you using (`go env`)?
GOVERSION="go1.17.6"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.
	CreatedAt      time.Time `json:"create_at" orm:"auto_now_add;type(datetime)"`
	UpdatedAt      time.Time `json:"update_at" orm:"auto_now;type(datetime)"`

4. What did you expect to see?
auto_now_add field  should not be updated.

5. What did you see instead?
CreatedAt updated every time

**Comment by flycash** [comment]
Can you help to fix this?

**Comment by yourmoonlight** [comment]
bug still there, this issue should not be closed!

**Comment by yourmoonlight** [comment]
#

> bug still there, this issue should not be closed!

@flycash
