### ISSUE TITLE
mysql bit 类型转换 struct  bool 失败

### ISSUE THREAD

**Issue by yaozuodao** [beego/beego#4965]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.16.11 windows/amd64
beego  V2.0.1

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.
"root:password@tcp(170.168.0.56:3306)/lm?collation=utf8mb4_unicode_ci&loc=Asia%2FShanghai"
4. What did you expect to see?

5. What did you see instead?

**Comment by jianzhiyao** [comment]
Pls provide some code example for debuging

**Comment by yaozuodao** [comment]
![image](https://user-images.githubusercontent.com/13032371/170614139-cd5c6051-e0f8-42ea-92cf-5bde630b354d.png)

**Comment by yaozuodao** [comment]
![image](https://user-images.githubusercontent.com/13032371/170614507-48c00031-9315-4324-a563-088bab0dd09c.png)

**Comment by flycash** [comment]
@jianzhiyao would you like to fix this?
