### ISSUE TITLE
Cache: RandomExpireCache 

### ISSUE THREAD

**Issue by flycash** [beego/beego#4966]
As we known, if there are many keys which has the same expire time, they will be expired at the same time. So the traffic will reach the database and may makes the database crash.
A simple idea to solve this problem is that we help users to add a random offset to the expire time.

For example, when users call:
```go
cache.Put(ctx, "key1", value1, 10 * time.Minute)
```
So we change the expired time to be `10 * time.Minute + offset`. For example, `10 * time.Minute + 20s`
We can use the `Decorator pattern` to design the API:
```go
type RandomExpireCache struct {
    c Cache
}
``` 
This decorator  will be responsible for calculating the `offset` and reset the expire time. And this decorator should allow users to specify the algorithm to calculate the offset.

**Comment by auula** [comment]
I would like to try to solve this task, thank you, please give me work instructions.

> As we known, if there are many keys which has the same expire time, they will be expired at the same time. So the traffic will reach the database and may makes the database crash. A simple idea to solve this problem is that we help users to add a random offset to the expire time.
> 
> For example, when users call:
> 
> ```go
> cache.Put(ctx, "key1", value1, 10 * time.Minute)
> ```
> 
> So we change the expired time to be `10 * time.Minute + offset`. For example, `10 * time.Minute + 20s` We can use the `Decorator pattern` to design the API:
> 
> ```go
> type RandomExpireCache struct {
>     c Cache
> }
> ```
> 
> This decorator will be responsible for calculating the `offset` and reset the expire time. And this decorator should allow users to specify the algorithm to calculate the offset.

hey bro,I would like to try to solve this task, thank you, please give me work instructions.
