### ISSUE TITLE
why beego need require redigo@v2.0.0 and replace redigo to v1.8.8 in go.mod file?

### ISSUE THREAD

**Issue by xuing** [beego/beego#4967]
`github.com/gomodule/redigo v2.0.0` should be a deprecated version.
redigo v1.8.8 is the latest version. 
why beego need require `redigo v2.0.0`  and add `replace github.com/gomodule/redigo => github.com/gomodule/redigo v1.8.8`  in go.mod file.
because of this, when I run `go list -u -m all`, I will encounter `go: github.com/gomodule/redigo@v2.0.0+incompatible: retracted by module author: Old development version Not maintained or published.` error.

-----

github.com/gomodule/redigo v2.0.0 应该是一个被废弃的版本。
直接用v1.8.8就是最新的了。为什么要做`replace github.com/gomodule/redigo => github.com/gomodule/redigo v1.8.8`
这样的操作。
目前的情况会导致依赖beego的项目，在使用 go list -u -m all的时候，会遇到`go: github.com/gomodule/redigo@v2.0.0+incompatible: retracted by module author: Old development version not maintained or published.`的报错。

**Comment by flycash** [comment]
I felt sorry about this because we tried to upgrade to 1.8.8 but failed to to this. You can try this.
