### ISSUE TITLE
beego v2  lost function that generate commentsRouter_xxx.go under routers folder

### ISSUE THREAD

**Issue by maxproc** [beego/beego#4969]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee version 2.0.2
beego version 2.0.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH    : arm64
GOOS      : darwin
GoVersion : go1.17.10

I read source code of beego v2 under beego/beego/v2/server/web/router.go{func (p *ControllerRegister) Include(cList ...ControllerInterface)}, I find that it lost function that generate commentsRouter_xxx.go under routers folder；Not anywhere else

**Comment by xuing** [comment]
It was confusing for me too. use `bee generate routers`
reference:
#4486 
https://github.com/beego/bee/pull/762

**Comment by maxproc** [comment]
> It was confusing for me too. use `bee generate routers`
> reference:
> #4486
> [beego/bee#762](https://github.com/beego/bee/pull/762)

thanks, I have solved it by using `bee generate routers`
