### ISSUE TITLE
orm will report an error when inserting, how to block

### ISSUE THREAD

**Issue by fengshunli** [beego/beego#4977]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/18587688/172761133-562fe960-e5ae-4fda-ae19-a71b230b0ba3.png">

**Comment by flycash** [comment]
Can you try:
```
orm.DebugLog(your_logger)
```

**Comment by fengshunli** [comment]
using the zap log framework, this DebugLog returns that the writer cannot be closed @flycash

**Comment by fengshunli** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/18587688/173367000-f7877178-0085-4a74-916a-8ddd5ceab8b5.png">


zap.Logger cannot force log.logger

**Comment by flycash** [comment]
```go
orm.DebugLog = NewLog(logger)
```
