### ISSUE TITLE
Cache: ReadThroughCache

### ISSUE THREAD

**Issue by flycash** [beego/beego#4985]
Similar to #4966 , we can use the decorator design pattern to implement the `Cache` interface. 

This implementation will apply the `read-through` cache pattern which means that:
- if the key is not present, it will try to read the data from other storage
- put the data into cache 

But this is more complicate than `RandomExpireCache`. We need to think about these two APIs:
```go
	Get(ctx context.Context, key string) (interface{}, error)

	GetMulti(ctx context.Context, keys []string) ([]interface{}, error)
```
For function `GetMulti`, there are two possible solution:
- ignore this function
- check the keys one by one, and if the key is not present, read the data from storage and put data into cache

The `ReadThroughCache` looks like:
```go
type ReadThroughCache {
    Cache
    loadFunc func(ctx context.Context, key string) (val interface{}, err error)
}
```

**Comment by auula** [comment]
> Similar to #4966 , we can use the decorator design pattern to implement the `Cache` interface.
> 
> This implementation will apply the `read-through` cache pattern which means that:
> 
> * if the key is not present, it will try to read the data from other storage
> * put the data into cache
> 
> But this is more complicate than `RandomExpireCache`. We need to think about these two APIs:
> 
> ```go
> 	Get(ctx context.Context, key string) (interface{}, error)
> 
> 	GetMulti(ctx context.Context, keys []string) ([]interface{}, error)
> ```
> 
> For function `GetMulti`, there are two possible solution:
> 
> * ignore this function
> * check the keys one by one, and if the key is not present, read the data from storage and put data into cache
> 
> The `ReadThroughCache` looks like:
> 
> ```go
> type ReadThroughCache {
>     Cache
>     loadFunc func(ctx context.Context, key string) (val interface{}, err error)
> }
> ```

i want to tay this task.

**Comment by ktalg** [comment]
[WeOpen Star]I would like to help.

**Comment by jakezhu9** [comment]
I would like to solve this issue
