### ISSUE TITLE
the var Field of Error is "", in beego/validation/validation.go-- func (v *Validation) apply(chk Validator, obj interface{}) *Result 

### ISSUE THREAD

**Issue by swf2020** [beego/beego#4987]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
github.com/beego/beego v1.12.9

2. What operating system and processor architecture are you using (`go env`)?
windows10

3. What did you do?
_in beego/validation/validation.go_
`
func (v *Validation) apply(chk Validator, obj interface{}) *Result {
	if nil == obj {
		if chk.IsSatisfied(obj) {
			return &Result{Ok: true}
		}
	} else if reflect.TypeOf(obj).Kind() == reflect.Ptr {
		if reflect.ValueOf(obj).IsNil() {
			if chk.IsSatisfied(nil) {
				return &Result{Ok: true}
			}
		} else {
			if chk.IsSatisfied(reflect.ValueOf(obj).Elem().Interface()) {
				return &Result{Ok: true}
			}
		}
	} else if chk.IsSatisfied(obj) {
		return &Result{Ok: true}
	}

	// Add the error to the validation context.
	key := chk.GetKey()
	Name := key
	Field := ""
	Label := ""
	parts := strings.Split(key, ".")
	if len(parts) == 3 {
		Field = parts[0]
		Name = parts[1]
		Label = parts[2]
		if len(Label) == 0 {
			Label = Field
		}
	}

	err := &Error{
		Message:    Label + " " + chk.DefaultMessage(),
		Key:        key,
		Name:       Name,
		Field:      Field,
		Value:      obj,
		Tmpl:       MessageTmpls[Name],
		LimitValue: chk.GetLimitValue(),
	}
	v.setError(err)

	// Also return it in the result.
	return &Result{
		Ok:    false,
		Error: err,
	}
}
`
_in beego/validation/util.go_
`
// Get Match function
// May be get NoMatch function in the future
func getRegFuncs(tag, key string) (vfs []ValidFunc, str string, err error) {
	tag = strings.TrimSpace(tag)
	index := strings.Index(tag, "Match(/")
	if index == -1 {
		str = tag
		return
	}
	end := strings.LastIndex(tag, "/)")
	if end < index {
		err = fmt.Errorf("invalid Match function")
		return
	}
	reg, err := regexp.Compile(tag[index+len("Match(/") : end])
	if err != nil {
		return
	}
	vfs = []ValidFunc{{"Match", []interface{}{reg, key + ".Match"}}}
	str = strings.TrimSpace(tag[:index]) + strings.TrimSpace(tag[end+len("/)"):])
	return
}
`
when my valid string has string **match**, I don't get  var **Field** , because, the function of getRegFuncs don't get xxx.Match.xxx but xxx.Match

4. What did you expect to see?
I hope I can get the Field value of Error when my valid format has errors.

5. What did you see instead?

`func getRegFuncs(tag, key string) (vfs []ValidFunc, str string, err error) {
	tag = strings.TrimSpace(tag)
	index := strings.Index(tag, "Match(/")
	if index == -1 {
		str = tag
		return
	}
	end := strings.LastIndex(tag, "/)")
	if end < index {
		err = fmt.Errorf("invalid Match function")
		return
	}
	reg, err := regexp.Compile(tag[index+len("Match(/") : end])
	if err != nil {
		return
	}
	vfs = []ValidFunc{{"Match", []interface{}{reg, key + ".Match"}}}
	str = strings.TrimSpace(tag[:index]) + strings.TrimSpace(tag[end+len("/)"):])
	return
}
`
instead 

`func getRegFuncs(tag, key label string) (vfs []ValidFunc, str string, err error) {
	tag = strings.TrimSpace(tag)
	index := strings.Index(tag, "Match(/")
	if index == -1 {
		str = tag
		return
	}
	end := strings.LastIndex(tag, "/)")
	if end < index {
		err = fmt.Errorf("invalid Match function")
		return
	}
	reg, err := regexp.Compile(tag[index+len("Match(/") : end])
	if err != nil {
		return
	}
	vfs = []ValidFunc{{"Match", []interface{}{reg, key + ".Match" + "." + label}}}
	str = strings.TrimSpace(tag[:index]) + strings.TrimSpace(tag[end+len("/)"):])
	return
}
`

**Comment by flycash** [comment]
Can you provide a demo to reproduce it? it's really hard to understand your issue

**Comment by swf2020** [comment]
ok, let me show you the case, when you execute the example case as below

`
package main

import (
	"fmt"
	"github.com/beego/beego/validation" // v1.12.9
)

type AA struct {
	ExampleEntity string `json:"example_entity" valid:"Match(/^(one|two)$/)"`
}

func main() {
	aa := AA{
		ExampleEntity: "three",
	}
	valid := validation.Validation{}
	valid.Valid(aa)
	fmt.Println("===============")
	fmt.Printf("%v\n", aa)
	fmt.Printf("valid.Errors:  %v\n", valid.Errors)
	fmt.Printf("valid.Errors[0]:   %v\n", valid.Errors[0])
	// Error show the error
	// type Error struct {
	//	 Message, Key, Name, Field, Tmpl string
	//	 Value                           interface{}
	//	 LimitValue                      interface{}
	// }
	err := valid.Errors[0]
	fmt.Printf("Message: %v\n", err.Message)
	fmt.Printf("Key: %v\n", err.Key)
	fmt.Printf("Name: %v\n", err.Name)
	fmt.Printf("Field: %v\n", err.Field)
	fmt.Printf("Tmpl: %v\n", err.Tmpl)
	fmt.Println("===============")
}
`
And you will get the result as below

`
===============
{three}
valid.Errors:  [ Must match ^(one|two)$]
valid.Errors[0]:    Must match ^(one|two)$
Message:  Must match ^(one|two)$
Key: ExampleEntity.Match
Name: ExampleEntity.Match
Field: 
Tmpl: 
===============
`
Generally，when valid.Errors[n] is not nil, I think all items should have specific value: Field should be "ExampleEntity",  Name should be "Match", Tmpl should be "Must Match %s", Because I need to do some log with Field, but now,  I get nil of Field, nil of Tmpl.
==============================
reason：I find the problem is the function apply in validation.go: 
 
func (v *Validation) apply(chk Validator, obj interface{}) *Result {
...
	// Add the error to the validation context.
	key := chk.GetKey()
	Name := key
	Field := ""
	Label := ""
	parts := strings.Split(key, ".")
	if len(parts) == 3 {        // the len of parts is 2, sometimes. finally, Field, Name, Label can not be assigned value of parts
		Field = parts[0]
		Name = parts[1]
		Label = parts[2]
		if len(Label) == 0 {
			Label = Field
		}
	}
...
}

===============
advice of reslove: the funcation of getRegFuncs in validation/util.go

`
func getRegFuncs(tag, key string) (vfs []ValidFunc, str string, err error) {
	tag = strings.TrimSpace(tag)
	index := strings.Index(tag, "Match(/")
	if index == -1 {
		str = tag
		return
	}
	end := strings.LastIndex(tag, "/)")
	if end < index {
		err = fmt.Errorf("invalid Match function")
		return
	}
	reg, err := regexp.Compile(tag[index+len("Match(/") : end])
	if err != nil {
		return
	}
	vfs = []ValidFunc{{"Match", []interface{}{reg, key + ".Match"}}}  // should append ("." + Label) in the after of (key + ".Match")
	str = strings.TrimSpace(tag[:index]) + strings.TrimSpace(tag[end+len("/)"):])
	return
}
`

**Comment by jianzhiyao** [comment]
@swf2020 pls provide some formatted code, we read your code so hard!
