### ISSUE TITLE
orm.ErrNoRows的判断问题

### ISSUE THREAD

**Issue by hydaizd** [beego/beego#4992]
使用orm时，代码如下：
```go
err = Ormer().Read(a, "name", "namespace_id")
if err != nil {
	// Apps with duplicate names are not allowed to appear under the same namespace
	if err == orm.ErrNoRows {
		id, err = Ormer().Insert(a)
		return
	}
}
```
当查询无记录时，err.Error()的打印结果是"< QuerySeter> no row found"，但判断的时候却是不相等，应该要如何判断才会让他们相等？不想用err.Error() == orm.ErrNoRows.Error()的方式来判断。

**Comment by hydaizd** [comment]
已解决，需要引入github.com/beego/beego/v2/client/orm包，而不是github.com/beego/beego/v2/adapter/orm

**Comment by mei2015** [comment]
close 一下
