### ISSUE TITLE
Why is "xsrf secure" and "xsrf httponly" changed back to not configurable in v1.12.7?

### ISSUE THREAD

**Issue by yangru** [beego/beego#4994]
https://github.com/beego/beego/blob/develop-1.x/controller.go#L683

This line was like this in [v1.12.3](https://github.com/beego/beego/blob/cbbb6bfb088c856d2c3302a5d128ff747041cd33/controller.go#L682) (not configurable),
2 params("xsrf secure" and "xsrf httponly") are [added](https://github.com/beego/beego/blob/8524b624773d54c324ae7d389cbda63df2c706f9/controller.go#L683) in v1.12.4 (configurable), 
however it's [changed back](https://github.com/beego/beego/commit/978b7e4a9dcc4f91f231ee11f39d19e385de75cf#diff-cc5d2cdea66aa1021f86124b6b59590af4179f66c5da18e04c43ae82c0b6bfbdL683) in v1.12.7(not configurable).
Why?

**Comment by jianzhiyao** [comment]
https://github.com/beego/beego/blob/v1.12.10/controller.go#L683
