### ISSUE TITLE
打包命令的改进建议

### ISSUE THREAD

**Issue by jqncc** [beego/beego#4996]
1.在打包时如readme之类的文件是不需要打包进去的, 但bee pack命令没有办法排除文件或文件夹, 只能打好压缩包后解压再删除重新压缩
2.按环境打包太弱, 没法想java maven一样, 通过打包命令指定环境,然后采用不用的环境配置文件

**Comment by mei2015** [comment]
兄弟 你怕是没有完整看 bee 的打包命令吧！
 **bee pack -exp=排除的文件夹名用:隔开 -exs=排除的文件名用:隔开**

**Comment by mei2015** [comment]
第二个问题：你可以写一个 sh 传入 命令 判断 在执行 bee pack
例如：
pack -linux

**Comment by jqncc** [comment]
> 兄弟 你怕是没有完整看 bee 的打包命令吧！ **bee pack -exp=排除的文件夹名用:隔开 -exs=排除的文件名用:隔开**

文档里没写,我以为没有

**Comment by jqncc** [comment]
> 兄弟 你怕是没有完整看 bee 的打包命令吧！ **bee pack -exp=排除的文件夹名用:隔开 -exs=排除的文件名用:隔开**

文档没写,我以为没有. 不过使用过程还是有问题 . 我的环境是windows10+vscode+git
如果指定-exp时.vscode  .git  .gitignore这些文件夹都会被打进来,  如果不指定-exp时这些是不会被打包的

**Comment by mei2015** [comment]
> > 兄弟 你怕是没有完整看 bee 的打包命令吧！ **bee pack -exp=排除的文件夹名用:隔开 -exs=排除的文件名用:隔开**
> 
> 文档没写,我以为没有. 不过使用过程还是有问题 . 我的环境是windows10+vscode+git 如果指定-exp时.vscode .git .gitignore这些文件夹都会被打进来, 如果不指定-exp时这些是不会被打包的

设置了这些 可能只有 全部写了 默认的 可能就不生效了
