### ISSUE TITLE
After SessionRegenerateID, beegosessionID cookie's secure flag is missing

### ISSUE THREAD

**Issue by yangru** [beego/beego#5003]
1. What version of Go and beego are you using (`bee version`)?
1.12.10

2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gpadmin/.cache/go-build"
GOENV="/home/gpadmin/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gpadmin/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gpadmin/gopath"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3060323132=/tmp/go-build -gno-record-gcc-switches"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
- beegosessionID cookie's secure flag was set before login,
- After a user login, [SessionRegenerateID](https://github.com/beego/beego/blob/36edb18d6e63b6492fdc95422699bd9123e4b91c/session/session.go#L298) is called 
- This secure flag is missing

4. What did you expect to see?
Expect beegosessionID cookie's secure flag is still set

5. What did you see instead?
Saw beegosessionID cookie's secure flag is missing.

6. RCA
It's because this line is not added after this line  [L330](https://github.com/beego/beego/blob/36edb18d6e63b6492fdc95422699bd9123e4b91c/session/session.go#L330):
```
http.Secure = manager.isSecure(r)
```

And if possible, could you please also set `Domain` and `SameSite` to keep align with [L315 - L317](https://github.com/beego/beego/blob/36edb18d6e63b6492fdc95422699bd9123e4b91c/session/session.go#L315)?
Like this:
![image](https://user-images.githubusercontent.com/4914591/176639724-f5f11cc2-a09f-4d84-9474-35b740603d2e.png)

**Comment by flycash** [comment]
good idea, can you make a merge request for us? I think you know how to fix it. 
And you can checkout the branch from develop-1.x

**Comment by yangru** [comment]
Hi, @flycash 
We created a merge request: https://github.com/beego/beego/pull/5007
Please review.

Thank you in advance!

**Comment by flycash** [comment]
I will release a new version at the end of this month
