### ISSUE TITLE
orm querySeter not support metrics

### ISSUE THREAD

**Issue by peachestao** [beego/beego#5006]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.4

3. What operating system and processor architecture are you using (`go env`)?
go1.16.2

4. What did you do?
I am monitoring the execution time of a global SQL statement. If it takes a long time, I will make some alarm notifications. It is used when using orm's Insert, Update and other operation statements, but it is invalid for query method（in the following code, duration is always 0）。

In addition, I can't get the native SQL statements, so I can't quickly locate the SQL statements that take a long time。

my logic code:
```
        o := orm.NewOrm()
	var logConfig []*AdminLogConfig
	_, err := o.QueryTable(l.TableName()).Filter("app_name", appName).Filter("log_module_type", logModuleType).OrderBy("id").All(&logConfig)
```
my filter code:
```
orm.AddGlobalFilterChain(func(next orm.Filter) orm.Filter {
		return func(ctx context.Context, inv *orm.Invocation) []interface{} {
			startTime := time.Now()
			nextFilter := next(ctx, inv)
			endTime := time.Now()
			duration := endTime.Sub(startTime)/time.Millisecond
			logs.Infof("orm trace method:%s args:%+v md:%+v tableName:%s duration:%d", inv.Method, inv.Args, inv.Md, inv.GetTableName(), duration)
			return nextFilter
		}
	})
```
6. What did you expect to see?
a、orm.Filter support query method‘s metrics
b、orm.Filter support get native SQL statements

7. What did you see instead?

**Comment by flycash** [comment]
Actually, Beego is an old framework so it didn't consider the AOP problems like tracing and metric  when it was created

**Comment by peachestao** [comment]
thank you for your answer, I will try it
