### ISSUE TITLE
Access log can trigger CRLF injection problem

### ISSUE THREAD

**Issue by xiangdong1987** [beego/beego#5010]
request url like this:
/v1/groups/actionsss%0adaaaa%0aqqqqqq
there is a  CRLF injection problem
https://github.com/beego/beego/blob/2c506f7c2b10a06a62a712fcf235d63463d96f4a/server/web/router.go#L1276
My demo run as result like this
![image](https://user-images.githubusercontent.com/5974016/177927791-e37bd1f6-7e48-4122-bbf8-d3c641c9592f.png)
I hope framwork to do some filter at here and avoid CRLF' problem

**Comment by xiangdong1987** [comment]
@flycash Do you think it is needed to fix ?

**Comment by flycash** [comment]
Is it the Beego filter?
I mean, I think users should be responsible for handling this case. But if the filter was provided by Beego, I think we need to fix the filter
