### ISSUE TITLE
grace热升级无法使用

### ISSUE THREAD

**Issue by soul-key** [beego/beego#5022]
![image](https://user-images.githubusercontent.com/53042448/178887560-b2979231-ea97-4b86-a621-62a1fbc670e2.png)

**Comment by LHRchina** [comment]
> ![image](https://user-images.githubusercontent.com/53042448/178887560-b2979231-ea97-4b86-a621-62a1fbc670e2.png)

没有配置监听地址吧，测试一下app.Cfg.Listen.HTTPSAddr 或 app.Cfg.Listen.HTTPAddr 是否为空

**Comment by soul-key** [comment]
httpaddr 设置了，看你的源码，发现从2.0.3版本开始
grace.NewServe()  之后，由原来的  调用  ListenAndServe() （此方法中有给 srv.ln  赋值）
改为了 直接定义ln 并 调用 **server.ServeWithListener(ln)** （虽然传值了ln,但并未赋值给  srv.ln），致使   **handleSignals** 方法循环 srv时，ln 未定义，从而报的错。
尝试改动你的源码，恢复部分2.0.2 版本的代码，此报错消失。修改部分见下图：
![image](https://user-images.githubusercontent.com/53042448/179393731-50a7cf94-a9fc-4d34-b52f-4d09744902a0.png)

**Comment by flycash** [comment]
可以给我发一个 PR 吗？

**Comment by flycash** [comment]
Can you help to make a MR to fix this?
