### ISSUE TITLE
[Feature request] Send custom mails utilizing the Parser of beego

### ISSUE THREAD

**Issue by asger-weirsoee** [beego/beego#5023]
It would be nice to use the build in parser for HTML or TPL files, to send mails.

Sending mails is something that could be relevant for larger websites, not only so the user can verify their mail, but also to confirm orders for shopping sites etc.

I can see that there is already some logic in handling SMTP calls for logging for logging, so maybe this could be an extension of this util to allow sending custom mails.

**Comment by flycash** [comment]
I am not sure supporting this by Beego is a good idea. Basically you can implement the `Logger` by yourself which supports the template.

**Comment by asger-weirsoee** [comment]
Well, I agree that beego does not necessarily need to have a "sendMail" option. I just wished that I could call a function which included a template name, a dataset and then get a parsed template as the return element.

I created a working example for how I'm currently handling it.

https://gist.github.com/asger-weirsoee/3e3ce7902e1facbe261352e4c7e72283
