### ISSUE TITLE
如何设置一个应用路径contextPath

### ISSUE THREAD

**Issue by jqncc** [beego/beego#5024]
如题, 能否做一个配置contextpath的配置项. 比如java web项目,都会有一个contextPath的配置项.默认是/. 而在jsp或模板引擎中可以直接取出contextpath用于设定页面来的url.
beego使用namespace也可实现, 但在namespace在有大量路径时显得太复杂了.而且模板里没法用

**Comment by flycash** [comment]
用一个伪代码的形式来描述一下你的场景？我看不懂，我已经把 contextpath 啥的忘光了
