### ISSUE TITLE
beego 2.0.4 on dev mode can't create commentsRouter_controllers.go

### ISSUE THREAD

**Issue by lij2960** [beego/beego#5027]
Go version：1.18
Bee version：2.0.4
Run command：bee run -gendoc=true -downdoc=true
On dev mode，go.mod config as：require github.com/beego/beego/v2 v2.0.4，Can't create commentsRouter_controllers.go
But go.mod config as：require github.com/beego/beego/v2 v2.0.1 ，Can create commentsRouter_controllers.go

Another problem swagger on version 4.6.1，Default swagger.json file is a network url：https://petstore.swagger.io/v2/swagger.json，It's not the location file swagger.json.

**Comment by sdlyingyong** [comment]
我也遇到了同样的问题 用2.0.4版本的bee工具 swagger显示了petstore 而不是本地项目的swagger.json
