### ISSUE TITLE
Command 'bee' not found

### ISSUE THREAD

**Issue by Bishwas-py** [beego/beego#5041]
I tried installing `bee` with `go get github.com/beego/bee/v2` and it goes well, but when I try the `bee` command I get something like this...

```
user@desktop-name:~/Projects/go-for-good/beego$ bee version

Command 'bee' not found, did you mean:

  command 'pee' from deb moreutils (0.63-1)
  command 'bbe' from deb bbe (0.2.2-3)
  command 'ree' from deb ree (1.4.1-1)

```

**Comment by summer-camellia** [comment]
you can use `go install` to install `bee`.
you can see the difference between `go get` and`go install`
https://stackoverflow.com/questions/24878737/what-is-the-difference-between-go-get-and-go-install
