### ISSUE TITLE
require github.com/beego/beego/v2 v2.0.5

### ISSUE THREAD

**Issue by bhswallow** [beego/beego#5045]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go version:  go version go1.18 windows/amd64
require github.com/beego/beego/v2 v2.0.5

2. What operating system and processor architecture are you using (`go env`)?
x86_64 windows11

3. What did you do?
module test111

go 1.16

require github.com/beego/beego/v2 v2.0.5

require (
	github.com/smartystreets/goconvey v1.7.2
	github.com/thirdweb-dev/go-sdk v1.2.12
)

4. What did you expect to see?

....

5. What did you see instead?
![image](https://user-images.githubusercontent.com/79976148/184060823-38f68f4c-9188-47ac-a4c8-5138204a5dc4.png)

**Comment by CCpro10** [comment]
i think you should learn how to use interface
