### ISSUE TITLE
Graceful = true 出现错误  Listen for HTTP[graceful mode]: listen tcp :6719: bind: address already in use

### ISSUE THREAD

**Issue by tongkai-wzq** [beego/beego#5046]
我使用 beego 版本 2.04 go 版本 1.18.2
在app.conf 配置 Graceful = true 后
执行 kill -HUP 6258 后出现错误 Listen for HTTP[graceful mode]: listen tcp :6719: bind: address already in use

2022/08/12 14:19:42.058 ^[[1;34m[I]^[[0m [server.go:219] graceful http server Running on http://:6719
2022/08/12 14:24:27 6258 Received SIGHUP. forking.
2022/08/12 14:24:27 [0xc00028e7f8]
2022/08/12 14:24:27.928 ^[[1;34m[I]^[[0m [server.go:219] graceful http server Running on http://:6719
2022/08/12 14:24:27.928 ^[[1;35m[C]^[[0m [server.go:221] Listen for HTTP[graceful mode]: listen tcp :6719: bind: address already in use
请问如何解决呢？

**Comment by flydt** [comment]
等一会重启服务就可以了，你杀死进程，操作系统知道端口需要关闭需要时间，过了这个时间就没问题了

**Comment by tongkai-wzq** [comment]
> 等一会重启服务就可以了，你杀死进程，操作系统知道端口需要关闭需要时间，过了这个时间就没问题了

kill -HUP 没有成功进行热更新
