### ISSUE TITLE
Feature to provides HTTP services by listening to Unix domain sockets

### ISSUE THREAD

**Issue by laurance-moon** [beego/beego#5050]
Scenario:
Using Beego as the Internal HTTP Server in the Kubernetes Environment，The Beego server and client are located in different containers in the same pod. Containers in the same pod share the IPC namespace by default. That is, Kubernetes supports communication between containers in the same pod using the Unix domain socket.Can this scenario be supported in the beego source code?

The modification method is as follows:
Modify the method “Run” in beego/server/web/server.go
When the "app.Cfg.Listen.EnableHTT" option is enabled, app.Cfg.Listen.HTTPPort is 0,app.Server.Addr is an unix domain socket address,then linten the specified unix domain socket address.

**Comment by laurance-moon** [comment]
What do you think about suggestion?

**Comment by flycash** [comment]
It should be a useful feature, let me do some investigation
