### ISSUE TITLE
beego.vip can't access

### ISSUE THREAD

**Issue by gunnrcrakr** [beego/beego#5073]
Do you have other english guide ? Because I can't access beego.vip

**Comment by hvdtam** [comment]
Same issues!
Down For: ~6 days 11 hours
https://www.isitdownrightnow.com/beego.vip.html

**Comment by gunnrcrakr** [comment]
I can't still access

I want Guide

**Comment by icehan2016** [comment]
can't still access

I want Guide

**Comment by dada0z** [comment]
@astaxie

**Comment by Alan-2018** [comment]
the same

**Comment by ywanbing** [comment]
Please visit https://github.com/beego/beedoc

**Comment by leirongfa** [comment]
I want Guide

**Comment by Alan-2018** [comment]
> Please visit https://github.com/beego/beedoc

beedoc is not good enough

**Comment by gunnrcrakr** [comment]
> > Please visit https://github.com/beego/beedoc
> 
> beedoc is not good enough

Agreed

**Comment by SunA0** [comment]
https://beego.gocn.vip/beego/zh/developing/

**Comment by icehan2016** [comment]
什么时候恢复啊 哭了

**Comment by GuyCheung** [comment]
还没有恢复吗。。。不能想像挂了这么久。。

**Comment by icehan2016** [comment]
> 还没有恢复吗。。。不能想像挂了这么久。。

没想到 这次挂了这么久

谢大 是不是被隔离了啊

**Comment by joaoamaral** [comment]
Hi,
I think it would be a better solution if you host it on github pages.

**Comment by sabbir360** [comment]
> Hi, I think it would be a better solution if you host it on github pages.

I agree!

**Comment by icehan2016** [comment]
> Hi, I think it would be a better solution if you host it on github pages.

I agree too !

**Comment by 0xshawn** [comment]
用 github page 吧，都是静态页面

**Comment by flycash** [comment]
access the git repo of the website directly.
