### ISSUE TITLE
Guys, can u enter beego.vip? I can't enter the site and I have already tried to enter it with different networks and vpn services.

### ISSUE THREAD

**Issue by minbala** [beego/beego#5141]
I can't enter the website since yesterday. The site is taking long time to respond.
![image](https://user-images.githubusercontent.com/65126269/213922256-9af251a7-cad1-45b2-8b08-1e42cd1670c2.png)

**Comment by isaacwein** [comment]
i have same issue

**Comment by msxiehui** [comment]
http://beego.gocn.vip/beego/zh/

**Comment by racastellanosm** [comment]
I can't access either! (Maybe some VPN/Internet Providers block the website)
