### ISSUE TITLE
ORM when db connection disconnected, got incomplete data without error

### ISSUE THREAD

**Issue by RicardoHPeng** [beego/beego#5145]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
GO version 1.17
beego version 1.12.3

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

https://github.com/beego/beego/blob/develop/client/orm/db.go#L1052
![image](https://user-images.githubusercontent.com/22120899/215268212-4ff7e0a3-e6e6-4b38-b6b0-52615eaa5048.png)

In sql.go, rs.Next() returns true on success, or false if there is no next result row or an error happened while preparing it. So when db connection disconnected, Line 1052 for rs.Next() will return false, means an error happened. But the beego framework will handle it as no next result row which  resulting in incomplete data without error.

4. What did you expect to see?
Got error when db connection disconnected.

5. What did you see instead?
Got incomplete data without error.

**Comment by flycash** [comment]
This is a tricky problem because we expect that the `Next()` function returning two values `bool, error` which the `error` indicates if the result set got some problems, i.e. connection closed. However, sql.Rows does not do this. so in general we don't want to handle this by ourselves.

**Comment by flycash** [comment]
As I known, other ORM frameworks do not handle this case either.
