### ISSUE TITLE
orm InsertOrUpdate returns 0 when inserting item

### ISSUE THREAD

**Issue by kotori2** [beego/beego#5158]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
`go version go1.19.5 darwin/arm64`
`github.com/beego/beego/v2 v2.0.7`

2. What operating system and processor architecture are you using (`go env`)?
```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/kotori/Library/Caches/go-build"
GOENV="/Users/kotori/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/kotori/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/kotori/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bg/zs2nw4xx17x9hsxp2jv9xvrh0000gn/T/go-build3211754999=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

```go
// db schema
type UserIdentity struct {
	ID               int              `orm:"PK;column(id)"`
	Name             string           `orm:"size(50)"`
}

// code
cnt := int64(0)
_ := o.DoTx(func(ctx context.Context, txOrm orm.TxOrmer) error {
    cnt, _ = txOrm.InsertOrUpdate(&UserIdentity{
        ID:    1,
        Name:  "name",
    })
    return nil
})
```

4. What did you expect to see?
If a new row of `UserIdentity` was inserted, I will get `1` at `cnt`.
Updating a row returns the correct result. 

5. What did you see instead?
 I always get `0` when something was inserted.

**Comment by kotori2** [comment]
bump

**Comment by flycash** [comment]
I think it's better to keep current behavior. Some other users don't want to make this change, it's not a compatible change.
And I think you misunderstand the function `InsertOrUpdate`, it returns the primary key, not the affected rows.
