### ISSUE TITLE
swagger try it out  using https not http

### ISSUE THREAD

**Issue by xshi0001** [beego/beego#5168]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
`❯ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.4

├── GoVersion : go1.18.10
├── GOOS      : darwin
├── GOARCH    : arm64
├── NumCPU    : 10
├── GOPATH    : /Users/shixiaokai02/workspace/golang
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 3 Mar 2023
`

2. What operating system and processor architecture are you using (`go env`)?
`❯ go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/Users/shixiaokai02/workspace/golang/bin"
GOCACHE="/Users/shixiaokai02/Library/Caches/go-build"
GOENV="/Users/shixiaokai02/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/shixiaokai02/workspace/golang/pkg/mod"
GONOPROXY="*.baidu.com*"
GONOSUMDB="*"
GOOS="darwin"
GOPATH="/Users/shixiaokai02/workspace/golang"
GOPRIVATE="*.baidu.com"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"

GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dq/vqbtwpgn76s0f57nkm7k_7780000gn/T/go-build697502910=/tmp/go-build -gno-record-gcc-switches -fno-common"`

3. What did you do?

![image](https://user-images.githubusercontent.com/28589533/222624744-fc3bb89f-1889-41f3-ae37-73df6f4efb00.png)

4. What did you expect to see?

expect  http  not https curl request

**Comment by fredgan** [comment]
What did you do? What is the problem? It's not clear.
