### ISSUE TITLE
beegoAppConfig  String and Strings function has bug

### ISSUE THREAD

**Issue by chenwei113524** [beego/beego#5176]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

 github.com/beego/beego/v2 v2.0.3
2. What operating system and processor architecture are you using (`go env`)?

go 1.17.8
3. What did you do?
```
beego.AppConfig.Set("rpcaddr", "a")
	beego.AppConfig.Set("rpcport", "b")
	i := InstanceName()
	if i != "a:b" {
		t.Fatalf("TestInstanceName failed")
	}
test failed
```
4. What did you expect to see?
```
beego.AppConfig.Set("rpcaddr", "a")
	beego.AppConfig.Set("rpcport", "b")
	i := InstanceName()
	if i != "a:b" {
		t.Fatalf("TestInstanceName failed")
	}
test success
```

5. What did you see instead?
i thinks `if v, err := b.innerConfig.String(BConfig.RunMode + "::" + key); len(v) > 0 && err != nil {
		return v
	}` is wrong
it shoud `if v, err := b.innerConfig.String(BConfig.RunMode + "::" + key); v != "" && err == nil {
		return v
	}`

**Comment by chenwei113524** [comment]
@markstory

**Comment by Stone-afk** [comment]
How is your InstanceName() implemented?

**Comment by Stone-afk** [comment]
@chenwei113524

**Comment by chenwei113524** [comment]
`func InstanceName() string {
	getEndpointOnce.Do(func() {
		restIp := beego.AppConfig.String("httpaddr")
		restPort := beego.AppConfig.String("httpport")
		if len(restIp) > 0 {
			instance = net.JoinHostPort(restIp, restPort)
			return
		}

		rpcIp := beego.AppConfig.String("rpcaddr")
		rpcPort := beego.AppConfig.String("rpcport")
		if len(rpcIp) > 0 {
			instance = net.JoinHostPort(rpcIp, rpcPort)
			return
		}
	})
	return instance
}`

**Comment by chenwei113524** [comment]
@Stone-afk
