### ISSUE TITLE
beego.me Bug加载跨域错误打不开

### ISSUE THREAD

**Issue by xnzdev** [beego/beego#5182]
访问 https://beego.me 时页面内存在请求http://xxx的连接，页面打不开，请问是故意的么？

**Comment by iakirago** [comment]
https://beego.gocn.vip/

**Comment by OneCricketeer** [comment]
`beego.me` is not correct. Also see #5151

**Comment by auula** [comment]
I meet a requirement that control session on or off with some option. I found session can only be controled by BConfig.WebConfig.Session.SessionOn globally.

issue https://github.com/beego/beego/issues/4176 bring a feature that we can control session on/off on some route. But it can only be used on v2.x,

My system is created at 2016, it's very complex and used on production environment. So I want to ask is there any possible to apply this feature on v1.x?

This framework code quality is very poor, do not recommend the use of the v1 version is not maintained for several years, how to pick up and maintain a v2 version, and finally put here no one to deal with, and garbage like waiting to be recycled by the garbage collection truck.
