### ISSUE TITLE
Regarding the issue of web.BConfig.WebConfig.Session.SessionOn = true not being effective.

### ISSUE THREAD

**Issue by ahui11** [beego/beego#5186]
I am currently using http://github.com/beego/beego/v2 v2.0.7.
I need to use session for certain scenarios. 

However, I encountered a strange phenomenon where if I set the configuration in app.conf with 'sessionon = true', it runs normally. But if I set it in the code with 'web.BConfig.WebConfig.Session.SessionOn = true', an exception will be thrown when I perform session storage operation.

--- A: true

conf/app.conf
---------------------
runmode = dev
httpport = 33
sessionon = true

main.go:
---------------------
	sessionConfig := &session.ManagerConfig{
		CookieName:      "A3SessionID",
		EnableSetCookie: false,
		Gclifetime:      3600,
		Maxlifetime:     3600,
		Secure:          true,
		CookieLifeTime:  3600,
		ProviderConfig:  "./tmp",
	}
	globalSessions, _ = session.NewManager("memory", sessionConfig)
	go globalSessions.GC()

--- B: error

conf/app.conf
---------------------
runmode = dev
httpport = 33

main.go:
---------------------
        web.BConfig.WebConfig.Session.SessionOn = true
	sessionConfig := &session.ManagerConfig{
		CookieName:      "A3SessionID",
		EnableSetCookie: false,
		Gclifetime:      3600,
		Maxlifetime:     3600,
		Secure:          true,
		CookieLifeTime:  3600,
		ProviderConfig:  "./tmp",
	}
	globalSessions, _ = session.NewManager("memory", sessionConfig)
	go globalSessions.GC()

**Comment by ahui11** [comment]
go version go1.20.2 darwin/arm64

**Comment by hookokoko** [comment]
If you write this code: "web.BConfig.WebConfig.Session.SessionOn = true", it will import "github.com/beego/beego/v2/server/web", which triggers the "init()" method in "beego/core/config/ini.go". This method initializes the configuration based on "conf/app.conf". If this file is missing, an error will occur.

In other words, "conf/app.conf" is necessary here, I think.
