### ISSUE TITLE
Does the beego regular routing expression support including all routes outside of a certain string?beego 正则路由表达式是否支持，包含某个字符串之外的所有路由？

### ISSUE THREAD

**Issue by Christian-health** [beego/beego#5188]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
nothing

2. What operating system and processor architecture are you using (`go env`)?
nothing

3. What did you do?
nothing

4. What did you expect to see?
Does the beego regular routing expression support including all routes outside of a certain string?
beego 正则路由表达式是否支持，包含某个字符串之外的所有路由？

beego.InsertFilter(pattern string, position int, filter FilterFunc)
我想做的是，如果一个路由字符串中不包含“health”，那么就执行filter这个函数？
What I want to do is, if a routing string does not contain 'health', then execute the filter function?
thank you 

5. What did you see instead?
nothing

**Comment by auula** [comment]
> **English Only**. Please use English because others could join the discussion if they got similar issue!
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What version of Go and beego are you using (`bee version`)?
>    nothing
> 2. What operating system and processor architecture are you using (`go env`)?
>    nothing
> 3. What did you do?
>    nothing
> 4. What did you expect to see?
>    Does the beego regular routing expression support including all routes outside of a certain string?
>    beego 正则路由表达式是否支持，包含某个字符串之外的所有路由？
> 
> beego.InsertFilter(pattern string, position int, filter FilterFunc) 我想做的是，如果一个路由字符串中不包含“health”，那么就执行filter这个函数？ What I want to do is, if a routing string does not contain 'health', then execute the filter function? thank you
> 
> 5. What did you see instead?
>    nothing

I meet a requirement that control session on or off with some option. I found session can only be controled by BConfig.WebConfig.Session.SessionOn globally.

issue https://github.com/beego/beego/issues/4176 bring a feature that we can control session on/off on some route. But it can only be used on v2.x,

My system is created at 2016, it's very complex and used on production environment. So I want to ask is there any possible to apply this feature on v1.x?

This framework code quality is very poor, do not recommend the use of the v1 version is not maintained for several years, how to pick up and maintain a v2 version, and finally put here no one to deal with, and garbage like waiting to be recycled by the garbage collection truck.

**Comment by flycash** [comment]
sorry, I am not good at regular expression, but I think you can write the specific regular expression.  Here is the example https://developer.aliyun.com/article/39147#:~:text=%E2%80%9C%5E%E2%80%9D%E5%9C%A8%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F,%E4%B8%80%E4%B8%AA%E9%9D%9E%E6%95%B0%E5%AD%97%E7%9A%84%E5%AD%97%E7%AC%A6%E3%80%82

**Comment by auula** [comment]
garbage collection truck
