### ISSUE TITLE
Is there any possible to apply #4176 feature on v1.x?

### ISSUE THREAD

**Issue by HaoKunT** [beego/beego#5193]
I meet a requirement that control session on or off with some option. I found session can only be controled by `BConfig.WebConfig.Session.SessionOn` globally.

issue #4176 bring a feature that we can control session on/off on some route. But it can only be used on v2.x,

My system is created at 2016, it's very complex and used on production environment. So I want to ask is there any possible to apply this  feature on v1.x?

**Comment by auula** [comment]
This framework code quality is very poor, do not recommend the use of the v1 version is not maintained for several years, how to pick up and maintain a v2 version, and finally put here no one to deal with, and garbage like waiting to be recycled by the garbage collection truck.

**Comment by auula** [comment]
> I meet a requirement that control session on or off with some option. I found session can only be controled by `BConfig.WebConfig.Session.SessionOn` globally.
> 
> issue #4176 bring a feature that we can control session on/off on some route. But it can only be used on v2.x,
> 
> My system is created at 2016, it's very complex and used on production environment. So I want to ask is there any possible to apply this feature on v1.x?

This framework code quality is very poor, do not recommend the use of the v1 version is not maintained for several years, how to pick up and maintain a v2 version, and finally put here no one to deal with, and garbage like waiting to be recycled by the garbage collection truck.

**Comment by flycash** [comment]
I think I won't apply it for v1.x. 
But if you can make a pull merge request for v1.x, I am happy to review it and merge it.
