### ISSUE TITLE
cgo json unmarshal err 

### ISSUE THREAD

**Issue by gmluckly** [beego/beego#5204]
在controller中处理请求，需要调用c代码，使用了cgo，在使用json unmarshal的时候，第一个参数包含字母的数据出不来，纯数子就没事；不知道大家有没有遇到过；我去掉C代码的引用，数据就能出来。

**Comment by flycash** [comment]
没遇到过这种问题。但是猜测和 Beego 没有关系，因为我们的序列化和反序列化都是直接依赖于默认的 JSON，并没有自己研发
