### ISSUE TITLE
Security vulnerability found 

### ISSUE THREAD

**Issue by porcupineyhairs** [beego/beego#5210]
Hi,

I would like to report a security vulnerability. Can you please [create a draft Github secuirty advisory](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/creating-a-repository-security-advisory) and add me as a collaborator?

cc: @astaxie @jianzhiyao

**Comment by flycash** [comment]
check it

**Comment by flycash** [comment]
https://github.com/beego/beego/security/advisories/GHSA-cmwm-xcc4-mj7v
