### ISSUE TITLE
mysql: protect field access with lock to avoid possible data race

### ISSUE THREAD

**Issue by yanke-xu** [beego/beego#5221]
Fixed inconsistency and also potential data race in mysql/sess_mysql.go:
st.values is read/written 4 times mysql/sess_mysql.go; 3 out of 4 times it is protected by st.lock.RLock()/Lock(); 1 out of 4 times it is read without a Lock, which is in func Set() on L73.
A data race may happen when SessionRelease() and other func like Set() are called in parallel.

**Comment by flycash** [comment]
hi, can you help to fix it ?

**Comment by flycash** [comment]
#5211

**Comment by yanke-xu** [comment]
Adding a lock may can avoid it.

**Comment by flycash** [comment]
It looks like we have fixed this and I will release the fix this month
