### ISSUE TITLE
beego.vip can't open

### ISSUE THREAD

**Issue by kyochou** [beego/beego#5227]

**Comment by flycash** [comment]
https://beego.gocn.vip/

**Comment by jsam** [comment]
@flycash 

Could you please update the front page description link? 
There is still the old link. 

Thanks

**Comment by flycash** [comment]
I think I have updated the link, did I miss anyone?

**Comment by kyochou** [comment]
main page
<img width="388" alt="image" src="https://github.com/beego/beego/assets/1185621/80d0b079-cc94-4238-9a72-81afa5cca41a">

and 

<img width="339" alt="image" src="https://github.com/beego/beego/assets/1185621/dcfb7814-5038-438b-be0b-44316da5ac14">
