### ISSUE TITLE
Replace github.com/gogo/protobuf/proto with github.com/golang/protobuf

### ISSUE THREAD

**Issue by flycash** [beego/beego#5237]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

Now the github.com/gogo/protobuf/proto is deprecated and I think we can replace it with the official github.com/golang/protobuf

**Comment by Han-songyang** [comment]
When I use "github.com/golang/protobuf" it says "go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead." Shouldn't we use "google.golang.org/protobuf" to replace github.com/gogo/protobuf/proto.
