### ISSUE TITLE
I think redis has a problem with the collection prefix setup

### ISSUE THREAD

**Issue by yqf-cc** [beego/beego#5248]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go 1.17

beego v2

2. What operating system and processor architecture are you using (`go env`)?
windows 
amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Cache collections for redis are added by default, but I hope I don't add them if I don't have a collection prefix set 

For example, I do not set cache.prefix and my key is login_user:2255, but the redis cache provided by beego will set it to : login_user:2255 ,with its own prefix colon （:）

func (rc *Cache) associate(originKey interface{}) string {
	return fmt.Sprintf("%s:%s", rc.key, originKey)
}

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
I hope I don't add them if I don't have a collection prefix set 
key=login_user:2255
5. What did you see instead?
key=:login_user:2255

**Comment by flycash** [comment]
I already know this issue, but it's a break change, so I am not sure if we need to fix it. In theory, it has no impact for you using the redis client.

**Comment by yqf-cc** [comment]
Thanks, I get it, but when my go program shares redis with other programs like java, the java side uses key=login_user:2255, and the go side uses key= :login_user:2255, which is pretty annoying

**Comment by flycash** [comment]
may be I can add one more option and release it in 2.0.1. But I think maybe you can specify the prefix. In general, in this scenario, I think using the prefix users:login_user:2255 looks good

**Comment by yqf-cc** [comment]
Because other programs have already used the login_user prefix, users:login_user:2255 is unable to search for the corresponding key, in addition to using the users prefix, other programs share redis data with go programs, also use this prefix, otherwise there will be problems
