### ISSUE TITLE
postgres: pq: column "%COL%" does not exist

### ISSUE THREAD

**Issue by brucelin-cn** [beego/beego#5254]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

github.com/beego/beego/v2 v2.0.7
go 1.19

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

3. What did you do?

when I use postgres，the postgresTypes  types contains ' CHECK("%COL%" >= 0)' ,need Replace  it 
otherwise，sql will showup err like:
sql:ALTER TABLE "user_deleted" ADD COLUMN "stype" bigint CHECK("%COL%" >= 0) NOT NULL  DEFAULT 0 
err:
EXTRA *pq.Error=pq: column "%COL%" does not exist

 DB schemas :"postgres://x:x@10.35.148.155:30432/vroom-v2?sslmode=disable"

4. What did you expect to see?
use orm auto ADD COLUMN

5. What did you see instead?
EXTRA *pq.Error=pq: column "%COL%" does not exist
![1687176313312](https://github.com/beego/beego/assets/11426127/2fe62b1e-66a3-4cfd-a2b2-b2382ba32e11)

**Comment by brucelin-cn** [comment]
> can you provide the reproduce demo

step1.  create UserDeleted struct ｛ Col  string｝，run orm.RunSyncdb ， table a has been create
step2. modify UserDeleted  struct {
Col  string  
Stype uint32
},
run orm.RunSyncdb ,then, we can see "sql:ALTER TABLE "user_deleted" ADD COLUMN "stype" bigint CHECK("%COL%" >= 0) NOT NULL DEFAULT 0",  and "pq.Error=pq: column "%COL%" does not exist"


I  fixed the error  in my local beego orm source code：
![image](https://github.com/beego/beego/assets/11426127/e9b8f9bf-6791-48a7-8803-ccc3a44c2668)

**Comment by flycash** [comment]
Thank you, so if you have fixed the issues, you can raise a pull request and I will review it,
