### ISSUE TITLE
rows.Next() ==false,maybe it's a normal end, no error handling will cause wrong response

### ISSUE THREAD

**Issue by maxproc** [beego/beego#5255]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

golang 1.17
github.com/beego/beego/v2 v2.1.0

2. What operating system and processor architecture are you using (`go env`)?
arm64、amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
 
code:
_, err := o.Raw("select * from " + tableName + ";").QueryRows(&all)
	if err != nil {
		fmt.Println(tableName+",error", len(all), err)
		return all, err
	}

size should is 503452,but reponse is 45599 and  err is nil and [mysql] print unexpected EOF

<img width="684" alt="image" src="https://github.com/beego/beego/assets/14543110/c7e5d971-b809-49f1-a28f-bdc939b6bef6">

it occur when mysql server kill slowslog

If this is ORM issue, please provide the DB schemas.
github.com/go-sql-driver/mysql v1.7.1

example: v2/client/orm/orm_raw.go:502
I think must check rows.Error() at the end of the loop(orm_raw.go:616) , otherwise it return incomplete data and err==nil，cause error

**Comment by flycash** [comment]
I will release this fix in this month
