### ISSUE TITLE
Error parsing request body:http: request body too large

### ISSUE THREAD

**Issue by coding-cgs** [beego/beego#5258]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
v2.0.1

upload 3.5GB file then occurred  error "Error parsing request body:http: request body too large"
<img width="984" alt="image" src="https://github.com/beego/beego/assets/24579983/5dc20e4d-1adc-466b-8a42-2caf8762dd1d">

app.conf
#Tue Jun 20 16:20:10 CST 2023
copyrequestbody=false
autorender=false
agent_ip_prefix=xxx.xxx.xxx.xx
httpport=10086
livecd_server_context_path=
appname=livecd
livecd_server_ip=xxx.xxx.xxx.xx
livecd_ssl=false
runmode=prod
livecd_server_port=7071
MaxMemory=1 << 32
MaxUploadSize=1 << 32

controller code:
<img width="864" alt="image" src="https://github.com/beego/beego/assets/24579983/c79f7d62-d1b9-46a7-8b55-e4a3c0faf41d">

How to fix this error？
MaxMemory and MaxUploadSize has no effect

**Comment by flycash** [comment]
`MaxMemory` and `MaxUploadSize` have no impact on the file sizes.  This error was caused by the SDK `net` package. If you want to upload the big files, you need to split it into several small chunk and upload then one by one, you can find more details from HTTP header Range and Content-Range

**Comment by coding-cgs** [comment]
@flycash

**Comment by coding-cgs** [comment]
> 

Ok, thank you very much for your reply
