### ISSUE TITLE
找不到 Debug 函数了

### ISSUE THREAD

**Issue by Jetereting** [beego/beego#5259]
httplib.Get("[http://beego.me/").Debug(true](http://beego.me/%22).Debug(true))

httplib.Get("[http://beego.me/").Debug](http://beego.me/%22).Debug) undefined (type *httplib.BeegoHTTPRequest has no field or method Debug)

**Comment by flycash** [comment]
using this one https://github.com/beego/beego/blob/develop/client/httplib/filter/log/filter.go
