### ISSUE TITLE
orm - postgre. escaping placeholder with backslash

### ISSUE THREAD

**Issue by chandratripmp** [beego/beego#5280]
**English Only**. Please use English because others could join the discussion if they got similar issue!

i need to escape placeholder `?` with backslash. in postgre `?` is used in jsonb query also (currently i use jsonb_path_exists function. pls refer to this documentation https://www.postgresql.org/docs/12/functions-json.html).

afaik, at function `ReplaceMarks(query *string)` only care about `?`. it replace my jsonb query `?` with `$n`.

or is there another method to achieve my problem? 
thanks in advance!

**Comment by flycash** [comment]
I think you'd better use the raw query. Currently, we only handle the symbol `?`

**Comment by chandratripmp** [comment]
sorry for lack of information. yes, i use raw query. please take a look my screenshot. postgre function `jsonb_path_exists` use `?` for checking is string is exists within the JSON value. but as `QueryRow()` was called, it replace `?` with `$1` which is treated as placeholder.

![image](https://github.com/beego/beego/assets/15280328/b434b339-c251-4866-8c4c-75ee5563276b)

currently i had some tweak at function `ReplaceMarks(query *string)` on db_postgres.go file below
```
// postgresql value placeholder is $n.
// replace default ? to $n.
func (d *dbBasePostgres) ReplaceMarks(query *string) {
	q := *query
	num := 0
	esc := 0
	for i, c := range q {
		if c == '?' && q[i-1] != '\\' {
			num++
		}
		if c == '?' && q[i-1] == '\\' {
			esc++
		}
	}
	if num == 0 && esc == 0 {
		return
	}
	data := make([]byte, 0, len(q)+num-esc)
	num = 1
	for i := 0; i < len(q); i++ {
		c := q[i]

		if c == '\\' {
			continue
		}

		if c == '?' && q[i-1] != '\\' {
			data = append(data, '$')
			data = append(data, []byte(strconv.Itoa(num))...)
			num++
		} else {
			data = append(data, c)
		}
	}
	*query = string(data)
}
```
after above tweak, my query works as i need

![image](https://github.com/beego/beego/assets/15280328/490a02b4-f60f-40ba-8c60-c20212710a78)


i know this is not recommended practice, but i need to escape `?` for my jsonb query.
maybe for future version in beego orm can escape `?` for this kind of needs

**Comment by jovti** [comment]
草你妈个逼谢孟军，老子草你妈的，草你妈个逼，狗日的死杂种草你妈的！我也不怕其他人看到，你妈个逼报你妈个逼警，草你妈的，有本事不要叫条子，约个地方，你看过你留不留块疤子，草你妈的，进去蹲几天，都要弄你个狗日的，草你妈的！草你妈的写你妈个逼笔录，写怎么日你妈的过程，生出你个狗日的傻逼草你妈的，草你妈的，写你妈个逼笔录。 @astaxie
