### ISSUE TITLE
field: models.SysUserBean.Username, unsupport field type &{{ %!s(bool=false)}}, may be miss setting tag

### ISSUE THREAD

**Issue by dishuiya** [beego/beego#5291]
I use beego(v2.0.2) with "gopkg.in/guregu/null.v4", my go version is 1.20, create struct 

type SysUserBean struct {
	UserId                int64       `orm:"auto" json:"userId"`
	Username              null.String `json:"username"`
}

when run "bee run", then tips, "field: models.SysUserBean.Username, unsupport field type &{{ %!s(bool=false)}}, may be miss setting tag", can't go on

how to fix it

**Comment by flycash** [comment]
what's the null.String?

**Comment by dishuiya** [comment]
// String is a nullable string. It supports SQL and JSON serialization.
// It will marshal to null if null. Blank string input will be considered null.
type String struct {
	sql.NullString
}

**Comment by flycash** [comment]
I think Beego doesn't support this use case, but you can use the sql.NullString directly.

**Comment by flycash** [comment]
I am thinking about support this case
