### ISSUE TITLE
Router is not auto mapping based on controller's URLMapping method

### ISSUE THREAD

**Issue by pettomartino** [beego/beego#5297]
**English Only**. Please use English because others could join the discussion if they got similar issue!

1. What version of Go and beego are you using (`bee version`)?
v2.1.0

2. What operating system and processor architecture are you using (`go env`)?
darwin / arm64 

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

1. I created a project using `bee new` and tried to generate scaffold to user.

2. `bee generate scaffold user -fields="user:string" -driver=mysql -conn="_"`
- I have answered `yes` to very question.

`routers/router.go`
```go
func init() {
	beego.Router("/", &controllers.MainController{})
	beego.Router("/users", &controllers.UserController{})
}
```

`controllers/user.go`
```go
// this is a default file created by the bee generate tool
// I have copied this part to show the URLMapping method

type UserController struct {
	beego.Controller
}

// URLMapping ...
func (c *UserController) URLMapping() {
	c.Mapping("Post", c.Post)
	c.Mapping("GetOne", c.GetOne)
	c.Mapping("Get", c.GetAll)
	c.Mapping("Put", c.Put)
	c.Mapping("Delete", c.Delete)
}


```
If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
Access http://localhost:8080/users in the browser and see `null`

5. What did you see instead?
`Method Not Allowed`

**Comment by flycash** [comment]
can you provide the whole projects? including the UserController and the main function, let me check it .

**Comment by pettomartino** [comment]
sure, I created a simpler version:
https://github.com/pettomartino/beego-controller-test

If I add the third parameter to beego.Router function it works. But then I don't see the reason got the `URLMapping`.

**Comment by flycash** [comment]
I think this is a bug, and I will fix it. But I am afraid that you need to add the routers manually now. 

😢 There are many tricky code in the Bee tool and Beego, it takes time to find the best way to fix it.

**Comment by jovti** [comment]
草你妈个逼谢孟军，老子草你妈的，草你妈个逼，狗日的死杂种草你妈的！我也不怕其他人看到，你妈个逼报你妈个逼警，草你妈的，有本事不要叫条子，约个地方，你看过你留不留块疤子，草你妈的，进去蹲几天，都要弄你个狗日的，草你妈的！草你妈的写你妈个逼笔录，写怎么日你妈的过程，生出你个狗日的傻逼草你妈的，草你妈的，写你妈个逼笔录。 @astaxie
