### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by simo-berto98** [beego/beego#5302]
1. What version of Go and beego are you using (`bee version`)?
2.0.4

2. What operating system and processor architecture are you using (`go env`)?
go version = 1.20.6
GOARCH="arm64"

Hi, I started a new project with this framework. 
I need to integrate Sentry for error handling and monitoring/performance metrics.
How can I integrate it?

Thank you very much

**Comment by flycash** [comment]
For web, I think you can use the Filter or FilterChain. For ORM, there is a FilterChain too, but it only works for Ormer interface. Alternatively, you can take `dbQueryLog` which implements the interface `dbQuerier`

**Comment by simo-berto98** [comment]
Sorry, but I think I don't understand.
My goal is to integrate Sentry (application monitoring).
For Go it is possible by setting up this snippet:

`func main() {
	err := sentry.Init(sentry.ClientOptions{
		Dsn: {{MY_DSN}},
	})
	if err != nil {
		log.Fatalf("sentry.Init: %s", err)
	}
`}``

But with Beego I can't see the errors.
