### ISSUE TITLE
orm 自动对表字段添加T0前缀问题

### ISSUE THREAD

**Issue by btfak** [beego/beego#534]
请教一个beego orm遇到的问题，定义好结构体并与数据库字段保持一致，做一个查询，提示Error 1054: Unknown column 'T0.buyer_account_id' in 'field list'，主要是T0.buyer_account_id这个，我在结构体定义的BuyerAccountId，数据库定义的是buyer_account_id,前缀T0应该是orm加上的，什么情况下会导致这种情况？

**Comment by zmingshi** [comment]
Hi , 这个问题你解决了吗？ 我今天也遇到这个问题了，一直没有解决？
Error 1054: Unknown column 'bio' in 'field list'
如果解决了能否分享一下，谢谢！

**Comment by doorOfChoice** [comment]
能够分享一下解决方案吗，今天在m2m删除中间表的时候提示Unknown column 'T0.id' in 'field list'

**Comment by chrisfeng0723** [comment]
我得是字段名称写错得时候出现得。
