### ISSUE TITLE
Can you provide an API to view the execution of sql, and can print out the sql to be executed when called

### ISSUE THREAD

**Issue by hertzzhang** [beego/beego#5357]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

5. What did you see instead?

**Comment by comment-reboot** [comment]
老子日你仙人，老子亲妈都干下手，这笔帐，老子狠狠记着，迟早要算到你头上你狗日的，那块疤子必须要留在你身上，蹲监狱都要搞你，以为脾气草你妈的，死杂种，草你妈的 @astaxie
