### ISSUE TITLE
serial use bigserial type

### ISSUE THREAD

**Issue by lengrongfu** [beego/beego#5398]
current auto type mapping `serial NOT NULL PRIMARY KEY`, `serial` default is interge type, when we hope use bigint, `serial` should is `bigserial`.

**Comment by flycash** [comment]
so, can you provide the model definition?

**Comment by flycash** [comment]
I think this is not BUG, but I think we need a new feature which allow users to specify the database column definition. Let me find someone to implement this feature.

**Comment by flycash** [comment]
will release soon
