### ISSUE TITLE
[Feature Request] Insert with only specific columns from particular model (struct) 

### ISSUE THREAD

**Issue by maneeshsaagar** [beego/beego#5401]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
1.29.0

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?
```go
type User struct{
 Name string
 Mobile int
 Address string 
}
Now I want to insert only mobile and Name not adresss ?
``` 

5. What did you see instead?

**Comment by xiangdong1987** [comment]
may there is tow diffrent struct  , one input struct one model struct ,input struck can use model struck.
