### ISSUE TITLE
2.1.1版本 orm.DebugLog 这个设置无效

### ISSUE THREAD

**Issue by Offensivetcw** [beego/beego#5403]
2.1.1版本 orm.DebugLog 这个设置无效

**Comment by flycash** [comment]
so, can you give more details?

**Comment by Offensivetcw** [comment]
v2.1.0版本，设置	orm.Debug = true    orm.DebugLog = orm.NewLog(newLog())，日志会在newLog()这个方法输出。
升级到v2.1.1版本，日志就不走newLog()这个方法了
![image](https://github.com/beego/beego/assets/23259660/bda5205e-b3b8-455f-b40c-08e88bcef297)

**Comment by flycash** [comment]
I try it, and it still works. I hope you can provide a reproduce demo.
