### ISSUE TITLE
Documentation grammatical errors

### ISSUE THREAD

**Issue by arthurkay** [beego/beego#5411]
1. What version of Go and beego are you using (`bee version`)?

Using golang v1.21.3 and bee v2.1.0

3. What operating system and processor architecture are you using (`go env`)?

OS: Ubuntu Linux 22.04 
Processor architecture: amd64

5. What did you do?

I was going through the documentation to understand how to use beego.

6. What did you expect to see?

Standard English grammar that clearly explains how things work in beego

8. What did you see instead?

I found some incorrect grammar in certain areas of the documentation.

**Comment by arthurkay** [comment]
Requesting to proceed with a pull request to fix these errors.

My proposal is to start with an initial pull request of the CONTIRBUTING.md file.

The motivation is to keep the same message, but communicate it more clearly

**Comment by flycash** [comment]
😄 so can you help to improve them?

**Comment by arthurkay** [comment]
Yes, I can.
