### ISSUE TITLE
Error parsing request body:mime: invalid media parameter

### ISSUE THREAD

**Issue by yuexiayiyu** [beego/beego#5459]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go1.19 and bee v2.1.0

2. What operating system and processor architecture are you using (`go env`)?
linux

3. What did you do?
beego.Router("/ssp", &controllers.SSPController{}, "get:Ssp")

4. What did you expect to see?
This error will not occur on my own request, and not all other requests are this error. It is just a prompt in the error log. I would like to ask under what circumstances this prompt will reappear

5. What did you see instead?
Error parsing request body:mime: invalid media parameter

**Comment by flycash** [comment]
can you provide a demo to reproduce the issue?

**Comment by yuexiayiyu** [comment]
I just couldn't reproduce it if I requested it myself

**Comment by yuexiayiyu** [comment]
This error did not occur in v1. x. When upgrading to v2.1, there will be an error prompt, as long as you don't know how to reproduce this error.
