### ISSUE TITLE
Cookie timeout

### ISSUE THREAD

**Issue by deatil** [beego/beego#5462]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
last ver

2. What operating system and processor architecture are you using (`go env`)?
win

3. What did you do?
use cookie set 10 days but no more 24h the cookie is timeout.
it is see what it is bug. Cookie is not used for long time.

**Comment by flycash** [comment]
can you upload a demo to reproduce this issue?

**Comment by deatil** [comment]
it is browser error.
