### ISSUE TITLE
What configuration options are available in Beego's configuration file? Could you provide a comprehensive example?

### ISSUE THREAD

**Issue by ideaviewes** [beego/beego#5499]
1. What version of Go and beego are you using (`bee version`)?
GoVersion : go1.20.5
2. What operating system and processor architecture are you using (`go env`)?
GOOS      : windows
GOARCH    : amd64

3. What did you do?
What configuration options are available in Beego's configuration file? Could you provide a comprehensive example?

**Comment by flycash** [comment]
https://beego.gocn.vip/beego/en-US/developing/config/#implementations

you can find the answer. By the way, the SSL of this docsite is expired

**Comment by ideaviewes** [comment]
Thank you for your reply. I meant, what are the configurable options? I don't know what can be included in this configuration file.

**Comment by flycash** [comment]
https://github.com/beego/beego/blob/develop/server/web/config.go
