### ISSUE TITLE
GitHub Stars

### ISSUE THREAD

**Issue by mikelerch** [beego/beego#5515]
Hey quick question,

I saw this repository has over 30k stars but literally no one is using it.
What website did you use to buy the stars? I'm looking for a good service.

Thanks in advance!

**Comment by daifuyang** [comment]
🐂🍺

**Comment by daifuyang** [comment]
🐂🍺

**Comment by elcozy** [comment]
> Hey quick question,
> 
> I saw this repository has over 30k stars but literally no one is using it. What website did you use to buy the stars? I'm looking for a good service.
> 
> Thanks in advance!

🫢

**Comment by Malix-off** [comment]
🥸

**Comment by Jorropo** [comment]
https://pkg.go.dev/github.com/beego/beego shows https://pkg.go.dev/vuln/GO-2022-0572 in bright red.

**Comment by Malix-off** [comment]
## Star History

<a href="https://star-history.com/#beego/beego&Timeline">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://api.star-history.com/svg?repos=beego/beego&type=Timeline&theme=dark" />
    <source media="(prefers-color-scheme: light)" srcset="https://api.star-history.com/svg?repos=beego/beego&type=Timeline" />
    <img alt="Star History Chart" src="https://api.star-history.com/svg?repos=beego/beego&type=Timeline" />
  </picture>
</a>

**Comment by longyue0521** [comment]
Your question is so rude. Why do you think no one is using it? Why do you think the stars was bought from somewhere?

**Comment by flycash** [comment]
I will keep this issue open even though this is slander.

**Comment by vigneshwar221B** [comment]
Hi, I'm selling one star. Please react out to me if you're interested.

**Comment by so1ve** [comment]
DM me for one star :D

**Comment by Winiex** [comment]
Hey bro, I just got one star in my deep dark pocket for a loooooong time, been waited for a wise guy like you. And the price is a down-to-earth level of nine pounds fifteen pence. I'm pretty sure you'd be interested.

**Comment by s-alad** [comment]
You can get a lot of stars by reaching your hands far up up into the sky and transcending the earthbound plane

**Comment by jbmagination** [comment]
If you believe hard enough it’ll become true

**Comment by Miguell-J** [comment]
How did you know that their are not using?

**Comment by NightScript370** [comment]
You just gotta...
https://www.youtube.com/watch?v=5eUswq5owJk

**Comment by jusunglee** [comment]
@flycash 

<img width="505" alt="image" src="https://github.com/beego/beego/assets/13562746/d8de40b9-e553-475f-9a31-7ad5f9f7520c">

**Comment by RGBCube** [comment]
I'll give you zero stars for zero dollars. Dm me your credit card details and I'll get right to it.

**Comment by luke-beep** [comment]
> Hey quick question,
> 
> I saw this repository has over 30k stars but literally no one is using it. What website did you use to buy the stars? I'm looking for a good service.
> 
> Thanks in advance!

That's very rude.

**Comment by Ahopness** [comment]
This is possibly the best issue ever written on this plataform

**Comment by jakobdylanc** [comment]
Guys I have 1 repo it's really cool please go star it please please please it will boost my ego thank you

**Comment by guisaliba** [comment]
Any star seller out there I am pretty interested in buying some for this amazing repo of mine, you can check it out here -> github.com/guisaliba/wow Thanks in advance!

**Comment by theoparis** [comment]
Bruh what :sku

**Comment by dylancvdean** [comment]
> Guys I have 1 repo it's really cool please go star it please please please it will boost my ego thank you

The API key is missing from the repo please resolve this and I will star

**Comment by jakobdylanc** [comment]
> > Guys I have 1 repo it's really cool please go star it please please please it will boost my ego thank you
> 
> The API key is missing from the repo please resolve this and I will star

Bruh

**Comment by MTAwsl** [comment]
Lmao

**Comment by astaxie** [comment]
@mikelerch Beego has been in development for 11 years since 2012. It's quite disappointing that you chose to use such language to criticize us. As a senior engineer, I find it deeply insulting. Beego has played a significant role in the overall development of Go. Its contributions are evident in various aspects, such as the design of Go's session package and the automatic generation of swagger docs. If you're not familiar with the history of Go's framework development, I suggest you do your homework before making baseless accusations against Beego. Furthermore, claiming that nobody uses Beego is simply untrue. Just take a look at the number of dependency packages Beego has. Please refrain from making uninformed judgments and using offensive language. 
 ![](https://media.tenor.com/bgtq4jlnflcaaaad/fuck-you-middle-finger.gif)

**Comment by mikelerch** [comment]
As a senior engineer, I ain't reading all that. I'm happy for u tho, or sorry that happened.

**Comment by lambdaq** [comment]
ML Infrastructure SDE @ Twitch Twitch Streamer

There needs to be a twitch battle.

**Comment by CC11001100** [comment]
Hi, I'm selling one star. Please reach out to me if you're interested.

**Comment by treasure567** [comment]
Hey. I've a premium star for sale. Hit me up 😅😅

**Comment by ceilingtilefan** [comment]
Selling -2 stars hmu if interested

**Comment by vksx** [comment]
This will be one of those easter eggs of GitHub that the next generation will find on a random tweet or a Reddit post down the line in 2035 or something.

**Comment by DaniGuardiola** [comment]
i was here before locked for spam

**Comment by AbhinavAchha** [comment]
Launching an AI tool which collect stars from different repos and transfers them to your given repo. Contact me for enterprise pricing 😎

**Comment by dylanngph** [comment]
I'm here waiting for the infinity war to begin.
