### ISSUE TITLE
Disable logging from 'bee run' for some static routes or all of them

### ISSUE THREAD

**Issue by davleb** [beego/beego#5517]
1. What version of Go and beego are you using (`bee version`)?
go 17.8 and bee 2.0.2

2. What operating system and processor architecture are you using (`go env`)?
linux/amd64

3. What did you do?
When executing bee run, the router traces from server.go are very noisy, because of every GET to /static or /assets content (images, css, ...)
Of course, I have settled all the static paths with beego.SetStaticPath()

I have many of them like (example)
`2023/11/10 16:50:21.668 [D] [server.go:2879]  |            ::1| 200 |     287.97µs|   match| GET      /static/css/bootstrap-3.3.5.css`

4. What did you expect to see?
I would like to exclude the GET traces for routes going to static assets when executing `bee run`
Why not adding a boolean parameter to beego.SetStaticPath to inhibate such output ? Is it possible ? Another way to do it ?

5. What did you see instead?
I see too much of them, that does not help debugging especially if the status code of getting static content is 200

**Comment by flycash** [comment]
Good idea.

**Comment by flycash** [comment]
I already check the Web configure, and I think you can disable the static files log via:
```go
type LogConfig struct {
	// AccessLogs
	// @Description If it's true, Beego will log the HTTP request info
	// @Default false
	AccessLogs bool
	// EnableStaticLogs
	// @Description log static files requests
	// @Default false
	EnableStaticLogs bool
}
// web.BConfig.LogConfig.EnableStaticLogs = false
```
