### ISSUE TITLE
rotate log file has a bug

### ISSUE THREAD

**Issue by TenshGU** [beego/beego#5527]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go：the latest version
beego：the latest version

2. What operating system and processor architecture are you using (`go env`)?
linux amd64

3. What did you do?
**issue1:**
I have configured as follows:
\> **the maximum dump size**
\> **Daily was set to false**
\> **Hourly is false as default**
I can see the logs with the dump, but the name of this file is not [xx.001. log (by line or size)] as mentioned in the comments. **The name of this file is xxx..001.log, double dot**
**issue2:**
when I use linux command to make log file oversize the maxsize, beego did not rotate the log file. 
But only when I first start the beego, the log file can be rotated successfully

4. What did you expect to see?
expect the file name is xxx.001.log

5. What did you see instead?
 file name is xx..001.log with double dot

6. my explain and suggestion:
**issue1:**
watch the code in **core/logs/file.go**
func (w *fileLogWriter) doRotate(logTime time.Time) error { xxx }
line330 and line 343-349
if format can not be assigned a value, line354 will output a empty string
so that the file name will carry double dot
**issue2:**
Beego maintains the **maxSizeCurSize** attribute on its own. It uses maxSizeCurSize to determine whether the log file needs to be rotated. Every time Beego writes a log, it updates and maintains maxSizeCurSize. By using maxSizeCurSize, it determines whether the file has reached the threshold to rotate. Therefore, when I use an external command to make the log file that exceeds the threshold, Beego does not respond anything and still uses the previous maxSizeCurSize to determine. The reason why Biego was able to react the first time it was restarted is because it read the properties of the log file to update maxSizeCurSize. The corresponding method is func (w * fileLogWriter) initFd() error {xx} 
Perhaps the community needs to write a **precheck method** that is called every time a log file is written

**Comment by flycash** [comment]
> when I use linux command to make log file oversize the maxsize, beego did not rotate the log file.
But only when I first start the beego, the log file can be rotated successfully

As I known, when Beego try to write the new log, it will rotate a new log file.  So if you make the log file oversize the maxSize and did not write log, I think beego will not rotate it.

**Comment by TenshGU** [comment]
> > when I use linux command to make log file oversize the maxsize, beego did not rotate the log file.
> > But only when I first start the beego, the log file can be rotated successfully
> 
> As I known, when Beego try to write the new log, it will rotate a new log file. So if you make the log file oversize the maxSize and did not write log, I think beego will not rotate it.

Yes, as I said before, beego maintains a variable internally that is maxSizeCurSize, which is updated in two ways:
1. when beego restarts
2. every time a file is written
Therefore, can we add a precheck mechanism to [check the log size] or [stat the log file and update maxSizeCurSize] each time log file is written?

In addition, when I set up daily to false, and make hourly to default, I found that the rotate file name had double dot, for example, mylog..001.log which reason I have been explained in point 6 of my first comment.

Thank you for your reply.

**Comment by flycash** [comment]
#1626 

I think we need to fix the file name bug, but it's not necessary to update the maxSizeCurSize even though someone change it manually.

**Comment by TenshGU** [comment]
OK, Thank you so much!

> #5548
> 
> I think we need to fix the file name bug, but it's not necessary to update the maxSizeCurSize even though someone change it manually.

Thank you so much

**Comment by TenshGU** [comment]
> #5548
> 
> I think we need to fix the file name bug, but it's not necessary to update the maxSizeCurSize even though someone change it manually.

OK, Thank you so much!
