### ISSUE TITLE
A research for generating PR checklists in Pull Request Template

### ISSUE THREAD

**Issue by chenkun1029** [beego/beego#5528]
Dear maintainers:
Our team is currently developing a tool for automatically generating PR checklists in Pull Request Template. The tool generates a set of PR rules based on the contribution guidelines in your project, which external contributors may be expected to adhere to. Below are the results of our generation:

**Test**: Tests pass successfully.
**Title**: Use a specific format in the PR title.
**Description**: a detailed bug description with a live demo
**Branch**: Use dedicated branches for development, not the master branch.
**Commit Message**: Commit message conventions for changelog automation.

Also, we suggest you add some checklist notes about **Documentation**, **Style**, **Contributing**, and **CLA**, which are also important for submitting PRs according to our analysis.

We hope you and your team can provide feedback on our generated output.
Best regards.

**Comment by Dawn77991** [comment]
Hi! i am not a member of this project, But i thought it may be helpful. Also, i have a question what is the specific format, can i have more details
