### ISSUE TITLE
 ORM logs to a custom file

### ISSUE THREAD

**Issue by douguohai** [beego/beego#5530]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go 1.21

require github.com/beego/beego/v2 v2.1.3

2. What operating system and processor architecture are you using (`go env`)?
 set GO111MODULE=on
set GOARCH=amd64                                 
set GOBIN=C:\Users\dougu\go\bin                  
set GOCACHE=C:\Users\dougu\AppData\Local\go-build
set GOENV=C:\Users\dougu\AppData\Roaming\go\env  
set GOEXE=.exe                                   
set GOEXPERIMENT=                                
set GOFLAGS=                                     
set GOHOSTARCH=amd64                             
set GOHOSTOS=windows                             
set GOINSECURE=                                  
set GOMODCACHE=C:\Users\dougu\go\pkg\mod         
set GONOPROXY=                                   
set GONOSUMDB=                                   
set GOOS=windows                                 
set GOPATH=C:\Users\dougu\go                     
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:/Program Files/Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.0
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\dougu\go\src\go-workflow\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\dougu\AppData\Local\Temp\go-build3542201173=/tmp/go-build -gno-record-gcc-switches

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I want to redirect the console logs generated by my ORM to a log file. I have tried the following code, but it still doesn't work.

``` golang
func init() {
	_ = orm.RegisterDriver("postgres", orm.DRPostgres)
	_ = orm.RegisterDataBase("default", "postgres", "user=postgres password=***dbname=workflow host=101.0.0.0  port=5432 sslmode=disable")
	_ = orm.RunSyncdb("default", false, true)
	orm.Debug = true

	errFile, _ := os.OpenFile("logs/access.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)

	orm.DebugLog = orm.NewLog(errFile)

	//orm.LogFunc = customLogFunc
	// 创建 ORM 对象
	O = orm.NewOrm()

}
````
Although the "logs/access.log" file was created, its contents are empty.

I debugged into the framework and found that the ORM logs are being output by the following object: `orm.DebugLog`. However, it seems that `orm.DebugLog` has not been referenced or used. To redirect the ORM logs to a log file, you may need to modify the `orm.DebugLog` or find an alternative way within the framework to configure the logging output.

![image](https://github.com/beego/beego/assets/35925212/85e34e72-1275-40ea-875e-327205065384)

I tried the following code:

```
package models

import (
	"github.com/beego/beego/v2/client/orm"
	ilogs "github.com/beego/beego/v2/client/orm/internal/logs"
	"github.com/beego/beego/v2/core/logs"
	"os"
)

// 自定义的日志记录函数
func customLogFunc(query map[string]interface{}) {
	logs.Info("Executing query: %s", query)
}

var O orm.Ormer

func init() {
	_ = orm.RegisterDriver("postgres", orm.DRPostgres)
	_ = orm.RegisterDataBase("default", "postgres", "user=postgres password=woshi dbname=workflow host=101.0.0.0 port=5432 sslmode=disable")
	_ = orm.RunSyncdb("default", false, true)
	orm.Debug = true

	errFile, _ := os.OpenFile("logs/access.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)

	ilogs.DebugLog = orm.NewLog(errFile)

	//orm.LogFunc = customLogFunc
	// 创建 ORM 对象
	O = orm.NewOrm()

}

```
GOLAND provides the following prompt:

![image](https://github.com/beego/beego/assets/35925212/83dd0b7e-374e-4479-9412-a7af71c8200a)

If this is ORM issue, please provide the DB schemas.

4. What did you expect to see?

I'm not sure if the issue lies with my usage or if beego doesn't provide the customization I need. Could you please let me know how I can redirect the ORM logs to a custom file without modifying the beego source code and without using `orm.LogFunc = customLogFunc`? Thank you.

5. What did you see instead?

**Comment by flycash** [comment]
let me check it.

**Comment by flycash** [comment]
Hi, please checkout master branch and confirm if it has solved the issue. I will release a new version when you confirmed

**Comment by douguohai** [comment]
it test ok, thank you

![image](https://github.com/beego/beego/assets/35925212/30748b4e-7d94-400a-a700-e6e8a755b5d0)
