### ISSUE TITLE
Cannot ignore failure to load conf/app.conf because log writes to STDOUT

### ISSUE THREAD

**Issue by jeffdoubleyou** [beego/beego#5537]
Hello,

I am trying to build a command line tool that is utilizing my already implemented APIs and other command line tools built using the Beego framework.

Everything is mostly working fine, but now I need to implement a command line tool that outputs only JSON to a client which runs an executable.

This is not possible unless the config file `conf/app.conf` exists, because a log is written to stdout by the init function unless this file exists.  The working directory is not always known and I cannot place the config file somewhere that will definitely be readable, so I don't seem to have a solution to this problem that I can figure out.

If this is meant to be ignored, is there a way to disable this log message or print by default to os.Stderr?

https://github.com/beego/beego/blob/3f007d382d241b61cac30d609a3636aa7ff626f0/core/config/ini.go#L520

`2023/11/29 20:47:19.539 [D]  init global config instance failed. If you donot use this, just ignore it.  open conf/app.conf: no such file or directory`

**Comment by flycash** [comment]
Currently we cannot ignore it. But i think it has no impact to live environment

**Comment by jeffdoubleyou** [comment]
It's meant to be able to be ignored, because you might not use this config file.  SInce it's logging to STDOUT though, my system cannot ignore this because it's printing the warning message into the output of the script.

For example, I have a command line tool that utilizes the models and services that I have built in my Beego application, and when running it, should output a valid JSON object, but this is not possible, because the output to STDOUT is always something like:

```
2023/11/29 20:47:19.539 [D]  init global config instance failed. If you donot use this, just ignore it.  open conf/app.conf: no such file or directory
{"order_id":"12345"}
```

This should be sent instead to STDERR so that you aren't forced to include this in the output.  I cannot override the logging here either.
