### ISSUE TITLE
response 返回的时候自动对特殊字符转义了，如何禁止？

### ISSUE THREAD

**Issue by zzBeeCoder** [beego/beego#5539]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
go v1.20 
beego v2.0.7

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"

3. What did you do?
请求返回的response，预期是返回一串unicode编码后的中文字符串，实际unicode字符响应之后其斜杆额外加了转义符。请问有什么方法阻止这种行为吗

4. What did you expect to see?
5. {"status":400,"message":"查询资源失败, \u627e\u4e0d\u5230\u4efb\u4f55\u5177\u6709\u6807\u8bc6 5c2ea90f-814d-4b21-99ff-eb4ba0ae460a \u7684\u6620\u50cf"}

6. What did you see instead?
{"status":400,"message":"查询资源失败, \\u627e\\u4e0d\\u5230\\u4efb\\u4f55\\u5177\\u6709\\u6807\\u8bc6 5c2ea90f-814d-4b21-99ff-eb4ba0ae460a \\u7684\\u6620\\u50cf"}

**Comment by zzBeeCoder** [comment]
预期结果：
{"status":400,"message":"查询资源失败, \u627e\u4e0d\u5230\u4efb\u4f55\u5177\u6709\u6807\u8bc6 5c2ea90f-814d-4b21-99ff-eb4ba0ae460a \u7684\u6620\u50cf"}
实际相应：
{"status":400,"message":"查询资源失败, \\\\u627e\\\\u4e0d\\\\u5230\\\\u4efb\\\\u4f55\\\\u5177\\\\u6709\\\\u6807\\\\u8bc6 5c2ea90f-814d-4b21-99ff-eb4ba0ae460a \\\\u7684\\\\u6620\\\\u50cf"}

**Comment by flycash** [comment]
I don't think the beego did the escape automatically. So do you specify the charset or some other similar HTTP header correctly?

**Comment by flycash** [comment]
I believe that we do not do the escape, so I think maybe you need to check your code.
