### ISSUE TITLE
all requests from client got incorrect http headers, suddenly

### ISSUE THREAD

**Issue by zhaoxiwu** [beego/beego#5540]
1. What version of Go and beego are you using (`bee version`)?
beego 1.9.1
golang  1.16.15

2. What operating system and processor architecture are you using (`go env`)?
 centos

3. What did you do?
If possible, provide a recipe for reproducing the error.
appear by chance

4. What did you expect to see?
correct http header，just like：
< HTTP/1.1 200 OK
< Cache-Control: public, max-age=
< Content-Length: 2920
< Content-Type: application/json; charset=utf-8
< Date: Thu, 30 Nov 2023 07:09:12 GMT

5. What did you see instead?
< HTTP/1.1 200 OK
< Cache-Control: **publicmaxage=**
< Content-Length: **494"**
< Content-Type: **applicationjson**; charset=**utf8**
< Date: Thu, 30 Nov 2023 07:09:12 GMT
* Excess found in a non pipelined read: excess = 2426, size = 494, maxdownload = 494, bytecount = 0

My service has been working normally for long times, but suddenly all requests from client got incorrect http response headers. 
1、The value of Content-Length less then the length of  response body.   
2、The value of other response header lost some character，like ”-“， ”/“， ”,“

**Comment by flycash** [comment]
let met check it

**Comment by hookokoko** [comment]
I used version 1.9.0 and the latest Beego version for verification, and I didn't find any exceptions in the response. Is it possible that you made modifications to the response headers while using some middlewares?
Alternatively, could you provide more detailed information to help identify the issue?

**Comment by zhaoxiwu** [comment]
> I used version 1.9.0 and the latest Beego version for verification, and I didn't find any exceptions in the response. Is it possible that you made modifications to the response headers while using some middlewares? Alternatively, could you provide more detailed information to help identify the issue?

It is appear by chance.  I have 10+  same servers， only one of them appear this problem。  And  I just use : 
"	this.Ctx.Output.Header("Cache-Control", "public,max-age="+strconv.Itoa(expired))",
"	func (output *BeegoOutput) JSON(data interface{}, hasIndent bool, coding bool) error {
	output.Header("Content-Type", "application/json; charset=utf-8")
       ...
    }
" to and http header

**Comment by zhaoxiwu** [comment]
> closed

I have no permission to reopen this issue

**Comment by hookokoko** [comment]
Is it maybe a network or client problem? @zhaoxiwu

**Comment by zhaoxiwu** [comment]
> Is it maybe a network or client problem? @zhaoxiwu

I do't think so, because I try many ways to check this. like: local curl, or curl the url in other host,  use nginx as the proxy then curl nginx  all failed(get invalid http response header).  but wget works, i can use wget download all response data.

**Comment by flycash** [comment]
If this issue was caused by Beego, I think you should always get the incorrect response header.

The Beego call the http.ResponseWriter directly, so Beego has no way to modify the header.

So I think you need to check the other components, i.e. proxy, gateway or something like that.

> but suddenly all requests from client got incorrect http response headers.

and you can check your code if you and your teammate make any changes.
