### ISSUE TITLE
Website SSL Certificate Expired

### ISSUE THREAD

**Issue by lstanden** [beego/beego#5594]
Was just looking at this, and noticed the SSL Certificate on the documentation website expired in 2022. This was immediately offputting, as it doesn't seem like the project is well maintained, despite you having recent releases.

**Comment by sahglie** [comment]
Really disappointing that not a single maintainer has commented (or fixed) this for the past 3 weeks. The framework looks quite good, but if basic things like updating the SSL Cert for the site's documentation are ignored it reflects poorly on the project as a whole and will probably turn away potential users / contributers.
