### ISSUE TITLE
Using --graceful instead of -graceful since single hyphen is treaded as short version of a flag

### ISSUE THREAD

**Issue by bo-er** [beego/beego#5604]
1. What version of Go and beego are you using (`bee version`)?
   the latest

2. What operating system and processor architecture are you using (`go env`)?
   irrelevent to the problem
3. What did you do?
   I have a project that is using both cobra and beego, when beego's graceful restart functionality is enabled, cobra treats "- graceful" as "-g" + "raceful"
4. What did you expect to see?
    beego should restart the program using "--graceful" instead of "-graceful"

5. What did you see instead?
   cobra now treats -graceful as "-g" + "raceful", and will return an error.

6. Why
   The single hyphen is used with "short" argument like this:
   `./bin/abc -h`
   While the double hyphen is used with "long" argument like this:
   `./bin/abc --help`

IMHO, we should follow the common wisdom and make a small change:
<img width="876" alt="image" src="https://github.com/beego/beego/assets/49479987/0226a80a-9552-4d76-acfe-77df5d914144">

**Comment by flycash** [comment]
good suggestion, can you help to raise a merge request?

**Comment by bo-er** [comment]
> good suggestion, can you help to raise a merge request?

Hi flycash, here is the merge request: https://github.com/beego/beego/pull/5633
