### ISSUE TITLE
Home site beego.gocn.vip return ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by SerhiiK** [beego/beego#5624]
1. What version of Go and beego are you using (`bee version`)?
 Doesn't matter

2. What operating system and processor architecture are you using (`go env`)?
Doesn't matter

3. What did you do?
 Go to site https://beego.gocn.vip/.

4. What did you expect to see?
Site is available

5. What did you see instead?
 Error ERR_CONNECTION_REFUSED

**Comment by flycash** [comment]
https://doc.meoying.com/beego/docs/en-US/v2.2.x/
