### ISSUE TITLE
../go/pkg/mod/github.com/beego/beego@v1.10.1/router.go:909:44: too many arguments in call to logs.ColorByStatus

### ISSUE THREAD

**Issue by wade-liwei** [beego/beego#5643]
这问题怎么解决？

go: downloading github.com/jcmturner/aescts/v2 v2.0.0
# github.com/beego/beego
../go/pkg/mod/github.com/beego/beego@v1.10.1/router.go:909:44: too many arguments in call to logs.ColorByStatus
	have (bool, int)
	want (int)
../go/pkg/mod/github.com/beego/beego@v1.10.1/router.go:910:44: too many arguments in call to logs.ColorByMethod
	have (bool, string)
	want (string)
../go/pkg/mod/github.com/beego/beego@v1.10.1/router.go:911:43: too many arguments in call to logs.ColorByMethod
	have (bool, string)
	want (string)
../go/pkg/mod/github.com/beego/beego@v1.10.1/router.go:926:9: undefined: logs.W32Debug

**Comment by flycash** [comment]
try new version
