### ISSUE TITLE
Some vulnerabilities exist in Beego passively dependent software.

### ISSUE THREAD

**Issue by tianshr123** [beego/beego#5659]
Some vulnerabilities exist in Beego passively dependent software, Do these vulnerabilities affect Beego? Is there a fix plan?

![image](https://github.com/beego/beego/assets/69893838/6bd1e330-7f60-475b-bda6-858c39412f75)

**Comment by flycash** [comment]
I think all of these issues are solved in the latest version. You can check it.

**Comment by chen990702** [comment]
![image](https://github.com/beego/beego/assets/90894620/2df6bb7d-2ed9-499d-9d93-7ee384c61312)
bee工具无法使用
