### ISSUE TITLE
Sorting using sql native statements fails

### ISSUE THREAD

**Issue by TomNewChao** [beego/beego#5661]
**English Only**. Please use English because others could join the discussion if they got similar issue!
When i exec orm in the below,I found that the sorting was not working.

~~~go
o := orm.NewOrm()
countSql := "select * from user where name != 'Private' order by ? desc limit ? offset ?" 
sqlParams = []string{"create_time", "10", "0"}
o.Raw(countSql, sqlParams).QueryRow(&sqlCount)
~~~

1. What did you do?
fix it 

> If this is ORM issue, please provide the DB schemas.
zhuxxxx:xxxxxx@tcp(127.0.0.1:3306)/database?charset=utf8&loc=Local

2. What did you expect to see?
Use the original SQL statement's order by to sort

4. What did you see instead?
Use the original SQL statement's order by to sort

5. How to reproduce the issue?
you can try it in mysql5.7

6. What version of Go and beego are you using (`bee version`)?
go version: 
go version go1.21.5 windows/amd64

beego version:
github.com/beego/beego/v2 v2.2.1
github.com/go-sql-driver/mysql v1.8.1

7. What operating system and processor architecture are you using (`go env`)?
set GO111MODULE=on 
set GOARCH=amd64                                               
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:/Program Files/Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Administrator\Desktop\xxx\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\2\go-build1353552369=/tmp/go-build -gno-record-gcc-switches

**Comment by saleroa** [comment]
Please assign this task to me and I will try to complete it.

**Comment by flycash** [comment]
> What did you expect to see?
Use the original SQL statement's order by to sort
> What did you see instead?
Use the original SQL statement's order by to sort

I cannot get your point. what's the issue?

**Comment by TomNewChao** [comment]
> > What did you expect to see?
> > Use the original SQL statement's order by to sort
> > What did you see instead?
> > Use the original SQL statement's order by to sort
> 
> I cannot get your point. what's the issue?

When I use the the below code to get data
~~~
o := orm.NewOrm()
countSql := "select * from user where name != 'Private' order by ? desc limit ? offset ?" 
sqlParams = []string{"create_time", "-1", "10"}
o.Raw(countSql, sqlParams).QueryRow(&sqlCount)
~~~
and it return the all the data, and not reported params failed. if i use the native sql to exec in mysql client , it reported the error about SQL syntax error. So Why are the returned results different?
~~~

**Comment by flycash** [comment]
what's the `sqlCount`?

**Comment by TomNewChao** [comment]
> what's the `sqlCount`?

the natvie sql is the below:
~~~
select * from user where name != 'Private' order by create_time desc LIMIT 10,-1;
~~~

**Comment by flycash** [comment]
I have confirmed that it's out of Beego control. When you run the query with `sql.DB`(the Go SDK), it still works:
```go
	db, err := sql.Open("mysql", "your_dsn")
	if err != nil {
		panic(err)
	}
// this not work
	rows, err := db.Query("select * from hello_users where name != 'Private' order by ? desc limit ? offset ?",
		"create_time", -1, 10)
// this works
	rows, err := db.Query("select * from hello_users where name != 'Private' order by ? desc limit ? offset ?",
		"create_time", "-1", "10")
```

Another possible reason is that you use the [mysql#interpolateParams](https://github.com/go-sql-driver/mysql?tab=readme-ov-file#interpolateparams)

**Comment by TomNewChao** [comment]
got it,  Thanks, I will continue to see if it is a driver or server problem.

**Comment by TomNewChao** [comment]
> I have confirmed that it's out of Beego control. When you run the query with `sql.DB`(the Go SDK), it still works:
> 
> ```go
> 	db, err := sql.Open("mysql", "your_dsn")
> 	if err != nil {
> 		panic(err)
> 	}
> // this not work
> 	rows, err := db.Query("select * from hello_users where name != 'Private' order by ? desc limit ? offset ?",
> 		"create_time", -1, 10)
> // this works
> 	rows, err := db.Query("select * from hello_users where name != 'Private' order by ? desc limit ? offset ?",
> 		"create_time", "-1", "10")
> ```
> 
> Another possible reason is that you use the [mysql#interpolateParams](https://github.com/go-sql-driver/mysql?tab=readme-ov-file#interpolateparams)

According to your guidance， There are different types of data processing here， And More infomation is in url about  https://github.com/go-sql-driver/mysql/blob/master/packets.go#L1057

**Comment by TomNewChao** [comment]
The cause of the problem has been found, let's close this issue
