### ISSUE TITLE
when I run beego in localhost, the displayed text is something wrong

### ISSUE THREAD

**Issue by ryuji-cre8ive** [beego/beego#5680]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
> If possible, provide a recipe for reproducing the error.
> A complete runnable program is good.
I tried to fix this message, but I can't

> If this is ORM issue, please provide the DB schemas.

2. What did you expect to see?
I want this to display "http server Running on http://localhost:8080"

4. What did you see instead?
> please provide log or error information.
<img width="258" alt="スクリーンショット 2024-07-18 10 10 11" src="https://github.com/user-attachments/assets/08e0dac2-63c6-4e59-a21c-2d9d7c3f6cbf">

5. How to reproduce the issue?

> or you can provide a reproduce demo.

6. What version of Go and beego are you using (`bee version`)?
<img width="396" alt="スクリーンショット 2024-07-18 10 12 24" src="https://github.com/user-attachments/assets/48ca98a9-3894-43b3-b303-2cface55baa6">

7. What operating system and processor architecture are you using (`go env`)?
arm64 is

**Comment by flycash** [comment]
I do notice that most of the similar frameworks also output the "http://:8080", so I think no need to change Beego's behavior. 

And it's very clear.
