### ISSUE TITLE
 the session store has a write conflict issue Under concurrent requests

### ISSUE THREAD

**Issue by lucklyt** [beego/beego#5681]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I was building an SSO system with Casdoor, I found that user logins often did not take effect. After investigating the source code and testing, I discovered that Casdoor uses Beego’s session to cache the user’s login status. When the user logs out, the user data in the session is deleted, but if there are multiple concurrent requests at this time, the request that finishes later will rewrite the deleted data during SessionRelease, causing the user’s login status to be restored.

2. What did you expect to see?
If a session store has already deleted a key in one request, the key-value pair read by other requests should not be rewritten during the release phase.
3. What did you see instead?
> please provide log or error information.

4. How to reproduce the issue?

> or you can provide a reproduce demo.

5. What version of Go and beego are you using (`bee version`)?
v1.12.12
6. What operating system and processor architecture are you using (`go env`)?

**Comment by flycash** [comment]
Let me check it.

**Comment by flycash** [comment]
which provider do you use?

**Comment by flycash** [comment]
And can you provide a demo that show you how to reproduce the issue? And I need the demo to confirm if I get your point.

**Comment by lucklyt** [comment]
> which provider do you use?

redis Sentinel

**Comment by lucklyt** [comment]
> And can you provide a demo that show you how to reproduce the issue? And I need the demo to confirm if I get your point.

I'll give you later.

**Comment by lucklyt** [comment]
> And can you provide a demo that show you how to reproduce the issue? And I need the demo to confirm if I get your point.

i cannot just provide a demo for beego,

**Comment by flycash** [comment]
so, let me confirm: one request call SessionRelease and another one request call SessionSet(or similar function), so the first request release the session but the second one rebuild the session. Right?

**Comment by flycash** [comment]
I think this MR should fix the issue. And can you help to double confirm that? I notice that you are still using the beego v1, you can apply the similar change to beego develop-1.x branch.

**Comment by lucklyt** [comment]
> I think this MR should fix the issue. And can you help to double confirm that? I notice that you are still using the beego v1, you can apply the similar change to beego develop-1.x branch.

I think there is an issue with this PR. If you use SETXX, the newly generated SID won't be saved.

**Comment by flycash** [comment]
You are right, I think we need to introduce new API to clear this behavior:
```go
SessionRelease() //... no change
SessionReleaseIfPresent() //... use the SetXX
```

That is the only solution I think.

**Comment by lucklyt** [comment]
Perhaps consider having the provider maintain an LRU Map that maps SID to store. Requests with the same SID would use the same store instance

**Comment by flycash** [comment]
It doesn't work I think. This is a distributed system problem, and you can image that one gorouine destroy the session from machine1 while another goroutine reset the session on other machine.

**Comment by flycash** [comment]
I will release v2.3.0 on August after updating the relate docs.
