### ISSUE TITLE
Log Configuration Parameter: maxdays doesn't work

### ISSUE THREAD

**Issue by robinwangrubin** [beego/beego#5686]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Below is my log configuration:
```
"filename":"/home/xxxxxx/xxxxxx/log/abc.log"
"level":6
"maxlines":0
"maxsize":0
"daily":true
"rotate":true
"maxdays":1
"separate":["error", "warning"]
```
As you can see the maxdays was set to 1 day; but i found out that it keeps my log more than 10 days. looks like this Parameter doesn't work. and the default value 7 days  doesn't work as well. 

3. What did you expect to see?
keep 1 day log files 

5. What did you see instead?
won't delete old log file.

6. How to reproduce the issue?
I used container to run Beego. 

8. What version of Go and beego are you using (`bee version`)?
go1.11.2

10. What operating system and processor architecture are you using (`go env`)?

**Comment by flycash** [comment]
can you try the latest v1.12.13?

**Comment by WinterCK** [comment]
same problem in v1.12.11。and in the case of multiprogramming，sometimes two program write different files。such as one program writes "file.log" , another writes "file.2024-08-09.001.log"

**Comment by flycash** [comment]
Do you mean you run two Beego application(two progress) and one write "file.log" but another write "file.2024-08-09.001.log"?

**Comment by WinterCK** [comment]
> Do you mean you run two Beego application(two progress) and one write "file.log" but another write "file.2024-08-09.001.log"?

One Beego application with multiple processes。A daemon process starts a worker process, use one config file

**Comment by WinterCK** [comment]
And I also found another problem，In logFile : file.2024-08-08.001.log, the content actually is the previous day（2024-08-07）. and write operations will eventually interrupted. Last line in this file would just write `2024/08/07 00:49:19.114 [xxxx.g` and stop。

**Comment by flycash** [comment]
Can you produce the demo? I don't get the point "One Beego application with multiple processes"

**Comment by robinwangrubin** [comment]
Hi all
I found out the reason why this happened. It's because i used soft link for my log dirname. i need to confiurate the real dirname in my log configuration.
