### ISSUE TITLE
beego orm how to Support Extension a new type of DB

### ISSUE THREAD

**Issue by O3cheng** [beego/beego#5693]
**English Only**. Please use English because others could join the discussion if they got similar issue!

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
> If possible, provide a recipe for reproducing the error.
> A complete runnable program is good.

> If this is ORM issue, please provide the DB schemas.

beego orm how to Support Extension a new type of DB

like https://github.com/beego/beego/issues/3516

2. What did you expect to see?
I need to be compatible with both uppercase and lowercase columns when using PostgreSQL
However, the quotation marks are added in the ORM 

in `client/orm/db_postgres.go`
```go
// postgresql quote is ".
func (d *dbBasePostgres) TableQuote() string {
	return `"`
}
```

4. What did you see instead?
> please provide log or error information.

5. How to reproduce the issue?

> or you can provide a reproduce demo.

6. What version of Go and beego are you using (`bee version`)?
 v2.0.6

7. What operating system and processor architecture are you using (`go env`)?
arm64

**Comment by flycash** [comment]
Can you provide more detail? What do you mean new type?

**Comment by O3cheng** [comment]
> Can you provide more detail? What do you mean new type?

Huawei GaussDB is based on Postgres but has some differences. In the V1 version, the fields in the database kernel are in uppercase by default. In the V5 version, the fields in the database kernel are in lowercase by default. Case insensitive from the kernel level, automatic compatibility without double quotes.

**Comment by flycash** [comment]
You can specify the column name like this:
```go
Name string `orm:"column(user_name)"`
```

**Comment by O3cheng** [comment]
Beego is not currently compatible with both versions of the database.
Table structure of V1
|ID | NAME | REMARK|
| --- | --- | --- |
| 1 | cheng | xxx |

Table structure of V5
| id | name | remark |
| --- | --- | --- |
| 1 | cheng | xxx |

model
```go
type UserInfo struct {
	Id     string `orm:"pk;column(ID)"`
	Name   string `orm:"column(NAME)"`
	Remark string `orm:"column(REMARK)"`
}
```

**Comment by flycash** [comment]
So, if you run `SELECT NAME FROM users`, you will get the unknown column error?

**Comment by O3cheng** [comment]
> So, if you run `SELECT NAME FROM users`, you will get the unknown column error?

yes

**Comment by flycash** [comment]
hhh, I think Beego cannot handle this case unless you provide a new implementation of `dbBaser` which is an internal interface of Beego.

```go
type dbBaser interface {
    Read(context.Context, dbQuerier, *models.ModelInfo, reflect.Value, *time.Location, []string, bool) error
// ... many functions
}
```

And I can image that you need to write the code like:
```go
func (db * GaussDB) Read(ctx context.Context...) {
// construct the sql
    if ctx.Value("gauss_db_v5") == true {
         sql = toLowerCase(sql)
    }
}
```

**Comment by flycash** [comment]
Not only Beego, but also GORM can not handle this case.

**Comment by flycash** [comment]
But I have another solution: write a new driver. The sql.Driver has two core interfaces:
```go
type ExecerContext interface {
	ExecContext(ctx context.Context, query string, args []NamedValue) (Result, error)
}

type QueryerContext interface {
	QueryContext(ctx context.Context, query string, args []NamedValue) (Rows, error)
}
```

And you can convert the sql to upper case or lower case.

**Comment by O3cheng** [comment]
> Not only Beego, but also GORM can not handle this case.

gorm have a Namer interface

https://gorm.io/zh_CN/docs/gorm_config.html

**Comment by O3cheng** [comment]
> But I have another solution: write a new driver. The sql.Driver has two core interfaces:
> 
> ```go
> type ExecerContext interface {
> 	ExecContext(ctx context.Context, query string, args []NamedValue) (Result, error)
> }
> 
> type QueryerContext interface {
> 	QueryContext(ctx context.Context, query string, args []NamedValue) (Rows, error)
> }
> ```
> 
> And you can convert the sql to upper case or lower case.

Let me see this.

**Comment by O3cheng** [comment]
> But I have another solution: write a new driver. The sql.Driver has two core interfaces:
> 
> ```go
> type ExecerContext interface {
> 	ExecContext(ctx context.Context, query string, args []NamedValue) (Result, error)
> }
> 
> type QueryerContext interface {
> 	QueryContext(ctx context.Context, query string, args []NamedValue) (Rows, error)
> }
> ```
> 
> And you can convert the sql to upper case or lower case.

This is gonna be complicated.

Can beego support orm as an interface support extension implementation?
