### ISSUE TITLE
Add Enum to validators

### ISSUE THREAD

**Issue by hamidrabedi** [beego/beego#5695]
add enum or valid values to validators, something like:
```go
type MFA struct {
	MFAType string `valid:"Required;Enum(sms,email,code)"`
}
```

so only those values are acceptable and any other values should return errors.

**Comment by hamidrabedi** [comment]
if we could make it like it accepts functions, that would be amazing like:
```
type MFA struct {
	MFAType string `valid:"Required;Values(GetValidValues)"`
}

func (c *MFA) GetValidValues() []string{
    // now we can fetch data from everywhere
}

```

**Comment by flycash** [comment]
@hamidrabedi hi, can you help to confirm if the #5697 meet your requirement. I think this design looks good.

The key point is that using different implementation to support different enum, so we will introduce two more validator:
- Enum
- IntEnum
