### ISSUE TITLE
Bug: AutoNowAdd only removes the last index from setNames during update

### ISSUE THREAD

**Issue by mohuanlanjing** [beego/beego#5701]
When updating records in the ORM, fields with the AutoNowAdd tag are not properly excluded from the setNames and setValues slices. The current implementation only removes the last matching field, which leads to incorrect SQL queries being generated, potentially causing data inconsistency or application errors.

How to reproduce the issue?
1. Create a model with multiple fields tagged with orm:"auto_now_add".
2. Attempt to update a record using Beego ORM.
3. Observe that only the last AutoNowAdd field is removed from the setNames slice during the update process.

client/orm/db.go:
<img width="582" alt="image" src="https://github.com/user-attachments/assets/3a0f63a8-dfd6-4867-a723-8e0a996a1847">

**Comment by flycash** [comment]
not really get your point. can you provide a query with Beego ORM and tell me what's your expectation.
