### ISSUE TITLE
Slice Bounds Out of Range Panic in queryM2M.AddWithCtx() (Beego ORM v2.3.0)

### ISSUE THREAD

**Issue by erbou** [beego/beego#5702]
Based on my understanding of the code in [orm_querym2m.go](https://github.com/beego/beego/blob/3cb34a8dd16c0f6f9e6c14436e8b94167eb7b3e4/client/orm/orm_querym2m.go#L64C1-L69C3) (Beego ORM - tag v2.3.0), any non-struct argument in queryM2M.AddWithCtx() after the first should map to the rel_through table fields (otherNames, otherValues).

However, it appears to panics with an out of bound slice in `mds = append(mds[:i], mds[i+1:]...)` if I follow this format.

Could you please tell me what I am doing wrong?
Thank you.

---
1. What did you do?

Create a m2m relationship between User and Group with a `rel_through` on a custom table that has additional fields, and invoke the QueryM2M(group, "User").Add(User, extra_fields...).

E.g.:

```
type Group struct {
        Id       int64
        Name string
        Users    []*User `orm:"reverse(many)"`
}


type User struct {
        Id       int64
        Name string
        Groups   []*Group  `orm:"rel(m2m);rel_through(myapp/models.UserGroup)"`
}

type UserGroup struct {
        Id       int64
        User    *User
        Group   *Group
        Role   string
}
```

And

```
m2m := o.QueryM2M(&group, "Users")
_, err := m2m.Add(u, "owner") // expect "owner" to map to UserGroup.Role but it panics with a slice bounds out of range !!
```

Note: I tried many combinations of orm:"..." tags to force primary, foreign keys, and defaults attribute values etc on the models.

3. What did you expect to see?

Success

4. What did you see instead?

```
2024/08/30 21:10:59.166 [M] [log.go:268]  [HTTP] http: panic serving 127.0.0.1:58456: runtime error: slice bounds out of range
[...]
github.com/beego/beego/v2/client/orm.(*queryM2M).AddWithCtx(0x1400034f140, {0x104c4ddb8, 0x10510bd60}, {0x14000293e00, 0x5, 0x5})
	/Users/user/go/pkg/mod/github.com/beego/beego/v2@v2.3.0/client/orm/orm_querym2m.go:67 +0xe78
github.com/beego/beego/v2/client/orm.(*queryM2M).Add(0x14000345980?, {0x14000293e00?, 0x0?, 0x1049df3a9?})
	/Users/user/go/pkg/mod/github.com/beego/beego/v2@v2.3.0/client/orm/orm_querym2m.go:42 +0x3c
pygrader-ws/models.GroupAddUser(0x1, 0x1)
	/Users/user/home/beego/myapp/models/group.go:95 +0x324
[...]
```

5. How to reproduce the issue?

6. What version of Go and beego are you using (`bee version`)?

```
% bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.1.0

├── GoVersion : go1.23.0
├── GOOS      : darwin
├── GOARCH    : arm64
├── NumCPU    : 8
├── GOPATH    : /Users/user/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 30 Aug 2024
```

7. What operating system and processor architecture are you using (`go env`)?

**Comment by flycash** [comment]
I will check this issue. But if you want to solve this issue as soon as possible, I suggest that you can insert user, group and userGroup directly.

And, I still have a question, what's the `owner` in your code. And if you can provide the reproduce demo, it would be helpful

**Comment by erbou** [comment]
> I will check this issue. But if you want to solve this issue as soon as possible, I suggest that you can insert user, group and userGroup directly.

Yes, that worked for me, thanks.

> And, I still have a question, what's the `owner` in your code.

This is the value I want to assign to the `UserGroup.Role` field; in this example, `User` is the `owner` of the `Group`. From what I understand, the code `m2m.Add(u, "owner")` iterates over the non-struct fields - `owner` in this case - after the first argument `u`, and assigns them to the fields of `UserGroup` in the same order, after skipping `Id`, `User`, and `Group` (pk and fk) fields, which means it assigns `owner` to `Role`.

> And if you can provide the reproduce demo, it would be helpful

Working on it.

**Comment by erbou** [comment]
> And if you can provide the reproduce demo, it would be helpful

This is the minimal version of the code that is causing the issue. I apologize for the earlier version being overly simplified - mea culpa.

Note: I modified the swagger.yml file to make it easier to test.

[myapp.tar.gz](https://github.com/user-attachments/files/16838939/myapp.tar.gz)

**Comment by flycash** [comment]
thank you, let me check it.

**Comment by junwense** [comment]
> > And if you can provide the reproduce demo, it would be helpful
> 
> This is the minimal version of the code that is causing the issue. I apologize for the earlier version being overly simplified - mea culpa.
> 
> Note: I modified the swagger.yml file to make it easier to test.
> 
> [myapp.tar.gz](https://github.com/user-attachments/files/16838939/myapp.tar.gz)

I checked the test cases of Beego and found that this method does not actually support inserting additional attributes of associated objects when inserting through the add method. Therefore, using this method will result in an error.
you can see like  this usage
![image](https://github.com/user-attachments/assets/5734aad2-2694-4427-a14f-f95b3aa11193)

**Comment by erbou** [comment]
I've been following your suggestion to insert the user group directly, and it has been working perfectly. Thanks again for your help!
