### ISSUE TITLE
beego can not find the template file

### ISSUE THREAD

**Issue by notedit** [beego/beego#65]
when i run an empty app that created with bee.  it told me that beego:can't find templatefile in the path:index.tpl

i run the app with "go run main.go"

**Comment by arjun-ajith** [comment]
Don't use "go run mainfile.go" command while using beego.. Try "bee run projectname"..

**Comment by YouZhengChuan** [comment]
IDE工具默认将二进制编译到一个临时目录，比如Win IDEA编译的时候就是这样：
"C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.3\bin\runnerw.exe" C:/Go\bin\go.exe build -o "C:\Users\youzhengchuan\AppData\Local\Temp\Build main.go and rungo" C:/Users/youzhengchuan/Documents/myGolangProject/src/myWebProject2/main.go

那么运行的时候，二进制当然找不到相对路径的 index.tpl了，修改下IDE工具的设置，选择编译输出目录为 $GOPATH/src/$UBEEGOPROJECT/ 即可。

**Comment by windyear** [comment]
碰到同样的问题，出错的地方应该是在于运行的二进制文件的路径跟模板存放的路径不一样，所以根据相对路径寻找模板文件的时候会找不到文件。正确的做法是将二进制文件移动到对应模板文件的目录，或者在IDE中设置好工作路径。不如在goland可以设置 working directory 为views所在的路径。

**Comment by godaner** [comment]
@503718696 只需将views放置在$GOPATH下即可找到页面

**Comment by mybirthfather** [comment]
> @503718696 只需将views放置在$GOPATH下即可找到页面

试了的确好用，但是这是bee生成的demo项目，一开始是跑起来的莫名其妙就跑不起来了 试了你这个方法 可以跑了

**Comment by mybirthfather** [comment]
如果你想点击 工具栏的运行按钮直接 运行项目 那么就得把views 放在$GOPATH下面 ，否则会报错这个文件找不到。 如果你是用 命令行 运行项目 src  cd quickstart   quickstart  bee run 你就又得把 view放在quickstart 项目名下面 否则也会报错。我试了一遍是这样的

**Comment by alpha-baby** [comment]
在这里还应该注意的是：
比如你的项目在 `GOPATH/src/Demo` 中
你应该把` go build -o demo.exe Demo`好的可执行程序放到你的 `GOPATH/src/Demo` 下,
并且你在shell 中去执行 ./demo.exe 的之后你当前shell 也必须要在 `GOPATH/src/Demo` 下面，不然也会找不到模版文件。

**Comment by langyichen** [comment]
> 在这里还应该注意的是：
> 比如你的项目在 `GOPATH/src/Demo` 中
> 你应该把` go build -o demo.exe Demo`好的可执行程序放到你的 `GOPATH/src/Demo` 下,
> 并且你在shell 中去执行 ./demo.exe 的之后你当前shell 也必须要在 `GOPATH/src/Demo` 下面，不然也会找不到模版文件。

终于解决我的问题了，谢谢。“当前shell也要在 `GOPATH/src/Demo` 下面！！！”
