### ISSUE TITLE
mail发送有时候无主题

### ISSUE THREAD

**Issue by w123dog** [beego/beego#672]
```
mail := utils.NewEMail(fmt.Sprintf("{\"username\":\"%s\",\"password\":\"%s\",\"host\":\"%s\",\"port\":%s}", user, pass, host, port))
    mail.To = []string{mailUser}
    mail.From = user
    mail.Subject = subject
    mail.Text = text
    mail.AttachFile(filepath)

    err := mail.Send()
    if err != nil {
        LogError(fmt.Sprintf("Send Mail Error:%v", err))
    }
```

![qq20140704105126](https://cloud.githubusercontent.com/assets/836445/3477888/d61ac008-0326-11e4-8278-d30111d0ab1a.png)

**Comment by phpqinsir** [comment]
@astaxie 我以为只有我一人遇到。我这几天也在使用这个工具。发现这问题还特别严重。出现的概率是10%。有时候出现20%。另外，QQ邮箱通过这个工具会出现503身份验证失败。

**Comment by Davion8948** [comment]
我也出现了
![beegobug](https://cloud.githubusercontent.com/assets/4756476/6664132/2b9fbdbc-cc08-11e4-9306-25fb2ad4b0ff.jpg)

复现条件：连续多次发送Email， 会出现有的Email不显示主题和收件人，但是邮件已经接收到

**Comment by Icedroid** [comment]
我也遇到了，经常会无主题，而且邮件附件的名字如果是中文会乱码。
