### ISSUE TITLE
must have one register DataBase alias named `default`

### ISSUE THREAD

**Issue by ultratxd** [beego/beego#678]
version 1.3.2
go version 1.3
init方法中注册default
但是还是显示错误 
must have one register DataBase alias named `default`

**Comment by minnao** [comment]
[ORM]2017/05/07 21:32:02 register db Ping `default`, Error 1049: Unknown database 'beeblog'
must have one register DataBase alias named `default`
我也是这个错误，不知道如何解决数据库别名的问题

**Comment by astaxie** [comment]
@minnao 应该是你们init的顺序问题

**Comment by miaomiaoguoke** [comment]
密码中有！好像就不行，换了个密码就好了。

**Comment by scrapup** [comment]
@astaxie 的确是init函数执行顺序的问题，被导入包的init函数先执行，但是数据库链接放在了main中，所以就出现了这样的情况。

不过我的问题是创建数据表RegisterModel()的确应该放在模型定义的包里面，但是这种init函数执行顺序所带来的‘不方便‘，是否有一种优雅的方式处理。

**Comment by andarm** [comment]
model/ 
db1.go ----------------------------
``` 
func init() {	
        orm.RegisterModel(new(STDevice))
	orm.RegisterDataBase("db1", "sqlite3", "base1.db")
         orm.RunSyncdb("db1", false, true)
}
db2.go --------------------------------
func init() {	
orm.RegisterModel(new(STDevice2))
	orm.RegisterDataBase("db2", "sqlite3", "base2.db")
orm.RunSyncdb("db1", false, true)
}
====================================
``` 
## 目的
- 想创建base1.db 和base2.db ，但是出现下面的告警 
- must have one register DataBase alias named `default`

**Comment by lijinghuatongxue** [comment]
大多数同学是把之前的老项目直接拿过来用，然后改掉数据库，但是有些路径引用没有改掉
