### ISSUE TITLE
切换到develop版本后模板部分好像出现了问题。

### ISSUE THREAD

**Issue by jilili** [beego/beego#702]
为了解决urlfor问题我将版本切换到了develop可是出现了以下问题，界面都进不去了，提示总是get.tpl或者post.tpl找不到。可是我没有使用这两种名字的模板。

eipack:can't find templatefile in the path:logincontroller/post.tpl

Request Method:     POST
Request URL:    /login
RemoteAddr:     127.0.0.1:55815
Stack

c:/go/src/pkg/runtime/panic.c 248
C:/Users/jilili/GoPath/src/github.com/astaxie/beego/controller.go 249
C:/Users/jilili/GoPath/src/github.com/astaxie/beego/controller.go 175
C:/Users/jilili/GoPath/src/github.com/astaxie/beego/router.go 725
c:/go/src/pkg/net/http/server.go 1673
c:/go/src/pkg/net/http/server.go 1174
c:/go/src/pkg/runtime/proc.c 1445

**Comment by fantaxy** [comment]
我在最新版1.4.3上也碰到相同的问题了，Handler crashed with error can't find templatefile in the path:logincontroller/post.tpl
是不是我哪里写得不对？


package controllers

import (
	"fmt"
	"github.com/astaxie/beego"
)

type LoginController struct {
	beego.Controller
}

func (this *LoginController) Get() {
	this.TplNames = "login.html"
}

func (this *LoginController) Post() {
	this.Ctx.WriteString(fmt.Sprint(this.Input()))
	return
}
