### ISSUE TITLE
关于注解路由

### ISSUE THREAD

**Issue by junbinWu** [beego/beego#708]
在dev模式下
注解路由只有通过bee run才可以自己生成go文件并支持注解路由  我使用go run 并不支持注解路由
其他模式下 go run  和 bee run 都是一样的没问题 
这个能否改下？

**Comment by spartacusX** [comment]
注解路由URL match不到 我的环境：
bee   :1.4.1
beego :1.6.0
Go    :go version go1.5.3 windows/amd64
dev和prod都试过，go run 和bee run也都试过，在线等，谢谢！
