### ISSUE TITLE
关于静态页的处理

### ISSUE THREAD

**Issue by bestlake** [beego/beego#717]
不知道beego是否有计划提供对站点下html或shtml文件的静态输出，貌似CMS都需要这个吧。

**Comment by niezuxue** [comment]
> 这个是自己逻辑里面做的啊。在beego里面有提供函数可以做这一块，在你的controller函数中
> 
> ```
> func (a *AController) Get() {
>     var str string
>     if str,ok:=isExistHtml();ok{
> 
>     }else{
>           str:=RenderString()
>           savetohtml(str)          
>     }     
>     c.Ctx.Output.Header("Content-Type", "text/html; charset=utf-8")
>     c.Ctx.Output.Body([]byte(str))
> }
> ```

也只能这么做了
下面是可以直接拷贝的代码
路由
beego.Router("/*.html", &controllers.MainController{}, "get:HtmlPage")
控制器
func (c *MainController) HtmlPage() {
	page := c.Ctx.Request.RequestURI
	_,err:=os.Stat("views" + page)
	if err !=nil {
		c.Data["err_msg"] = err.Error()
		c.TplName = "500.html"
	} else if os.IsNotExist(err) {
		c.TplName = "404.html"
	} else {
		c.TplName = page[1:]
	}

	c.Render()
}
