### ISSUE TITLE
sqlite3 foreign keys question

### ISSUE THREAD

**Issue by alexeyco** [beego/beego#768]
This is my models.Album:

``` go
package models

import "time"

type Album struct {
    Id int
    User *User `orm:"rel(fk);column(user_id)"`
    Created time.Time `orm:"auto_now_add;column(created);type(datetime)"`
    Updated time.Time `orm:"auto_now;column(updated);type(datetime)"`
    Date time.Time `orm:"column(date);type(date);null"`
    Artist string `orm:"column(artist);size(255);null"`
    Title string `orm:"column(title);size(255);null"`
}

func (u *Album) TableName() string {
    return "albums"
}

func (u *Album) TableIndex() [][]string {
    return [][]string{
        []string{"user_id", "Artist"},
        []string{"user_id", "Title"},
    }
}
```

And User:

``` go
package models

import "time"

type User struct {
    Id int
    Created time.Time `orm:"auto_now_add;column(created);type(datetime)"`
    Updated time.Time `orm:"auto_now;column(updated);type(datetime)"`
    Username string `orm:"column(username);size(32);index;unique"`
    Email string `orm:"column(email);size(32);index;unique"`
    Password string `orm:"column(password)"`
    Albums []*Album `orm:"reverse(many)"`
}

func (u *User) TableName() string {
    return "users"
}

func (u *User) TableUnique() [][]string {
    return [][]string{
        []string{"username"},
        []string{"email"},
    }
}

func (u *User) TableIndex() [][]string {
    return [][]string{
        []string{"username", "password"},
        []string{"email", "password"},
    }
}
```

Ok... then look at sqlite3 schema code:

``` sql
-- --------------------------------------------------
--  Table Structure for `arpha/models.User`
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS `arpha_users` (
    `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    `created` datetime NOT NULL,
    `updated` datetime NOT NULL,
    `username` varchar(32) NOT NULL UNIQUE,
    `email` varchar(32) NOT NULL UNIQUE,
    `password` varchar(255) NOT NULL,
    UNIQUE (`username`),
    UNIQUE (`email`)
);
CREATE INDEX `arpha_users_username_password` ON `arpha_users` (`username`, `password`);
CREATE INDEX `arpha_users_email_password` ON `arpha_users` (`email`, `password`);

-- --------------------------------------------------
--  Table Structure for `arpha/models.Album`
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS `arpha_albums` (
    `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    `user_id` integer NOT NULL,
    `created` datetime NOT NULL,
    `updated` datetime NOT NULL,
    `date` date,
    `artist` varchar(255),
    `title` varchar(255)
);
CREATE INDEX `arpha_albums_user_id_artist` ON `arpha_albums` (`user_id`, `artist`);
CREATE INDEX `arpha_albums_user_id_title` ON `arpha_albums` (`user_id`, `title`);
```

And there is no foreign keys... What i'm doing wrong?

**Comment by lucasSa** [comment]
I have the same "problem", maybe they don't generate the fk.
have u found a solution ?

**Comment by lucasSa** [comment]
have you found a solution for it ?

**Comment by Alexeyco** [comment]
No, I dont't have a fancy solution.
10 апр. 2015 г. 4:00 пользователь "lucasSa" <notifications@github.com>
написал:

**Comment by jerson** [comment]
+1 :+1:

**Comment by xlr-8** [comment]
I'm currently wondering the same thing

**Comment by hamidfzm** [comment]
👍

**Comment by SmileAI** [comment]
my models User is
`package models

import (
  "time"
)

type User struct {
  Id      int
  Name    string `orm:"size(128);column(user_name);index;unique"`
  Pass    string `orm:"size(128);column(password)"`
  Phone   string `orm:"size(16);null;index"`
  Email   string `orm:"size(128);null;index"`
  Desc    string `orm:"size(256);null;column(description)"`
  Created time.Time `orm:"auto_now_add;type(datetime);column(created_at)"`
  Updated time.Time `orm:"auto_now;type(datetime);column(updated_at)"`
}

func (user *User) TableName() string {
  return "users"
}

// 为多个字段增加索引
func (user *User) TableIndex() [][]string {
  return [][]string {
    []string{"Id", "Name", "Phone", "Email"},
  }
}

// 为多个字段增加唯一性
func (user *User) TableUnique() [][]string {
  return [][]string {
    []string{"Name", "Pass"},
  }
}`

my file to create table <migrate.go> 
`package main

import (
  models "Pavilion.Ink/models"
  "github.com/astaxie/beego/orm"
  _ "github.com/go-sql-driver/mysql"
)

func init() {
  orm.RegisterDataBase("default", "mysql", "root:@/ink_pavilion_pro?charset=utf8", 30)
  orm.RegisterModel(new(models.User))
  //orm.RunSyncdb("default", true, true)
}

func main() {
  orm.RunCommand()
}
`

LAST:  rum command on console
`go run migrate.go orm sqlall`
and output:

> -- --------------------------------------------------
--  Table Structure for `Pavilion.Ink/models.User`
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
    `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `user_name` varchar(128) NOT NULL DEFAULT ''  UNIQUE,
    `password` varchar(128) NOT NULL DEFAULT '' ,
    `phone` varchar(16),
    `email` varchar(128),
    `description` varchar(256),
    `created_at` datetime NOT NULL,
    `updated_at` datetime NOT NULL,
    UNIQUE (`user_name`, `password`)
) ENGINE=mysql;
CREATE INDEX `users_phone` ON `users` (`phone`);
CREATE INDEX `users_email` ON `users` (`email`);
CREATE INDEX `users_id_user_name_phone_email` ON `users` (`id`, `user_name`, `phone`, `email`);

Hope to have help！！！！   My Database Driver is mysql !!!

**Comment by zjsxwc** [comment]
i find that beego orm not create real foreign key in the Database(Mysql, sqlite), 

but when we do delete the Model in beego orm golang code, it will do delete the other related Model(s).

so there is the soft foreign key constraints in its golang code.

see the references of method `deleteRels()` https://github.com/astaxie/beego/blob/v1.12.0/orm/db.go#L805
