### ISSUE TITLE
如何检查内存泄露?

### ISSUE THREAD

**Issue by zhfish** [beego/beego#786]
做一个爬虫,用的httplib,大概1秒2-3次访问接口,然后会解析json,再调用api上传部分数据
总是出错在100条左右数据的时候,几种情况,感觉像是内存满了?
1. json解析失败,map[string]interface{} is nil
2. http超时
3. tcp faild, dns 解析失败
随后用python写了一个逻辑一样的脚本,900多条数据完美..

思来想去,无外乎两种情况
1. beego的httplib有泄露,或者go的http库..
2. 我写的代码有泄露
大概就是定义了些struct,然后传来传去的...
所以想问问可以怎么查?

**Comment by lryong** [comment]
我也遇到这个问题，当周期性大频率访问https接口不同的时候，我程序也内存溢出啊！

**Comment by mr-tcx** [comment]
> 但是在访问接口的时候`httplib.Post(url).SetTimeout(time.Second,3*time.Second).Debug(true).SetTLSClientConfig(tls)`把Debug设置为true就不会内存溢出了
这个我在线上环境也出现了，周期性访问一个域名不同，内存会不断往上增长
