### ISSUE TITLE
beego高级查询中Filter与cond使用时会造成Filter无效

### ISSUE THREAD

**Issue by tongjh2** [beego/beego#802]
文档中是这么写的
ORM 以 QuerySeter 来组织查询，每个返回 QuerySeter 的方法都会获得一个新的 QuerySeter 对象。
但是当我使用高级查询的 Filter 之后再使用SetCond后，会造成开始的Filter丢失

代码如下
    var group []models.Group
    cond := orm.NewCondition()
    o := orm.NewOrm()
    qs := o.QueryTable(new(models.Group))
    qs = qs.Filter("id", 1) //这里的Filter会被下面的SetCond清空
    cond1 := cond.And("status", 1)
    qs = qs.SetCond(cond1)
    qs.All(&group)

**Comment by wucl202000** [comment]
这个问题依然存在啊，SetCond之后再加Filter没有用
