### ISSUE TITLE
beego 日志丢失

### ISSUE THREAD

**Issue by meilihao** [beego/beego#803]
期望代码在for...range循环中输出日志9次,但实际输出的次数带有随机性,有时1次,有时3次(beego设置了beego.SetLogger)

![20140905162700](https://cloud.githubusercontent.com/assets/4382586/4162123/4325b018-34d7-11e4-8c38-bab3ca519308.png)

**Comment by emaste-r** [comment]
尴尬，我也遇到了。。。偶尔输出偶尔不输出。。

**Comment by emaste-r** [comment]
@DennisMao  不好意思，刚发现是多实例竞争问题，和beego无关系。日志不输出是因为别的机器上消费了队列。sorry!!!  orz...

**Comment by DennisMao** [comment]
@emaste-r 好
