### ISSUE TITLE
BeeGo JSON parser could be replaced

### ISSUE THREAD

**Issue by mvpmvh** [beego/beego#806]
I've been working to switch from app.conf INI configuration to an app.json JSON configuration and I noticed that you already have a registered json adapter. I started using it, but it looks as though you may have written the parser interface with INI in mind, because the methods implemented seem more favorable to INI than json. I did some research into parsing configuration files, particularly json parsing, and there are a handful of repos that handle this. 
The repo I'm looking at adding is https://github.com/bitly/go-simplejson. 

Is it better to add this repo to your codebase, or would you prefer to fork this repo and add your fork to beego codebase?

**Comment by xmapst** [comment]
Can you tell me your app.json, my app.json doesn't work
