### ISSUE TITLE
Beego ORM uses empty string instead of null for string type columns

### ISSUE THREAD

**Issue by owentran** [beego/beego#816]
If you have a model with a nullable string field:

```
type User struct {
  Id   int
  Name string `orm:"size(100);null"`
}
```

When you do an insert it will use '' as the value of the Name if you don't define it. Is there a way for it to be equivalent to NULL? Yes, the logic seems tricky since Go strings doesn't have a nil value. Do you have any other suggestions if you really want a NULL value?

A workaround is to use RAW SQL and replace '' with NULL but seems like an issue others must be facing.

**Comment by caslino** [comment]
What if you don't use a struct but use a var of  []orm.Param type to get the result from the db. 
The orm.Param returns an interface type, so the values (string, int, float ..) will have to be converted to the respective datatype. 

So, for example, I retrieve a primary key of type int64 which is in the orm.Param interface variable. I now want to convert it to sql.NullInt64. 

Any idea how to handle this?

**Comment by stonezdj** [comment]
It seems that when call QueryRow(&user), the pointer field can not set to the value.

**Comment by blueskiner** [comment]
@pdf Thanks for sharing the answer.It helps me a lot
