### ISSUE TITLE
How to do unit test on controllers 

### ISSUE THREAD

**Issue by kathe-jing** [beego/beego#905]
Now I am using ginkgo framework to do unit test，How to do this on beego‘s controllers (using ginkgo and gomock or something else to mock)?

**Comment by nishantmodak** [comment]
@astaxie any chances of getting this soon?

**Comment by trobert2** [comment]
Any updates on this?

**Comment by winhbb** [comment]
Any updates on this?+1

**Comment by zhuyaguang** [comment]
Any updates on this?+2

**Comment by DennisMao** [comment]
@astaxie  What if add the example of controllers' unit test through [httptest](https://golang.org/pkg/net/http/httptest/)

**Comment by mapreal19** [comment]
@DennisMao we should do that. I've tried to answer this in [StackOverflow](https://stackoverflow.com/a/54463808/2273578).

I still have to see how to test these scenarios:
- Testing a logged in user. 
- Testing if a controller sets the right flash message.
