### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by piotrkowalczuk** [beego/beego#912]
```
package v1

import (
    "encoding/json"
    "net/http"

    // ... intenral imports

    beego "gopkg.in/astaxie/beego.v1"
    "gopkg.in/astaxie/beego.v1/logs"
    mgo "gopkg.in/mgo.v2"
)

// BaseController contains common properties accross multiple controllers
type BaseController struct {
    beego.Controller
    Logger            *logs.BeeLogger
    MongoDBSession    *mgo.Session
    RepositoryManager *lib.RepositoryManager
    ResponseData      interface{}
}

// Prepare is called prior to the BaseController method
func (bc *BaseController) Prepare() {
    bc.CustomAbort(400, "TEST")
        //...extra code
}
```

Just like in the topic. Even if i put abort at the begining of `Controller::Prepare()` i see following error:

```
2014/11/06 17:17:03 [app.go:96] [I] http server Running on :8080
2014/11/06 17:17:06 http: multiple response.WriteHeader calls
2014/11/06 17:17:07 http: multiple response.WriteHeader calls
2014/11/06 17:17:07 http: multiple response.WriteHeader calls
2014/11/06 17:17:07 http: multiple response.WriteHeader calls
2014/11/06 17:17:08 http: multiple response.WriteHeader calls
```

Without this line everything is fine:
https://github.com/astaxie/beego/blob/master/router.go#L861

Looks like this line is redundant:
https://github.com/astaxie/beego/blob/master/context/context.go#L59

**Comment by feuvan** [comment]
When will this bug fix be in master branch?

**Comment by mewben** [comment]
+1 Please merge to master. Thanks.

**Comment by astaxie** [comment]
has merged to the master now. just release 1.4.3

**Comment by mewben** [comment]
cool. thanks

**Comment by GokulSrinivas** [comment]
I've defined a custom ErrorController and I aborted with a 404 for `/` 

This was my output.

```
2015/12/07 16:23:04 http: multiple response.WriteHeader calls
2015/12/07 16:23:04 http: panic serving 127.0.0.1:40134: can't find templatefile in the path:errorcontroller/error404.tpl
goroutine 18 [running]:
```

I wanted to serve a JSON response and not a template response.

There is an ErrorController and I get a proper JSON from `Error404` in `ErrorController` if I visit any unregistered route.

 Any help?

**Comment by cappuccino5** [comment]
请问这个错误是在哪个分支上解决的？目前我也遇到了这个问题

**Comment by cappuccino5** [comment]
2019/02/20 11:14:53.637 [server.go:2977]  [HTTP] http: multiple response.WriteHeader calls

**Comment by 1770697081** [comment]
this issue still exists;
 "[HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:230)"

**Comment by 1770697081** [comment]
我也遇到了这个问题，是因为浏览器默认会加载static/favicon.ico这个文件，如果你的beego项目下没有这个文件，加载会报404错误，会打印：
 [HTTP] http: superfluous response.WriteHeader call from github.com/astaxie/beego/context.(*Response).WriteHeader (context.go:231)；

解决办法：把这个文件加入对应目录就行。
