### ISSUE TITLE
Absolute path for filesystem cache

### ISSUE THREAD

**Issue by ghost** [beego/beego#945]
Is it possible to have an absolute path for the filesystem cache? 

```
{"CachePath":"/home/cache","FileSuffix":".cache","DirectoryLevel":2,"EmbedExpiry":120}
```

When I install my .go file the cache gets put as "/home/cache/home/cache" rather than "/home/cache"

thx!

**Comment by kristen1980** [comment]
Over a year and this still isn't in the master?  https://github.com/astaxie/beego/blob/master/cache/file.go#l95

**Comment by astaxie** [comment]
@kristen1980 what do you want? error handle?

**Comment by kristen1980** [comment]
No....just wondering why it isn't in the master branch. The old code is in the master branch.
